/**
 * "Not sure? Get a hint" nudges for select / situational-choose /
 * listening-choose exercises, keyed by exercise id. Applied to LESSONS in
 * mock-data.ts at assembly time, so content files (and `listen()` voice
 * order) stay untouched.
 *
 * Rules for writing one: point at the clue (time of day, tú vs usted, the
 * verb that goes with the idea, what to listen for) — never quote the answer.
 * Units 1–3 are covered here; Units 4–11 are a separate content task.
 */
export const EXERCISE_HINTS: Record<string, string> = {
  // ---------------------------------------------------------------- Unit 1
  "u1l1-1": "You want the one word that works morning, noon and night.",
  "u1l1-2": "Días is the clue — which greeting has it?",
  "u1l1-3": "3 p.m. is afternoon. Pick the greeting for that part of the day.",
  "u1l1-4": "Listen for noches — it points to a time of day.",
  "u1l1-5": "You'll see them tomorrow, so it's a soft, see-you-soon goodbye.",
  "u1l1-8": "Two words; the second one is luego.",
  "u1l1-10": "Late evening means the greeting with noches.",
  "u1l2-1": "The name phrase starts with me, not yo.",
  "u1l2-2": "Casual “you,” so the verb ends in -as.",
  "u1l2-4": "Two words, and gusto is the second one.",
  "u1l2-6": "It opens with the name phrase, then the name.",
  "u1l2-7": "Right after names, you say the “nice to meet you” line.",
  "u1l2-8": "With a friend, use the informal form ending in -ás.",
  "u1l2-9": "The formal form drops the final s from the informal form.",
  "u1l2-10": "A hello, then the casual how-are-you question.",
  "u1l3-3": "The reply to gracias is two short words starting with de.",
  "u1l3-4": "The thank-you word — one word, starts with g.",
  "u1l3-5": "The soft apology is a single word, also used to get attention.",
  "u1l3-6": "The polite formal way to say “excuse me” starts with dis-.",
  "u1l3-8": "One word — the light “sorry”.",
  "u1l3-9": "The formal excuse-me, three syllables.",
  "u1l3-11": "Say no, then the thank-you word.",
  "u1l4-1": "9 a.m. is morning — pick the días greeting.",
  "u1l4-3": "A greeting followed by the casual how-are-you.",
  "u1l4-4": "The you're-welcome reply starts with de.",
  "u1l4-6": "Light bump, light apology — the one-word sorry.",
  "u1l4-7": "Starts with the name phrase (me…), then Sofía.",
  "u1l4-9": "Three of these are objects, not greetings.",
  "u1l4-11": "Listen for días at the end.",
  "u1l4-12": "You'll meet again soon — the goodbye with luego.",
  "u1l5-1": "Informal ends in -ás; formal drops the s.",
  "u1l5-2": "It's two words and starts with qué.",
  "u1l5-3": "For how you feel, use estar (estoy), not ser (soy).",
  "u1l5-5": "First word is a hello; then comes a question about you.",
  "u1l6-1": "Two words, the second is favor.",
  "u1l6-3": "The polite formal opener starts with dis-.",
  "u1l6-4": "Listen for café, then the please phrase.",
  "u1l6-7": "One word, the soft sorry.",
  "u1l6-8": "After gracias comes the two-word “you're welcome”.",
  "u1l7-1": "Morning greeting first, then ask the name.",
  "u1l7-3": "The “nice to meet you” reply — two words with gusto.",
  "u1l7-4": "Gusto is in there — think “pleasure”.",
  "u1l7-7": "Which opener means “we'll see each other”?",
  "u1l7-8": "Vemos comes from ver (to see).",
  "u1l8-1": "Afternoon is tardes.",
  "u1l8-3": "Return the pleasantry — “likewise” or echo it back.",
  "u1l8-4": "Qué tal is a quick check-in, not a price or a greeting.",
  "u1l8-7": "The goodbye that sounds like you won't see them soon.",
  "u1l8-8": "Late and heading to bed — noches.",
  "u1l8-p1": "One word meaning “likewise”.",
  "u1l10-1": "10 a.m. — still morning.",
  "u1l10-2": "8 p.m. — evening, so noches.",
  "u1l10-4": "Listen for mañana at the end — tomorrow.",
  "u1l10-7": "Soon = luego.",
  "u1l12-1": "One short word, works any time of day.",
  "u1l12-2": "Tú form: ¿Cómo te…?",
  "u1l12-6": "The soft goodbye that literally says “we'll see each other”.",
  "u1l12-7": "Cómo + a form of estar.",

  // ---------------------------------------------------------------- Unit 2
  "u2l1-1": "Origin uses ser (soy) + de.",
  "u2l1-2": "Living somewhere uses vivir + en.",
  "u2l1-5": "Listen for soy de — origin.",
  "u2l1-7": "One word for the nationality, after soy.",
  "u2l1-8": "Starts with vivo en — where you live.",
  "u2l1-9": "Grew up there = origin: soy de.",
  "u2l2-1": "Yo forms of -ar verbs end in -o.",
  "u2l2-3": "“A little” is un poco de + the language.",
  "u2l2-5": "Hablo + the language.",
  "u2l2-7": "You're agreeing — which word means “also”?",
  "u2l2-8": "A question starting with hablas — informal “you.”",
  "u2l2-9": "Ustedes form ends in -an (no vosotros here).",
  "u2l3-1": "Asking origin: ¿De dónde…? with the informal form of ser.",
  "u2l3-2": "Origin is the one with ser (soy).",
  "u2l3-3": "Soy de + a country.",
  "u2l3-6": "Hablo, then un poco de, then the language.",
  "u2l3-7": "Origin = soy de, home = vivo en, joined by pero.",
  "u2l3-8": "You need the word for “also” at the start.",
  "u2l3-9": "It starts with de and asks where you're from.",
  "u2l3-11": "Sí, then “a little”.",
  "u2l4-1": "The everyday name line starts with me llamo.",
  "u2l4-2": "Soy comes from ser — who or what you are.",
  "u2l4-4": "Listen for llamo.",
  "u2l4-7": "Hola, then me llamo + name.",
  "u2l5-1": "¿De dónde + informal form of ser.",
  "u2l5-3": "Origin = soy de.",
  "u2l5-4": "Dónde = where.",
  "u2l5-7": "Estados Unidos is in the word.",
  "u2l5-p2": "Where you're from = soy de.",
  "u2l6-1": "Vivir + en.",
  "u2l6-2": "Soy de for origin, vivo en for where you live now.",
  "u2l6-4": "Vivo comes from vivir; ciudad is a place.",
  "u2l6-7": "Vivo en la ciudad — I live in the ____.",
  "u2l7-1": "The verb has to be ‘to speak’ in the yo form; the wrong options put ‘am’, ‘live’ and ‘have’ in front of the language.",
  "u2l7-3": "Hablo un poco de + language.",
  "u2l7-4": "Two languages joined by y; listen for un poco.",
  "u2l7-6": "It's the word you use to add a contrast.",
  "u2l7-8": "Turn it around — which option has the informal “you” pronoun?",
  "u2l7-p1": "Speaking uses hablar, not ser or tener.",
  "u2l8-1": "Origin uses ser + de.",
  "u2l8-2": "Residence uses vivir + en.",
  "u2l8-4": "Hablar + un poco — which option has both ideas?",
  "u2l8-7": "Hablo inglés, pero un poco de… — contrast with pero.",
  "u2l10-1": "Think of paisano — someone from the same ____.",
  "u2l10-3": "Origin = soy de, current home = vivo en.",
  "u2l10-4": "Soy de = origin.",
  "u2l10-7": "Estadounidense contains Estados Unidos.",
  "u2l12-1": "The name line starts with me, not yo.",
  "u2l12-2": "Origin question: ¿De dónde…?",
  "u2l12-6": "Which one adds the “you” pronoun?",
  "u2l12-7": "Mucho gusto — “pleasure” — is the meeting phrase.",

  // ---------------------------------------------------------------- Unit 3
  "u3l1-1": "The first counting number — starts with u-.",
  "u3l1-2": "Think of a pair.",
  "u3l1-4": "Cuesta = it costs; then a number and pesos.",
  "u3l1-5": "Think of “decade” — it starts with di-.",
  "u3l1-7": "Three numbers in a row, counting up from one.",
  "u3l1-8": "Counting out loud — three numbers.",
  "u3l2-1": "The everyday word for a mobile phone, not a landline.",
  "u3l2-2": "“I have” uses tener — pick its yo form.",
  "u3l2-5": "Listen for número and celular.",
  "u3l2-6": "Age uses tener: tengo + number + años.",
  "u3l2-7": "“Do you have” uses tener: ¿Tienes…?",
  "u3l2-8": "Tengo = I have; catch what comes after.",
  "u3l3-1": "Price questions start with the ‘how much’ word; the other three ask about age, name and origin.",
  "u3l3-3": "Cuesta + a number + dólares.",
  "u3l3-4": "Es + the no-cost word. Libre is freedom, not price.",
  "u3l3-5": "Pointing at something to buy — ask the price.",
  "u3l3-7": "Listen for gratis.",
  "u3l3-8": "Aceptan = they accept; then the currency.",
  "u3l3-9": "No charge = gratis.",
  "u3l4-1": "Think “quarter” — one of four.",
  "u3l4-2": "Eight starts with o.",
  "u3l4-4": "Three numbers counting up from five.",
  "u3l4-8": "The number for eight, then por favor.",
  "u3l5-1": "Starts with do-, like dos, but longer.",
  "u3l5-2": "Starts with qu-.",
  "u3l5-4": "Once is eleven; count up from there.",
  "u3l5-8": "Teens 16–19 start with dieci-, then pesos.",
  "u3l6-1": "The everyday word for a mobile phone.",
  "u3l6-2": "Cuál es tu… asks “what is your…”.",
  "u3l6-4": "The same number, repeated three times.",
  "u3l6-6": "Mi número es… — my number is.",
  "u3l7-1": "Age uses tener — informal: tienes.",
  "u3l7-2": "Tengo + number + años.",
  "u3l7-4": "Tengo + años = age; catch the number.",
  "u3l7-7": "Age never uses ser. Which one does?",
  "u3l7-p2": "Age = cuántos años + tener.",
  "u3l8-1": "Price = the ‘how much’ word + a form of costar. One option mixes in qué tal; the others ask about age or your name.",
  "u3l8-2": "Es + an adjective for ‘no charge’. The other options glue es to an age, a phone, or ‘my name is’.",
  "u3l8-4": "Cuesta + number + dólares.",
  "u3l8-7": "It looks like the English word.",
  "u3l8-p1": "Several juices = plural verb: cuestan.",
  "u3l10-1": "Starts with tre-, like tres.",
  "u3l10-2": "Teens 16–19 start with dieci-.",
  "u3l10-4": "Listen for the number after cuesta — once isn't “one time” here.",
  "u3l10-7": "Free = gratis.",
  "u3l12-1": "Think of “decade”.",
  "u3l12-2": "Price = the ‘how much’ question word + a costar form; the others ask your name, origin, or how it’s going.",
  "u3l12-6": "No charge = gratis.",
  "u3l12-7": "Three numbers, counting up from one.",
};
