/**
 * Intermediate track (Units 4–8) — strong A2 / early B1 LatAm Spanish.
 * Merged into mock-data WORD_CARDS / LESSONS.
 */
import type { Lesson, WordCard } from "../types";
import { audioSrcFor } from "../audio";

const LATAM_PRESENT = (forms: [string, string, string, string, string]) => [
  {
    label: "Present indicative (LatAm)",
    forms: [
      { person: "yo", form: forms[0] },
      { person: "tú", form: forms[1] },
      { person: "él/ella/usted", form: forms[2] },
      { person: "nosotros/as", form: forms[3] },
      { person: "ustedes", form: forms[4] },
    ],
  },
];

const LATAM_PRETERITE = (forms: [string, string, string, string, string]) => [
  {
    label: "Preterite (LatAm)",
    forms: [
      { person: "yo", form: forms[0] },
      { person: "tú", form: forms[1] },
      { person: "él/ella/usted", form: forms[2] },
      { person: "nosotros/as", form: forms[3] },
      { person: "ustedes", form: forms[4] },
    ],
  },
];

function teach(
  id: string,
  wordCardId: string
): import("../types").TeachExercise {
  return {
    id,
    type: "teach",
    prompt: "New word — learn it, then practice.",
    explanation: "",
    wordCardId,
    wordCardIds: [wordCardId],
    xp: 0,
  };
}

let listenVoiceIndex = 100;

function listen(
  id: string,
  audioText: string,
  options: string[],
  correctIndex: number,
  explanation: string,
  wordCardIds: string[],
  xp = 3
): import("../types").ListeningChooseExercise {
  const voice = listenVoiceIndex % 2 === 0 ? "f" : "m";
  listenVoiceIndex += 1;
  return {
    id,
    type: "listening-choose",
    prompt: "What did you hear?",
    audioText,
    audioSrc: audioSrcFor(audioText, voice),
    options,
    correctIndex,
    explanation,
    wordCardIds,
    xp,
  };
}

export const INTERMEDIATE_WORD_CARDS: Record<string, WordCard> = {
  despertarse: {
    id: "despertarse",
    lemma: "despertarse",
    pos: "verb",
    gender: "n/a",
    gloss: "to wake up",
    meaningSummary:
      "Reflexive for waking up. Me despierto a las siete is everyday routine talk. Ask someone ¿A qué hora te despiertas?",
    conjugations: LATAM_PRESENT([
      "me despierto",
      "te despiertas",
      "se despierta",
      "nos despertamos",
      "se despiertan",
    ]),
    examples: [
      { es: "Me despierto a las siete.", en: "I wake up at seven." },
      { es: "¿A qué hora te despiertas?", en: "What time do you wake up?" },
    ],
    useWhen: "Talking about waking up / morning routine.",
    dontUseWhen: "Don't drop the reflexive: not 'despierto a las siete' for yourself.",
    formality: "neutral",
    cefr: "A2",
  },
  trabajar: {
    id: "trabajar",
    lemma: "trabajar",
    pos: "verb",
    gender: "n/a",
    gloss: "to work",
    meaningSummary:
      "Regular -ar verb for work. Trabajo en una oficina / Trabajo desde casa. Common small-talk: ¿En qué trabajas?",
    conjugations: LATAM_PRESENT([
      "trabajo",
      "trabajas",
      "trabaja",
      "trabajamos",
      "trabajan",
    ]),
    examples: [
      { es: "Trabajo en una oficina.", en: "I work in an office." },
      { es: "¿En qué trabajas?", en: "What do you do for work?" },
    ],
    useWhen: "Jobs, office, remote work.",
    dontUseWhen: "For 'I have a job' you can also say Tengo trabajo.",
    formality: "neutral",
    cefr: "A2",
  },
  departamento: {
    id: "departamento",
    lemma: "departamento",
    pos: "noun",
    gender: "m",
    gloss: "apartment",
    meaningSummary:
      "LatAm word for an apartment (Spain: piso). Vivo en un departamento cerca del centro.",
    examples: [
      { es: "Vivo en un departamento en la ciudad.", en: "I live in an apartment in the city." },
      { es: "El departamento es pequeño pero cómodo.", en: "The apartment is small but comfortable." },
    ],
    useWhen: "Housing in LatAm Spanish.",
    dontUseWhen: "In Spain you'll hear piso more often.",
    contrast: "casa (house) / piso (Spain)",
    formality: "neutral",
    region: "LatAm-wide",
    cefr: "A2",
  },
  carro: {
    id: "carro",
    lemma: "carro",
    pos: "noun",
    gender: "m",
    gloss: "car",
    meaningSummary:
      "Everyday LatAm word for car (Spain: coche). Voy en carro / No tengo carro.",
    examples: [
      { es: "Voy al trabajo en carro.", en: "I go to work by car." },
      { es: "¿Tienes carro?", en: "Do you have a car?" },
    ],
    useWhen: "Talking about cars in LatAm.",
    dontUseWhen: "In Spain coche is more common.",
    contrast: "coche (Spain) / autobús (bus)",
    formality: "neutral",
    region: "LatAm-wide",
    cefr: "A2",
  },
  "todos-los-dias": {
    id: "todos-los-dias",
    lemma: "todos los días",
    pos: "phrase",
    gender: "n/a",
    gloss: "every day",
    meaningSummary:
      "Frequency phrase for daily habits. Trabajo todos los días / Camino todos los días.",
    examples: [
      { es: "Trabajo todos los días.", en: "I work every day." },
      { es: "Me despierto temprano todos los días.", en: "I wake up early every day." },
    ],
    useWhen: "Describing daily routines.",
    dontUseWhen: "For 'all day' use todo el día — different meaning.",
    contrast: "a veces / nunca / todo el día",
    formality: "neutral",
    cefr: "A2",
  },
  caminar: {
    id: "caminar",
    lemma: "caminar",
    pos: "verb",
    gender: "n/a",
    gloss: "to walk",
    meaningSummary:
      "To walk / go on foot. Camino al trabajo / Prefiero caminar.",
    conjugations: LATAM_PRESENT([
      "camino",
      "caminas",
      "camina",
      "caminamos",
      "caminan",
    ]),
    examples: [
      { es: "Camino al trabajo.", en: "I walk to work." },
      { es: "¿Quieres caminar al centro?", en: "Do you want to walk downtown?" },
    ],
    useWhen: "Going on foot or suggesting a walk.",
    dontUseWhen: "For 'I'm leaving' use me voy — not camino alone.",
    formality: "neutral",
    cefr: "A2",
  },
  "me-gusta": {
    id: "me-gusta",
    lemma: "gustar",
    pos: "verb",
    gender: "n/a",
    gloss: "to like (pleasing to me)",
    meaningSummary:
      "Gustar flips the usual subject: Me gusta el café = Coffee is pleasing to me. Plural: Me gustan los tacos. Soft preference — not the same as ordering with quiero.",
    conjugations: [
      {
        label: "Present with me/te/le… (LatAm)",
        forms: [
          { person: "me gusta(n)", form: "me gusta / me gustan" },
          { person: "te gusta(n)", form: "te gusta / te gustan" },
          { person: "le gusta(n)", form: "le gusta / le gustan" },
          { person: "nos gusta(n)", form: "nos gusta / nos gustan" },
          { person: "les gusta(n)", form: "les gusta / les gustan" },
        ],
      },
    ],
    examples: [
      { es: "Me gusta el café.", en: "I like coffee." },
      { es: "Me gustan los tacos.", en: "I like tacos." },
    ],
    useWhen: "Saying you like food, places, activities.",
    dontUseWhen:
      "At a café when ordering, prefer Quiero un café — me gusta is preference, not the order.",
    contrast: "quiero (I want / I'm ordering)",
    formality: "neutral",
    cefr: "A2",
  },
  quiero: {
    id: "quiero",
    lemma: "querer",
    pos: "verb",
    gender: "n/a",
    gloss: "to want",
    meaningSummary:
      "Querer → yo quiero. At restaurants Quiero un jugo is a clear order. Also Quiero + infinitive for plans: Quiero comer.",
    conjugations: LATAM_PRESENT([
      "quiero",
      "quieres",
      "quiere",
      "queremos",
      "quieren",
    ]),
    examples: [
      { es: "Quiero un jugo, por favor.", en: "I want a juice, please." },
      { es: "¿Qué quieres comer?", en: "What do you want to eat?" },
    ],
    useWhen: "Orders, wants, and quiero + infinitive plans.",
    dontUseWhen:
      "For soft likes use me gusta. With servers, add por favor and often usted forms.",
    contrast: "me gusta (I like) / me gustaría (I would like — softer)",
    formality: "neutral",
    cefr: "A2",
  },
  jugo: {
    id: "jugo",
    lemma: "jugo",
    pos: "noun",
    gender: "m",
    gloss: "juice",
    meaningSummary:
      "LatAm word for juice (Spain: zumo). Un jugo de naranja is a classic café order.",
    examples: [
      { es: "Quiero un jugo de naranja.", en: "I want an orange juice." },
      { es: "¿Tienen jugo natural?", en: "Do you have fresh juice?" },
    ],
    useWhen: "Ordering or talking about juice in LatAm.",
    dontUseWhen: "In Spain you'll hear zumo.",
    contrast: "zumo (Spain) / agua / café",
    formality: "neutral",
    region: "LatAm-wide",
    cefr: "A2",
  },
  cafe: {
    id: "cafe",
    lemma: "café",
    pos: "noun",
    gender: "m",
    gloss: "coffee / café",
    meaningSummary:
      "Coffee drink or the café place. Un café, por favor is core travel Spanish.",
    examples: [
      { es: "Un café, por favor.", en: "A coffee, please." },
      { es: "Me gusta el café con leche.", en: "I like coffee with milk." },
    ],
    useWhen: "Ordering coffee or meeting at a café.",
    dontUseWhen: "n/a — extremely common.",
    formality: "neutral",
    cefr: "A2",
  },
  "la-cuenta": {
    id: "la-cuenta",
    lemma: "la cuenta",
    pos: "phrase",
    gender: "f",
    gloss: "the check / bill",
    meaningSummary:
      "Restaurant bill. Polite with usted: ¿Me trae la cuenta, por favor?",
    examples: [
      { es: "¿Me trae la cuenta, por favor?", en: "Could you bring me the check, please?" },
      { es: "La cuenta, por favor.", en: "The check, please." },
    ],
    useWhen: "Asking for the bill at a restaurant or café.",
    dontUseWhen: "Not for bank accounts in this lesson — here it means the check.",
    formality: "neutral",
    cefr: "A2",
  },
  "usted-server": {
    id: "usted-server",
    lemma: "usted (with servers)",
    pos: "phrase",
    gender: "n/a",
    gloss: "formal you with service staff",
    meaningSummary:
      "With waiters and shop staff, usted is the safe default in much of LatAm: ¿Me puede traer…? Softer and more polite than tú with strangers at work.",
    examples: [
      { es: "Disculpe, ¿me puede traer un menú?", en: "Excuse me, could you bring me a menu?" },
      { es: "¿Me recomienda algo, por favor?", en: "Could you recommend something, please?" },
    ],
    useWhen: "Ordering and asking staff for help.",
    dontUseWhen: "With close friends, tú is fine — read the room.",
    contrast: "tú (informal peers)",
    formality: "formal",
    cefr: "A2",
  },
  "donde-esta": {
    id: "donde-esta",
    lemma: "¿dónde está?",
    pos: "phrase",
    gender: "n/a",
    gloss: "where is…?",
    meaningSummary:
      "Core location question. ¿Dónde está el baño? / ¿Dónde está la estación?",
    examples: [
      { es: "¿Dónde está el baño?", en: "Where is the bathroom?" },
      { es: "¿Dónde está la estación?", en: "Where is the station?" },
    ],
    useWhen: "Asking where a place or thing is.",
    dontUseWhen: "For route help, ¿cómo llego a…? may be better.",
    contrast: "¿cómo llego a…? (how do I get to…)",
    formality: "neutral",
    cefr: "A2",
  },
  cerca: {
    id: "cerca",
    lemma: "cerca",
    pos: "adverb",
    gender: "n/a",
    gloss: "near / close",
    meaningSummary: "Near: Está cerca / Está cerca del parque. Opposite of lejos.",
    examples: [
      { es: "El café está cerca.", en: "The café is nearby." },
      { es: "Vivo cerca del centro.", en: "I live near downtown." },
    ],
    useWhen: "Saying something is close by.",
    dontUseWhen: "Don't use cerca alone as 'I close' — that's cierro.",
    contrast: "lejos (far)",
    formality: "neutral",
    cefr: "A2",
  },
  lejos: {
    id: "lejos",
    lemma: "lejos",
    pos: "adverb",
    gender: "n/a",
    gloss: "far",
    meaningSummary: "Far: Está lejos / Queda lejos del hotel.",
    examples: [
      { es: "La estación está lejos.", en: "The station is far." },
      { es: "No queda muy lejos caminando.", en: "It's not very far walking." },
    ],
    useWhen: "Saying a place is far away.",
    dontUseWhen: "n/a",
    contrast: "cerca (near)",
    formality: "neutral",
    cefr: "A2",
  },
  "a-la-derecha": {
    id: "a-la-derecha",
    lemma: "a la derecha",
    pos: "phrase",
    gender: "n/a",
    gloss: "to the right",
    meaningSummary: "Direction phrase: Gira a la derecha / Está a la derecha.",
    examples: [
      { es: "Gira a la derecha.", en: "Turn right." },
      { es: "El banco está a la derecha.", en: "The bank is on the right." },
    ],
    useWhen: "Giving or following street directions.",
    dontUseWhen: "n/a",
    contrast: "a la izquierda / todo recto",
    formality: "neutral",
    cefr: "A2",
  },
  "a-la-izquierda": {
    id: "a-la-izquierda",
    lemma: "a la izquierda",
    pos: "phrase",
    gender: "n/a",
    gloss: "to the left",
    meaningSummary: "Turn or location on the left. Dobla a la izquierda en la esquina.",
    examples: [
      { es: "Dobla a la izquierda.", en: "Turn left." },
      { es: "La farmacia está a la izquierda.", en: "The pharmacy is on the left." },
    ],
    useWhen: "Directions involving the left side.",
    dontUseWhen: "n/a",
    contrast: "a la derecha",
    formality: "neutral",
    cefr: "A2",
  },
  "todo-recto": {
    id: "todo-recto",
    lemma: "todo recto",
    pos: "phrase",
    gender: "n/a",
    gloss: "straight ahead",
    meaningSummary: "Keep going straight. Sigue todo recto dos cuadras.",
    examples: [
      { es: "Sigue todo recto.", en: "Keep going straight." },
      { es: "Todo recto y luego a la derecha.", en: "Straight ahead and then to the right." },
    ],
    useWhen: "Telling someone to continue straight.",
    dontUseWhen: "n/a",
    contrast: "gira / dobla",
    formality: "neutral",
    cefr: "A2",
  },
  "el-centro": {
    id: "el-centro",
    lemma: "el centro",
    pos: "noun",
    gender: "m",
    gloss: "downtown / city center",
    meaningSummary: "Downtown / historic center. Voy al centro / ¿Cómo llego al centro?",
    examples: [
      { es: "Voy al centro en metro.", en: "I'm going downtown by metro." },
      { es: "¿Cómo llego al centro?", en: "How do I get downtown?" },
    ],
    useWhen: "Talking about downtown / city center.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A2",
  },
  metro: {
    id: "metro",
    lemma: "metro",
    pos: "noun",
    gender: "m",
    gloss: "subway / metro",
    meaningSummary: "Subway system. Tomo el metro / ¿Dónde está la estación de metro?",
    examples: [
      { es: "Tomo el metro todos los días.", en: "I take the metro every day." },
      { es: "¿Dónde está la estación de metro?", en: "Where is the metro station?" },
    ],
    useWhen: "City transit by subway.",
    dontUseWhen: "For buses say autobús / camión (MX) depending on country.",
    formality: "neutral",
    cefr: "A2",
  },
  "como-llego": {
    id: "como-llego",
    lemma: "¿cómo llego a…?",
    pos: "phrase",
    gender: "n/a",
    gloss: "how do I get to…?",
    meaningSummary: "Ask for directions: ¿Cómo llego al aeropuerto?",
    examples: [
      { es: "¿Cómo llego al centro?", en: "How do I get downtown?" },
      { es: "Disculpe, ¿cómo llego a la estación?", en: "Excuse me, how do I get to the station?" },
    ],
    useWhen: "Asking for route directions.",
    dontUseWhen: "If you only need the location, ¿dónde está? may be enough.",
    contrast: "¿dónde está?",
    formality: "neutral",
    cefr: "A2",
  },
  comer: {
    id: "comer",
    lemma: "comer",
    pos: "verb",
    gender: "n/a",
    gloss: "to eat",
    meaningSummary:
      "Core -er verb. Present: como… Preterite: comí, comiste, comió… Comí tacos hoy is natural LatAm past talk.",
    conjugations: [
      ...LATAM_PRESENT(["como", "comes", "come", "comemos", "comen"]),
      ...LATAM_PRETERITE(["comí", "comiste", "comió", "comimos", "comieron"]),
    ],
    examples: [
      { es: "Comí tacos hoy.", en: "I ate tacos today." },
      { es: "¿Qué comiste ayer?", en: "What did you eat yesterday?" },
    ],
    useWhen: "Eating — present habits or completed past meals.",
    dontUseWhen: "For 'I am hungry' use Tengo hambre — not Como hambre.",
    formality: "neutral",
    cefr: "A2",
  },
  "hablar-preterite": {
    id: "hablar-preterite",
    lemma: "hablar (preterite)",
    pos: "verb",
    gender: "n/a",
    gloss: "to speak (past)",
    meaningSummary:
      "Regular -ar preterite: hablé, hablaste, habló, hablamos, hablaron.",
    conjugations: LATAM_PRETERITE([
      "hablé",
      "hablaste",
      "habló",
      "hablamos",
      "hablaron",
    ]),
    examples: [
      { es: "Hablé con mi hermana ayer.", en: "I talked with my sister yesterday." },
      { es: "¿Hablaste con el mesero?", en: "Did you speak with the waiter?" },
    ],
    useWhen: "Completed conversations in the past.",
    dontUseWhen: "For ongoing past 'I was talking' use imperfect later (hablaba).",
    formality: "neutral",
    cefr: "A2",
  },
  ayer: {
    id: "ayer",
    lemma: "ayer",
    pos: "adverb",
    gender: "n/a",
    gloss: "yesterday",
    meaningSummary: "Time anchor for preterite stories. Ayer comí… / Ayer fui al centro.",
    examples: [
      { es: "Ayer trabajé hasta tarde.", en: "Yesterday I worked until late." },
      { es: "¿Qué hiciste ayer?", en: "What did you do yesterday?" },
    ],
    useWhen: "Situating completed past actions.",
    dontUseWhen: "n/a",
    contrast: "hoy / mañana / anoche",
    formality: "neutral",
    cefr: "A2",
  },
  hoy: {
    id: "hoy",
    lemma: "hoy",
    pos: "adverb",
    gender: "n/a",
    gloss: "today",
    meaningSummary:
      "Today — present or preterite depending on whether the action is done: Hoy como… vs Hoy comí…",
    examples: [
      { es: "Hoy comí temprano.", en: "Today I ate early." },
      { es: "Hoy voy al centro.", en: "Today I'm going downtown." },
    ],
    useWhen: "Talking about today's events or plans.",
    dontUseWhen: "n/a",
    contrast: "ayer / mañana",
    formality: "neutral",
    cefr: "A2",
  },
  ir: {
    id: "ir",
    lemma: "ir",
    pos: "verb",
    gender: "n/a",
    gloss: "to go",
    meaningSummary:
      "Irregular essential. Present: voy… Preterite: fui, fuiste, fue… Same preterite as ser — context tells you. Also ir a + infinitive: Voy a comer.",
    conjugations: [
      ...LATAM_PRESENT(["voy", "vas", "va", "vamos", "van"]),
      ...LATAM_PRETERITE(["fui", "fuiste", "fue", "fuimos", "fueron"]),
    ],
    examples: [
      { es: "Fui al supermercado ayer.", en: "I went to the supermarket yesterday." },
      { es: "Voy a estudiar esta noche.", en: "I'm going to study tonight." },
    ],
    useWhen: "Going places, past trips, and ir a + infinitive plans.",
    dontUseWhen: "Don't confuse fui (I went / I was) — listen for destination vs identity.",
    contrast: "venir (to come)",
    formality: "neutral",
    cefr: "A2",
  },
  hacer: {
    id: "hacer",
    lemma: "hacer",
    pos: "verb",
    gender: "n/a",
    gloss: "to do / to make",
    meaningSummary:
      "High-frequency irregular. Present: hago… Preterite: hice, hiciste, hizo, hicimos, hicieron.",
    conjugations: [
      ...LATAM_PRESENT(["hago", "haces", "hace", "hacemos", "hacen"]),
      ...LATAM_PRETERITE(["hice", "hiciste", "hizo", "hicimos", "hicieron"]),
    ],
    examples: [
      { es: "Hice la tarea anoche.", en: "I did the homework last night." },
      { es: "¿Qué hiciste hoy?", en: "What did you do today?" },
    ],
    useWhen: "Talking about things you did or made.",
    dontUseWhen: "n/a — extremely common.",
    formality: "neutral",
    cefr: "A2",
  },
  "tener-preterite": {
    id: "tener-preterite",
    lemma: "tener (preterite)",
    pos: "verb",
    gender: "n/a",
    gloss: "to have (past)",
    meaningSummary: "Preterite of tener: tuve, tuviste, tuvo, tuvimos, tuvieron.",
    conjugations: LATAM_PRETERITE([
      "tuve",
      "tuviste",
      "tuvo",
      "tuvimos",
      "tuvieron",
    ]),
    examples: [
      { es: "Tuve una reunión hoy.", en: "I had a meeting today." },
      { es: "No tuve tiempo ayer.", en: "I didn't have time yesterday." },
    ],
    useWhen: "Completed possession / experiences in the past.",
    dontUseWhen: "For age in the past you'll often still hear tenía (imperfect) later.",
    formality: "neutral",
    cefr: "A2",
  },
  decir: {
    id: "decir",
    lemma: "decir",
    pos: "verb",
    gender: "n/a",
    gloss: "to say / to tell",
    meaningSummary:
      "Irregular: digo… Preterite: dije, dijiste, dijo, dijimos, dijeron.",
    conjugations: [
      ...LATAM_PRESENT(["digo", "dices", "dice", "decimos", "dicen"]),
      ...LATAM_PRETERITE(["dije", "dijiste", "dijo", "dijimos", "dijeron"]),
    ],
    examples: [
      { es: "Dije la verdad.", en: "I told the truth." },
      { es: "¿Qué te dijo?", en: "What did he/she tell you?" },
    ],
    useWhen: "Reporting what was said.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "B1",
  },
  "ir-a": {
    id: "ir-a",
    lemma: "ir a + infinitive",
    pos: "phrase",
    gender: "n/a",
    gloss: "going to (near future)",
    meaningSummary:
      "Near-future plan: Voy a + infinitive. Voy a comer / Vamos a salir.",
    examples: [
      { es: "Voy a cocinar esta noche.", en: "I'm going to cook tonight." },
      { es: "¿Vas a venir?", en: "Are you going to come?" },
    ],
    useWhen: "Plans and intentions in the near future.",
    dontUseWhen: "For a firm café order, Quiero… is clearer than Voy a querer…",
    contrast: "quiero + infinitive (I want to…)",
    formality: "neutral",
    cefr: "A2",
  },
  "quiero-inf": {
    id: "quiero-inf",
    lemma: "quiero + infinitive",
    pos: "phrase",
    gender: "n/a",
    gloss: "I want to…",
    meaningSummary: "Desire + action: Quiero salir / Quiero aprender español.",
    examples: [
      { es: "Quiero salir el viernes.", en: "I want to go out on Friday." },
      { es: "No quiero llegar tarde.", en: "I don't want to arrive late." },
    ],
    useWhen: "Stating what you want to do.",
    dontUseWhen: "For scheduled near future, ir a + inf is very natural too.",
    contrast: "voy a + infinitive",
    formality: "neutral",
    cefr: "A2",
  },
  "te-gustaria": {
    id: "te-gustaria",
    lemma: "¿te gustaría…?",
    pos: "phrase",
    gender: "n/a",
    gloss: "would you like…?",
    meaningSummary: "Polite invitation: ¿Te gustaría tomar un café?",
    examples: [
      { es: "¿Te gustaría tomar un café?", en: "Would you like to get a coffee?" },
      { es: "¿Te gustaría ir al cine?", en: "Would you like to go to the movies?" },
    ],
    useWhen: "Inviting someone politely (tú).",
    dontUseWhen: "With formal strangers use ¿Le gustaría…? (usted).",
    contrast: "¿quieres…? (more direct)",
    formality: "informal",
    cefr: "A2",
  },
  "otra-vez": {
    id: "otra-vez",
    lemma: "otra vez / tal vez",
    pos: "phrase",
    gender: "n/a",
    gloss: "soft refusal helpers",
    meaningSummary:
      "Soft no to plans: Tal vez otro día / Ahora no puedo. Keeps the door open.",
    examples: [
      { es: "Gracias, pero ahora no puedo.", en: "Thanks, but I can't right now." },
      { es: "Tal vez otro día. ¡Gracias!", en: "Maybe another day. Thanks!" },
    ],
    useWhen: "Declining invitations gently.",
    dontUseWhen: "If you truly never want to, be clearer — soft refusals are polite default.",
    formality: "neutral",
    cefr: "A2",
  },
  "me-parece": {
    id: "me-parece",
    lemma: "me parece",
    pos: "phrase",
    gender: "n/a",
    gloss: "it seems to me / I think",
    meaningSummary: "Opinion softener: Me parece bien / Me parece interesante.",
    examples: [
      { es: "Me parece bien.", en: "Sounds good to me." },
      { es: "Me parece una buena idea.", en: "It seems like a good idea to me." },
    ],
    useWhen: "Giving opinions or agreeing with plans.",
    dontUseWhen: "n/a",
    contrast: "creo que…",
    formality: "neutral",
    cefr: "B1",
  },
};

export const INTERMEDIATE_LESSONS: Record<string, Lesson> = {
  "u4-l1": {
    id: "u4-l1",
    unitId: "unit-4",
    title: "My day",
    description: "Wake up, work, and talk about daily routine.",
    xpReward: 40,
    exercises: [
      teach("teach-u4l1-despertarse", "despertarse"),
      {
        id: "u4l1-1",
        type: "select",
        prompt: "“I wake up” (yo) is…",
        options: ["Me despierto", "Despierto me", "Soy despierto", "Tengo despierto"],
        correctIndex: 0,
        explanation: "Reflexive: Me despierto.",
        wordCardIds: ["despertarse"],
        xp: 3,
      },
      teach("teach-u4l1-trabajar", "trabajar"),
      {
        id: "u4l1-2",
        type: "tap-chips",
        prompt: "Build: “I work in an office.”",
        chips: ["Trabajo", "en", "una", "oficina.", "departamento", "carro"],
        correctOrder: ["Trabajo", "en", "una", "oficina."],
        explanation: "Trabajo en una oficina.",
        wordCardIds: ["trabajar"],
        xp: 3,
      },
      teach("teach-u4l1-todos-los-dias", "todos-los-dias"),
      {
        id: "u4l1-3",
        type: "translate",
        prompt: "Translate: “I work every day.”",
        acceptedAnswers: [
          "Trabajo todos los días.",
          "Trabajo todos los dias.",
          "Yo trabajo todos los días.",
          "Yo trabajo todos los dias",
        ],
        hint: "todos los días",
        explanation: "Trabajo todos los días.",
        wordCardIds: ["trabajar", "todos-los-dias"],
        xp: 4,
      },
      listen(
        "u4l1-4",
        "Me despierto a las siete.",
        ["I wake up at seven.", "I work at seven.", "I have a car.", "I live in an apartment."],
        0,
        "Me despierto a las siete = I wake up at seven.",
        ["despertarse"]
      ),
      {
        id: "u4l1-5",
        type: "situational-choose",
        prompt: "Pick the best question.",
        situation: "You want to know what someone does for work (tú).",
        options: [
          "¿En qué trabajas?",
          "¿Dónde comes carro?",
          "¿Me gusta trabajar?",
          "¿Cómo te llamas oficina?",
        ],
        correctIndex: 0,
        explanation: "¿En qué trabajas? is the everyday job question.",
        wordCardIds: ["trabajar"],
        xp: 3,
      },
      {
        id: "u4l1-6",
        type: "fill-blank",
        prompt: "Fill in the blank.",
        template: "Me ___ a las siete.",
        acceptedAnswers: ["despierto", "Despierto"],
        hint: "wake up (yo)",
        explanation: "Me despierto a las siete.",
        wordCardIds: ["despertarse"],
        xp: 3,
      },
      {
        id: "u4l1-7",
        type: "match-pairs",
        prompt: "Match routine phrases.",
        pairs: [
          { left: "me despierto", right: "I wake up" },
          { left: "trabajo", right: "I work" },
          { left: "todos los días", right: "every day" },
          { left: "¿En qué trabajas?", right: "What do you do for work?" },
        ],
        explanation: "Core daily-routine building blocks.",
        wordCardIds: ["despertarse", "trabajar", "todos-los-dias"],
        xp: 4,
      },
      listen(
        "u4l1-8",
        "Trabajo todos los días.",
        ["I work every day.", "I wake up every day.", "I want juice every day.", "I went yesterday."],
        0,
        "Trabajo todos los días = I work every day.",
        ["trabajar", "todos-los-dias"]
      ),
    ],
  },
  "u4-l2": {
    id: "u4-l2",
    unitId: "unit-4",
    title: "Home & getting around",
    description: "Departamento, carro, and walking your neighborhood.",
    xpReward: 38,
    exercises: [
      teach("teach-u4l2-departamento", "departamento"),
      {
        id: "u4l2-1",
        type: "select",
        prompt: "LatAm word for apartment?",
        options: ["Departamento", "Piso only", "Jugo", "Metro"],
        correctIndex: 0,
        explanation: "Departamento is the LatAm-standard word for apartment.",
        wordCardIds: ["departamento"],
        xp: 3,
      },
      teach("teach-u4l2-carro", "carro"),
      {
        id: "u4l2-2",
        type: "select",
        prompt: "LatAm word for car?",
        options: ["Carro", "Zumo", "Cuenta", "Derecha"],
        correctIndex: 0,
        explanation: "Carro is everyday LatAm for car (Spain: coche).",
        wordCardIds: ["carro"],
        xp: 3,
      },
      teach("teach-u4l2-caminar", "caminar"),
      {
        id: "u4l2-3",
        type: "tap-chips",
        prompt: "Build: “I walk to work.”",
        chips: ["Camino", "al", "trabajo.", "carro", "jugo"],
        correctOrder: ["Camino", "al", "trabajo."],
        explanation: "Camino al trabajo.",
        wordCardIds: ["caminar"],
        xp: 3,
      },
      {
        id: "u4l2-4",
        type: "translate",
        prompt: "Translate: “I live in an apartment.”",
        acceptedAnswers: [
          "Vivo en un departamento.",
          "Vivo en un departamento",
          "Yo vivo en un departamento.",
        ],
        hint: "departamento",
        explanation: "Vivo en un departamento.",
        wordCardIds: ["departamento"],
        xp: 4,
      },
      listen(
        "u4l2-5",
        "Voy al trabajo en carro.",
        ["I go to work by car.", "I walk to work.", "I live in an apartment.", "I want orange juice."],
        0,
        "Voy al trabajo en carro = I go to work by car.",
        ["carro"]
      ),
      {
        id: "u4l2-6",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "A coworker asks how you get to the office; you drive.",
        options: ["Voy en carro.", "Me gusta la cuenta.", "Comí ayer.", "Gira a la izquierda."],
        correctIndex: 0,
        explanation: "Voy en carro.",
        wordCardIds: ["carro"],
        xp: 3,
      },
      {
        id: "u4l2-7",
        type: "fill-blank",
        prompt: "Fill in the blank.",
        template: "Vivo en un ___.",
        acceptedAnswers: ["departamento", "Departamento"],
        hint: "apartment (LatAm)",
        explanation: "Vivo en un departamento.",
        wordCardIds: ["departamento"],
        xp: 3,
      },
      {
        id: "u4l2-8",
        type: "match-pairs",
        prompt: "Match LatAm daily-life words.",
        pairs: [
          { left: "departamento", right: "apartment" },
          { left: "carro", right: "car" },
          { left: "caminar", right: "to walk" },
          { left: "Camino al trabajo", right: "I walk to work" },
        ],
        explanation: "Home and commute vocab.",
        wordCardIds: ["departamento", "carro", "caminar"],
        xp: 4,
      },
      listen(
        "u4l2-9",
        "¿Tienes carro?",
        ["Do you have a car?", "Do you like juice?", "Where is the bathroom?", "Would you like coffee?"],
        0,
        "¿Tienes carro? = Do you have a car?",
        ["carro"]
      ),
    ],
  },
  "u5-l1": {
    id: "u5-l1",
    unitId: "unit-5",
    title: "Me gusta vs quiero",
    description: "Likes vs ordering — café, jugo, and clear wants.",
    xpReward: 42,
    exercises: [
      teach("teach-u5l1-me-gusta", "me-gusta"),
      {
        id: "u5l1-1",
        type: "select",
        prompt: "“I like coffee” is…",
        options: ["Me gusta el café.", "Quiero gusta café.", "Soy café.", "Tengo gusto café."],
        correctIndex: 0,
        explanation: "Me gusta el café — gustar flips the subject.",
        wordCardIds: ["me-gusta", "cafe"],
        xp: 3,
      },
      teach("teach-u5l1-quiero", "quiero"),
      {
        id: "u5l1-2",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "You're at the counter ordering a juice.",
        options: [
          "Quiero un jugo, por favor.",
          "Me gusta un jugo, por favor.",
          "Soy un jugo.",
          "Comí un jugo ayer.",
        ],
        correctIndex: 0,
        explanation: "Orders use quiero. Me gusta states preference, not the order itself.",
        wordCardIds: ["quiero", "jugo"],
        xp: 4,
      },
      teach("teach-u5l1-jugo", "jugo"),
      teach("teach-u5l1-cafe", "cafe"),
      {
        id: "u5l1-3",
        type: "tap-chips",
        prompt: "Build: “I like tacos.”",
        chips: ["Me", "gustan", "los", "tacos.", "quiero", "jugo"],
        correctOrder: ["Me", "gustan", "los", "tacos."],
        explanation: "Plural liked things → me gustan.",
        wordCardIds: ["me-gusta"],
        xp: 3,
      },
      {
        id: "u5l1-4",
        type: "translate",
        prompt: "Translate: “I want an orange juice.”",
        acceptedAnswers: [
          "Quiero un jugo de naranja.",
          "Quiero un jugo de naranja",
          "Yo quiero un jugo de naranja.",
        ],
        hint: "jugo de naranja",
        explanation: "Quiero un jugo de naranja.",
        wordCardIds: ["quiero", "jugo"],
        xp: 4,
      },
      listen(
        "u5l1-5",
        "Me gusta el café.",
        ["I like coffee.", "I want coffee.", "The check, please.", "I ate coffee."],
        0,
        "Me gusta el café = I like coffee.",
        ["me-gusta", "cafe"]
      ),
      {
        id: "u5l1-6",
        type: "select",
        prompt: "At a café, the clearer order is…",
        options: [
          "Quiero un café, por favor.",
          "Me gusta un café, por favor.",
          "Fui un café.",
          "Me parece un café.",
        ],
        correctIndex: 0,
        explanation: "Quiero + item (+ por favor) for ordering.",
        wordCardIds: ["quiero", "cafe"],
        xp: 3,
      },
      {
        id: "u5l1-7",
        type: "fill-blank",
        prompt: "Fill in the blank.",
        template: "Me ___ el café.",
        acceptedAnswers: ["gusta", "Gusta"],
        hint: "I like (singular)",
        explanation: "Me gusta el café.",
        wordCardIds: ["me-gusta"],
        xp: 3,
      },
      {
        id: "u5l1-8",
        type: "match-pairs",
        prompt: "Match preference vs order.",
        pairs: [
          { left: "Me gusta el café", right: "I like coffee" },
          { left: "Quiero un café", right: "I want a coffee (ordering)" },
          { left: "jugo", right: "juice (LatAm)" },
          { left: "Me gustan los tacos", right: "I like tacos" },
        ],
        explanation: "Gustar = like; querer = want/order.",
        wordCardIds: ["me-gusta", "quiero", "jugo", "cafe"],
        xp: 4,
      },
      listen(
        "u5l1-9",
        "Quiero un jugo de naranja.",
        ["I want an orange juice.", "I like orange juice.", "Where is the juice?", "I went for juice yesterday."],
        0,
        "Quiero un jugo de naranja = I want an orange juice.",
        ["quiero", "jugo"]
      ),
    ],
  },
  "u5-l2": {
    id: "u5-l2",
    unitId: "unit-5",
    title: "Ordering with usted",
    description: "Polite café Spanish — menus, recommendations, the check.",
    xpReward: 40,
    exercises: [
      teach("teach-u5l2-usted", "usted-server"),
      {
        id: "u5l2-1",
        type: "select",
        prompt: "With a waiter you don't know, the safer default is…",
        options: ["usted", "vosotros", "only slang", "no greeting"],
        correctIndex: 0,
        explanation: "Usted is the polite default with service staff in much of LatAm.",
        wordCardIds: ["usted-server"],
        xp: 3,
      },
      teach("teach-u5l2-cuenta", "la-cuenta"),
      {
        id: "u5l2-2",
        type: "tap-chips",
        prompt: "Build: “The check, please.”",
        chips: ["La", "cuenta,", "por", "favor.", "jugo", "carro"],
        correctOrder: ["La", "cuenta,", "por", "favor."],
        explanation: "La cuenta, por favor.",
        wordCardIds: ["la-cuenta"],
        xp: 3,
      },
      {
        id: "u5l2-3",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "You need a menu from the server (polite).",
        options: [
          "Disculpe, ¿me puede traer un menú?",
          "Oye, dame menú ya.",
          "Me gusta el menú ayer.",
          "Fui el menú.",
        ],
        correctIndex: 0,
        explanation: "Disculpe + ¿me puede traer…? is polite usted service Spanish.",
        wordCardIds: ["usted-server"],
        xp: 4,
      },
      listen(
        "u5l2-4",
        "¿Me trae la cuenta, por favor?",
        ["Could you bring me the check, please?", "Do you like the check?", "Where is the metro?", "I woke up early."],
        0,
        "¿Me trae la cuenta, por favor? — polite bill request.",
        ["la-cuenta", "usted-server"]
      ),
      {
        id: "u5l2-5",
        type: "translate",
        prompt: "Translate: “Could you recommend something, please?”",
        acceptedAnswers: [
          "¿Me recomienda algo, por favor?",
          "Me recomienda algo, por favor?",
          "¿Me recomienda algo por favor?",
        ],
        hint: "me recomienda (usted)",
        explanation: "¿Me recomienda algo, por favor?",
        wordCardIds: ["usted-server"],
        xp: 4,
      },
      {
        id: "u5l2-6",
        type: "select",
        prompt: "“Excuse me” to get a server's attention:",
        options: ["Disculpe", "Adiós", "Todo recto", "Ayer"],
        correctIndex: 0,
        explanation: "Disculpe is the polite attention-getter.",
        wordCardIds: ["usted-server"],
        xp: 3,
      },
      {
        id: "u5l2-7",
        type: "fill-blank",
        prompt: "Fill in the blank.",
        template: "¿Me trae la ___, por favor?",
        acceptedAnswers: ["cuenta", "Cuenta"],
        hint: "the check",
        explanation: "¿Me trae la cuenta, por favor?",
        wordCardIds: ["la-cuenta"],
        xp: 3,
      },
      {
        id: "u5l2-8",
        type: "match-pairs",
        prompt: "Match café service lines.",
        pairs: [
          { left: "Disculpe", right: "Excuse me (polite)" },
          { left: "la cuenta", right: "the check" },
          { left: "¿Me puede traer…?", right: "Could you bring me…?" },
          { left: "¿Me recomienda algo?", right: "Could you recommend something?" },
        ],
        explanation: "Polite ordering toolkit.",
        wordCardIds: ["usted-server", "la-cuenta"],
        xp: 4,
      },
      listen(
        "u5l2-9",
        "Disculpe, ¿me puede traer un menú?",
        ["Excuse me, could you bring me a menu?", "I like the menu.", "Where is the apartment?", "I went yesterday."],
        0,
        "Polite menu request with usted.",
        ["usted-server"]
      ),
    ],
  },
  "u6-l1": {
    id: "u6-l1",
    unitId: "unit-6",
    title: "Where is it?",
    description: "Dónde está, cerca, lejos, and left/right.",
    xpReward: 40,
    exercises: [
      teach("teach-u6l1-donde", "donde-esta"),
      {
        id: "u6l1-1",
        type: "select",
        prompt: "How do you ask “Where is the bathroom?”",
        options: [
          "¿Dónde está el baño?",
          "¿Qué comiste el baño?",
          "¿Me gusta el baño?",
          "¿Quiero el baño ayer?",
        ],
        correctIndex: 0,
        explanation: "¿Dónde está el baño?",
        wordCardIds: ["donde-esta"],
        xp: 3,
      },
      teach("teach-u6l1-cerca", "cerca"),
      teach("teach-u6l1-lejos", "lejos"),
      {
        id: "u6l1-2",
        type: "select",
        prompt: "Opposite of cerca?",
        options: ["lejos", "jugo", "cuenta", "despierto"],
        correctIndex: 0,
        explanation: "cerca = near; lejos = far.",
        wordCardIds: ["cerca", "lejos"],
        xp: 3,
      },
      teach("teach-u6l1-derecha", "a-la-derecha"),
      teach("teach-u6l1-izquierda", "a-la-izquierda"),
      {
        id: "u6l1-3",
        type: "tap-chips",
        prompt: "Build: “Turn right.”",
        chips: ["Gira", "a", "la", "derecha.", "izquierda", "jugo"],
        correctOrder: ["Gira", "a", "la", "derecha."],
        explanation: "Gira a la derecha.",
        wordCardIds: ["a-la-derecha"],
        xp: 3,
      },
      listen(
        "u6l1-4",
        "El café está cerca.",
        ["The café is nearby.", "The café is far.", "I want coffee.", "Turn left."],
        0,
        "El café está cerca = The café is nearby.",
        ["cerca"]
      ),
      {
        id: "u6l1-5",
        type: "situational-choose",
        prompt: "Pick the best answer.",
        situation: "Someone asks if the station is close; it isn't.",
        options: ["Está lejos.", "Me gusta lejos.", "Quiero lejos.", "Comí lejos."],
        correctIndex: 0,
        explanation: "Está lejos.",
        wordCardIds: ["lejos"],
        xp: 3,
      },
      {
        id: "u6l1-6",
        type: "translate",
        prompt: "Translate: “The pharmacy is on the left.”",
        acceptedAnswers: [
          "La farmacia está a la izquierda.",
          "La farmacia esta a la izquierda.",
          "La farmacia está a la izquierda",
        ],
        hint: "a la izquierda",
        explanation: "La farmacia está a la izquierda.",
        wordCardIds: ["a-la-izquierda"],
        xp: 4,
      },
      {
        id: "u6l1-7",
        type: "match-pairs",
        prompt: "Match direction words.",
        pairs: [
          { left: "¿Dónde está?", right: "Where is…?" },
          { left: "cerca", right: "near" },
          { left: "lejos", right: "far" },
          { left: "a la derecha", right: "to the right" },
          { left: "a la izquierda", right: "to the left" },
        ],
        explanation: "Location & direction basics.",
        wordCardIds: ["donde-esta", "cerca", "lejos", "a-la-derecha", "a-la-izquierda"],
        xp: 4,
      },
      {
        id: "u6l1-8",
        type: "fill-blank",
        prompt: "Fill in the blank.",
        template: "¿Dónde ___ el baño?",
        acceptedAnswers: ["está", "esta", "Está"],
        hint: "is (location)",
        explanation: "¿Dónde está el baño?",
        wordCardIds: ["donde-esta"],
        xp: 3,
      },
    ],
  },
  "u6-l2": {
    id: "u6-l2",
    unitId: "unit-6",
    title: "How do I get there?",
    description: "Centro, metro, todo recto, and asking the way.",
    xpReward: 40,
    exercises: [
      teach("teach-u6l2-como-llego", "como-llego"),
      {
        id: "u6l2-1",
        type: "select",
        prompt: "“How do I get downtown?”",
        options: [
          "¿Cómo llego al centro?",
          "¿Me gusta el centro?",
          "¿Comí el centro?",
          "¿Quiero lejos centro?",
        ],
        correctIndex: 0,
        explanation: "¿Cómo llego al centro?",
        wordCardIds: ["como-llego", "el-centro"],
        xp: 3,
      },
      teach("teach-u6l2-centro", "el-centro"),
      teach("teach-u6l2-metro", "metro"),
      {
        id: "u6l2-2",
        type: "tap-chips",
        prompt: "Build: “I take the metro every day.”",
        chips: ["Tomo", "el", "metro", "todos", "los", "días.", "carro"],
        correctOrder: ["Tomo", "el", "metro", "todos", "los", "días."],
        explanation: "Tomo el metro todos los días.",
        wordCardIds: ["metro", "todos-los-dias"],
        xp: 3,
      },
      teach("teach-u6l2-recto", "todo-recto"),
      {
        id: "u6l2-3",
        type: "situational-choose",
        prompt: "Pick the best directions.",
        situation: "A tourist should keep going straight, then turn right.",
        options: [
          "Todo recto y luego a la derecha.",
          "Me gusta el jugo.",
          "Comí ayer.",
          "La cuenta, por favor.",
        ],
        correctIndex: 0,
        explanation: "Todo recto y luego a la derecha.",
        wordCardIds: ["todo-recto", "a-la-derecha"],
        xp: 4,
      },
      listen(
        "u6l2-4",
        "¿Cómo llego al centro?",
        ["How do I get downtown?", "Where is the bathroom?", "I like downtown.", "I went downtown yesterday."],
        0,
        "¿Cómo llego al centro? = How do I get downtown?",
        ["como-llego", "el-centro"]
      ),
      {
        id: "u6l2-5",
        type: "translate",
        prompt: "Translate: “Keep going straight.”",
        acceptedAnswers: [
          "Sigue todo recto.",
          "Sigue todo recto",
          "Todo recto.",
          "Todo recto",
        ],
        hint: "todo recto",
        explanation: "Sigue todo recto / Todo recto.",
        wordCardIds: ["todo-recto"],
        xp: 4,
      },
      listen(
        "u6l2-6",
        "Voy al centro en metro.",
        ["I'm going downtown by metro.", "I want juice downtown.", "Turn left downtown.", "I woke up downtown."],
        0,
        "Voy al centro en metro.",
        ["el-centro", "metro"]
      ),
      {
        id: "u6l2-7",
        type: "fill-blank",
        prompt: "Fill in the blank.",
        template: "¿Cómo ___ al centro?",
        acceptedAnswers: ["llego", "Llego"],
        hint: "I arrive / I get (to)",
        explanation: "¿Cómo llego al centro?",
        wordCardIds: ["como-llego"],
        xp: 3,
      },
      {
        id: "u6l2-8",
        type: "match-pairs",
        prompt: "Match getting-around phrases.",
        pairs: [
          { left: "el centro", right: "downtown" },
          { left: "metro", right: "subway" },
          { left: "todo recto", right: "straight ahead" },
          { left: "¿Cómo llego a…?", right: "How do I get to…?" },
        ],
        explanation: "Transit & directions.",
        wordCardIds: ["el-centro", "metro", "todo-recto", "como-llego"],
        xp: 4,
      },
    ],
  },
  "u7-l1": {
    id: "u7-l1",
    unitId: "unit-7",
    title: "I ate… today",
    description: "Preterite stories with comer, hablar, ayer, hoy.",
    xpReward: 42,
    exercises: [
      teach("teach-u7l1-comer", "comer"),
      {
        id: "u7l1-1",
        type: "select",
        prompt: "“I ate” (yo, preterite) is…",
        options: ["Comí", "Como", "Comer", "Comía always"],
        correctIndex: 0,
        explanation: "Preterite yo of comer → comí.",
        wordCardIds: ["comer"],
        xp: 3,
      },
      teach("teach-u7l1-hablar-pret", "hablar-preterite"),
      {
        id: "u7l1-2",
        type: "select",
        prompt: "“I spoke / I talked” (yo) is…",
        options: ["Hablé", "Hablo", "Hablaba only", "Hacer"],
        correctIndex: 0,
        explanation: "Regular -ar preterite: hablé.",
        wordCardIds: ["hablar-preterite"],
        xp: 3,
      },
      teach("teach-u7l1-ayer", "ayer"),
      teach("teach-u7l1-hoy", "hoy"),
      {
        id: "u7l1-3",
        type: "tap-chips",
        prompt: "Build: “I ate tacos today.”",
        chips: ["Comí", "tacos", "hoy.", "ayer", "quiero"],
        correctOrder: ["Comí", "tacos", "hoy."],
        explanation: "Comí tacos hoy.",
        wordCardIds: ["comer", "hoy"],
        xp: 3,
      },
      {
        id: "u7l1-4",
        type: "translate",
        prompt: "Translate: “Yesterday I talked with my sister.”",
        acceptedAnswers: [
          "Ayer hablé con mi hermana.",
          "Ayer hable con mi hermana.",
          "Hablé con mi hermana ayer.",
          "Hable con mi hermana ayer.",
        ],
        hint: "hablé",
        explanation: "Ayer hablé con mi hermana.",
        wordCardIds: ["hablar-preterite", "ayer"],
        xp: 4,
      },
      listen(
        "u7l1-5",
        "Comí tacos hoy.",
        ["I ate tacos today.", "I like tacos today.", "I want tacos today.", "Turn right today."],
        0,
        "Comí tacos hoy = I ate tacos today.",
        ["comer", "hoy"]
      ),
      {
        id: "u7l1-6",
        type: "situational-choose",
        prompt: "Pick the best question.",
        situation: "You want to know what a friend ate yesterday (tú).",
        options: [
          "¿Qué comiste ayer?",
          "¿Qué comes carro?",
          "¿Dónde está ayer?",
          "¿Me gusta ayer?",
        ],
        correctIndex: 0,
        explanation: "¿Qué comiste ayer?",
        wordCardIds: ["comer", "ayer"],
        xp: 3,
      },
      {
        id: "u7l1-7",
        type: "fill-blank",
        prompt: "Fill in the blank.",
        template: "Ayer ___ con Ana.",
        acceptedAnswers: ["hablé", "hable", "Hablé"],
        hint: "I talked (preterite)",
        explanation: "Ayer hablé con Ana.",
        wordCardIds: ["hablar-preterite", "ayer"],
        xp: 3,
      },
      {
        id: "u7l1-8",
        type: "match-pairs",
        prompt: "Match preterite forms.",
        pairs: [
          { left: "comí", right: "I ate" },
          { left: "hablé", right: "I spoke" },
          { left: "ayer", right: "yesterday" },
          { left: "hoy", right: "today" },
        ],
        explanation: "Regular preterite storytelling anchors.",
        wordCardIds: ["comer", "hablar-preterite", "ayer", "hoy"],
        xp: 4,
      },
      listen(
        "u7l1-9",
        "¿Qué comiste ayer?",
        ["What did you eat yesterday?", "What do you like yesterday?", "Where is yesterday?", "I want juice yesterday."],
        0,
        "¿Qué comiste ayer?",
        ["comer", "ayer"]
      ),
    ],
  },
  "u7-l2": {
    id: "u7-l2",
    unitId: "unit-7",
    title: "Irregular past hits",
    description: "Fui, hice, tuve, dije — high-frequency preterite irregulars.",
    xpReward: 44,
    exercises: [
      teach("teach-u7l2-ir", "ir"),
      {
        id: "u7l2-1",
        type: "select",
        prompt: "“I went” (yo) is…",
        options: ["Fui", "Voy", "Ir", "Comí"],
        correctIndex: 0,
        explanation: "Ir preterite yo → fui (same form as ser — context decides).",
        wordCardIds: ["ir"],
        xp: 3,
      },
      teach("teach-u7l2-hacer", "hacer"),
      {
        id: "u7l2-2",
        type: "select",
        prompt: "“I did / I made” (yo) is…",
        options: ["Hice", "Hago", "Hacer", "Hablé"],
        correctIndex: 0,
        explanation: "Hacer preterite yo → hice.",
        wordCardIds: ["hacer"],
        xp: 3,
      },
      teach("teach-u7l2-tener-pret", "tener-preterite"),
      teach("teach-u7l2-decir", "decir"),
      {
        id: "u7l2-3",
        type: "tap-chips",
        prompt: "Build: “I went to the supermarket yesterday.”",
        chips: ["Fui", "al", "supermercado", "ayer.", "hice", "jugo"],
        correctOrder: ["Fui", "al", "supermercado", "ayer."],
        explanation: "Fui al supermercado ayer.",
        wordCardIds: ["ir", "ayer"],
        xp: 3,
      },
      {
        id: "u7l2-4",
        type: "translate",
        prompt: "Translate: “What did you do today?” (tú)",
        acceptedAnswers: [
          "¿Qué hiciste hoy?",
          "Que hiciste hoy?",
          "¿Qué hiciste hoy",
          "Qué hiciste hoy",
        ],
        hint: "hiciste",
        explanation: "¿Qué hiciste hoy?",
        wordCardIds: ["hacer", "hoy"],
        xp: 4,
      },
      listen(
        "u7l2-5",
        "Fui al supermercado ayer.",
        ["I went to the supermarket yesterday.", "I like the supermarket.", "I want the check.", "Turn left yesterday."],
        0,
        "Fui al supermercado ayer.",
        ["ir", "ayer"]
      ),
      {
        id: "u7l2-6",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "You had a meeting today and want to say so.",
        options: [
          "Tuve una reunión hoy.",
          "Tengo una reunión ayer.",
          "Me gusta reunión.",
          "Todo recto reunión.",
        ],
        correctIndex: 0,
        explanation: "Tuve una reunión hoy.",
        wordCardIds: ["tener-preterite", "hoy"],
        xp: 3,
      },
      {
        id: "u7l2-7",
        type: "fill-blank",
        prompt: "Fill in the blank.",
        template: "___ la verdad.",
        acceptedAnswers: ["Dije", "dije"],
        hint: "I said (decir)",
        explanation: "Dije la verdad.",
        wordCardIds: ["decir"],
        xp: 3,
      },
      {
        id: "u7l2-8",
        type: "match-pairs",
        prompt: "Match irregular preterites.",
        pairs: [
          { left: "fui", right: "I went" },
          { left: "hice", right: "I did / I made" },
          { left: "tuve", right: "I had" },
          { left: "dije", right: "I said" },
        ],
        explanation: "High-frequency irregular preterites.",
        wordCardIds: ["ir", "hacer", "tener-preterite", "decir"],
        xp: 4,
      },
      listen(
        "u7l2-9",
        "¿Qué hiciste hoy?",
        ["What did you do today?", "What do you like today?", "Where is today?", "I want coffee today."],
        0,
        "¿Qué hiciste hoy?",
        ["hacer", "hoy"]
      ),
      {
        id: "u7l2-10",
        type: "select",
        prompt: "“He/she said” is…",
        options: ["dijo", "dije", "digo", "comí"],
        correctIndex: 0,
        explanation: "decir → él/ella/usted dijo.",
        wordCardIds: ["decir"],
        xp: 3,
      },
    ],
  },
  "u8-l1": {
    id: "u8-l1",
    unitId: "unit-8",
    title: "Plans with ir a / quiero",
    description: "Near future and wants — voy a…, quiero + infinitive.",
    xpReward: 40,
    exercises: [
      teach("teach-u8l1-ir-a", "ir-a"),
      {
        id: "u8l1-1",
        type: "select",
        prompt: "“I'm going to cook tonight” starts with…",
        options: ["Voy a cocinar…", "Fui a cocinar ayer only", "Me gusta a…", "Dije a…"],
        correctIndex: 0,
        explanation: "Voy a + infinitive = near future.",
        wordCardIds: ["ir-a"],
        xp: 3,
      },
      teach("teach-u8l1-quiero-inf", "quiero-inf"),
      {
        id: "u8l1-2",
        type: "tap-chips",
        prompt: "Build: “I want to go out on Friday.”",
        chips: ["Quiero", "salir", "el", "viernes.", "fui", "metro"],
        correctOrder: ["Quiero", "salir", "el", "viernes."],
        explanation: "Quiero salir el viernes.",
        wordCardIds: ["quiero-inf"],
        xp: 3,
      },
      {
        id: "u8l1-3",
        type: "translate",
        prompt: "Translate: “Are you going to come?” (tú)",
        acceptedAnswers: ["¿Vas a venir?", "Vas a venir?", "¿Vas a venir", "Vas a venir"],
        hint: "vas a + venir",
        explanation: "¿Vas a venir?",
        wordCardIds: ["ir-a"],
        xp: 4,
      },
      listen(
        "u8l1-4",
        "Voy a cocinar esta noche.",
        ["I'm going to cook tonight.", "I cooked tonight.", "I like cooking the check.", "Turn right tonight."],
        0,
        "Voy a cocinar esta noche.",
        ["ir-a"]
      ),
      {
        id: "u8l1-5",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "You don't want to arrive late.",
        options: [
          "No quiero llegar tarde.",
          "No comí llegar tarde.",
          "Está lejos llegar.",
          "La cuenta llegar.",
        ],
        correctIndex: 0,
        explanation: "No quiero llegar tarde.",
        wordCardIds: ["quiero-inf"],
        xp: 3,
      },
      {
        id: "u8l1-6",
        type: "fill-blank",
        prompt: "Fill in the blank.",
        template: "Voy ___ estudiar esta noche.",
        acceptedAnswers: ["a", "A"],
        hint: "ir a + infinitive",
        explanation: "Voy a estudiar esta noche.",
        wordCardIds: ["ir-a"],
        xp: 3,
      },
      {
        id: "u8l1-7",
        type: "match-pairs",
        prompt: "Match plan phrases.",
        pairs: [
          { left: "Voy a cocinar", right: "I'm going to cook" },
          { left: "Quiero salir", right: "I want to go out" },
          { left: "¿Vas a venir?", right: "Are you going to come?" },
          { left: "No quiero llegar tarde", right: "I don't want to arrive late" },
        ],
        explanation: "ir a vs quiero + inf.",
        wordCardIds: ["ir-a", "quiero-inf"],
        xp: 4,
      },
      listen(
        "u8l1-8",
        "¿Vas a venir?",
        ["Are you going to come?", "Did you come yesterday?", "Do you like juice?", "Where is the metro?"],
        0,
        "¿Vas a venir?",
        ["ir-a"]
      ),
    ],
  },
  "u8-l2": {
    id: "u8-l2",
    unitId: "unit-8",
    title: "Invites & soft no",
    description: "¿Te gustaría…?, me parece, and polite refusals.",
    xpReward: 40,
    exercises: [
      teach("teach-u8l2-gustaria", "te-gustaria"),
      {
        id: "u8l2-1",
        type: "select",
        prompt: "Polite “Would you like to get a coffee?”",
        options: [
          "¿Te gustaría tomar un café?",
          "¿Comiste un café?",
          "¿Dónde está un café ayer?",
          "Fui un café.",
        ],
        correctIndex: 0,
        explanation: "¿Te gustaría tomar un café?",
        wordCardIds: ["te-gustaria", "cafe"],
        xp: 3,
      },
      teach("teach-u8l2-parece", "me-parece"),
      {
        id: "u8l2-2",
        type: "select",
        prompt: "“Sounds good to me” is…",
        options: ["Me parece bien.", "Me despierto bien.", "Comí bien ayer only", "Todo recto bien"],
        correctIndex: 0,
        explanation: "Me parece bien — soft agreement.",
        wordCardIds: ["me-parece"],
        xp: 3,
      },
      teach("teach-u8l2-otra", "otra-vez"),
      {
        id: "u8l2-3",
        type: "situational-choose",
        prompt: "Pick the soft refusal.",
        situation: "A friend invites you out but you can't tonight.",
        options: [
          "Gracias, pero ahora no puedo.",
          "Nunca hables conmigo.",
          "¿Dónde está el baño? No.",
          "Comí tu invitación.",
        ],
        correctIndex: 0,
        explanation: "Gracias, pero ahora no puedo — polite and clear.",
        wordCardIds: ["otra-vez"],
        xp: 4,
      },
      {
        id: "u8l2-4",
        type: "tap-chips",
        prompt: "Build: “Maybe another day. Thanks!”",
        chips: ["Tal", "vez", "otro", "día.", "¡Gracias!", "metro"],
        correctOrder: ["Tal", "vez", "otro", "día.", "¡Gracias!"],
        explanation: "Tal vez otro día. ¡Gracias!",
        wordCardIds: ["otra-vez"],
        xp: 3,
      },
      listen(
        "u8l2-5",
        "¿Te gustaría tomar un café?",
        ["Would you like to get a coffee?", "Did you drink coffee yesterday?", "Where is the café?", "I want the check."],
        0,
        "¿Te gustaría tomar un café?",
        ["te-gustaria"]
      ),
      {
        id: "u8l2-6",
        type: "translate",
        prompt: "Translate: “It seems like a good idea to me.”",
        acceptedAnswers: [
          "Me parece una buena idea.",
          "Me parece una buena idea",
          "Me parece buena idea.",
          "Me parece buena idea",
        ],
        hint: "Me parece…",
        explanation: "Me parece una buena idea.",
        wordCardIds: ["me-parece"],
        xp: 4,
      },
      {
        id: "u8l2-7",
        type: "fill-blank",
        prompt: "Fill in the blank.",
        template: "¿Te ___ ir al cine?",
        acceptedAnswers: ["gustaría", "gustaria", "Gustaría"],
        hint: "would like",
        explanation: "¿Te gustaría ir al cine?",
        wordCardIds: ["te-gustaria"],
        xp: 3,
      },
      {
        id: "u8l2-8",
        type: "match-pairs",
        prompt: "Match social phrases.",
        pairs: [
          { left: "¿Te gustaría…?", right: "Would you like…?" },
          { left: "Me parece bien", right: "Sounds good to me" },
          { left: "ahora no puedo", right: "I can't right now" },
          { left: "Tal vez otro día", right: "Maybe another day" },
        ],
        explanation: "Invitations and soft refusals.",
        wordCardIds: ["te-gustaria", "me-parece", "otra-vez"],
        xp: 4,
      },
      listen(
        "u8l2-9",
        "Tal vez otro día. ¡Gracias!",
        ["Maybe another day. Thanks!", "I went another day.", "Where is another day?", "I ate thanks yesterday."],
        0,
        "Soft refusal with gratitude.",
        ["otra-vez"]
      ),
    ],
  },
};

export const INTERMEDIATE_UNITS_META = [
  {
    id: "unit-4",
    number: 4,
    title: "Daily life",
    description: "Routines, departamento, carro — deeper than Unit 1.",
    lessonIds: ["u4-l1", "u4-l2"],
    unlocked: true,
    track: "intermediate" as const,
  },
  {
    id: "unit-5",
    number: 5,
    title: "Food & ordering",
    description: "Me gusta vs quiero, café/jugo, usted with servers.",
    lessonIds: ["u5-l1", "u5-l2"],
    unlocked: true,
    track: "intermediate" as const,
  },
  {
    id: "unit-6",
    number: 6,
    title: "Getting around",
    description: "Directions, centro, metro, cerca/lejos.",
    lessonIds: ["u6-l1", "u6-l2"],
    unlocked: true,
    track: "intermediate" as const,
  },
  {
    id: "unit-7",
    number: 7,
    title: "What I did",
    description: "Preterite focus — Comí… hoy; fui, hice, tuve, dije.",
    lessonIds: ["u7-l1", "u7-l2"],
    unlocked: true,
    track: "intermediate" as const,
  },
  {
    id: "unit-8",
    number: 8,
    title: "Plans & invitations",
    description: "Quiero + inf, ir a, soft refusals and opinions.",
    lessonIds: ["u8-l1", "u8-l2"],
    unlocked: true,
    track: "intermediate" as const,
  },
];
