/**
 * Unit 3 — Numbers that matter (lessons 4–12). Spanish.
 * Existing u3-l1…u3-l3 stay in mock-data.ts (audio voice indices stable).
 */
import type { Lesson, WordCard } from "../types";
import { audioSrcFor, voiceForIndex, type AudioVoice } from "../audio";
import { dlg } from "./dialogues";

function teach(
  id: string,
  wordCardId: string
): import("../types").TeachExercise {
  return {
    id,
    type: "teach",
    prompt: "New word — learn it, then practice.",
    explanation: "",
    wordCardId,
    wordCardIds: [wordCardId],
    xp: 0,
  };
}

let listenVoiceIndex = 3200;

function listen(
  id: string,
  audioText: string,
  options: string[],
  correctIndex: number,
  explanation: string,
  wordCardIds: string[],
  xp = 3
): import("../types").ListeningChooseExercise {
  const voice = voiceForIndex(listenVoiceIndex);
  listenVoiceIndex += 1;
  return {
    id,
    type: "listening-choose",
    prompt: "What did you hear?",
    audioText,
    audioSrc: audioSrcFor(audioText, voice),
    options,
    correctIndex,
    explanation,
    wordCardIds,
    xp,
  };
}

function cloze(
  id: string,
  template: string,
  acceptedAnswers: string[],
  explanation: string,
  wordCardIds: string[],
  opts: {
    hint?: string;
    audioText: string;
    voice?: AudioVoice;
    storyLabel?: string;
    xp?: number;
  }
): import("../types").ClozeExercise {
  const voice = opts.voice ?? "f";
  return {
    id,
    type: "cloze",
    prompt: "Fill the blank from the story",
    template,
    acceptedAnswers,
    hint: opts.hint,
    explanation,
    wordCardIds,
    audioText: opts.audioText,
    audioSrc: audioSrcFor(opts.audioText, voice),
    storyLabel: opts.storyLabel ?? "From the story",
    xp: opts.xp ?? 3,
  };
}

function storyListen(
  id: string,
  title: string,
  lines: { text: string; en?: string; voice?: AudioVoice }[],
  questions: {
    prompt: string;
    options: string[];
    correctIndex: number;
    explanation?: string;
  }[],
  wordCardIds: string[],
  explanation = "Story comprehension — replay anytime.",
  xp = 10
): import("../types").StoryListenExercise {
  const withVoices = lines.map((line, i) => ({
    text: line.text,
    en: line.en,
    voice: line.voice ?? voiceForIndex(i),
  }));
  return {
    id,
    type: "story-listen",
    prompt: "Listen to the story, then answer",
    title,
    lines: withVoices,
    questions,
    explanation,
    wordCardIds,
    xp,
  };
}




export const UNIT3_WORD_CARDS: Record<string, WordCard> = {
  "cuatro": {
    id: "cuatro",
    lemma: "cuatro",
    pos: "noun",
    gender: "n/a",
    gloss: "four",
    meaningSummary:
      "Four. Cuatro pesos / Tengo cuatro.",
    examples: [
      { es: "Tengo cuatro.", en: "I have four." },
      { es: "Cuesta cuatro pesos.", en: "It costs four pesos." },
    ],
    useWhen: "Counting and everyday amounts.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A1",
  },
  "seis": {
    id: "seis",
    lemma: "seis",
    pos: "noun",
    gender: "n/a",
    gloss: "six",
    meaningSummary:
      "Six. Seis dólares / Quiero seis.",
    examples: [
      { es: "Quiero seis.", en: "I want six." },
      { es: "Cuesta seis dólares.", en: "It costs six dollars." },
    ],
    useWhen: "Counting and everyday amounts.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A1",
  },
  "siete": {
    id: "siete",
    lemma: "siete",
    pos: "noun",
    gender: "n/a",
    gloss: "seven",
    meaningSummary:
      "Seven. Siete pesos / Tengo siete.",
    examples: [
      { es: "Tengo siete.", en: "I have seven." },
      { es: "Son siete pesos.", en: "It is seven pesos." },
    ],
    useWhen: "Counting and everyday amounts.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A1",
  },
  "ocho": {
    id: "ocho",
    lemma: "ocho",
    pos: "noun",
    gender: "n/a",
    gloss: "eight",
    meaningSummary:
      "Eight. Ocho dólares / Tengo ocho.",
    examples: [
      { es: "Cuesta ocho dólares.", en: "It costs eight dollars." },
      { es: "Tengo ocho.", en: "I have eight." },
    ],
    useWhen: "Counting and everyday amounts.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A1",
  },
  "nueve": {
    id: "nueve",
    lemma: "nueve",
    pos: "noun",
    gender: "n/a",
    gloss: "nine",
    meaningSummary:
      "Nine. Nueve pesos / Tengo nueve.",
    examples: [
      { es: "Cuesta nueve pesos.", en: "It costs nine pesos." },
      { es: "Tengo nueve.", en: "I have nine." },
    ],
    useWhen: "Counting and everyday amounts.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A1",
  },
  "once": {
    id: "once",
    lemma: "once",
    pos: "noun",
    gender: "n/a",
    gloss: "eleven",
    meaningSummary:
      "Eleven. Once — ages, counts, and prices.",
    examples: [
      { es: "Tengo once.", en: "I have eleven." },
      { es: "Cuesta once pesos.", en: "It costs eleven pesos." },
    ],
    useWhen: "Counting and everyday amounts.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A1",
  },
  "doce": {
    id: "doce",
    lemma: "doce",
    pos: "noun",
    gender: "n/a",
    gloss: "twelve",
    meaningSummary:
      "Twelve. Doce pesos is a common small price.",
    examples: [
      { es: "Cuesta doce pesos.", en: "It costs twelve pesos." },
      { es: "Tengo doce.", en: "I have twelve." },
    ],
    useWhen: "Counting and everyday amounts.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A1",
  },
  "trece": {
    id: "trece",
    lemma: "trece",
    pos: "noun",
    gender: "n/a",
    gloss: "thirteen",
    meaningSummary:
      "Thirteen. Trece dólares / Tengo trece.",
    examples: [
      { es: "Cuesta trece dólares.", en: "It costs thirteen dollars." },
      { es: "Tengo trece.", en: "I have thirteen." },
    ],
    useWhen: "Counting and everyday amounts.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A1",
  },
  "catorce": {
    id: "catorce",
    lemma: "catorce",
    pos: "noun",
    gender: "n/a",
    gloss: "fourteen",
    meaningSummary:
      "Fourteen. Catorce / Tengo catorce años.",
    examples: [
      { es: "Tengo catorce.", en: "I have fourteen." },
      { es: "Cuesta catorce pesos.", en: "It costs fourteen pesos." },
    ],
    useWhen: "Counting and everyday amounts.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A1",
  },
  "quince": {
    id: "quince",
    lemma: "quince",
    pos: "noun",
    gender: "n/a",
    gloss: "fifteen",
    meaningSummary:
      "Fifteen. Quince pesos — very common amount.",
    examples: [
      { es: "Cuesta quince pesos.", en: "It costs fifteen pesos." },
      { es: "Tengo quince.", en: "I have fifteen." },
    ],
    useWhen: "Counting and everyday amounts.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A1",
  },
  "dieciseis": {
    id: "dieciseis",
    lemma: "dieciséis",
    pos: "noun",
    gender: "n/a",
    gloss: "sixteen",
    meaningSummary:
      "Sixteen. Written dieciséis with accent.",
    examples: [
      { es: "Tengo dieciséis años.", en: "I am sixteen years old." },
      { es: "Cuesta dieciséis pesos.", en: "It costs sixteen pesos." },
    ],
    useWhen: "Counting and everyday amounts.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A1",
  },
  "diecisiete": {
    id: "diecisiete",
    lemma: "diecisiete",
    pos: "noun",
    gender: "n/a",
    gloss: "seventeen",
    meaningSummary:
      "Seventeen. Diecisiete for age and counts.",
    examples: [
      { es: "Tengo diecisiete años.", en: "I am seventeen." },
      { es: "Cuesta diecisiete pesos.", en: "It costs seventeen pesos." },
    ],
    useWhen: "Counting and everyday amounts.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A1",
  },
  "dieciocho": {
    id: "dieciocho",
    lemma: "dieciocho",
    pos: "noun",
    gender: "n/a",
    gloss: "eighteen",
    meaningSummary:
      "Eighteen. Dieciocho años is a common age line.",
    examples: [
      { es: "Tengo dieciocho años.", en: "I am eighteen years old." },
      { es: "Cuesta dieciocho dólares.", en: "It costs eighteen dollars." },
    ],
    useWhen: "Counting and everyday amounts.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A1",
  },
  "diecinueve": {
    id: "diecinueve",
    lemma: "diecinueve",
    pos: "noun",
    gender: "n/a",
    gloss: "nineteen",
    meaningSummary:
      "Nineteen. Diecinueve — last step before veinte.",
    examples: [
      { es: "Tengo diecinueve.", en: "I have nineteen." },
      { es: "Cuesta diecinueve pesos.", en: "It costs nineteen pesos." },
    ],
    useWhen: "Counting and everyday amounts.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A1",
  },
  numero: {
    id: "numero",
    lemma: "número",
    pos: "noun",
    gender: "m",
    gloss: "number",
    meaningSummary:
      "Number — phone or otherwise. ¿Cuál es tu número? / Mi número es…",
    examples: [
      { es: "¿Cuál es tu número?", en: "What's your number?" },
      { es: "Mi número es…", en: "My number is…" },
    ],
    useWhen: "Asking for or giving a number (often phone).",
    dontUseWhen: "For how-many questions prefer ¿cuántos? / ¿cuántas?",
    formality: "neutral",
    cefr: "A1",
  },
  "mi-numero": {
    id: "mi-numero",
    lemma: "mi número",
    pos: "phrase",
    gender: "n/a",
    gloss: "my number",
    meaningSummary:
      "Handy chunk for phone exchange: Mi número es… Pair with celular.",
    examples: [
      { es: "Mi número es cinco cinco cinco…", en: "My number is five five five…" },
      { es: "Te paso mi número.", en: "I'll give you my number." },
    ],
    useWhen: "Sharing your phone number.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A1",
  },
};

export const UNIT3_LESSONS: Record<string, Lesson> = {
  "u3-l4": {
    id: "u3-l4",
    unitId: "unit-3",
    title: "Numbers 1–10 deepen",
    description: "Fill the gaps: cuatro, seis, siete, ocho, nueve + review.",
    xpReward: 32,
    exercises: [
      teach("teach-u3l4-cuatro", "cuatro"),
      teach("teach-u3l4-seis", "seis"),
      {
        id: "u3l4-1",
        type: "select",
        prompt: "Which means “four”?",
        options: ["cuatro", "ocho", "veinte", "gratis"],
        correctIndex: 0,
        explanation: "Cuatro = 4.",
        wordCardIds: ["cuatro"],
        xp: 3,
      },
      teach("teach-u3l4-siete", "siete"),
      teach("teach-u3l4-ocho", "ocho"),
      teach("teach-u3l4-nueve", "nueve"),
      {
        id: "u3l4-2",
        type: "select",
        prompt: "Which means “eight”?",
        options: ["seis", "ocho", "uno", "cien"],
        correctIndex: 1,
        explanation: "Ocho = 8.",
        wordCardIds: ["ocho"],
        xp: 3,
      },
      {
        id: "u3l4-3",
        type: "tap-chips",
        prompt: "Build: “one, two, three, four”",
        chips: ["uno,", "dos,", "tres,", "cuatro", "veinte", "mal"],
        correctOrder: ["uno,", "dos,", "tres,", "cuatro"],
        explanation: "Uno, dos, tres, cuatro.",
        wordCardIds: ["uno", "dos", "tres", "cuatro"],
        xp: 4,
      },
      listen(
        "u3l4-4",
        "cinco, seis, siete",
        ["five, six, seven", "one, two, three", "eight, nine, ten", "twenty only"],
        0,
        "cinco, seis, siete = 5, 6, 7.",
        ["cinco", "seis", "siete"]
      ),
      {
        id: "u3l4-5",
        type: "fill-blank",
        prompt: "Complete the Spanish.",
        template: "Tengo ___.",
        englishPrompt: "I have nine.",
        acceptedAnswers: ["nueve", "Nueve"],
        hint: "9",
        explanation: "Tengo nueve.",
        wordCardIds: ["nueve", "tener"],
        xp: 3,
      },
      {
        id: "u3l4-6",
        type: "translate",
        prompt: "Translate to Spanish: “six”",
        acceptedAnswers: ["seis", "Seis"],
        hint: "6",
        explanation: "Seis.",
        wordCardIds: ["seis"],
        xp: 3,
      },
      {
        id: "u3l4-7",
        type: "match-pairs",
        prompt: "Match 1–10 fillers.",
        pairs: [
          { left: "cuatro", right: "4" },
          { left: "seis", right: "6" },
          { left: "siete", right: "7" },
          { left: "nueve", right: "9" },
        ],
        explanation: "The missing 1–10 pieces.",
        wordCardIds: ["cuatro", "seis", "siete", "nueve"],
        xp: 4,
      },
      {
        id: "u3l4-8",
        type: "situational-choose",
        prompt: "Someone asks how many tacos (you want 8):",
        situation: "Street stall: “¿Cuántos?”",
        options: ["Ocho, por favor.", "Hola ocho soy.", "Vivo ocho.", "Perdón ocho ciudad."],
        correctIndex: 0,
        explanation: "Ocho, por favor.",
        wordCardIds: ["ocho", "por-favor"],
        xp: 3,
      },
    ],
  },

  "u3-l5": {
    id: "u3-l5",
    unitId: "unit-3",
    title: "Numbers 11–20",
    description: "Once through veinte — teens you’ll hear in ages and prices.",
    xpReward: 34,
    exercises: [
      teach("teach-u3l5-once", "once"),
      teach("teach-u3l5-doce", "doce"),
      teach("teach-u3l5-trece", "trece"),
      {
        id: "u3l5-1",
        type: "select",
        prompt: "Twelve is:",
        options: ["doce", "dos", "veinte", "diez"],
        correctIndex: 0,
        explanation: "Doce = 12.",
        wordCardIds: ["doce"],
        xp: 3,
      },
      teach("teach-u3l5-catorce", "catorce"),
      teach("teach-u3l5-quince", "quince"),
      {
        id: "u3l5-2",
        type: "select",
        prompt: "Fifteen is:",
        options: ["quince", "cinco", "cincuenta", "uno"],
        correctIndex: 0,
        explanation: "Quince = 15.",
        wordCardIds: ["quince"],
        xp: 3,
      },
      teach("teach-u3l5-dieciseis", "dieciseis"),
      teach("teach-u3l5-dieciocho", "dieciocho"),
      {
        id: "u3l5-3",
        type: "tap-chips",
        prompt: "Build: “eighteen”",
        chips: ["dieciocho", "ocho", "diez", "carro"],
        correctOrder: ["dieciocho"],
        explanation: "Dieciocho = 18.",
        wordCardIds: ["dieciocho"],
        xp: 3,
      },
      listen(
        "u3l5-4",
        "once, doce, trece",
        ["eleven, twelve, thirteen", "one, two, three", "twenty only", "nine, ten"],
        0,
        "once, doce, trece = 11, 12, 13.",
        ["once", "doce", "trece"]
      ),
      {
        id: "u3l5-5",
        type: "fill-blank",
        prompt: "Complete the Spanish.",
        template: "Cuesta ___ pesos.",
        englishPrompt: "It costs fifteen pesos.",
        acceptedAnswers: ["quince", "Quince"],
        hint: "15",
        explanation: "Cuesta quince pesos.",
        wordCardIds: ["quince", "pesos", "cuanto-cuesta"],
        xp: 3,
      },
      {
        id: "u3l5-6",
        type: "translate",
        prompt: "Translate to Spanish: “twenty”",
        acceptedAnswers: ["veinte", "Veinte"],
        hint: "20",
        explanation: "Veinte.",
        wordCardIds: ["veinte"],
        xp: 3,
      },
      {
        id: "u3l5-7",
        type: "match-pairs",
        prompt: "Match the teens.",
        pairs: [
          { left: "once", right: "11" },
          { left: "catorce", right: "14" },
          { left: "dieciséis", right: "16" },
          { left: "diecinueve", right: "19" },
        ],
        explanation: "Teens map.",
        wordCardIds: ["once", "catorce", "dieciseis", "diecinueve"],
        xp: 4,
      },
      teach("teach-u3l5-diecisiete", "diecisiete"),
      teach("teach-u3l5-diecinueve", "diecinueve"),
      {
        id: "u3l5-8",
        type: "situational-choose",
        prompt: "Price is 16 pesos:",
        situation: "Vendor: “¿Cuánto cuesta?” You read the sign.",
        options: [
          "Dieciséis pesos.",
          "Sesenta ciudad.",
          "Hablo dieciséis.",
          "Soy dieciséis pesos.",
        ],
        correctIndex: 0,
        explanation: "Dieciséis pesos.",
        wordCardIds: ["dieciseis", "pesos"],
        xp: 3,
      },
    ],
  },

  "u3-l6": {
    id: "u3-l6",
    unitId: "unit-3",
    title: "Phone numbers practice",
    description: "Celular + número — dig through spoken digits.",
    xpReward: 30,
    exercises: [
      teach("teach-u3l6-numero", "numero"),
      teach("teach-u3l6-mi-numero", "mi-numero"),
      {
        id: "u3l6-1",
        type: "select",
        prompt: "Everyday word for cell phone:",
        options: ["celular", "móvil only forever", "carro", "gratis"],
        correctIndex: 0,
        explanation: "Celular is the everyday word for cell phone here.",
        wordCardIds: ["celular"],
        xp: 3,
      },
      {
        id: "u3l6-2",
        type: "select",
        prompt: "“What's your number?” closest chunk:",
        options: ["¿Cuál es tu número?", "¿Cuánto es tu ciudad?", "¿Cómo estás número?", "¿De dónde número?"],
        correctIndex: 0,
        explanation: "¿Cuál es tu número?",
        wordCardIds: ["numero"],
        xp: 3,
      },
      {
        id: "u3l6-3",
        type: "tap-chips",
        prompt: "Build: “My number is…”",
        chips: ["Mi", "número", "es…", "ciudad", "mal"],
        correctOrder: ["Mi", "número", "es…"],
        explanation: "Mi número es…",
        wordCardIds: ["mi-numero", "numero"],
        xp: 4,
      },
      listen(
        "u3l6-4",
        "cinco cinco cinco",
        ["five five five", "ten ten ten", "please please", "hello hello"],
        0,
        "Digits often come in groups: cinco cinco cinco…",
        ["cinco"]
      ),
      {
        id: "u3l6-5",
        type: "fill-blank",
        prompt: "Complete the Spanish.",
        template: "Mi ___ es…",
        englishPrompt: "My number is…",
        acceptedAnswers: ["número", "numero", "Número"],
        hint: "number",
        explanation: "Mi número es…",
        wordCardIds: ["mi-numero", "numero"],
        xp: 3,
      },
      {
        id: "u3l6-6",
        type: "situational-choose",
        prompt: "Friend wants your cell:",
        situation: "“¿Me pasas tu celular?”",
        options: [
          "Sí. Mi número es…",
          "Sí. Soy de número.",
          "Sí. Cuesta celular.",
          "Sí. Hablo gratis número.",
        ],
        correctIndex: 0,
        explanation: "Mi número es…",
        wordCardIds: ["celular", "mi-numero"],
        xp: 3,
      },
      {
        id: "u3l6-7",
        type: "translate",
        prompt: "Translate to Spanish: “cell phone”",
        acceptedAnswers: ["celular", "el celular", "mi celular", "Celular"],
        hint: "everyday word",
        explanation: "Celular.",
        wordCardIds: ["celular"],
        xp: 3,
      },
      {
        id: "u3l6-match",
        type: "match-pairs",
        prompt: "Phone matches.",
        pairs: [
          { left: "celular", right: "cell phone" },
          { left: "número", right: "number" },
          { left: "Mi número es…", right: "My number is…" },
          { left: "cinco", right: "5" },
        ],
        explanation: "Phone exchange basics.",
        wordCardIds: ["celular", "numero", "mi-numero", "cinco"],
        xp: 4,
      },
    ],
  },

  "u3-l7": {
    id: "u3-l7",
    unitId: "unit-3",
    title: "Age with tener",
    description: "¿Cuántos años tienes? — ages use tener, not ser.",
    xpReward: 30,
    exercises: [
      {
        id: "u3l7-1",
        type: "select",
        prompt: "How do you ask “How old are you?” (tú)",
        options: [
          "¿Cuántos años tienes?",
          "¿Cuántos años eres?",
          "¿Cómo te llamas años?",
          "¿De dónde años?",
        ],
        correctIndex: 0,
        explanation: "Spanish uses tener for age: ¿Cuántos años tienes?",
        wordCardIds: ["cuantos-anos", "tener"],
        xp: 3,
      },
      {
        id: "u3l7-2",
        type: "situational-choose",
        prompt: "You’re 18:",
        situation: "Someone asks ¿Cuántos años tienes?",
        options: [
          "Tengo dieciocho años.",
          "Soy dieciocho años.",
          "Vivo dieciocho años.",
          "Hablo dieciocho años.",
        ],
        correctIndex: 0,
        explanation: "Tengo + number + años.",
        wordCardIds: ["tener", "dieciocho", "cuantos-anos"],
        xp: 3,
      },
      {
        id: "u3l7-3",
        type: "tap-chips",
        prompt: "Build: “I am twenty years old.”",
        chips: ["Tengo", "veinte", "años", "soy", "ciudad"],
        correctOrder: ["Tengo", "veinte", "años"],
        explanation: "Tengo veinte años — not soy veinte.",
        wordCardIds: ["tener", "veinte", "cuantos-anos"],
        xp: 4,
      },
      listen(
        "u3l7-4",
        "Tengo dieciséis años",
        ["I am sixteen years old", "It costs sixteen", "My name is sixteen", "See you at sixteen"],
        0,
        "Tengo dieciséis años.",
        ["tener", "dieciseis", "cuantos-anos"]
      ),
      {
        id: "u3l7-5",
        type: "fill-blank",
        prompt: "Complete the Spanish.",
        template: "___ quince años.",
        englishPrompt: "I am fifteen years old.",
        acceptedAnswers: ["Tengo", "tengo"],
        hint: "I have (age)",
        explanation: "Tengo quince años.",
        wordCardIds: ["tener", "quince"],
        xp: 3,
      },
      {
        id: "u3l7-6",
        type: "translate",
        prompt: "Translate to Spanish: “How old are you?”",
        acceptedAnswers: [
          "cuántos años tienes",
          "cuantos anos tienes",
          "¿cuántos años tienes?",
          "¿cuantos anos tienes?",
        ],
        hint: "cuántos años tienes",
        explanation: "¿Cuántos años tienes?",
        wordCardIds: ["cuantos-anos"],
        xp: 3,
      },
      {
        id: "u3l7-7",
        type: "select",
        prompt: "Wrong pattern to avoid:",
        options: ["Soy veinte años", "Tengo veinte años", "Tengo quince años", "Tengo dieciocho años"],
        correctIndex: 0,
        explanation: "Don’t use ser for age — use tener.",
        wordCardIds: ["tener", "cuantos-anos"],
        xp: 3,
      },
      {
        id: "u3l7-match",
        type: "match-pairs",
        prompt: "Age matches.",
        pairs: [
          { left: "¿Cuántos años tienes?", right: "How old are you?" },
          { left: "Tengo veinte años", right: "I am 20" },
          { left: "dieciocho", right: "18" },
          { left: "quince", right: "15" },
        ],
        explanation: "Age toolkit.",
        wordCardIds: ["cuantos-anos", "tener", "dieciocho", "quince"],
        xp: 4,
      },
      dlg("dlg-u3-age"),
      {
        id: "u3l7-p1",
        type: "fill-blank",
        prompt: "Complete the sentence.",
        template: "___ veinticinco años.",
        englishPrompt: "I am twenty-five years old.",
        acceptedAnswers: ["Tengo", "tengo"],
        explanation: "Age uses tener, never ser.",
        wordCardIds: ["tener"],
        xp: 3,
      },
      {
        id: "u3l7-p2",
        type: "select",
        prompt: "Which question asks someone's age?",
        options: [
          "¿Cuántos años tienes?",
          "¿Cuánto cuesta?",
          "¿De dónde eres?",
          "¿Cómo te llamas?",
        ],
        correctIndex: 0,
        explanation: "Cuántos años tienes asks for age.",
        wordCardIds: ["tener", "numeros"],
        xp: 3,
      },
      {
        id: "u3l7-p3",
        type: "translate",
        prompt: "Say in Spanish: “She is thirty years old.”",
        acceptedAnswers: ["Ella tiene treinta anos.", "Tiene treinta anos.", "Ella tiene treinta", "Tiene treinta"],
        explanation: "Third person of tener is tiene.",
        wordCardIds: ["tener", "numeros"],
        xp: 4,
      },
    ],
  },

  "u3-l8": {
    id: "u3-l8",
    unitId: "unit-3",
    title: "Prices & cuánto review",
    description: "¿Cuánto cuesta? with pesos, dólares, and gratis.",
    xpReward: 30,
    exercises: [
      {
        id: "u3l8-1",
        type: "select",
        prompt: "“How much does it cost?”",
        options: ["¿Cuánto cuesta?", "¿Cuántos años?", "¿Cómo te llamas?", "¿Qué tal cuesta?"],
        correctIndex: 0,
        explanation: "¿Cuánto cuesta?",
        wordCardIds: ["cuanto-cuesta"],
        xp: 3,
      },
      {
        id: "u3l8-2",
        type: "situational-choose",
        prompt: "It's free:",
        situation: "Market sample tray — no charge.",
        options: ["Es gratis.", "Es veinte años.", "Es celular.", "Es me llamo."],
        correctIndex: 0,
        explanation: "Es gratis.",
        wordCardIds: ["gratis"],
        xp: 3,
      },
      {
        id: "u3l8-3",
        type: "tap-chips",
        prompt: "Build: “It costs ten pesos.”",
        chips: ["Cuesta", "diez", "pesos", "dólares", "mal"],
        correctOrder: ["Cuesta", "diez", "pesos"],
        explanation: "Cuesta diez pesos.",
        wordCardIds: ["cuanto-cuesta", "diez", "pesos"],
        xp: 4,
      },
      listen(
        "u3l8-4",
        "Cuesta veinte dólares",
        ["It costs twenty dollars", "I am twenty dollars", "See you dollars", "My name is twenty"],
        0,
        "Cuesta veinte dólares.",
        ["cuanto-cuesta", "veinte", "dolares"]
      ),
      {
        id: "u3l8-5",
        type: "fill-blank",
        prompt: "Complete the Spanish.",
        template: "Cuesta doce ___.",
        englishPrompt: "It costs twelve pesos.",
        acceptedAnswers: ["pesos", "Pesos"],
        hint: "currency word",
        explanation: "Cuesta doce pesos.",
        wordCardIds: ["pesos", "doce"],
        xp: 3,
      },
      {
        id: "u3l8-6",
        type: "translate",
        prompt: "Translate to Spanish: “How much does it cost?”",
        acceptedAnswers: ["cuánto cuesta", "cuanto cuesta", "¿cuánto cuesta?", "¿cuanto cuesta?"],
        hint: "cuánto cuesta",
        explanation: "¿Cuánto cuesta?",
        wordCardIds: ["cuanto-cuesta"],
        xp: 3,
      },
      {
        id: "u3l8-7",
        type: "select",
        prompt: "Dólares are:",
        options: ["dollars", "only Mexican coins forever", "goodbyes", "languages"],
        correctIndex: 0,
        explanation: "Dólares = dollars.",
        wordCardIds: ["dolares"],
        xp: 3,
      },
      {
        id: "u3l8-match",
        type: "match-pairs",
        prompt: "Price matches.",
        pairs: [
          { left: "¿Cuánto cuesta?", right: "How much is it?" },
          { left: "pesos", right: "pesos (currency)" },
          { left: "dólares", right: "dollars" },
          { left: "gratis", right: "free" },
        ],
        explanation: "Money talk basics.",
        wordCardIds: ["cuanto-cuesta", "pesos", "dolares", "gratis"],
        xp: 4,
      },
      dlg("dlg-u3-market"),
      {
        id: "u3l8-p1",
        type: "select",
        prompt: "Which one asks the price of several juices?",
        options: [
          "¿Cuánto cuestan los jugos?",
          "¿Cuánto cuesta los jugos?",
          "¿Cuántos años cuestan?",
          "¿Cómo cuestan los jugos?",
        ],
        correctIndex: 0,
        explanation: "Plural subject takes cuestan.",
        wordCardIds: ["cuanto-cuesta", "jugo"],
        xp: 3,
      },
      {
        id: "u3l8-p2",
        type: "tap-chips",
        prompt: "Build: “How much does the coffee cost?”",
        chips: ["¿Cuánto", "cuesta", "el", "café?", "cuestan", "años"],
        correctOrder: ["¿Cuánto", "cuesta", "el", "café?"],
        explanation: "One item, so cuesta.",
        wordCardIds: ["cuanto-cuesta"],
        xp: 3,
      },
      {
        id: "u3l8-p3",
        type: "fill-blank",
        prompt: "Complete the sentence.",
        template: "___ diez pesos.",
        englishPrompt: "It costs ten pesos.",
        acceptedAnswers: ["Cuesta", "cuesta"],
        explanation: "One item costs: cuesta.",
        wordCardIds: ["cuanto-cuesta", "pesos"],
        xp: 3,
      },
    ],
  },

  "u3-l9": {
    id: "u3-l9",
    unitId: "unit-3",
    title: "Story: Buying fruit",
    description: "A tiny market story with numbers and prices + cloze.",
    xpReward: 40,
    exercises: [
      storyListen(
        "u3l9-story",
        "En el mercado",
        [
          { text: "Hola, buenos días.", en: "Hello, good morning." },
          { text: "¿Cuánto cuesta?", en: "How much does it cost?" },
          { text: "Cuesta quince pesos.", en: "It costs fifteen pesos." },
          { text: "Quiero cuatro, por favor.", en: "I want four, please." },
          { text: "Okay, quince por uno.", en: "Okay, fifteen each." },
          { text: "Gracias. Está bien.", en: "Thanks. That's fine." },
        ],
        [
          {
            prompt: "What does the shopper ask?",
            options: ["How much it costs", "Their age only", "A phone number only", "Where they're from"],
            correctIndex: 0,
            explanation: "¿Cuánto cuesta?",
          },
          {
            prompt: "What's the unit price?",
            options: ["Fifteen pesos", "Twenty years", "Free forever", "Eight dollars only"],
            correctIndex: 0,
            explanation: "Cuesta quince pesos.",
          },
          {
            prompt: "How many do they want?",
            options: ["Four", "Zero", "One hundred", "None — they leave angry"],
            correctIndex: 0,
            explanation: "Quiero cuatro, por favor.",
          },
          {
            prompt: "How does it end?",
            options: ["Thanks — it's fine", "They ask for English class", "They buy a car", "They say soy de"],
            correctIndex: 0,
            explanation: "Gracias. Está bien.",
          },
        ],
        ["buenos-dias", "cuanto-cuesta", "quince", "pesos", "cuatro", "por-favor", "gracias"],
        "Simple market numbers story.",
        12
      ),
      cloze(
        "u3l9-cloze-1",
        "¿Cuánto ___?",
        ["cuesta", "Cuesta"],
        "¿Cuánto cuesta?",
        ["cuanto-cuesta"],
        { hint: "costs", audioText: "¿Cuánto cuesta?", voice: "f" }
      ),
      cloze(
        "u3l9-cloze-2",
        "Cuesta ___ pesos.",
        ["quince", "Quince"],
        "Cuesta quince pesos.",
        ["quince", "pesos"],
        { hint: "15", audioText: "Cuesta quince pesos.", voice: "m" }
      ),
      cloze(
        "u3l9-cloze-3",
        "Quiero ___, por favor.",
        ["cuatro", "Cuatro"],
        "Quiero cuatro, por favor.",
        ["cuatro", "por-favor"],
        { hint: "4", audioText: "Quiero cuatro, por favor.", voice: "c" }
      ),
    ],
  },

  "u3-l10": {
    id: "u3-l10",
    unitId: "unit-3",
    title: "Mixed numbers practice",
    description: "1–20, age, phone, and prices in one workout.",
    xpReward: 30,
    exercises: [
      {
        id: "u3l10-1",
        type: "select",
        prompt: "Thirteen is:",
        options: ["trece", "tres", "treinta", "doce"],
        correctIndex: 0,
        explanation: "Trece = 13.",
        wordCardIds: ["trece"],
        xp: 3,
      },
      {
        id: "u3l10-2",
        type: "select",
        prompt: "Nineteen is:",
        options: ["diecinueve", "nueve", "veinte", "diez"],
        correctIndex: 0,
        explanation: "Diecinueve = 19.",
        wordCardIds: ["diecinueve"],
        xp: 3,
      },
      {
        id: "u3l10-3",
        type: "tap-chips",
        prompt: "Build: “I am seventeen years old.”",
        chips: ["Tengo", "diecisiete", "años", "soy", "pesos"],
        correctOrder: ["Tengo", "diecisiete", "años"],
        explanation: "Tengo diecisiete años.",
        wordCardIds: ["tener", "diecisiete"],
        xp: 4,
      },
      listen(
        "u3l10-4",
        "Cuesta once pesos",
        ["It costs eleven pesos", "I am eleven pesos", "Hello eleven", "My number is pesos"],
        0,
        "Cuesta once pesos.",
        ["cuanto-cuesta", "once", "pesos"]
      ),
      {
        id: "u3l10-5",
        type: "fill-blank",
        prompt: "Complete the Spanish.",
        template: "Mi número es ___ cinco cinco.",
        englishPrompt: "My number is eight five five…",
        acceptedAnswers: ["ocho", "Ocho"],
        hint: "8",
        explanation: "…ocho cinco cinco…",
        wordCardIds: ["ocho", "mi-numero"],
        xp: 3,
      },
      {
        id: "u3l10-6",
        type: "translate",
        prompt: "Translate to Spanish: “fourteen”",
        acceptedAnswers: ["catorce", "Catorce"],
        hint: "14",
        explanation: "Catorce.",
        wordCardIds: ["catorce"],
        xp: 3,
      },
      {
        id: "u3l10-7",
        type: "situational-choose",
        prompt: "It’s free water:",
        situation: "Café: “¿Cuánto cuesta el agua?”",
        options: ["Es gratis.", "Tengo gratis años.", "Soy gratis de México.", "Hablo gratis celular."],
        correctIndex: 0,
        explanation: "Es gratis.",
        wordCardIds: ["gratis"],
        xp: 3,
      },
      {
        id: "u3l10-match",
        type: "match-pairs",
        prompt: "Mixed number matches.",
        pairs: [
          { left: "doce", right: "12" },
          { left: "dieciocho", right: "18" },
          { left: "veinte", right: "20" },
          { left: "siete", right: "7" },
        ],
        explanation: "Speed matches.",
        wordCardIds: ["doce", "dieciocho", "veinte", "siete"],
        xp: 4,
      },
      {
        id: "u3l10-m1",
        type: "match-pairs",
        prompt: "Match each number to its Spanish word.",
        pairMode: "emoji-es",
        pairs: [
          { left: "1️⃣", right: "uno" },
          { left: "2️⃣", right: "dos" },
          { left: "3️⃣", right: "tres" },
          { left: "4️⃣", right: "cuatro" },
          { left: "5️⃣", right: "cinco" },
        ],
        explanation: "Numbers one to five.",
        wordCardIds: ["pesos"],
        xp: 3,
      },
      {
        id: "u3l10-m2",
        type: "match-pairs",
        prompt: "Match the Spanish to its English.",
        pairs: [
          { left: "cuánto cuesta", right: "how much does it cost" },
          { left: "los pesos", right: "the pesos" },
          { left: "diez", right: "ten" },
          { left: "veinte", right: "twenty" },
        ],
        explanation: "Price words you will hear at any counter.",
        wordCardIds: ["cuanto-cuesta", "pesos"],
        xp: 3,
      },
    ],
  },

  "u3-l11": {
    id: "u3-l11",
    unitId: "unit-3",
    title: "Story: Phone and age",
    description: "Friends trade age and a phone number — then cloze.",
    xpReward: 40,
    exercises: [
      storyListen(
        "u3l11-story",
        "Tu número",
        [
          { text: "Hola, ¿qué tal?", en: "Hi, how's it going?" },
          { text: "Bien. ¿Cuántos años tienes?", en: "Good. How old are you?" },
          { text: "Tengo diecinueve años.", en: "I am nineteen years old." },
          { text: "Yo tengo veinte.", en: "I am twenty." },
          { text: "¿Cuál es tu número de celular?", en: "What is your cell phone number?" },
          { text: "Mi número es cinco cinco cinco… Gracias.", en: "My number is five five five… Thanks." },
        ],
        [
          {
            prompt: "What personal fact is asked first after the hello?",
            options: ["Age", "Price of tacos only", "Country only", "Nothing"],
            correctIndex: 0,
            explanation: "¿Cuántos años tienes?",
          },
          {
            prompt: "How old is the first answerer?",
            options: ["19", "11", "4", "100"],
            correctIndex: 0,
            explanation: "Tengo diecinueve años.",
          },
          {
            prompt: "The other person is:",
            options: ["20", "Free", "A city", "A goodbye"],
            correctIndex: 0,
            explanation: "Yo tengo veinte.",
          },
          {
            prompt: "What do they exchange next?",
            options: ["A cell number", "A car", "Only adiós", "Pesos for English"],
            correctIndex: 0,
            explanation: "Número de celular.",
          },
        ],
        ["que-tal", "cuantos-anos", "diecinueve", "veinte", "tener", "celular", "mi-numero", "cinco", "gracias"],
        "Age + phone story.",
        12
      ),
      cloze(
        "u3l11-cloze-1",
        "¿Cuántos ___ tienes?",
        ["años", "anos", "Años"],
        "¿Cuántos años tienes?",
        ["cuantos-anos"],
        { hint: "years", audioText: "¿Cuántos años tienes?", voice: "f" }
      ),
      cloze(
        "u3l11-cloze-2",
        "Tengo ___ años.",
        ["diecinueve", "Diecinueve"],
        "Tengo diecinueve años.",
        ["diecinueve", "tener"],
        { hint: "19", audioText: "Tengo diecinueve años.", voice: "m" }
      ),
      cloze(
        "u3l11-cloze-3",
        "Mi ___ es cinco cinco cinco…",
        ["número", "numero", "Número"],
        "Mi número es cinco cinco cinco…",
        ["mi-numero", "numero"],
        { hint: "number", audioText: "Mi número es cinco cinco cinco.", voice: "c" }
      ),
    ],
  },

  "u3-l12": {
    id: "u3-l12",
    unitId: "unit-3",
    title: "Unit 3 check",
    description: "Numbers, age, phone, and prices — final beginner numbers check.",
    xpReward: 35,
    exercises: [
      {
        id: "u3l12-1",
        type: "select",
        prompt: "Ten is:",
        options: ["diez", "dos", "doce", "veinte"],
        correctIndex: 0,
        explanation: "Diez = 10.",
        wordCardIds: ["diez"],
        xp: 3,
      },
      {
        id: "u3l12-2",
        type: "select",
        prompt: "Ask a price:",
        options: ["¿Cuánto cuesta?", "¿Cómo te llamas?", "¿De dónde eres?", "¿Qué tal?"],
        correctIndex: 0,
        explanation: "¿Cuánto cuesta?",
        wordCardIds: ["cuanto-cuesta"],
        xp: 3,
      },
      {
        id: "u3l12-3",
        type: "tap-chips",
        prompt: "Build: “I am eighteen years old.”",
        chips: ["Tengo", "dieciocho", "años", "soy", "gratis"],
        correctOrder: ["Tengo", "dieciocho", "años"],
        explanation: "Tengo dieciocho años.",
        wordCardIds: ["tener", "dieciocho"],
        xp: 4,
      },
      {
        id: "u3l12-4",
        type: "translate",
        prompt: "Translate to Spanish: “cell phone”",
        acceptedAnswers: ["celular", "el celular", "Celular"],
        hint: "everyday word",
        explanation: "Celular.",
        wordCardIds: ["celular"],
        xp: 3,
      },
      {
        id: "u3l12-5",
        type: "fill-blank",
        prompt: "Complete the Spanish.",
        template: "Cuesta ___ dólares.",
        englishPrompt: "It costs twenty dollars.",
        acceptedAnswers: ["veinte", "Veinte"],
        hint: "20",
        explanation: "Cuesta veinte dólares.",
        wordCardIds: ["veinte", "dolares"],
        xp: 3,
      },
      {
        id: "u3l12-6",
        type: "situational-choose",
        prompt: "No charge:",
        situation: "Museum day — entry is free.",
        options: ["Es gratis.", "Es me llamo.", "Es buenos días pesos.", "Es ¿cómo estás?"],
        correctIndex: 0,
        explanation: "Es gratis.",
        wordCardIds: ["gratis"],
        xp: 3,
      },
      listen(
        "u3l12-7",
        "uno, dos, tres",
        ["one, two, three", "eight, nine, ten", "please thanks", "hello goodbye"],
        0,
        "uno, dos, tres.",
        ["uno", "dos", "tres"]
      ),
      {
        id: "u3l12-match",
        type: "match-pairs",
        prompt: "Unit 3 final matches.",
        pairs: [
          { left: "quince", right: "15" },
          { left: "celular", right: "cell phone" },
          { left: "Tengo… años", right: "I am … years old" },
          { left: "¿Cuánto cuesta?", right: "How much is it?" },
        ],
        explanation: "Numbers that matter — locked in.",
        wordCardIds: ["quince", "celular", "cuantos-anos", "cuanto-cuesta"],
        xp: 4,
      },
    ],
  },
};
