/**
 * Unit 8 — Plans & invitations (~12 lessons). Near future, wants, invites. LatAm-neutral.
 * Merged via intermediate.ts into mock-data.
 */
import type { Lesson, WordCard } from "../types";
import { audioSrcFor, voiceForIndex, type AudioVoice } from "../audio";

function teach(
  id: string,
  wordCardId: string
): import("../types").TeachExercise {
  return {
    id,
    type: "teach",
    prompt: "New word — learn it, then practice.",
    explanation: "",
    wordCardId,
    wordCardIds: [wordCardId],
    xp: 0,
  };
}

let listenVoiceIndex = 800;

function listen(
  id: string,
  audioText: string,
  options: string[],
  correctIndex: number,
  explanation: string,
  wordCardIds: string[],
  xp = 3
): import("../types").ListeningChooseExercise {
  const voice = voiceForIndex(listenVoiceIndex);
  listenVoiceIndex += 1;
  return {
    id,
    type: "listening-choose",
    prompt: "What did you hear?",
    audioText,
    audioSrc: audioSrcFor(audioText, voice),
    options,
    correctIndex,
    explanation,
    wordCardIds,
    xp,
  };
}

function cloze(
  id: string,
  template: string,
  acceptedAnswers: string[],
  explanation: string,
  wordCardIds: string[],
  opts: {
    hint?: string;
    audioText: string;
    voice?: AudioVoice;
    storyLabel?: string;
    xp?: number;
  }
): import("../types").ClozeExercise {
  const voice = opts.voice ?? "f";
  return {
    id,
    type: "cloze",
    prompt: "Fill the blank from the story",
    template,
    acceptedAnswers,
    hint: opts.hint,
    explanation,
    wordCardIds,
    audioText: opts.audioText,
    audioSrc: audioSrcFor(opts.audioText, voice),
    storyLabel: opts.storyLabel ?? "From the story",
    xp: opts.xp ?? 3,
  };
}

function storyListen(
  id: string,
  title: string,
  lines: { text: string; voice?: AudioVoice }[],
  questions: {
    prompt: string;
    options: string[];
    correctIndex: number;
    explanation?: string;
  }[],
  wordCardIds: string[],
  explanation = "Story comprehension — replay anytime.",
  xp = 10
): import("../types").StoryListenExercise {
  const withVoices = lines.map((line, i) => ({
    text: line.text,
    voice: line.voice ?? voiceForIndex(i),
  }));
  return {
    id,
    type: "story-listen",
    prompt: "Listen to the story, then answer",
    title,
    lines: withVoices,
    questions,
    explanation,
    wordCardIds,
    xp,
  };
}

export const UNIT8_WORD_CARDS: Record<string, WordCard> = {
  "ir-a": {
    id: "ir-a",
    lemma: "ir a + infinitive",
    pos: "phrase",
    gender: "n/a",
    gloss: "going to (near future)",
    meaningSummary:
      "Near-future plan: Voy a + infinitive. Voy a comer / Vamos a salir. The most natural way to talk about what you are about to do.",
    examples: [
      { es: "Voy a cocinar esta noche.", en: "I'm going to cook tonight." },
      { es: "¿Vas a venir?", en: "Are you going to come?" },
    ],
    useWhen: "Plans and intentions in the near future.",
    dontUseWhen: "For a firm café order, Quiero… is clearer than Voy a querer…",
    contrast: "quiero + infinitive (I want to…)",
    formality: "neutral",
    cefr: "A2",
  },
  "quiero-inf": {
    id: "quiero-inf",
    lemma: "quiero + infinitive",
    pos: "phrase",
    gender: "n/a",
    gloss: "I want to…",
    meaningSummary:
      "Desire + action: Quiero salir / Quiero aprender español. Direct and everyday — stronger than me gustaría.",
    examples: [
      { es: "Quiero salir el viernes.", en: "I want to go out on Friday." },
      { es: "No quiero llegar tarde.", en: "I don't want to arrive late." },
    ],
    useWhen: "Stating what you want to do.",
    dontUseWhen: "For scheduled near future, ir a + inf is very natural too.",
    contrast: "voy a + infinitive / me gustaría + infinitive",
    formality: "neutral",
    cefr: "A2",
  },
  "te-gustaria": {
    id: "te-gustaria",
    lemma: "¿te gustaría…?",
    pos: "phrase",
    gender: "n/a",
    gloss: "would you like…?",
    meaningSummary:
      "Polite invitation: ¿Te gustaría tomar un café? Softens ¿quieres…? without sounding stiff among friends.",
    examples: [
      { es: "¿Te gustaría tomar un café?", en: "Would you like to get a coffee?" },
      { es: "¿Te gustaría ir al cine?", en: "Would you like to go to the movies?" },
    ],
    useWhen: "Inviting someone politely (tú).",
    dontUseWhen: "With formal strangers use ¿Le gustaría…? (usted).",
    contrast: "¿quieres…? (more direct)",
    formality: "informal",
    cefr: "A2",
  },
  "otra-vez": {
    id: "otra-vez",
    lemma: "otra vez / tal vez",
    pos: "phrase",
    gender: "n/a",
    gloss: "soft refusal helpers",
    meaningSummary:
      "Soft no to plans: Tal vez otro día / Ahora no puedo. Keeps the door open without a hard rejection.",
    examples: [
      { es: "Gracias, pero ahora no puedo.", en: "Thanks, but I can't right now." },
      { es: "Tal vez otro día. ¡Gracias!", en: "Maybe another day. Thanks!" },
    ],
    useWhen: "Declining invitations gently.",
    dontUseWhen: "If you truly never want to, be clearer — soft refusals are the polite default.",
    formality: "neutral",
    cefr: "A2",
  },
  "me-parece": {
    id: "me-parece",
    lemma: "me parece",
    pos: "phrase",
    gender: "n/a",
    gloss: "it seems to me / I think",
    meaningSummary:
      "Opinion softener for plans: Me parece bien / Me parece una buena idea. Agree without sounding pushy.",
    examples: [
      { es: "Me parece bien.", en: "Sounds good to me." },
      { es: "Me parece una buena idea.", en: "It seems like a good idea to me." },
    ],
    useWhen: "Giving opinions or agreeing with plans.",
    dontUseWhen: "n/a",
    contrast: "creo que…",
    formality: "neutral",
    cefr: "B1",
  },
  manana: {
    id: "manana",
    lemma: "mañana",
    pos: "adverb",
    gender: "n/a",
    gloss: "tomorrow",
    meaningSummary:
      "Tomorrow as a time anchor for plans: Mañana voy a estudiar / Nos vemos mañana. Not the same as por la mañana (in the morning).",
    examples: [
      { es: "Mañana voy a estudiar.", en: "Tomorrow I'm going to study." },
      { es: "¿Qué vas a hacer mañana?", en: "What are you going to do tomorrow?" },
    ],
    useWhen: "Talking about tomorrow's plans.",
    dontUseWhen: "For 'in the morning' use por la mañana; for 'this morning' (past) use esta mañana.",
    contrast: "por la mañana / hoy / el sábado",
    formality: "neutral",
    cefr: "A2",
  },
  "el-sabado": {
    id: "el-sabado",
    lemma: "el sábado",
    pos: "phrase",
    gender: "n/a",
    gloss: "on Saturday / this Saturday",
    meaningSummary:
      "Day-of-week plan phrase: El sábado voy al cine. In LatAm, el + day often means 'this coming' Saturday.",
    examples: [
      { es: "El sábado voy al cine.", en: "On Saturday I'm going to the movies." },
      { es: "¿Qué haces el sábado?", en: "What are you doing on Saturday?" },
    ],
    useWhen: "Weekend / day plans.",
    dontUseWhen: "Don't say 'en sábado' for this meaning.",
    contrast: "el viernes / el fin de semana",
    formality: "neutral",
    cefr: "A2",
  },
  "el-viernes": {
    id: "el-viernes",
    lemma: "el viernes",
    pos: "phrase",
    gender: "n/a",
    gloss: "on Friday / this Friday",
    meaningSummary:
      "Day plan: Quiero salir el viernes / Voy a cocinar el viernes. Same el + day pattern as el sábado.",
    examples: [
      { es: "Quiero salir el viernes.", en: "I want to go out on Friday." },
      { es: "El viernes vamos a cenar.", en: "On Friday we're going to have dinner." },
    ],
    useWhen: "Friday plans and invites.",
    dontUseWhen: "n/a",
    contrast: "el sábado / mañana",
    formality: "neutral",
    cefr: "A2",
  },
  "a-las": {
    id: "a-las",
    lemma: "a las…",
    pos: "phrase",
    gender: "n/a",
    gloss: "at (clock time)",
    meaningSummary:
      "Clock time for plans: a las siete / a las ocho. Pair with ir a: Voy a llegar a las seis.",
    examples: [
      { es: "Nos vemos a las siete.", en: "See you at seven." },
      { es: "Voy a llegar a las seis.", en: "I'm going to arrive at six." },
    ],
    useWhen: "Setting a meeting time.",
    dontUseWhen: "For 'in the morning' prefer por la mañana, not a las mañanas.",
    contrast: "por la mañana / por la tarde",
    formality: "neutral",
    cefr: "A2",
  },
  "esta-noche": {
    id: "esta-noche",
    lemma: "esta noche",
    pos: "phrase",
    gender: "n/a",
    gloss: "tonight",
    meaningSummary:
      "Tonight as a plan window: Voy a cocinar esta noche / ¿Quieres salir esta noche?",
    examples: [
      { es: "Voy a cocinar esta noche.", en: "I'm going to cook tonight." },
      { es: "¿Te gustaría salir esta noche?", en: "Would you like to go out tonight?" },
    ],
    useWhen: "Tonight's plans.",
    dontUseWhen: "For last night (past) use anoche.",
    contrast: "anoche / mañana",
    formality: "neutral",
    cefr: "A2",
  },
  salir: {
    id: "salir",
    lemma: "salir",
    pos: "verb",
    gender: "n/a",
    gloss: "to go out",
    meaningSummary:
      "Go out socially or leave: Quiero salir / Vamos a salir el viernes. Everyday invite verb.",
    conjugations: [
      {
        label: "Present indicative (LatAm)",
        forms: [
          { person: "yo", form: "salgo" },
          { person: "tú", form: "sales" },
          { person: "él/ella/usted", form: "sale" },
          { person: "nosotros/as", form: "salimos" },
          { person: "ustedes", form: "salen" },
        ],
      },
    ],
    examples: [
      { es: "Quiero salir el viernes.", en: "I want to go out on Friday." },
      { es: "¿Vas a salir esta noche?", en: "Are you going to go out tonight?" },
    ],
    useWhen: "Social plans — going out.",
    dontUseWhen: "For leaving a building you can also say salir de…",
    formality: "neutral",
    cefr: "A2",
  },
  "el-cine": {
    id: "el-cine",
    lemma: "el cine",
    pos: "noun",
    gender: "m",
    gloss: "the movies / cinema",
    meaningSummary:
      "Movie plans: ir al cine. Classic invite: ¿Te gustaría ir al cine el sábado?",
    examples: [
      { es: "Voy al cine el sábado.", en: "I'm going to the movies on Saturday." },
      { es: "¿Te gustaría ir al cine?", en: "Would you like to go to the movies?" },
    ],
    useWhen: "Movie / cinema plans.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A2",
  },
  "vamos-a": {
    id: "vamos-a",
    lemma: "vamos a + infinitive",
    pos: "phrase",
    gender: "n/a",
    gloss: "we're going to… / let's…",
    meaningSummary:
      "Group near future or soft suggestion: Vamos a cenar / Vamos a tomar un café. Often invites without sounding bossy.",
    examples: [
      { es: "Vamos a cenar el viernes.", en: "We're going to have dinner on Friday." },
      { es: "¿Vamos a tomar un café?", en: "Shall we get a coffee?" },
    ],
    useWhen: "Shared plans and light suggestions.",
    dontUseWhen: "For 'I alone' use voy a…",
    contrast: "voy a / ¿te gustaría…?",
    formality: "neutral",
    cefr: "A2",
  },
  "quieres-inf": {
    id: "quieres-inf",
    lemma: "¿quieres…?",
    pos: "phrase",
    gender: "n/a",
    gloss: "do you want…? / want to…?",
    meaningSummary:
      "Direct friendly invite: ¿Quieres salir? / ¿Quieres ir al cine? More casual than ¿te gustaría…?",
    examples: [
      { es: "¿Quieres salir esta noche?", en: "Do you want to go out tonight?" },
      { es: "¿Quieres ir al centro?", en: "Do you want to go downtown?" },
    ],
    useWhen: "Casual invites with friends (tú).",
    dontUseWhen: "With strangers, ¿te gustaría…? or usted forms feel softer.",
    contrast: "¿te gustaría…?",
    formality: "informal",
    cefr: "A2",
  },
  "que-tal-si": {
    id: "que-tal-si",
    lemma: "¿qué tal si…?",
    pos: "phrase",
    gender: "n/a",
    gloss: "how about if…? / what if…?",
    meaningSummary:
      "Soft suggestion for plans: ¿Qué tal si vamos al cine? Opens negotiation without pressure.",
    examples: [
      { es: "¿Qué tal si vamos al cine?", en: "How about we go to the movies?" },
      { es: "¿Qué tal si cenamos a las ocho?", en: "How about we have dinner at eight?" },
    ],
    useWhen: "Proposing an alternative time or activity.",
    dontUseWhen: "n/a",
    contrast: "¿te gustaría…? / ¿vamos a…?",
    formality: "neutral",
    cefr: "A2",
  },
  "otro-dia": {
    id: "otro-dia",
    lemma: "otro día",
    pos: "phrase",
    gender: "n/a",
    gloss: "another day",
    meaningSummary:
      "Reschedule softener: Otro día / Tal vez otro día. Declines now while leaving the invite open.",
    examples: [
      { es: "Otro día, gracias.", en: "Another day, thanks." },
      { es: "¿Podemos otro día?", en: "Can we do another day?" },
    ],
    useWhen: "Soft decline or reschedule.",
    dontUseWhen: "If you mean a specific day, name it (el sábado).",
    contrast: "ahora no puedo / el sábado",
    formality: "neutral",
    cefr: "A2",
  },
  cocinar: {
    id: "cocinar",
    lemma: "cocinar",
    pos: "verb",
    gender: "n/a",
    gloss: "to cook",
    meaningSummary:
      "Cook at home: Voy a cocinar esta noche. Pairs with cocina (kitchen) from daily-life units.",
    conjugations: [
      {
        label: "Present indicative (LatAm)",
        forms: [
          { person: "yo", form: "cocino" },
          { person: "tú", form: "cocinas" },
          { person: "él/ella/usted", form: "cocina" },
          { person: "nosotros/as", form: "cocinamos" },
          { person: "ustedes", form: "cocinan" },
        ],
      },
    ],
    examples: [
      { es: "Voy a cocinar esta noche.", en: "I'm going to cook tonight." },
      { es: "¿Quieres cocinar juntos?", en: "Do you want to cook together?" },
    ],
    useWhen: "Home cooking plans.",
    dontUseWhen: "Don't confuse with cocina (the kitchen / he-she cooks).",
    contrast: "cocina (kitchen)",
    formality: "neutral",
    cefr: "A2",
  },
};

export const UNIT8_LESSONS: Record<string, Lesson> = {
  "u8-l1": {
    id: "u8-l1",
    unitId: "unit-8",
    title: "Plans with ir a / quiero",
    description: "Near future and wants — voy a…, quiero + infinitive.",
    xpReward: 44,
    exercises: [
      teach("teach-u8l1-ir-a", "ir-a"),
      {
        id: "u8l1-1",
        type: "select",
        prompt: "“I'm going to cook tonight” starts with…",
        options: ["Voy a cocinar…", "Fui a cocinar ayer only", "Me gusta a…", "Dije a…"],
        correctIndex: 0,
        explanation: "Voy a + infinitive = near future.",
        wordCardIds: ["ir-a", "cocinar", "esta-noche"],
        xp: 3,
      },
      teach("teach-u8l1-quiero-inf", "quiero-inf"),
      {
        id: "u8l1-2",
        type: "tap-chips",
        prompt: "Build: “I want to go out on Friday.”",
        chips: ["Quiero", "salir", "el", "viernes.", "fui", "metro"],
        correctOrder: ["Quiero", "salir", "el", "viernes."],
        explanation: "Quiero salir el viernes.",
        wordCardIds: ["quiero-inf", "salir", "el-viernes"],
        xp: 3,
      },
      teach("teach-u8l1-esta-noche", "esta-noche"),
      {
        id: "u8l1-3",
        type: "translate",
        prompt: "Translate: “Are you going to come?” (tú)",
        acceptedAnswers: ["¿Vas a venir?", "Vas a venir?", "¿Vas a venir", "Vas a venir"],
        hint: "vas a + venir",
        explanation: "¿Vas a venir?",
        wordCardIds: ["ir-a"],
        xp: 4,
      },
      listen(
        "u8l1-4",
        "Voy a cocinar esta noche.",
        ["I'm going to cook tonight.", "I cooked tonight.", "I like cooking the check.", "Turn right tonight."],
        0,
        "Voy a cocinar esta noche.",
        ["ir-a", "cocinar", "esta-noche"]
      ),
      {
        id: "u8l1-5",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "You don't want to arrive late.",
        options: [
          "No quiero llegar tarde.",
          "No comí llegar tarde.",
          "Está lejos llegar.",
          "La cuenta llegar.",
        ],
        correctIndex: 0,
        explanation: "No quiero llegar tarde.",
        wordCardIds: ["quiero-inf"],
        xp: 3,
      },
      {
        id: "u8l1-6",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I'm going to study tonight.",
        template: "Voy ___ estudiar esta noche.",
        acceptedAnswers: ["a", "A"],
        hint: "ir a + infinitive",
        explanation: "Voy a estudiar esta noche.",
        wordCardIds: ["ir-a", "estudiar", "esta-noche"],
        xp: 3,
      },
      {
        id: "u8l1-7",
        type: "match-pairs",
        prompt: "Match plan phrases.",
        pairs: [
          { left: "Voy a cocinar", right: "I'm going to cook" },
          { left: "Quiero salir", right: "I want to go out" },
          { left: "¿Vas a venir?", right: "Are you going to come?" },
          { left: "No quiero llegar tarde", right: "I don't want to arrive late" },
        ],
        explanation: "ir a vs quiero + inf.",
        wordCardIds: ["ir-a", "quiero-inf", "salir", "cocinar"],
        xp: 4,
      },
      listen(
        "u8l1-8",
        "¿Vas a venir?",
        ["Did you come yesterday?", "Are you going to come?", "Do you like juice?", "Where is the metro?"],
        1,
        "¿Vas a venir?",
        ["ir-a"]
      ),
      {
        id: "u8l1-9",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I want to go out on Friday.",
        template: "Quiero ___ el viernes.",
        acceptedAnswers: ["salir", "Salir"],
        hint: "to go out",
        explanation: "Quiero salir el viernes.",
        wordCardIds: ["quiero-inf", "salir", "el-viernes"],
        xp: 3,
      },
      {
        id: "u8l1-10",
        type: "select",
        prompt: "Near future “I'm going to work” is…",
        options: ["Voy a trabajar", "Fui a trabajar only past", "Como trabajar", "La cuenta trabajar"],
        correctIndex: 0,
        explanation: "Voy a trabajar.",
        wordCardIds: ["ir-a", "trabajar"],
        xp: 3,
      },
    ],
  },

  "u8-l2": {
    id: "u8-l2",
    unitId: "unit-8",
    title: "Invites & soft no",
    description: "¿Te gustaría…?, me parece, and polite refusals.",
    xpReward: 44,
    exercises: [
      teach("teach-u8l2-gustaria", "te-gustaria"),
      {
        id: "u8l2-1",
        type: "select",
        prompt: "Polite “Would you like to get a coffee?”",
        options: [
          "¿Te gustaría tomar un café?",
          "¿Comiste un café?",
          "¿Dónde está un café ayer?",
          "Fui un café.",
        ],
        correctIndex: 0,
        explanation: "¿Te gustaría tomar un café?",
        wordCardIds: ["te-gustaria", "cafe"],
        xp: 3,
      },
      teach("teach-u8l2-parece", "me-parece"),
      {
        id: "u8l2-2",
        type: "select",
        prompt: "“Sounds good to me” is…",
        options: ["Me parece bien.", "Me despierto bien.", "Comí bien ayer only", "Todo recto bien"],
        correctIndex: 0,
        explanation: "Me parece bien — soft agreement.",
        wordCardIds: ["me-parece"],
        xp: 3,
      },
      teach("teach-u8l2-otra", "otra-vez"),
      {
        id: "u8l2-3",
        type: "situational-choose",
        prompt: "Pick the soft refusal.",
        situation: "A friend invites you out but you can't tonight.",
        options: [
          "Gracias, pero ahora no puedo.",
          "Nunca hables conmigo.",
          "¿Dónde está el baño? No.",
          "Comí tu invitación.",
        ],
        correctIndex: 0,
        explanation: "Gracias, pero ahora no puedo — polite and clear.",
        wordCardIds: ["otra-vez"],
        xp: 4,
      },
      {
        id: "u8l2-4",
        type: "tap-chips",
        prompt: "Build: “Maybe another day. Thanks!”",
        chips: ["Tal", "vez", "otro", "día.", "¡Gracias!", "metro"],
        correctOrder: ["Tal", "vez", "otro", "día.", "¡Gracias!"],
        explanation: "Tal vez otro día. ¡Gracias!",
        wordCardIds: ["otra-vez", "otro-dia"],
        xp: 3,
      },
      listen(
        "u8l2-5",
        "¿Te gustaría tomar un café?",
        ["Did you drink coffee yesterday?", "Would you like to get a coffee?", "Where is the café?", "I want the check."],
        1,
        "¿Te gustaría tomar un café?",
        ["te-gustaria", "cafe"]
      ),
      {
        id: "u8l2-6",
        type: "translate",
        prompt: "Translate: “It seems like a good idea to me.”",
        acceptedAnswers: [
          "Me parece una buena idea.",
          "Me parece una buena idea",
          "Me parece buena idea.",
          "Me parece buena idea",
        ],
        hint: "Me parece…",
        explanation: "Me parece una buena idea.",
        wordCardIds: ["me-parece"],
        xp: 4,
      },
      {
        id: "u8l2-7",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "Would you like to go to the movies?",
        template: "¿Te ___ ir al cine?",
        acceptedAnswers: ["gustaría", "gustaria", "Gustaría"],
        hint: "would like",
        explanation: "¿Te gustaría ir al cine?",
        wordCardIds: ["te-gustaria", "el-cine"],
        xp: 3,
      },
      {
        id: "u8l2-8",
        type: "match-pairs",
        prompt: "Match social phrases.",
        pairs: [
          { left: "¿Te gustaría…?", right: "Would you like…?" },
          { left: "Me parece bien", right: "Sounds good to me" },
          { left: "ahora no puedo", right: "I can't right now" },
          { left: "Tal vez otro día", right: "Maybe another day" },
        ],
        explanation: "Invitations and soft refusals.",
        wordCardIds: ["te-gustaria", "me-parece", "otra-vez", "otro-dia"],
        xp: 4,
      },
      listen(
        "u8l2-9",
        "Tal vez otro día. ¡Gracias!",
        ["Maybe another day. Thanks!", "I went another day.", "Where is another day?", "I ate thanks yesterday."],
        0,
        "Soft refusal with gratitude.",
        ["otra-vez", "otro-dia"]
      ),
      {
        id: "u8l2-10",
        type: "situational-choose",
        prompt: "Pick the best reply.",
        situation: "Friend suggests coffee; you agree.",
        options: [
          "Me parece bien.",
          "Fui al metro ayer only.",
          "Comí la cuenta.",
          "Todo recto café.",
        ],
        correctIndex: 0,
        explanation: "Me parece bien.",
        wordCardIds: ["me-parece", "cafe"],
        xp: 3,
      },
    ],
  },

  "u8-l3": {
    id: "u8-l3",
    unitId: "unit-8",
    title: "Voy a / vas a plans",
    description: "Conjugate ir a for yo/tú/nosotros — real weekend plans.",
    xpReward: 46,
    exercises: [
      teach("teach-u8l3-vamos-a", "vamos-a"),
      {
        id: "u8l3-1",
        type: "select",
        prompt: "“We're going to have dinner” is…",
        options: ["Vamos a cenar", "Voy a cenar only me", "Fui a cenar forever", "Como cenar"],
        correctIndex: 0,
        explanation: "Vamos a cenar.",
        wordCardIds: ["vamos-a"],
        xp: 3,
      },
      teach("teach-u8l3-manana", "manana"),
      {
        id: "u8l3-2",
        type: "select",
        prompt: "“Tomorrow I'm going to study” is…",
        options: [
          "Mañana voy a estudiar.",
          "Anoche voy a estudiar.",
          "Mañana comí estudiar.",
          "La cuenta mañana.",
        ],
        correctIndex: 0,
        explanation: "Mañana voy a estudiar.",
        wordCardIds: ["manana", "ir-a", "estudiar"],
        xp: 3,
      },
      {
        id: "u8l3-3",
        type: "tap-chips",
        prompt: "Build: “Are you going to work tomorrow?” (tú)",
        chips: ["¿Vas", "a", "trabajar", "mañana?", "fui", "jugo"],
        correctOrder: ["¿Vas", "a", "trabajar", "mañana?"],
        explanation: "¿Vas a trabajar mañana?",
        wordCardIds: ["ir-a", "trabajar", "manana"],
        xp: 3,
      },
      {
        id: "u8l3-4",
        type: "translate",
        prompt: "Translate: “I'm going to go downtown.”",
        acceptedAnswers: [
          "Voy a ir al centro.",
          "Voy a ir al centro",
          "Voy al centro.",
          "Voy al centro",
        ],
        hint: "voy a ir / voy al…",
        explanation: "Voy a ir al centro (or Voy al centro).",
        wordCardIds: ["ir-a", "el-centro"],
        xp: 4,
      },
      listen(
        "u8l3-5",
        "Mañana voy a estudiar.",
        ["Yesterday I studied.", "Tomorrow I'm going to study.", "I like study juice.", "Where is tomorrow?"],
        1,
        "Mañana voy a estudiar.",
        ["manana", "ir-a", "estudiar"]
      ),
      {
        id: "u8l3-6",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "We're going to take the metro.",
        template: "Vamos ___ tomar el metro.",
        acceptedAnswers: ["a", "A"],
        hint: "vamos a + inf",
        explanation: "Vamos a tomar el metro.",
        wordCardIds: ["vamos-a", "metro"],
        xp: 3,
      },
      {
        id: "u8l3-7",
        type: "situational-choose",
        prompt: "Pick the best question.",
        situation: "Ask a friend if they are going to cook tonight (tú).",
        options: [
          "¿Vas a cocinar esta noche?",
          "¿Comiste cocinar?",
          "¿Dónde está cocinar?",
          "¿Me ducho cocinar?",
        ],
        correctIndex: 0,
        explanation: "¿Vas a cocinar esta noche?",
        wordCardIds: ["ir-a", "cocinar", "esta-noche"],
        xp: 3,
      },
      {
        id: "u8l3-8",
        type: "match-pairs",
        prompt: "Match ir a forms.",
        pairs: [
          { left: "voy a", right: "I'm going to" },
          { left: "vas a", right: "you're going to (tú)" },
          { left: "vamos a", right: "we're going to" },
          { left: "mañana", right: "tomorrow" },
        ],
        explanation: "Core near-future conjugations.",
        wordCardIds: ["ir-a", "vamos-a", "manana"],
        xp: 4,
      },
      listen(
        "u8l3-9",
        "¿Vas a trabajar mañana?",
        ["Did you work yesterday?", "Do you like work?", "Are you going to work tomorrow?", "Where is the office?"],
        2,
        "¿Vas a trabajar mañana?",
        ["ir-a", "trabajar", "manana"]
      ),
      {
        id: "u8l3-10",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "Tomorrow we're going to rest.",
        template: "Mañana vamos a ___.",
        acceptedAnswers: ["descansar", "Descansar"],
        hint: "to rest",
        explanation: "Mañana vamos a descansar.",
        wordCardIds: ["manana", "vamos-a", "descansar"],
        xp: 3,
      },
    ],
  },

  "u8-l4": {
    id: "u8-l4",
    unitId: "unit-8",
    title: "Quiero vs me gustaría",
    description: "Direct want vs softer would-like — plans and polite tone.",
    xpReward: 46,
    exercises: [
      {
        id: "u8l4-1",
        type: "select",
        prompt: "Softer “I would like to go out” is…",
        options: [
          "Me gustaría salir.",
          "Comí salir.",
          "Fui salir ayer only",
          "La cuenta salir.",
        ],
        correctIndex: 0,
        explanation: "Me gustaría salir — softer than Quiero salir.",
        wordCardIds: ["me-gustaria", "salir"],
        xp: 3,
      },
      {
        id: "u8l4-2",
        type: "select",
        prompt: "More direct “I want to study” is…",
        options: ["Quiero estudiar.", "Me gusta estudiar only preference forever", "Fui estudiar.", "Metro estudiar."],
        correctIndex: 0,
        explanation: "Quiero estudiar.",
        wordCardIds: ["quiero-inf", "estudiar"],
        xp: 3,
      },
      {
        id: "u8l4-3",
        type: "tap-chips",
        prompt: "Build: “I would like to go to the movies.”",
        chips: ["Me", "gustaría", "ir", "al", "cine.", "fui", "jugo"],
        correctOrder: ["Me", "gustaría", "ir", "al", "cine."],
        explanation: "Me gustaría ir al cine.",
        wordCardIds: ["me-gustaria", "el-cine"],
        xp: 3,
      },
      {
        id: "u8l4-4",
        type: "translate",
        prompt: "Translate: “I want to rest this weekend.”",
        acceptedAnswers: [
          "Quiero descansar este fin de semana.",
          "Quiero descansar este fin de semana",
          "Quiero descansar el fin de semana.",
          "Quiero descansar el fin de semana",
        ],
        hint: "Quiero + descansar",
        explanation: "Quiero descansar este fin de semana.",
        wordCardIds: ["quiero-inf", "descansar", "fin-de-semana"],
        xp: 4,
      },
      listen(
        "u8l4-5",
        "Me gustaría salir el viernes.",
        ["I went out Friday.", "I would like to go out on Friday.", "I ate Friday.", "Where is Friday?"],
        1,
        "Me gustaría salir el viernes.",
        ["me-gustaria", "salir", "el-viernes"]
      ),
      {
        id: "u8l4-6",
        type: "situational-choose",
        prompt: "Pick the softer line.",
        situation: "You want coffee but you're being polite with a new coworker.",
        options: [
          "Me gustaría un café, por favor.",
          "Dame café ahora o nada.",
          "Comí tu café.",
          "Soy el metro café.",
        ],
        correctIndex: 0,
        explanation: "Me gustaría un café, por favor. (U5 reuse + polite tone)",
        wordCardIds: ["me-gustaria", "cafe"],
        xp: 3,
      },
      {
        id: "u8l4-7",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I would like to cook tonight.",
        template: "Me ___ cocinar esta noche.",
        acceptedAnswers: ["gustaría", "gustaria", "Gustaría"],
        hint: "would like",
        explanation: "Me gustaría cocinar esta noche.",
        wordCardIds: ["me-gustaria", "cocinar", "esta-noche"],
        xp: 3,
      },
      {
        id: "u8l4-8",
        type: "match-pairs",
        prompt: "Match tone.",
        pairs: [
          { left: "Quiero salir", right: "I want to go out (direct)" },
          { left: "Me gustaría salir", right: "I would like to go out (softer)" },
          { left: "No quiero llegar tarde", right: "I don't want to arrive late" },
          { left: "Me gustaría un café", right: "I would like a coffee" },
        ],
        explanation: "quiero vs me gustaría.",
        wordCardIds: ["quiero-inf", "me-gustaria", "salir", "cafe"],
        xp: 4,
      },
      listen(
        "u8l4-9",
        "Quiero descansar este fin de semana.",
        ["I rested last weekend.", "I want to rest this weekend.", "Where is rest?", "I like the metro weekend."],
        1,
        "Quiero descansar este fin de semana.",
        ["quiero-inf", "descansar", "fin-de-semana"]
      ),
      {
        id: "u8l4-10",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I want to go downtown.",
        template: "___ ir al centro.",
        acceptedAnswers: ["Quiero", "quiero"],
        hint: "I want",
        explanation: "Quiero ir al centro.",
        wordCardIds: ["quiero-inf", "el-centro"],
        xp: 3,
      },
    ],
  },

  "u8-l5": {
    id: "u8-l5",
    unitId: "unit-8",
    title: "Inviting someone",
    description: "¿Quieres…?, ¿te gustaría…?, ¿qué tal si…?, vamos a…",
    xpReward: 46,
    exercises: [
      teach("teach-u8l5-quieres", "quieres-inf"),
      {
        id: "u8l5-1",
        type: "select",
        prompt: "Casual “Do you want to go out tonight?”",
        options: [
          "¿Quieres salir esta noche?",
          "¿Comiste salir?",
          "¿Dónde está salir?",
          "Fui salir.",
        ],
        correctIndex: 0,
        explanation: "¿Quieres salir esta noche?",
        wordCardIds: ["quieres-inf", "salir", "esta-noche"],
        xp: 3,
      },
      teach("teach-u8l5-que-tal", "que-tal-si"),
      {
        id: "u8l5-2",
        type: "select",
        prompt: "“How about we go to the movies?” is…",
        options: [
          "¿Qué tal si vamos al cine?",
          "¿Qué comiste el cine?",
          "¿Dónde está el cine ayer?",
          "La cuenta cine.",
        ],
        correctIndex: 0,
        explanation: "¿Qué tal si vamos al cine?",
        wordCardIds: ["que-tal-si", "el-cine", "vamos-a"],
        xp: 3,
      },
      teach("teach-u8l5-cine", "el-cine"),
      {
        id: "u8l5-3",
        type: "tap-chips",
        prompt: "Build: “Would you like to go to the movies on Saturday?”",
        chips: ["¿Te", "gustaría", "ir", "al", "cine", "el", "sábado?", "metro"],
        correctOrder: ["¿Te", "gustaría", "ir", "al", "cine", "el", "sábado?"],
        explanation: "¿Te gustaría ir al cine el sábado?",
        wordCardIds: ["te-gustaria", "el-cine", "el-sabado"],
        xp: 3,
      },
      {
        id: "u8l5-4",
        type: "translate",
        prompt: "Translate: “Shall we get a coffee?”",
        acceptedAnswers: [
          "¿Vamos a tomar un café?",
          "Vamos a tomar un café?",
          "¿Vamos a tomar un café",
          "Vamos a tomar un café",
          "¿Tomamos un café?",
          "Tomamos un café?",
        ],
        hint: "Vamos a tomar…",
        explanation: "¿Vamos a tomar un café?",
        wordCardIds: ["vamos-a", "cafe"],
        xp: 4,
      },
      listen(
        "u8l5-5",
        "¿Quieres ir al centro?",
        ["Did you go downtown?", "Do you want to go downtown?", "Where is downtown forever?", "I want the check."],
        1,
        "¿Quieres ir al centro?",
        ["quieres-inf", "el-centro"]
      ),
      {
        id: "u8l5-6",
        type: "situational-choose",
        prompt: "Pick the best invite.",
        situation: "Suggest dinner with a friend without sounding pushy.",
        options: [
          "¿Qué tal si cenamos a las ocho?",
          "Cenas o te odio.",
          "Comí tu cena ayer only.",
          "Todo recto cena.",
        ],
        correctIndex: 0,
        explanation: "¿Qué tal si cenamos a las ocho?",
        wordCardIds: ["que-tal-si", "a-las"],
        xp: 3,
      },
      {
        id: "u8l5-7",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "Do you want to go out on Friday?",
        template: "¿Quieres ___ el viernes?",
        acceptedAnswers: ["salir", "Salir"],
        hint: "to go out",
        explanation: "¿Quieres salir el viernes?",
        wordCardIds: ["quieres-inf", "salir", "el-viernes"],
        xp: 3,
      },
      {
        id: "u8l5-8",
        type: "match-pairs",
        prompt: "Match invite styles.",
        pairs: [
          { left: "¿Quieres…?", right: "Do you want…? (casual)" },
          { left: "¿Te gustaría…?", right: "Would you like…? (softer)" },
          { left: "¿Qué tal si…?", right: "How about if…?" },
          { left: "¿Vamos a…?", right: "Shall we…?" },
        ],
        explanation: "Four invite patterns.",
        wordCardIds: ["quieres-inf", "te-gustaria", "que-tal-si", "vamos-a"],
        xp: 4,
      },
      listen(
        "u8l5-9",
        "¿Qué tal si vamos al cine?",
        ["How about we go to the movies?", "I went to the movies.", "Where is the tip?", "I ate the map."],
        0,
        "¿Qué tal si vamos al cine?",
        ["que-tal-si", "el-cine", "vamos-a"]
      ),
      {
        id: "u8l5-10",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "Would you like to get a coffee?",
        template: "¿Te gustaría tomar un ___?",
        acceptedAnswers: ["café", "cafe", "Café"],
        hint: "coffee",
        explanation: "¿Te gustaría tomar un café?",
        wordCardIds: ["te-gustaria", "cafe"],
        xp: 3,
      },
    ],
  },

  "u8-l6": {
    id: "u8-l6",
    unitId: "unit-8",
    title: "Soft decline & reschedule",
    description: "Ahora no puedo, otro día, and polite counters.",
    xpReward: 46,
    exercises: [
      teach("teach-u8l6-otro-dia", "otro-dia"),
      {
        id: "u8l6-1",
        type: "select",
        prompt: "Soft “Another day, thanks” is…",
        options: [
          "Otro día, gracias.",
          "Nunca jamás gracias.",
          "Comí otro día.",
          "La cuenta otro día.",
        ],
        correctIndex: 0,
        explanation: "Otro día, gracias.",
        wordCardIds: ["otro-dia"],
        xp: 3,
      },
      {
        id: "u8l6-2",
        type: "situational-choose",
        prompt: "Pick the soft decline.",
        situation: "Invite for tonight — you already have plans.",
        options: [
          "Gracias, pero esta noche no puedo.",
          "No. Adiós para siempre.",
          "¿Dónde está el baño? No.",
          "Comí tu plan.",
        ],
        correctIndex: 0,
        explanation: "Gracias, pero esta noche no puedo.",
        wordCardIds: ["otra-vez", "esta-noche"],
        xp: 4,
      },
      {
        id: "u8l6-3",
        type: "tap-chips",
        prompt: "Build: “Can we do another day?”",
        chips: ["¿Podemos", "otro", "día?", "metro", "fui", "jugo"],
        correctOrder: ["¿Podemos", "otro", "día?"],
        explanation: "¿Podemos otro día?",
        wordCardIds: ["otro-dia"],
        xp: 3,
      },
      {
        id: "u8l6-4",
        type: "translate",
        prompt: "Translate: “Maybe another day. Thanks!”",
        acceptedAnswers: [
          "Tal vez otro día. ¡Gracias!",
          "Tal vez otro día. Gracias!",
          "Tal vez otro día. ¡Gracias",
          "Tal vez otro día. Gracias",
          "Tal vez otro día, gracias.",
          "Tal vez otro día, gracias",
        ],
        hint: "Tal vez…",
        explanation: "Tal vez otro día. ¡Gracias!",
        wordCardIds: ["otra-vez", "otro-dia"],
        xp: 4,
      },
      listen(
        "u8l6-5",
        "Gracias, pero ahora no puedo.",
        ["Thanks, but I can't right now.", "I ate thanks.", "Where is now?", "I want the check now."],
        0,
        "Gracias, pero ahora no puedo.",
        ["otra-vez"]
      ),
      {
        id: "u8l6-6",
        type: "select",
        prompt: "Reschedule to Saturday:",
        options: [
          "¿Qué tal el sábado?",
          "¿Qué comiste sábado carro?",
          "Soy el sábado.",
          "La cuenta sábado.",
        ],
        correctIndex: 0,
        explanation: "¿Qué tal el sábado?",
        wordCardIds: ["el-sabado", "que-tal-si"],
        xp: 3,
      },
      {
        id: "u8l6-7",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "Thanks, but I can't right now.",
        template: "Gracias, pero ahora no ___.",
        acceptedAnswers: ["puedo", "Puedo"],
        hint: "I can (negative)",
        explanation: "Gracias, pero ahora no puedo.",
        wordCardIds: ["otra-vez"],
        xp: 3,
      },
      {
        id: "u8l6-8",
        type: "match-pairs",
        prompt: "Match soft-no phrases.",
        pairs: [
          { left: "ahora no puedo", right: "I can't right now" },
          { left: "otro día", right: "another day" },
          { left: "tal vez", right: "maybe" },
          { left: "¿Qué tal el sábado?", right: "How about Saturday?" },
        ],
        explanation: "Decline and reschedule toolkit.",
        wordCardIds: ["otra-vez", "otro-dia", "el-sabado"],
        xp: 4,
      },
      listen(
        "u8l6-9",
        "¿Podemos otro día?",
        ["Can we do another day?", "I went another day.", "Where is another day?", "Eat another day."],
        0,
        "¿Podemos otro día?",
        ["otro-dia"]
      ),
      {
        id: "u8l6-10",
        type: "situational-choose",
        prompt: "Pick the best reply.",
        situation: "Friend accepts your soft no and asks about Saturday.",
        options: [
          "El sábado me parece bien.",
          "Comí el sábado metro.",
          "Todo recto sábado.",
          "Soy la cuenta.",
        ],
        correctIndex: 0,
        explanation: "El sábado me parece bien.",
        wordCardIds: ["el-sabado", "me-parece"],
        xp: 3,
      },
    ],
  },

  "u8-l7": {
    id: "u8-l7",
    unitId: "unit-8",
    title: "Weekend & time phrases",
    description: "mañana, el sábado, a las…, fin de semana plans.",
    xpReward: 46,
    exercises: [
      teach("teach-u8l7-sabado", "el-sabado"),
      teach("teach-u8l7-viernes", "el-viernes"),
      teach("teach-u8l7-a-las", "a-las"),
      {
        id: "u8l7-1",
        type: "select",
        prompt: "“On Saturday I'm going to the movies” is…",
        options: [
          "El sábado voy al cine.",
          "En sábado comí cine.",
          "Soy el sábado cine.",
          "La cuenta sábado.",
        ],
        correctIndex: 0,
        explanation: "El sábado voy al cine.",
        wordCardIds: ["el-sabado", "el-cine"],
        xp: 3,
      },
      {
        id: "u8l7-2",
        type: "tap-chips",
        prompt: "Build: “See you at seven.”",
        chips: ["Nos", "vemos", "a", "las", "siete.", "metro", "fui"],
        correctOrder: ["Nos", "vemos", "a", "las", "siete."],
        explanation: "Nos vemos a las siete.",
        wordCardIds: ["a-las"],
        xp: 3,
      },
      {
        id: "u8l7-3",
        type: "translate",
        prompt: "Translate: “What are you doing this weekend?” (tú)",
        acceptedAnswers: [
          "¿Qué haces este fin de semana?",
          "Que haces este fin de semana?",
          "¿Qué haces este fin de semana",
          "Qué haces este fin de semana",
          "¿Qué vas a hacer este fin de semana?",
          "Que vas a hacer este fin de semana?",
        ],
        hint: "fin de semana",
        explanation: "¿Qué haces este fin de semana?",
        wordCardIds: ["fin-de-semana"],
        xp: 4,
      },
      listen(
        "u8l7-4",
        "Voy a llegar a las seis.",
        ["I arrived at six.", "I'm going to arrive at six.", "Where is six?", "I like juice at six."],
        1,
        "Voy a llegar a las seis.",
        ["ir-a", "a-las"]
      ),
      {
        id: "u8l7-5",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "On Friday we're going to have dinner.",
        template: "El viernes vamos a ___.",
        acceptedAnswers: ["cenar", "Cenar"],
        hint: "to have dinner",
        explanation: "El viernes vamos a cenar.",
        wordCardIds: ["el-viernes", "vamos-a"],
        xp: 3,
      },
      {
        id: "u8l7-6",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "You want to rest this weekend.",
        options: [
          "Este fin de semana quiero descansar.",
          "Este fin de semana comí el metro.",
          "Este fin de semana soy la cuenta.",
          "Este fin de semana todo recto.",
        ],
        correctIndex: 0,
        explanation: "Este fin de semana quiero descansar.",
        wordCardIds: ["fin-de-semana", "quiero-inf", "descansar"],
        xp: 3,
      },
      {
        id: "u8l7-7",
        type: "match-pairs",
        prompt: "Match time phrases.",
        pairs: [
          { left: "mañana", right: "tomorrow" },
          { left: "el sábado", right: "on Saturday" },
          { left: "a las siete", right: "at seven" },
          { left: "esta noche", right: "tonight" },
        ],
        explanation: "Plan time anchors.",
        wordCardIds: ["manana", "el-sabado", "a-las", "esta-noche"],
        xp: 4,
      },
      listen(
        "u8l7-8",
        "El sábado voy al cine.",
        ["On Saturday I'm going to the movies.", "I went Saturday.", "Where is the cinema tip?", "I want the check Saturday."],
        0,
        "El sábado voy al cine.",
        ["el-sabado", "el-cine"]
      ),
      {
        id: "u8l7-9",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "See you at eight.",
        template: "Nos vemos a ___ ocho.",
        acceptedAnswers: ["las", "Las"],
        hint: "a las…",
        explanation: "Nos vemos a las ocho.",
        wordCardIds: ["a-las"],
        xp: 3,
      },
      {
        id: "u8l7-10",
        type: "select",
        prompt: "Unit 4 reuse: “in the morning” is…",
        options: ["por la mañana", "por el carro", "por los platos", "a las mañana wrong"],
        correctIndex: 0,
        explanation: "por la mañana (U4).",
        wordCardIds: ["por-la-manana"],
        xp: 3,
      },
    ],
  },

  "u8-l8": {
    id: "u8-l8",
    unitId: "unit-8",
    title: "Review + reuse",
    description: "Mix ir a, wants, invites, soft no — plus U4–U7 vocab.",
    xpReward: 48,
    exercises: [
      {
        id: "u8l8-1",
        type: "select",
        prompt: "“I'm going to take the metro” is…",
        options: [
          "Voy a tomar el metro.",
          "Fui tomar el metro only past",
          "Como el metro.",
          "La cuenta metro.",
        ],
        correctIndex: 0,
        explanation: "Voy a tomar el metro.",
        wordCardIds: ["ir-a", "metro"],
        xp: 3,
      },
      {
        id: "u8l8-2",
        type: "tap-chips",
        prompt: "Build: “Would you like to get juice?”",
        chips: ["¿Te", "gustaría", "tomar", "un", "jugo?", "fui", "oficina"],
        correctOrder: ["¿Te", "gustaría", "tomar", "un", "jugo?"],
        explanation: "¿Te gustaría tomar un jugo?",
        wordCardIds: ["te-gustaria", "jugo"],
        xp: 3,
      },
      {
        id: "u8l8-3",
        type: "translate",
        prompt: "Translate: “I'm going to clean the apartment tomorrow.”",
        acceptedAnswers: [
          "Voy a limpiar el departamento mañana.",
          "Voy a limpiar el departamento mañana",
          "Mañana voy a limpiar el departamento.",
          "Mañana voy a limpiar el departamento",
        ],
        hint: "Voy a limpiar…",
        explanation: "Voy a limpiar el departamento mañana.",
        wordCardIds: ["ir-a", "limpiar", "departamento", "manana"],
        xp: 4,
      },
      listen(
        "u8l8-4",
        "Me parece una buena idea.",
        ["It seems like a good idea to me.", "I ate a good idea.", "Where is the idea?", "Turn left idea."],
        0,
        "Me parece una buena idea.",
        ["me-parece"]
      ),
      {
        id: "u8l8-5",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "Invite a friend downtown for coffee.",
        options: [
          "¿Quieres ir al centro a tomar un café?",
          "¿Comiste el centro café?",
          "Soy el centro.",
          "La cuenta centro.",
        ],
        correctIndex: 0,
        explanation: "¿Quieres ir al centro a tomar un café?",
        wordCardIds: ["quieres-inf", "el-centro", "cafe"],
        xp: 3,
      },
      {
        id: "u8l8-6",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "Maybe another day. Thanks!",
        template: "Tal ___ otro día. ¡Gracias!",
        acceptedAnswers: ["vez", "Vez"],
        hint: "tal vez",
        explanation: "Tal vez otro día. ¡Gracias!",
        wordCardIds: ["otra-vez", "otro-dia"],
        xp: 3,
      },
      {
        id: "u8l8-7",
        type: "match-pairs",
        prompt: "Review match.",
        pairs: [
          { left: "voy a", right: "I'm going to" },
          { left: "me gustaría", right: "I would like" },
          { left: "el fin de semana", right: "the weekend" },
          { left: "el centro", right: "downtown" },
        ],
        explanation: "Plans + U4–U6 reuse.",
        wordCardIds: ["ir-a", "me-gustaria", "fin-de-semana", "el-centro"],
        xp: 4,
      },
      listen(
        "u8l8-8",
        "Voy a limpiar el departamento mañana.",
        ["I'm going to clean the apartment tomorrow.", "I cleaned yesterday.", "Where is the apartment?", "I want juice."],
        0,
        "Voy a limpiar el departamento mañana.",
        ["ir-a", "limpiar", "departamento", "manana"]
      ),
      {
        id: "u8l8-9",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "We're going to cook tonight.",
        template: "Vamos a ___ esta noche.",
        acceptedAnswers: ["cocinar", "Cocinar"],
        hint: "to cook",
        explanation: "Vamos a cocinar esta noche.",
        wordCardIds: ["vamos-a", "cocinar", "esta-noche"],
        xp: 3,
      },
      {
        id: "u8l8-10",
        type: "select",
        prompt: "U7 contrast: “I went downtown yesterday” is past…",
        options: [
          "Ayer fui al centro.",
          "Ayer voy a ir al centro forever future",
          "Ayer quiero el metro.",
          "Ayer la cuenta.",
        ],
        correctIndex: 0,
        explanation: "Ayer fui al centro — past, not plan.",
        wordCardIds: ["el-centro"],
        xp: 3,
      },
    ],
  },

  "u8-l9": {
    id: "u8-l9",
    unitId: "unit-8",
    title: "Story: Friday plans",
    description: "Story-listen #1 + cloze — invites and near future.",
    xpReward: 48,
    exercises: [
      storyListen(
        "u8l9-story",
        "Planes para el viernes",
        [
          { text: "Ana me dice: ¿Te gustaría salir el viernes?" },
          { text: "Me parece bien. ¿Qué tal si vamos al cine?" },
          { text: "Sí. Vamos a tomar un café antes." },
          { text: "Nos vemos a las siete en el centro." },
          { text: "Yo voy a llegar temprano." },
        ],
        [
          {
            prompt: "What does Ana ask?",
            options: ["Would you like to go out Friday?", "Only ask for the tip", "Where is the metro forever?", "Nothing"],
            correctIndex: 0,
            explanation: "¿Te gustaría salir el viernes?",
          },
          {
            prompt: "What do they suggest next?",
            options: ["Go to the movies", "Only clean forever", "Ask for the check only", "Sleep at the station"],
            correctIndex: 0,
            explanation: "¿Qué tal si vamos al cine?",
          },
          {
            prompt: "What before the movie?",
            options: ["Get a coffee", "Only the tip jar", "Only the bank tip", "Nothing"],
            correctIndex: 0,
            explanation: "Vamos a tomar un café antes.",
          },
          {
            prompt: "Where and when?",
            options: ["Downtown at seven", "Only juice forever", "Only the map", "No meeting"],
            correctIndex: 0,
            explanation: "Nos vemos a las siete en el centro.",
          },
        ],
        ["te-gustaria", "salir", "el-viernes", "me-parece", "que-tal-si", "el-cine", "vamos-a", "cafe", "a-las", "el-centro", "ir-a", "temprano"],
        "Friday-plans story — Neural2 voice rotation.",
        12
      ),
      {
        id: "u8l9-1",
        type: "select",
        prompt: "From the story — soft agreement was…",
        options: ["Me parece bien.", "Comí bien.", "Todo recto bien.", "La cuenta bien."],
        correctIndex: 0,
        explanation: "Me parece bien.",
        wordCardIds: ["me-parece"],
        xp: 3,
      },
      cloze(
        "u8l9-cloze-1",
        "¿Te ___ salir el viernes?",
        ["gustaría", "gustaria", "Gustaría"],
        "¿Te gustaría salir el viernes?",
        ["te-gustaria", "salir", "el-viernes"],
        {
          hint: "would like",
          audioText: "¿Te gustaría salir el viernes?",
          voice: "f",
        }
      ),
      cloze(
        "u8l9-cloze-2",
        "¿Qué tal si vamos al ___?",
        ["cine", "Cine"],
        "¿Qué tal si vamos al cine?",
        ["que-tal-si", "el-cine"],
        {
          hint: "movies",
          audioText: "¿Qué tal si vamos al cine?",
          voice: "m",
        }
      ),
      cloze(
        "u8l9-cloze-3",
        "Nos vemos a ___ siete en el centro.",
        ["las", "Las"],
        "Nos vemos a las siete en el centro.",
        ["a-las", "el-centro"],
        {
          hint: "a las…",
          audioText: "Nos vemos a las siete en el centro.",
          voice: "c",
        }
      ),
    ],
  },

  "u8-l10": {
    id: "u8-l10",
    unitId: "unit-8",
    title: "More plans practice",
    description: "New mixes — time, invites, soft no, U4–U7 reuse.",
    xpReward: 44,
    exercises: [
      {
        id: "u8l10-1",
        type: "translate",
        prompt: "Translate: “I'm going to study at the office tomorrow.”",
        acceptedAnswers: [
          "Voy a estudiar en la oficina mañana.",
          "Voy a estudiar en la oficina mañana",
          "Mañana voy a estudiar en la oficina.",
          "Mañana voy a estudiar en la oficina",
        ],
        hint: "Voy a estudiar…",
        explanation: "Voy a estudiar en la oficina mañana.",
        wordCardIds: ["ir-a", "estudiar", "oficina", "manana"],
        xp: 4,
      },
      {
        id: "u8l10-2",
        type: "tap-chips",
        prompt: "Build: “How about Saturday at eight?”",
        chips: ["¿Qué", "tal", "el", "sábado", "a", "las", "ocho?", "metro"],
        correctOrder: ["¿Qué", "tal", "el", "sábado", "a", "las", "ocho?"],
        explanation: "¿Qué tal el sábado a las ocho?",
        wordCardIds: ["que-tal-si", "el-sabado", "a-las"],
        xp: 3,
      },
      listen(
        "u8l10-3",
        "¿Quieres cocinar juntos esta noche?",
        ["Do you want to cook together tonight?", "Did you cook yesterday?", "Where is tonight?", "I want the check."],
        0,
        "¿Quieres cocinar juntos esta noche?",
        ["quieres-inf", "cocinar", "esta-noche"]
      ),
      {
        id: "u8l10-4",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I would like to rest this weekend.",
        template: "Me gustaría ___ este fin de semana.",
        acceptedAnswers: ["descansar", "Descansar"],
        hint: "to rest",
        explanation: "Me gustaría descansar este fin de semana.",
        wordCardIds: ["me-gustaria", "descansar", "fin-de-semana"],
        xp: 3,
      },
      {
        id: "u8l10-5",
        type: "situational-choose",
        prompt: "Pick the best soft no.",
        situation: "Friend invites you out but you need to work.",
        options: [
          "Gracias, pero voy a trabajar.",
          "Nunca.",
          "Comí trabajar.",
          "Todo recto trabajar.",
        ],
        correctIndex: 0,
        explanation: "Gracias, pero voy a trabajar.",
        wordCardIds: ["otra-vez", "ir-a", "trabajar"],
        xp: 3,
      },
      {
        id: "u8l10-6",
        type: "select",
        prompt: "“Shall we go downtown?” is…",
        options: [
          "¿Vamos al centro?",
          "¿Comimos el centro?",
          "¿Dónde está centro ayer?",
          "La cuenta centro.",
        ],
        correctIndex: 0,
        explanation: "¿Vamos al centro?",
        wordCardIds: ["vamos-a", "el-centro"],
        xp: 3,
      },
      {
        id: "u8l10-7",
        type: "match-pairs",
        prompt: "Practice match.",
        pairs: [
          { left: "esta noche", right: "tonight" },
          { left: "mañana", right: "tomorrow" },
          { left: "otro día", right: "another day" },
          { left: "a las seis", right: "at six" },
        ],
        explanation: "Time + soft reschedule.",
        wordCardIds: ["esta-noche", "manana", "otro-dia", "a-las"],
        xp: 4,
      },
      listen(
        "u8l10-8",
        "Mañana voy a limpiar la cocina.",
        ["Tomorrow I'm going to clean the kitchen.", "I cleaned yesterday.", "Where is the kitchen?", "I want tacos."],
        0,
        "Mañana voy a limpiar la cocina.",
        ["manana", "ir-a", "limpiar", "cocina"]
      ),
      {
        id: "u8l10-9",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "Are you going to come on Friday? (tú)",
        template: "¿Vas a venir el ___?",
        acceptedAnswers: ["viernes", "Viernes"],
        hint: "Friday",
        explanation: "¿Vas a venir el viernes?",
        wordCardIds: ["ir-a", "el-viernes"],
        xp: 3,
      },
      {
        id: "u8l10-10",
        type: "situational-choose",
        prompt: "Pick the best question.",
        situation: "Ask if they want coffee (tú, casual).",
        options: [
          "¿Quieres un café?",
          "¿Comiste un café carro?",
          "¿Soy café?",
          "¿La cuenta café?",
        ],
        correctIndex: 0,
        explanation: "¿Quieres un café?",
        wordCardIds: ["quieres-inf", "cafe"],
        xp: 3,
      },
    ],
  },

  "u8-l11": {
    id: "u8-l11",
    unitId: "unit-8",
    title: "Story: Weekend invite",
    description: "Story-listen #2 + cloze — soft no then Saturday plan.",
    xpReward: 48,
    exercises: [
      storyListen(
        "u8l11-story",
        "Invitación de fin de semana",
        [
          { text: "Luis pregunta: ¿Quieres salir esta noche?" },
          { text: "Gracias, pero ahora no puedo." },
          { text: "¿Qué tal el sábado?" },
          { text: "El sábado me parece bien." },
          { text: "Vamos a caminar por el centro a las diez." },
        ],
        [
          {
            prompt: "What does Luis ask first?",
            options: ["Want to go out tonight?", "Only the tip", "Where is juice forever?", "Nothing"],
            correctIndex: 0,
            explanation: "¿Quieres salir esta noche?",
          },
          {
            prompt: "How does the friend reply?",
            options: ["Soft no — can't right now", "Hard never forever", "Asks for the check only", "Leaves town"],
            correctIndex: 0,
            explanation: "Gracias, pero ahora no puedo.",
          },
          {
            prompt: "What alternative day?",
            options: ["Saturday", "Only yesterday", "Only the metro tip", "No day"],
            correctIndex: 0,
            explanation: "¿Qué tal el sábado?",
          },
          {
            prompt: "Final plan?",
            options: ["Walk downtown at ten", "Only clean forever", "Ask for tip only", "Stay home silent"],
            correctIndex: 0,
            explanation: "Vamos a caminar por el centro a las diez.",
          },
        ],
        ["quieres-inf", "salir", "esta-noche", "otra-vez", "el-sabado", "me-parece", "vamos-a", "caminar", "el-centro", "a-las", "fin-de-semana"],
        "Weekend-invite story — Neural2 voice rotation.",
        12
      ),
      {
        id: "u8l11-1",
        type: "select",
        prompt: "From the story — soft no used…",
        options: ["ahora no puedo", "nunca jamás", "comí tu plan", "todo recto"],
        correctIndex: 0,
        explanation: "ahora no puedo.",
        wordCardIds: ["otra-vez"],
        xp: 3,
      },
      cloze(
        "u8l11-cloze-1",
        "¿Quieres ___ esta noche?",
        ["salir", "Salir"],
        "¿Quieres salir esta noche?",
        ["quieres-inf", "salir", "esta-noche"],
        {
          hint: "to go out",
          audioText: "¿Quieres salir esta noche?",
          voice: "f",
        }
      ),
      cloze(
        "u8l11-cloze-2",
        "El sábado me ___ bien.",
        ["parece", "Parece"],
        "El sábado me parece bien.",
        ["el-sabado", "me-parece"],
        {
          hint: "seems",
          audioText: "El sábado me parece bien.",
          voice: "m",
        }
      ),
      cloze(
        "u8l11-cloze-3",
        "Vamos a caminar por el centro a ___ diez.",
        ["las", "Las"],
        "Vamos a caminar por el centro a las diez.",
        ["vamos-a", "caminar", "el-centro", "a-las"],
        {
          hint: "a las…",
          audioText: "Vamos a caminar por el centro a las diez.",
          voice: "c",
        }
      ),
    ],
  },

  "u8-l12": {
    id: "u8-l12",
    unitId: "unit-8",
    title: "Unit 8 check",
    description: "Final check — ir a, wants, invites, soft no, time phrases.",
    xpReward: 50,
    exercises: [
      {
        id: "u8l12-1",
        type: "select",
        prompt: "Near future “I'm going to…” starts with…",
        options: ["Voy a", "Fui a always past", "Como a", "La cuenta a"],
        correctIndex: 0,
        explanation: "Voy a + infinitive.",
        wordCardIds: ["ir-a"],
        xp: 3,
      },
      {
        id: "u8l12-2",
        type: "select",
        prompt: "Polite invite “Would you like…?” is…",
        options: ["¿Te gustaría…?", "¿Comiste…?", "¿Dónde está… ayer?", "Fui…"],
        correctIndex: 0,
        explanation: "¿Te gustaría…?",
        wordCardIds: ["te-gustaria"],
        xp: 3,
      },
      {
        id: "u8l12-3",
        type: "tap-chips",
        prompt: "Build: “Tomorrow I'm going to cook.”",
        chips: ["Mañana", "voy", "a", "cocinar.", "fui", "jugo"],
        correctOrder: ["Mañana", "voy", "a", "cocinar."],
        explanation: "Mañana voy a cocinar.",
        wordCardIds: ["manana", "ir-a", "cocinar"],
        xp: 3,
      },
      {
        id: "u8l12-4",
        type: "translate",
        prompt: "Translate: “Would you like to go to the movies on Saturday?”",
        acceptedAnswers: [
          "¿Te gustaría ir al cine el sábado?",
          "Te gustaría ir al cine el sábado?",
          "¿Te gustaría ir al cine el sábado",
          "Te gustaría ir al cine el sábado",
        ],
        hint: "¿Te gustaría ir al cine…?",
        explanation: "¿Te gustaría ir al cine el sábado?",
        wordCardIds: ["te-gustaria", "el-cine", "el-sabado"],
        xp: 4,
      },
      listen(
        "u8l12-5",
        "Gracias, pero ahora no puedo.",
        ["Thanks, but I can't right now.", "I went thanks.", "Where is now?", "I want tacos."],
        0,
        "Gracias, pero ahora no puedo.",
        ["otra-vez"]
      ),
      {
        id: "u8l12-6",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "We're going to rest this weekend.",
        template: "Vamos a ___ este fin de semana.",
        acceptedAnswers: ["descansar", "Descansar"],
        hint: "to rest",
        explanation: "Vamos a descansar este fin de semana.",
        wordCardIds: ["vamos-a", "descansar", "fin-de-semana"],
        xp: 3,
      },
      {
        id: "u8l12-7",
        type: "match-pairs",
        prompt: "Final Unit 8 match.",
        pairs: [
          { left: "voy a", right: "I'm going to" },
          { left: "me parece bien", right: "sounds good to me" },
          { left: "otro día", right: "another day" },
          { left: "a las siete", right: "at seven" },
        ],
        explanation: "Core Unit 8 lemmas.",
        wordCardIds: ["ir-a", "me-parece", "otro-dia", "a-las"],
        xp: 4,
      },
      {
        id: "u8l12-8",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "Friend asks ¿Qué vas a hacer mañana? You will study.",
        options: [
          "Voy a estudiar.",
          "Comí estudiar.",
          "Todo recto estudiar.",
          "Soy el metro.",
        ],
        correctIndex: 0,
        explanation: "Voy a estudiar.",
        wordCardIds: ["ir-a", "estudiar", "manana"],
        xp: 3,
      },
      {
        id: "u8l12-9",
        type: "select",
        prompt: "Softer than quiero for “I would like to go out”…",
        options: [
          "Me gustaría salir.",
          "Fui salir.",
          "Como salir.",
          "La cuenta salir.",
        ],
        correctIndex: 0,
        explanation: "Me gustaría salir.",
        wordCardIds: ["me-gustaria", "salir"],
        xp: 3,
      },
      {
        id: "u8l12-10",
        type: "situational-choose",
        prompt: "Pick the best answer.",
        situation: "Someone says ¿Qué tal si cenamos a las ocho? You agree.",
        options: ["Me parece bien.", "Nunca.", "Comí ocho.", "Todo recto ocho."],
        correctIndex: 0,
        explanation: "Me parece bien.",
        wordCardIds: ["me-parece", "que-tal-si", "a-las"],
        xp: 3,
      },
      listen(
        "u8l12-11",
        "¿Te gustaría ir al cine el sábado?",
        ["Would you like to go to the movies on Saturday?", "Did you go Saturday?", "Where is Saturday?", "I want the check."],
        0,
        "¿Te gustaría ir al cine el sábado?",
        ["te-gustaria", "el-cine", "el-sabado"]
      ),
    ],
  },
};

export const UNIT8_LESSON_IDS = [
  "u8-l1",
  "u8-l2",
  "u8-l3",
  "u8-l4",
  "u8-l5",
  "u8-l6",
  "u8-l7",
  "u8-l8",
  "u8-l9",
  "u8-l10",
  "u8-l11",
  "u8-l12",
] as const;
