/**
 * Unit 6 — Getting around (~12 lessons). Spanish.
 * Merged via intermediate.ts into mock-data.
 */
import type { Lesson, WordCard } from "../types";
import { audioSrcFor, voiceForIndex, type AudioVoice } from "../audio";
import { dlg } from "./dialogues";

function teach(
  id: string,
  wordCardId: string
): import("../types").TeachExercise {
  return {
    id,
    type: "teach",
    prompt: "New word — learn it, then practice.",
    explanation: "",
    wordCardId,
    wordCardIds: [wordCardId],
    xp: 0,
  };
}

let listenVoiceIndex = 600;

function listen(
  id: string,
  audioText: string,
  options: string[],
  correctIndex: number,
  explanation: string,
  wordCardIds: string[],
  xp = 3
): import("../types").ListeningChooseExercise {
  const voice = voiceForIndex(listenVoiceIndex);
  listenVoiceIndex += 1;
  return {
    id,
    type: "listening-choose",
    prompt: "What did you hear?",
    audioText,
    audioSrc: audioSrcFor(audioText, voice),
    options,
    correctIndex,
    explanation,
    wordCardIds,
    xp,
  };
}

function cloze(
  id: string,
  template: string,
  acceptedAnswers: string[],
  explanation: string,
  wordCardIds: string[],
  opts: {
    hint?: string;
    audioText: string;
    voice?: AudioVoice;
    storyLabel?: string;
    xp?: number;
  }
): import("../types").ClozeExercise {
  const voice = opts.voice ?? "f";
  return {
    id,
    type: "cloze",
    prompt: "Fill the blank from the story",
    template,
    acceptedAnswers,
    hint: opts.hint,
    explanation,
    wordCardIds,
    audioText: opts.audioText,
    audioSrc: audioSrcFor(opts.audioText, voice),
    storyLabel: opts.storyLabel ?? "From the story",
    xp: opts.xp ?? 3,
  };
}

function storyListen(
  id: string,
  title: string,
  lines: { text: string; en?: string; voice?: AudioVoice }[],
  questions: {
    prompt: string;
    options: string[];
    correctIndex: number;
    explanation?: string;
  }[],
  wordCardIds: string[],
  explanation = "Story comprehension — replay anytime.",
  xp = 10
): import("../types").StoryListenExercise {
  const withVoices = lines.map((line, i) => ({
    text: line.text,
    en: line.en,
    voice: line.voice ?? voiceForIndex(i),
  }));
  return {
    id,
    type: "story-listen",
    prompt: "Listen to the story, then answer",
    title,
    lines: withVoices,
    questions,
    explanation,
    wordCardIds,
    xp,
  };
}


function dictation(
  id: string,
  audioText: string,
  acceptedAnswers: string[],
  explanation: string,
  wordCardIds: string[],
  opts: { hint?: string; voice?: AudioVoice; xp?: number } = {}
): import("../types").DictationExercise {
  const voice = opts.voice ?? "f";
  return {
    id,
    type: "dictation",
    prompt: "Type what you hear",
    audioText,
    audioSrc: audioSrcFor(audioText, voice),
    acceptedAnswers,
    hint: opts.hint,
    explanation,
    wordCardIds,
    xp: opts.xp ?? 4,
  };
}


export const UNIT6_WORD_CARDS: Record<string, WordCard> = {
  bano: {
    id: "bano",
    lemma: "el baño",
    pos: "noun",
    gender: "m",
    gloss: "bathroom / restroom",
    meaningSummary:
      "Public or home bathroom. ¿Dónde está el baño? is the classic ask.",
    examples: [
      { es: "¿Dónde está el baño?", en: "Where is the bathroom?" },
      { es: "El baño está a la derecha.", en: "The bathroom is on the right." },
    ],
    useWhen: "Finding a restroom.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A2",
  },
  farmacia: {
    id: "farmacia",
    lemma: "la farmacia",
    pos: "noun",
    gender: "f",
    gloss: "pharmacy",
    meaningSummary: "Drugstore / pharmacy. La farmacia está cerca / a la izquierda.",
    examples: [
      { es: "La farmacia está a la izquierda.", en: "The pharmacy is on the left." },
      { es: "¿Dónde está la farmacia?", en: "Where is the pharmacy?" },
    ],
    useWhen: "Looking for a pharmacy.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A2",
  },
  estacion: {
    id: "estacion",
    lemma: "la estación",
    pos: "noun",
    gender: "f",
    gloss: "station",
    meaningSummary:
      "Train / metro station. ¿Dónde está la estación? / la estación de metro.",
    examples: [
      { es: "La estación está lejos.", en: "The station is far." },
      { es: "¿Cómo llego a la estación?", en: "How do I get to the station?" },
    ],
    useWhen: "Talking about transit stations.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A2",
  },
  banco: {
    id: "banco",
    lemma: "el banco",
    pos: "noun",
    gender: "m",
    gloss: "bank",
    meaningSummary: "Bank (money). El banco está a la derecha / cerca del centro.",
    examples: [
      { es: "El banco está a la derecha.", en: "The bank is on the right." },
      { es: "Necesito ir al banco.", en: "I need to go to the bank." },
    ],
    useWhen: "Finding a bank.",
    dontUseWhen: "For a park bench, context differs — here we mean the bank.",
    formality: "neutral",
    cefr: "A2",
  },
  hotel: {
    id: "hotel",
    lemma: "el hotel",
    pos: "noun",
    gender: "m",
    gloss: "hotel",
    meaningSummary: "Hotel. Mi hotel está cerca / ¿Cómo llego al hotel?",
    examples: [
      { es: "Mi hotel está cerca del centro.", en: "My hotel is near downtown." },
      { es: "¿Cómo llego al hotel?", en: "How do I get to the hotel?" },
    ],
    useWhen: "Travel lodging directions.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A2",
  },
  "a-pie": {
    id: "a-pie",
    lemma: "a pie",
    pos: "phrase",
    gender: "n/a",
    gloss: "on foot / walking",
    meaningSummary: "Travel by walking. Voy a pie / ¿Queda lejos a pie?",
    examples: [
      { es: "Voy al centro a pie.", en: "I'm going downtown on foot." },
      { es: "No queda muy lejos a pie.", en: "It's not very far on foot." },
    ],
    useWhen: "Saying you'll walk instead of taking transit.",
    dontUseWhen: "Don't confuse with pie (foot) alone as a body part lesson.",
    contrast: "en metro / en carro",
    formality: "neutral",
    cefr: "A2",
  },
  autobus: {
    id: "autobus",
    lemma: "el autobús",
    pos: "noun",
    gender: "m",
    gloss: "bus",
    meaningSummary:
      "Bus (widely understood). Tomo el autobús / Voy en autobús. Some countries also say camión — we stay with autobús here.",
    examples: [
      { es: "Tomo el autobús al centro.", en: "I take the bus downtown." },
      { es: "¿Dónde está la parada del autobús?", en: "Where is the bus stop?" },
    ],
    useWhen: "City bus transit.",
    dontUseWhen: "For subway use metro.",
    contrast: "metro / carro / a pie",
    formality: "neutral",
    cefr: "A2",
  },
  gira: {
    id: "gira",
    lemma: "gira / girar",
    pos: "verb",
    gender: "n/a",
    gloss: "turn (imperative)",
    meaningSummary:
      "Common street direction: Gira a la derecha / Gira a la izquierda. Dobla is a close synonym in many places.",
    conjugations: [
      {
        label: "Present indicative",
        forms: [
          { person: "yo", form: "giro" },
          { person: "tú", form: "giras" },
          { person: "él/ella/usted", form: "gira" },
          { person: "nosotros/as", form: "giramos" },
          { person: "ustedes", form: "giran" },
        ],
      },
    ],
    examples: [
      { es: "Gira a la derecha.", en: "Turn right." },
      { es: "Gira a la izquierda en la esquina.", en: "Turn left at the corner." },
    ],
    useWhen: "Giving turn-by-turn directions.",
    dontUseWhen: "n/a",
    contrast: "todo recto (go straight)",
    formality: "neutral",
    cefr: "A2",
  },
  cuadra: {
    id: "cuadra",
    lemma: "la cuadra",
    pos: "noun",
    gender: "f",
    gloss: "city block",
    meaningSummary:
      "City block — everyday street talk. Sigue dos cuadras / Está a una cuadra.",
    examples: [
      { es: "Sigue todo recto dos cuadras.", en: "Keep going straight two blocks." },
      { es: "La farmacia está a una cuadra.", en: "The pharmacy is one block away." },
    ],
    useWhen: "Measuring short walking distances in a city.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A2",
  },
  parada: {
    id: "parada",
    lemma: "la parada",
    pos: "noun",
    gender: "f",
    gloss: "stop (bus/transit)",
    meaningSummary: "Transit stop. La parada del autobús / ¿Dónde está la parada?",
    examples: [
      { es: "¿Dónde está la parada?", en: "Where is the stop?" },
      { es: "La parada está cerca.", en: "The stop is nearby." },
    ],
    useWhen: "Finding where to catch a bus.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A2",
  },
  mapa: {
    id: "mapa",
    lemma: "el mapa",
    pos: "noun",
    gender: "m",
    gloss: "map",
    meaningSummary: "Map. ¿Tienes un mapa? / Mira el mapa, por favor.",
    examples: [
      { es: "Disculpe, ¿tiene un mapa?", en: "Excuse me, do you have a map?" },
      { es: "Según el mapa, el hotel está cerca.", en: "According to the map, the hotel is nearby." },
    ],
    useWhen: "Asking for or reading a map.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A2",
  },
};

export const UNIT6_LESSONS: Record<string, Lesson> = {
  "u6-l1": {
    id: "u6-l1",
    unitId: "unit-6",
    title: "Where is it?",
    description: "¿Dónde está…?, cerca, lejos — core location asks.",
    xpReward: 42,
    exercises: [
      teach("teach-u6l1-donde", "donde-esta"),
      {
        id: "u6l1-1",
        type: "select",
        prompt: "How do you ask “Where is the bathroom?”",
        options: [
          "¿Dónde está el baño?",
          "¿Qué comiste el baño?",
          "¿Me gusta el baño?",
          "¿Quiero el baño ayer?",
        ],
        correctIndex: 0,
        explanation: "¿Dónde está el baño?",
        wordCardIds: ["donde-esta", "bano"],
        xp: 3,
      },
      teach("teach-u6l1-bano", "bano"),
      teach("teach-u6l1-cerca", "cerca"),
      teach("teach-u6l1-lejos", "lejos"),
      {
        id: "u6l1-2",
        type: "select",
        prompt: "Opposite of cerca?",
        options: ["jugo", "lejos", "cuenta", "despierto"],
        correctIndex: 1,
        explanation: "cerca = near; lejos = far.",
        wordCardIds: ["cerca", "lejos"],
        xp: 3,
      },
      {
        id: "u6l1-3",
        type: "tap-chips",
        prompt: "Build: “The café is nearby.”",
        chips: ["El", "café", "está", "cerca.", "lejos", "baño"],
        correctOrder: ["El", "café", "está", "cerca."],
        explanation: "El café está cerca.",
        wordCardIds: ["cerca"],
        xp: 3,
      },
      listen(
        "u6l1-4",
        "El café está cerca.",
        ["The café is nearby.", "The café is far.", "I want coffee.", "Turn left."],
        0,
        "El café está cerca = The café is nearby.",
        ["cerca"]
      ),
      {
        id: "u6l1-5",
        type: "situational-choose",
        prompt: "Pick the best answer.",
        situation: "Someone asks if the station is close; it isn't.",
        options: ["Está lejos.", "Me gusta lejos.", "Quiero lejos.", "Comí lejos."],
        correctIndex: 0,
        explanation: "Está lejos.",
        wordCardIds: ["lejos", "estacion"],
        xp: 3,
      },
      {
        id: "u6l1-6",
        type: "translate",
        prompt: "Translate: “Where is the pharmacy?”",
        acceptedAnswers: [
          "¿Dónde está la farmacia?",
          "¿Donde esta la farmacia?",
          "¿Dónde esta la farmacia?",
          "Donde está la farmacia?",
        ],
        hint: "¿Dónde está…?",
        explanation: "¿Dónde está la farmacia?",
        wordCardIds: ["donde-esta", "farmacia"],
        xp: 4,
      },
      {
        id: "u6l1-7",
        type: "match-pairs",
        prompt: "Match location basics.",
        pairs: [
          { left: "¿Dónde está?", right: "Where is…?" },
          { left: "cerca", right: "near" },
          { left: "lejos", right: "far" },
          { left: "el baño", right: "the bathroom" },
        ],
        explanation: "Location & distance basics.",
        wordCardIds: ["donde-esta", "cerca", "lejos", "bano"],
        xp: 4,
      },
      {
        id: "u6l1-8",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "Where is the bathroom?",
        template: "¿Dónde ___ el baño?",
        acceptedAnswers: ["está", "esta", "Está"],
        hint: "is (location)",
        explanation: "¿Dónde está el baño?",
        wordCardIds: ["donde-esta", "bano"],
        xp: 3,
      },
      listen(
        "u6l1-9",
        "La estación está lejos.",
        ["The station is far.", "The station is nearby.", "Turn right at the station.", "I like the station."],
        0,
        "La estación está lejos.",
        ["estacion", "lejos"]
      ),
    ],
  },

  "u6-l2": {
    id: "u6-l2",
    unitId: "unit-6",
    title: "How do I get there?",
    description: "¿Cómo llego…?, el centro, metro, and todo recto.",
    xpReward: 42,
    exercises: [
      teach("teach-u6l2-como-llego", "como-llego"),
      {
        id: "u6l2-1",
        type: "select",
        prompt: "“How do I get downtown?”",
        options: [
          "¿Me gusta el centro?",
          "¿Cómo llego al centro?",
          "¿Comí el centro?",
          "¿Quiero lejos centro?",
        ],
        correctIndex: 1,
        explanation: "¿Cómo llego al centro?",
        wordCardIds: ["como-llego", "el-centro"],
        xp: 3,
      },
      teach("teach-u6l2-centro", "el-centro"),
      teach("teach-u6l2-metro", "metro"),
      {
        id: "u6l2-2",
        type: "tap-chips",
        prompt: "Build: “I take the metro every day.”",
        chips: ["Tomo", "el", "metro", "todos", "los", "días.", "carro"],
        correctOrder: ["Tomo", "el", "metro", "todos", "los", "días."],
        explanation: "Tomo el metro todos los días.",
        wordCardIds: ["metro"],
        xp: 3,
      },
      teach("teach-u6l2-recto", "todo-recto"),
      {
        id: "u6l2-3",
        type: "situational-choose",
        prompt: "Pick the best directions.",
        situation: "A tourist should keep going straight, then turn right.",
        options: [
          "Me gusta el jugo.",
          "Comí ayer.",
          "Todo recto y luego a la derecha.",
          "La cuenta, por favor.",
        ],
        correctIndex: 2,
        explanation: "Todo recto y luego a la derecha.",
        wordCardIds: ["todo-recto", "a-la-derecha"],
        xp: 4,
      },
      listen(
        "u6l2-4",
        "¿Cómo llego al centro?",
        ["How do I get downtown?", "Where is the bathroom?", "I like downtown.", "I went downtown yesterday."],
        0,
        "¿Cómo llego al centro? = How do I get downtown?",
        ["como-llego", "el-centro"]
      ),
      {
        id: "u6l2-5",
        type: "translate",
        prompt: "Translate: “Keep going straight.”",
        acceptedAnswers: [
          "Sigue todo recto.",
          "Sigue todo recto",
          "Todo recto.",
          "Todo recto",
        ],
        hint: "todo recto",
        explanation: "Sigue todo recto / Todo recto.",
        wordCardIds: ["todo-recto"],
        xp: 4,
      },
      listen(
        "u6l2-6",
        "Voy al centro en metro.",
        ["I'm going downtown by metro.", "I want juice downtown.", "Turn left downtown.", "I woke up downtown."],
        0,
        "Voy al centro en metro.",
        ["el-centro", "metro"]
      ),
      {
        id: "u6l2-7",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "How do I get downtown?",
        template: "¿Cómo ___ al centro?",
        acceptedAnswers: ["llego", "Llego"],
        hint: "I arrive / I get (to)",
        explanation: "¿Cómo llego al centro?",
        wordCardIds: ["como-llego"],
        xp: 3,
      },
      {
        id: "u6l2-8",
        type: "match-pairs",
        prompt: "Match getting-around phrases.",
        pairs: [
          { left: "el centro", right: "downtown" },
          { left: "metro", right: "subway" },
          { left: "todo recto", right: "straight ahead" },
          { left: "¿Cómo llego a…?", right: "How do I get to…?" },
        ],
        explanation: "Transit & directions.",
        wordCardIds: ["el-centro", "metro", "todo-recto", "como-llego"],
        xp: 4,
      },
    ],
  },

  "u6-l3": {
    id: "u6-l3",
    unitId: "unit-6",
    title: "Left, right, straight",
    description: "Gira, a la derecha / izquierda, todo recto, and cuadras.",
    xpReward: 42,
    exercises: [
      teach("teach-u6l3-derecha", "a-la-derecha"),
      teach("teach-u6l3-izquierda", "a-la-izquierda"),
      teach("teach-u6l3-gira", "gira"),
      {
        id: "u6l3-1",
        type: "select",
        prompt: "“Turn right” is…",
        options: [
          "Gira a la izquierda.",
          "Me gusta la derecha.",
          "Gira a la derecha.",
          "Comí a la derecha.",
        ],
        correctIndex: 2,
        explanation: "Gira a la derecha.",
        wordCardIds: ["gira", "a-la-derecha"],
        xp: 3,
      },
      {
        id: "u6l3-2",
        type: "tap-chips",
        prompt: "Build: “Turn left.”",
        chips: ["Gira", "a", "la", "izquierda.", "derecha", "jugo"],
        correctOrder: ["Gira", "a", "la", "izquierda."],
        explanation: "Gira a la izquierda.",
        wordCardIds: ["gira", "a-la-izquierda"],
        xp: 3,
      },
      teach("teach-u6l3-recto", "todo-recto"),
      teach("teach-u6l3-cuadra", "cuadra"),
      {
        id: "u6l3-3",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "Someone should go straight for two blocks.",
        options: [
          "Sigue todo recto dos cuadras.",
          "Quiero dos cuadras de jugo.",
          "Me ducho dos cuadras.",
          "La cuenta dos cuadras.",
        ],
        correctIndex: 0,
        explanation: "Sigue todo recto dos cuadras.",
        wordCardIds: ["todo-recto", "cuadra"],
        xp: 4,
      },
      listen(
        "u6l3-4",
        "Gira a la derecha.",
        ["Turn right.", "Turn left.", "Go straight.", "The café is far."],
        0,
        "Gira a la derecha = Turn right.",
        ["gira", "a-la-derecha"]
      ),
      {
        id: "u6l3-5",
        type: "translate",
        prompt: "Translate: “The pharmacy is on the left.”",
        acceptedAnswers: [
          "La farmacia está a la izquierda.",
          "La farmacia esta a la izquierda.",
          "La farmacia está a la izquierda",
        ],
        hint: "a la izquierda",
        explanation: "La farmacia está a la izquierda.",
        wordCardIds: ["farmacia", "a-la-izquierda"],
        xp: 4,
      },
      {
        id: "u6l3-6",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "Turn right.",
        template: "Gira a la ___.",
        acceptedAnswers: ["derecha", "Derecha"],
        hint: "right",
        explanation: "Gira a la derecha.",
        wordCardIds: ["gira", "a-la-derecha"],
        xp: 3,
      },
      listen(
        "u6l3-7",
        "Sigue todo recto dos cuadras.",
        [
          "Keep going straight two blocks.",
          "Turn left two times.",
          "The metro is far.",
          "I want two juices.",
        ],
        0,
        "Sigue todo recto dos cuadras.",
        ["todo-recto", "cuadra"]
      ),
      {
        id: "u6l3-8",
        type: "match-pairs",
        prompt: "Match direction words.",
        pairs: [
          { left: "a la derecha", right: "to the right" },
          { left: "a la izquierda", right: "to the left" },
          { left: "todo recto", right: "straight ahead" },
          { left: "cuadra", right: "city block" },
        ],
        explanation: "Street directions.",
        wordCardIds: ["a-la-derecha", "a-la-izquierda", "todo-recto", "cuadra"],
        xp: 4,
      },
    ],
  },

  "u6-l4": {
    id: "u6-l4",
    unitId: "unit-6",
    title: "Near, far & places",
    description: "Cerca/lejos with farmacia, estación, banco, hotel.",
    xpReward: 42,
    exercises: [
      teach("teach-u6l4-farmacia", "farmacia"),
      teach("teach-u6l4-estacion", "estacion"),
      teach("teach-u6l4-banco", "banco"),
      teach("teach-u6l4-hotel", "hotel"),
      {
        id: "u6l4-1",
        type: "select",
        prompt: "“The bank is nearby” is…",
        options: [
          "El banco está cerca.",
          "El banco está lejos siempre.",
          "Me gusta el banco lejos.",
          "Quiero banco ayer.",
        ],
        correctIndex: 0,
        explanation: "El banco está cerca.",
        wordCardIds: ["banco", "cerca"],
        xp: 3,
      },
      {
        id: "u6l4-2",
        type: "tap-chips",
        prompt: "Build: “My hotel is near downtown.”",
        chips: ["Mi", "hotel", "está", "cerca", "del", "centro.", "lejos"],
        correctOrder: ["Mi", "hotel", "está", "cerca", "del", "centro."],
        explanation: "Mi hotel está cerca del centro.",
        wordCardIds: ["hotel", "cerca", "el-centro"],
        xp: 3,
      },
      listen(
        "u6l4-3",
        "La farmacia está a una cuadra.",
        [
          "The pharmacy is one block away.",
          "The pharmacy is far by metro.",
          "Turn left at the hotel.",
          "I like the pharmacy.",
        ],
        0,
        "La farmacia está a una cuadra.",
        ["farmacia", "cuadra"]
      ),
      {
        id: "u6l4-4",
        type: "situational-choose",
        prompt: "Pick the best answer.",
        situation: "A friend asks if the metro station is close — it is far.",
        options: [
          "Está lejos.",
          "Me gusta la estación.",
          "Quiero la estación.",
          "Comí la estación.",
        ],
        correctIndex: 0,
        explanation: "Está lejos.",
        wordCardIds: ["lejos", "estacion"],
        xp: 3,
      },
      {
        id: "u6l4-5",
        type: "translate",
        prompt: "Translate: “The station is far.”",
        acceptedAnswers: [
          "La estación está lejos.",
          "La estacion esta lejos.",
          "La estación esta lejos.",
          "La estacion está lejos.",
        ],
        hint: "está lejos",
        explanation: "La estación está lejos.",
        wordCardIds: ["estacion", "lejos"],
        xp: 4,
      },
      {
        id: "u6l4-6",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "The bank is on the right.",
        template: "El banco está a la ___.",
        acceptedAnswers: ["derecha", "Derecha"],
        hint: "right",
        explanation: "El banco está a la derecha.",
        wordCardIds: ["banco", "a-la-derecha"],
        xp: 3,
      },
      {
        id: "u6l4-7",
        type: "match-pairs",
        prompt: "Match places.",
        pairs: [
          { left: "la farmacia", right: "the pharmacy" },
          { left: "la estación", right: "the station" },
          { left: "el banco", right: "the bank" },
          { left: "el hotel", right: "the hotel" },
        ],
        explanation: "Useful city places.",
        wordCardIds: ["farmacia", "estacion", "banco", "hotel"],
        xp: 4,
      },
      listen(
        "u6l4-8",
        "Mi hotel está cerca del centro.",
        [
          "My hotel is near downtown.",
          "My hotel is far from downtown.",
          "Turn right at the hotel.",
          "I take the metro to the hotel only.",
        ],
        0,
        "Mi hotel está cerca del centro.",
        ["hotel", "cerca", "el-centro"]
      ),
    ],
  },

  "u6-l5": {
    id: "u6-l5",
    unitId: "unit-6",
    title: "Asking where it is",
    description: "Polite ¿dónde está…? with Disculpe — tú and situational usted.",
    xpReward: 44,
    exercises: [
      teach("teach-u6l5-donde", "donde-esta"),
      teach("teach-u6l5-disculpe", "disculpe"),
      {
        id: "u6l5-1",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "You ask a stranger on the street where the bathroom is (polite).",
        options: [
          "Oye baño ya.",
          "Disculpe, ¿dónde está el baño?",
          "Me despierto el baño.",
          "Quiero comí baño.",
        ],
        correctIndex: 1,
        explanation: "Disculpe, ¿dónde está el baño? — usted-friendly with strangers.",
        wordCardIds: ["disculpe", "donde-esta", "bano"],
        xp: 4,
      },
      {
        id: "u6l5-2",
        type: "select",
        prompt: "With a close friend (tú), a natural ask is…",
        options: [
          "¿Dónde está la farmacia?",
          "Soy la farmacia.",
          "Me gusta lejos farmacia.",
          "La cuenta farmacia.",
        ],
        correctIndex: 0,
        explanation: "¿Dónde está…? works with friends too — tone + Disculpe mark formality.",
        wordCardIds: ["donde-esta", "farmacia"],
        xp: 3,
      },
      {
        id: "u6l5-3",
        type: "tap-chips",
        prompt: "Build: “Excuse me, where is the station?”",
        chips: ["Disculpe,", "¿dónde", "está", "la", "estación?", "carro", "jugo"],
        correctOrder: ["Disculpe,", "¿dónde", "está", "la", "estación?"],
        explanation: "Disculpe, ¿dónde está la estación?",
        wordCardIds: ["disculpe", "donde-esta", "estacion"],
        xp: 3,
      },
      listen(
        "u6l5-4",
        "Disculpe, ¿dónde está el baño?",
        [
          "Excuse me, where is the bathroom?",
          "Excuse me, I want juice.",
          "Turn left at the bathroom.",
          "The bathroom is far.",
        ],
        0,
        "Disculpe, ¿dónde está el baño?",
        ["disculpe", "donde-esta", "bano"]
      ),
      {
        id: "u6l5-5",
        type: "translate",
        prompt: "Translate: “Excuse me, where is the bank?”",
        acceptedAnswers: [
          "Disculpe, ¿dónde está el banco?",
          "Disculpe, ¿donde esta el banco?",
          "Disculpe ¿dónde está el banco?",
        ],
        hint: "Disculpe, ¿dónde está…?",
        explanation: "Disculpe, ¿dónde está el banco?",
        wordCardIds: ["disculpe", "donde-esta", "banco"],
        xp: 4,
      },
      {
        id: "u6l5-6",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "Excuse me, where is the hotel?",
        template: "Disculpe, ¿dónde ___ el hotel?",
        acceptedAnswers: ["está", "esta", "Está"],
        hint: "is (location)",
        explanation: "Disculpe, ¿dónde está el hotel?",
        wordCardIds: ["disculpe", "donde-esta", "hotel"],
        xp: 3,
      },
      {
        id: "u6l5-7",
        type: "situational-choose",
        prompt: "Pick the best answer.",
        situation: "A tourist asks you where the pharmacy is; it's on the left.",
        options: [
          "Está a la izquierda.",
          "Me gusta la izquierda.",
          "Quiero izquierda.",
          "Comí izquierda.",
        ],
        correctIndex: 0,
        explanation: "Está a la izquierda.",
        wordCardIds: ["a-la-izquierda", "farmacia"],
        xp: 3,
      },
      listen(
        "u6l5-8",
        "Disculpe, ¿dónde está la farmacia?",
        [
          "Excuse me, where is the pharmacy?",
          "How do I get downtown?",
          "I take the metro every day.",
          "Turn right two blocks.",
        ],
        0,
        "Disculpe, ¿dónde está la farmacia?",
        ["disculpe", "farmacia"]
      ),
      dlg("dlg-u6-metro"),
      dlg("dlg-u6-repeat"),
    ],
  },

  "u6-l6": {
    id: "u6-l6",
    unitId: "unit-6",
    title: "Getting there — transport",
    description: "Metro, carro, a pie, autobús — how you get around.",
    xpReward: 44,
    exercises: [
      teach("teach-u6l6-como", "como-llego"),
      teach("teach-u6l6-metro", "metro"),
      teach("teach-u6l6-carro", "carro"),
      teach("teach-u6l6-apie", "a-pie"),
      teach("teach-u6l6-bus", "autobus"),
      {
        id: "u6l6-1",
        type: "select",
        prompt: "“I go downtown on foot” is…",
        options: [
          "Voy al centro a pie.",
          "Voy al centro en pie metro.",
          "Soy a pie el centro.",
          "Me gusta a pie cuenta.",
        ],
        correctIndex: 0,
        explanation: "Voy al centro a pie.",
        wordCardIds: ["a-pie", "el-centro"],
        xp: 3,
      },
      {
        id: "u6l6-2",
        type: "tap-chips",
        prompt: "Build: “I take the bus downtown.”",
        chips: ["Tomo", "el", "autobús", "al", "centro.", "baño", "lejos"],
        correctOrder: ["Tomo", "el", "autobús", "al", "centro."],
        explanation: "Tomo el autobús al centro.",
        wordCardIds: ["autobus", "el-centro"],
        xp: 3,
      },
      {
        id: "u6l6-3",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "Someone asks how you get to work — you drive.",
        options: [
          "Voy en carro.",
          "Voy a la cuenta.",
          "Me ducho en carro.",
          "Quiero lejos carro.",
        ],
        correctIndex: 0,
        explanation: "Voy en carro. (Unit 4 reuse)",
        wordCardIds: ["carro"],
        xp: 3,
      },
      listen(
        "u6l6-4",
        "Voy al centro a pie.",
        [
          "I'm going downtown on foot.",
          "I'm going downtown by metro.",
          "The downtown is far.",
          "Turn left downtown.",
        ],
        0,
        "Voy al centro a pie.",
        ["a-pie", "el-centro"]
      ),
      {
        id: "u6l6-5",
        type: "translate",
        prompt: "Translate: “How do I get to the station?”",
        acceptedAnswers: [
          "¿Cómo llego a la estación?",
          "¿Como llego a la estacion?",
          "¿Cómo llego a la estacion?",
          "Disculpe, ¿cómo llego a la estación?",
        ],
        hint: "¿Cómo llego a…?",
        explanation: "¿Cómo llego a la estación?",
        wordCardIds: ["como-llego", "estacion"],
        xp: 4,
      },
      {
        id: "u6l6-6",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I go to work by car.",
        template: "Voy al trabajo en ___.",
        acceptedAnswers: ["carro", "Carro"],
        hint: "car",
        explanation: "Voy al trabajo en carro.",
        wordCardIds: ["carro"],
        xp: 3,
      },
      {
        id: "u6l6-7",
        type: "match-pairs",
        prompt: "Match transport.",
        pairs: [
          { left: "en metro", right: "by subway" },
          { left: "en carro", right: "by car" },
          { left: "a pie", right: "on foot" },
          { left: "en autobús", right: "by bus" },
        ],
        explanation: "Ways to get around.",
        wordCardIds: ["metro", "carro", "a-pie", "autobus"],
        xp: 4,
      },
      listen(
        "u6l6-8",
        "Tomo el metro todos los días.",
        [
          "I take the metro every day.",
          "I take the bus every day.",
          "I walk every day only.",
          "The metro is far every day.",
        ],
        0,
        "Tomo el metro todos los días.",
        ["metro"]
      ),
      teach("teach-u6l6-parada", "parada"),
      {
        id: "u6l6-9",
        type: "select",
        prompt: "“Where is the bus stop?”",
        options: [
          "¿Dónde está la parada?",
          "¿Me gusta la parada?",
          "¿Comí la parada?",
          "¿Soy la parada lejos?",
        ],
        correctIndex: 0,
        explanation: "¿Dónde está la parada?",
        wordCardIds: ["parada", "donde-esta"],
        xp: 3,
      },
    ],
  },

  "u6-l7": {
    id: "u6-l7",
    unitId: "unit-6",
    title: "Map situations",
    description: "Short map / street scenes — ask, point, and follow directions.",
    xpReward: 44,
    exercises: [
      teach("teach-u6l7-mapa", "mapa"),
      {
        id: "u6l7-1",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "You politely ask a stranger if they have a map.",
        options: [
          "Disculpe, ¿tiene un mapa?",
          "Oye mapa ya.",
          "Me despierto el mapa.",
          "Quiero comí mapa.",
        ],
        correctIndex: 0,
        explanation: "Disculpe, ¿tiene un mapa? — usted with strangers.",
        wordCardIds: ["disculpe", "mapa"],
        xp: 4,
      },
      {
        id: "u6l7-2",
        type: "select",
        prompt: "According to directions: hotel is near downtown. Best line?",
        options: [
          "El hotel está cerca del centro.",
          "El hotel está jugo.",
          "Me gusta el hotel lejos siempre.",
          "La cuenta del hotel recto.",
        ],
        correctIndex: 0,
        explanation: "El hotel está cerca del centro.",
        wordCardIds: ["hotel", "cerca", "el-centro"],
        xp: 3,
      },
      {
        id: "u6l7-3",
        type: "tap-chips",
        prompt: "Build: “Straight ahead and then to the right.”",
        chips: ["Todo", "recto", "y", "luego", "a", "la", "derecha.", "baño"],
        correctOrder: ["Todo", "recto", "y", "luego", "a", "la", "derecha."],
        explanation: "Todo recto y luego a la derecha.",
        wordCardIds: ["todo-recto", "a-la-derecha"],
        xp: 3,
      },
      listen(
        "u6l7-4",
        "Según el mapa, el hotel está cerca.",
        [
          "According to the map, the hotel is nearby.",
          "According to the map, turn left only.",
          "I want a map of juice.",
          "The metro map is far forever.",
        ],
        0,
        "Según el mapa, el hotel está cerca.",
        ["mapa", "hotel", "cerca"]
      ),
      {
        id: "u6l7-5",
        type: "situational-choose",
        prompt: "Pick the best directions.",
        situation: "Map says: go straight two blocks, then turn left.",
        options: [
          "Todo recto dos cuadras y luego a la izquierda.",
          "Me gusta dos cuadras el jugo.",
          "Comí dos cuadras ayer.",
          "La cuenta dos cuadras.",
        ],
        correctIndex: 0,
        explanation: "Todo recto dos cuadras y luego a la izquierda.",
        wordCardIds: ["todo-recto", "cuadra", "a-la-izquierda"],
        xp: 4,
      },
      {
        id: "u6l7-6",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "How do I get to the hotel?",
        template: "¿Cómo ___ al hotel?",
        acceptedAnswers: ["llego", "Llego"],
        hint: "I get / I arrive",
        explanation: "¿Cómo llego al hotel?",
        wordCardIds: ["como-llego", "hotel"],
        xp: 3,
      },
      {
        id: "u6l7-7",
        type: "translate",
        prompt: "Translate: “The stop is nearby.”",
        acceptedAnswers: [
          "La parada está cerca.",
          "La parada esta cerca.",
          "La parada está cerca",
        ],
        hint: "está cerca",
        explanation: "La parada está cerca.",
        wordCardIds: ["parada", "cerca"],
        xp: 4,
      },
      listen(
        "u6l7-8",
        "Gira a la izquierda en la esquina.",
        [
          "Turn left at the corner.",
          "Turn right at the corner.",
          "Go straight at the corner.",
          "The corner is far.",
        ],
        0,
        "Gira a la izquierda en la esquina.",
        ["gira", "a-la-izquierda"]
      ),
      {
        id: "u6l7-9",
        type: "match-pairs",
        prompt: "Match map talk.",
        pairs: [
          { left: "el mapa", right: "the map" },
          { left: "la parada", right: "the stop" },
          { left: "gira", right: "turn" },
          { left: "cerca del centro", right: "near downtown" },
        ],
        explanation: "Map & street phrases.",
        wordCardIds: ["mapa", "parada", "gira", "el-centro"],
        xp: 4,
      },
      dlg("dlg-u6-howto"),
      dlg("dlg-u6-lost"),
    ],
  },

  "u6-l8": {
    id: "u6-l8",
    unitId: "unit-6",
    title: "Directions review",
    description: "Reuse Unit 6 + weak words from daily life and food.",
    xpReward: 42,
    exercises: [
      {
        id: "u6l8-1",
        type: "select",
        prompt: "“Where is the bathroom?”",
        options: [
          "¿Dónde está el baño?",
          "¿Me gusta el baño?",
          "¿Comí el baño?",
          "¿Soy el baño lejos?",
        ],
        correctIndex: 0,
        explanation: "¿Dónde está el baño?",
        wordCardIds: ["donde-esta", "bano"],
        xp: 3,
      },
      {
        id: "u6l8-2",
        type: "tap-chips",
        prompt: "Build: “I go by metro.”",
        chips: ["Voy", "en", "metro.", "jugo", "platos"],
        correctOrder: ["Voy", "en", "metro."],
        explanation: "Voy en metro.",
        wordCardIds: ["metro"],
        xp: 3,
      },
      listen(
        "u6l8-3",
        "Está cerca del centro.",
        [
          "It's near downtown.",
          "It's far from downtown.",
          "I want downtown juice.",
          "Turn left forever.",
        ],
        0,
        "Está cerca del centro.",
        ["cerca", "el-centro"]
      ),
      {
        id: "u6l8-4",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "Friend asks how you get to the office (Unit 4 reuse).",
        options: [
          "Camino a la oficina.",
          "Me ducho la oficina.",
          "La cuenta oficina.",
          "Quiero lejos oficina siempre.",
        ],
        correctIndex: 0,
        explanation: "Camino a la oficina.",
        wordCardIds: ["caminar", "oficina"],
        xp: 3,
      },
      {
        id: "u6l8-5",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "Keep going straight.",
        template: "Sigue todo ___.",
        acceptedAnswers: ["recto", "Recto"],
        hint: "straight",
        explanation: "Sigue todo recto.",
        wordCardIds: ["todo-recto"],
        xp: 3,
      },
      {
        id: "u6l8-6",
        type: "translate",
        prompt: "Translate: “Turn left.”",
        acceptedAnswers: [
          "Gira a la izquierda.",
          "Gira a la izquierda",
          "Dobla a la izquierda.",
          "Dobla a la izquierda",
        ],
        hint: "Gira a la…",
        explanation: "Gira a la izquierda.",
        wordCardIds: ["gira", "a-la-izquierda"],
        xp: 4,
      },
      {
        id: "u6l8-7",
        type: "match-pairs",
        prompt: "Quick Unit 6 match.",
        pairs: [
          { left: "cerca", right: "near" },
          { left: "lejos", right: "far" },
          { left: "a pie", right: "on foot" },
          { left: "el metro", right: "the subway" },
        ],
        explanation: "Core getting-around lemmas.",
        wordCardIds: ["cerca", "lejos", "a-pie", "metro"],
        xp: 4,
      },
      {
        id: "u6l8-8",
        type: "select",
        prompt: "Unit 5 reuse: word for juice?",
        options: ["oficina", "jugo", "derecha", "cuadra"],
        correctIndex: 1,
        explanation: "jugo.",
        wordCardIds: ["jugo"],
        xp: 3,
      },
      listen(
        "u6l8-9",
        "Disculpe, ¿cómo llego al centro?",
        [
          "Excuse me, how do I get downtown?",
          "Excuse me, where is juice?",
          "I like downtown metro.",
          "Turn right at the check.",
        ],
        0,
        "Disculpe, ¿cómo llego al centro?",
        ["disculpe", "como-llego", "el-centro"]
      ),
    ],
  },

  "u6-l9": {
    id: "u6-l9",
    unitId: "unit-6",
    title: "Story: Finding the station",
    description: "Listen to a directions story, then cloze drills.",
    xpReward: 45,
    exercises: [
      storyListen(
        "u6l9-story",
        "Buscamos la estación",
        [
          { text: "Disculpe, ¿dónde está la estación de metro?", en: "Excuse me, where is the metro station?" },
          { text: "Está cerca. Sigue todo recto dos cuadras.", en: "It's nearby. Go straight two blocks." },
          { text: "Luego gira a la derecha.", en: "Then turn right." },
          { text: "La estación no está lejos a pie.", en: "The station isn't far on foot." },
          { text: "¡Gracias! Voy a tomar el metro al centro.", en: "Thanks! I'm going to take the metro downtown." },
        ],
        [
          {
            prompt: "What are they looking for?",
            options: ["Only a juice bar", "The metro station", "The check", "A kitchen"],
            correctIndex: 1,
            explanation: "la estación de metro.",
          },
          {
            prompt: "How far is the first instruction?",
            options: ["Two blocks straight", "Ten metros by car only", "Far forever", "No directions given"],
            correctIndex: 0,
            explanation: "Sigue todo recto dos cuadras.",
          },
          {
            prompt: "Which way after going straight?",
            options: ["Turn left", "Turn right", "Go home", "Order tacos"],
            correctIndex: 1,
            explanation: "Luego gira a la derecha.",
          },
          {
            prompt: "How will they finish the trip downtown?",
            options: ["Only sleep", "Take the metro", "Wash clothes", "Ask for the tip"],
            correctIndex: 1,
            explanation: "Voy a tomar el metro al centro.",
          },
        ],
        ["disculpe", "estacion", "metro", "cerca", "todo-recto", "cuadra", "gira", "a-la-derecha", "a-pie", "el-centro"],
        "Directions story — voices rotate across Neural2 A/B/C.",
        12
      ),
      dictation(
        "u6l9-story-dict-1",
        "Disculpe, ¿dónde está la estación de metro?",
        ["Disculpe, ¿dónde está la estación de metro?", "Disculpe, dónde está la estación de metro"],
        "Type the line you heard: Disculpe, ¿dónde está la estación de metro?",
        [],
        { hint: "Replay if needed", voice: "f", xp: 4 }
      ),
      dictation(
        "u6l9-story-dict-2",
        "Está cerca. Sigue todo recto dos cuadras.",
        ["Está cerca. Sigue todo recto dos cuadras."],
        "Type the line you heard: Está cerca. Sigue todo recto dos cuadras.",
        [],
        { hint: "Replay if needed", voice: "m", xp: 4 }
      ),
      {
        id: "u6l9-1",
        type: "select",
        prompt: "From the story — polite station ask was…",
        options: [
          "Oye estación ya.",
          "Disculpe, ¿dónde está la estación de metro?",
          "Me despierto la estación.",
          "Lavo la estación.",
        ],
        correctIndex: 1,
        explanation: "Disculpe, ¿dónde está la estación de metro?",
        wordCardIds: ["disculpe", "estacion", "metro"],
        xp: 3,
      },
      cloze(
        "u6l9-cloze-1",
        "Disculpe, ¿dónde está la ___ de metro?",
        ["estación", "estacion", "Estación"],
        "Disculpe, ¿dónde está la estación de metro?",
        ["estacion", "metro", "disculpe"],
        {
          hint: "station",
          audioText: "Disculpe, ¿dónde está la estación de metro?",
          voice: "f",
        }
      ),
      cloze(
        "u6l9-cloze-2",
        "Sigue todo recto dos ___.",
        ["cuadras", "Cuadras"],
        "Sigue todo recto dos cuadras.",
        ["todo-recto", "cuadra"],
        {
          hint: "blocks",
          audioText: "Sigue todo recto dos cuadras.",
          voice: "m",
        }
      ),
      cloze(
        "u6l9-cloze-3",
        "Luego gira a la ___.",
        ["derecha", "Derecha"],
        "Luego gira a la derecha.",
        ["gira", "a-la-derecha"],
        {
          hint: "right",
          audioText: "Luego gira a la derecha.",
          voice: "c",
        }
      ),
    ],
  },

  "u6-l10": {
    id: "u6-l10",
    unitId: "unit-6",
    title: "More getting-around practice",
    description: "New mixes — transport, places, polite asks, weak reuse.",
    xpReward: 42,
    exercises: [
      {
        id: "u6l10-1",
        type: "translate",
        prompt: "Translate: “I go downtown by metro.”",
        acceptedAnswers: [
          "Voy al centro en metro.",
          "Voy al centro en metro",
          "Yo voy al centro en metro.",
        ],
        hint: "en metro",
        explanation: "Voy al centro en metro.",
        wordCardIds: ["el-centro", "metro"],
        xp: 4,
      },
      {
        id: "u6l10-2",
        type: "tap-chips",
        prompt: "Build: “The pharmacy is nearby.”",
        chips: ["La", "farmacia", "está", "cerca.", "lejos", "cuenta"],
        correctOrder: ["La", "farmacia", "está", "cerca."],
        explanation: "La farmacia está cerca.",
        wordCardIds: ["farmacia", "cerca"],
        xp: 3,
      },
      listen(
        "u6l10-3",
        "¿Me puede ayudar? ¿Cómo llego al hotel?",
        [
          "Can you help me? How do I get to the hotel?",
          "Do you wash the hotel?",
          "Where is the tip?",
          "I study the hotel.",
        ],
        0,
        "¿Me puede ayudar? ¿Cómo llego al hotel? — usted.",
        ["como-llego", "hotel", "usted-server"]
      ),
      {
        id: "u6l10-4",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I go on foot.",
        template: "Voy a ___.",
        acceptedAnswers: ["pie", "Pie"],
        hint: "foot (a ___)",
        explanation: "Voy a pie.",
        wordCardIds: ["a-pie"],
        xp: 3,
      },
      {
        id: "u6l10-5",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "Bus stop is close; point it out.",
        options: [
          "La parada está cerca.",
          "Me gusta la parada jugo.",
          "Comí la parada.",
          "Soy la parada lejos.",
        ],
        correctIndex: 0,
        explanation: "La parada está cerca.",
        wordCardIds: ["parada", "cerca"],
        xp: 3,
      },
      {
        id: "u6l10-6",
        type: "select",
        prompt: "“Turn left at the corner” vibe — best option?",
        options: [
          "Gira a la izquierda en la esquina.",
          "Gira a la cuenta en la esquina.",
          "Me ducho en la esquina.",
          "Quiero lejos esquina.",
        ],
        correctIndex: 0,
        explanation: "Gira a la izquierda en la esquina.",
        wordCardIds: ["gira", "a-la-izquierda"],
        xp: 3,
      },
      {
        id: "u6l10-7",
        type: "match-pairs",
        prompt: "Practice match.",
        pairs: [
          { left: "el autobús", right: "the bus" },
          { left: "a pie", right: "on foot" },
          { left: "la farmacia", right: "the pharmacy" },
          { left: "el banco", right: "the bank" },
        ],
        explanation: "Places & transport.",
        wordCardIds: ["autobus", "a-pie", "farmacia", "banco"],
        xp: 4,
      },
      listen(
        "u6l10-8",
        "No queda muy lejos caminando.",
        [
          "It's not very far walking.",
          "It's very far by metro only.",
          "I want far juice.",
          "Turn right forever.",
        ],
        0,
        "No queda muy lejos caminando.",
        ["lejos", "caminar"]
      ),
      {
        id: "u6l10-m1",
        type: "match-pairs",
        prompt: "Match each place to its Spanish word.",
        pairMode: "emoji-es",
        pairs: [
          { left: "🚇", right: "el metro" },
          { left: "💊", right: "la farmacia" },
          { left: "🏨", right: "el hotel" },
          { left: "🚉", right: "la estación" },
          { left: "🚻", right: "el baño" },
        ],
        explanation: "Places you will need to find.",
        wordCardIds: ["metro", "farmacia", "hotel", "estacion", "bano"],
        xp: 3,
      },
      {
        id: "u6l10-m2",
        type: "match-pairs",
        prompt: "Match the Spanish to its English.",
        pairs: [
          { left: "la parada", right: "the stop" },
          { left: "el centro", right: "downtown" },
          { left: "el carro", right: "the car" },
          { left: "la estación", right: "the station" },
        ],
        explanation: "Getting-around vocabulary.",
        wordCardIds: ["parada", "el-centro", "carro", "estacion"],
        xp: 3,
      },
    ],
  },

  "u6-l11": {
    id: "u6-l11",
    unitId: "unit-6",
    title: "Story: Walk to the hotel",
    description: "Second story-listen + cloze — hotel, map, walking.",
    xpReward: 45,
    exercises: [
      storyListen(
        "u6l11-story",
        "Al hotel a pie",
        [
          { text: "Disculpe, ¿tiene un mapa?", en: "Excuse me, do you have a map?" },
          { text: "Sí. Su hotel está cerca del centro.", en: "Yes. Your hotel is near downtown." },
          { text: "Puede ir a pie. No está lejos.", en: "You can go on foot. It isn't far." },
          { text: "Todo recto una cuadra y luego a la izquierda.", en: "Straight one block and then left." },
          { text: "El banco está a la derecha. El hotel queda después.", en: "The bank is on the right. The hotel is after that." },
          { text: "¡Perfecto! Gracias.", en: "Perfect! Thank you." },
        ],
        [
          {
            prompt: "What does the traveler ask for first?",
            options: ["A map", "Only tacos", "The check", "A shower"],
            correctIndex: 0,
            explanation: "¿tiene un mapa?",
          },
          {
            prompt: "Where is the hotel?",
            options: ["Far from everything", "Near downtown", "Only on the metro track", "In the kitchen"],
            correctIndex: 1,
            explanation: "cerca del centro.",
          },
          {
            prompt: "How can they go?",
            options: ["Only by plane", "On foot — it's not far", "Only by washing clothes", "Never"],
            correctIndex: 1,
            explanation: "Puede ir a pie. No está lejos.",
          },
          {
            prompt: "After one block straight, which way?",
            options: ["Left", "Right only forever", "Ask for juice", "Sleep"],
            correctIndex: 0,
            explanation: "luego a la izquierda.",
          },
        ],
        ["disculpe", "mapa", "hotel", "cerca", "el-centro", "a-pie", "lejos", "todo-recto", "cuadra", "a-la-izquierda", "banco", "a-la-derecha"],
        "Hotel walk story — Neural2 A/B/C rotation.",
        12
      ),
      dictation(
        "u6l11-story-dict-1",
        "Disculpe, ¿tiene un mapa?",
        ["Disculpe, ¿tiene un mapa?", "Disculpe, tiene un mapa"],
        "Type the line you heard: Disculpe, ¿tiene un mapa?",
        [],
        { hint: "Replay if needed", voice: "f", xp: 4 }
      ),
      dictation(
        "u6l11-story-dict-2",
        "Sí. Su hotel está cerca del centro.",
        ["Sí. Su hotel está cerca del centro."],
        "Type the line you heard: Sí. Su hotel está cerca del centro.",
        [],
        { hint: "Replay if needed", voice: "m", xp: 4 }
      ),
      cloze(
        "u6l11-cloze-1",
        "Disculpe, ¿tiene un ___?",
        ["mapa", "Mapa"],
        "Disculpe, ¿tiene un mapa?",
        ["mapa", "disculpe"],
        {
          hint: "map",
          audioText: "Disculpe, ¿tiene un mapa?",
          voice: "f",
        }
      ),
      cloze(
        "u6l11-cloze-2",
        "Puede ir a ___. No está lejos.",
        ["pie", "Pie"],
        "Puede ir a pie. No está lejos.",
        ["a-pie", "lejos"],
        {
          hint: "on foot",
          audioText: "Puede ir a pie. No está lejos.",
          voice: "m",
        }
      ),
      cloze(
        "u6l11-cloze-3",
        "Todo recto una cuadra y luego a la ___.",
        ["izquierda", "Izquierda"],
        "Todo recto una cuadra y luego a la izquierda.",
        ["todo-recto", "cuadra", "a-la-izquierda"],
        {
          hint: "left",
          audioText: "Todo recto una cuadra y luego a la izquierda.",
          voice: "c",
        }
      ),
      {
        id: "u6l11-1",
        type: "situational-choose",
        prompt: "Pick the best line from the story vibe.",
        situation: "Point out the bank on the right before the hotel.",
        options: [
          "El banco está a la derecha.",
          "El banco está jugo.",
          "Me ducho el banco.",
          "Quiero banco ayer.",
        ],
        correctIndex: 0,
        explanation: "El banco está a la derecha.",
        wordCardIds: ["banco", "a-la-derecha"],
        xp: 3,
      },
    ],
  },

  "u6-l12": {
    id: "u6-l12",
    unitId: "unit-6",
    title: "Unit 6 check",
    description: "Mixed review — directions, places, transport, past units.",
    xpReward: 48,
    exercises: [
      {
        id: "u6l12-1",
        type: "select",
        prompt: "Opposite of cerca?",
        options: ["oficina", "lejos", "jugo", "platos"],
        correctIndex: 1,
        explanation: "lejos.",
        wordCardIds: ["cerca", "lejos"],
        xp: 3,
      },
      {
        id: "u6l12-2",
        type: "select",
        prompt: "“How do I get downtown?” is…",
        options: [
          "¿Me gusta el centro?",
          "¿Soy el centro?",
          "¿Cómo llego al centro?",
          "¿La cuenta centro?",
        ],
        correctIndex: 2,
        explanation: "¿Cómo llego al centro?",
        wordCardIds: ["como-llego", "el-centro"],
        xp: 3,
      },
      {
        id: "u6l12-3",
        type: "tap-chips",
        prompt: "Build: “Turn right.”",
        chips: ["Gira", "a", "la", "derecha.", "ducho", "metro"],
        correctOrder: ["Gira", "a", "la", "derecha."],
        explanation: "Gira a la derecha.",
        wordCardIds: ["gira", "a-la-derecha"],
        xp: 3,
      },
      {
        id: "u6l12-4",
        type: "translate",
        prompt: "Translate: “I go on foot.”",
        acceptedAnswers: ["Voy a pie.", "Voy a pie", "Yo voy a pie."],
        hint: "a pie",
        explanation: "Voy a pie.",
        wordCardIds: ["a-pie"],
        xp: 4,
      },
      listen(
        "u6l12-5",
        "La farmacia está a la izquierda.",
        [
          "I clean the kitchen only.",
          "Wake up at seven.",
          "The pharmacy is on the left.",
          "Turn left downtown forever only.",
        ],
        2,
        "La farmacia está a la izquierda.",
        ["farmacia", "a-la-izquierda"]
      ),
      {
        id: "u6l12-6",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "Where is the bathroom?",
        template: "¿Dónde ___ el baño?",
        acceptedAnswers: ["está", "esta", "Está"],
        hint: "is (location)",
        explanation: "¿Dónde está el baño?",
        wordCardIds: ["donde-esta", "bano"],
        xp: 3,
      },
      {
        id: "u6l12-7",
        type: "match-pairs",
        prompt: "Final Unit 6 match.",
        pairs: [
          { left: "todo recto", right: "straight ahead" },
          { left: "en carro", right: "by car" },
          { left: "la estación", right: "the station" },
          { left: "el mapa", right: "the map" },
        ],
        explanation: "Core Unit 6 lemmas.",
        wordCardIds: ["todo-recto", "carro", "estacion", "mapa"],
        xp: 4,
      },
      {
        id: "u6l12-8",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "Polite ask for the bus stop.",
        options: [
          "¿Me ducho la parada?",
          "¿Camino algo la oficina?",
          "Disculpe, ¿dónde está la parada?",
          "¿Soy algo temprano?",
        ],
        correctIndex: 2,
        explanation: "Disculpe, ¿dónde está la parada?",
        wordCardIds: ["disculpe", "parada"],
        xp: 3,
      },
      {
        id: "u6l12-9",
        type: "select",
        prompt: "Unit 4 reuse: “I go to work by car” is…",
        options: [
          "Me gusta temprano la cuenta.",
          "Quiero temprano menú.",
          "Voy al trabajo en carro.",
          "Soy temprano arroz.",
        ],
        correctIndex: 2,
        explanation: "Voy al trabajo en carro.",
        wordCardIds: ["carro"],
        xp: 3,
      },
      {
        id: "u6l12-10",
        type: "situational-choose",
        prompt: "Pick the best answer.",
        situation: "Someone asks if your hotel is close; it is.",
        options: ["Está cerca.", "Me gusta cerca.", "Quiero cerca.", "Comí cerca."],
        correctIndex: 0,
        explanation: "Está cerca.",
        wordCardIds: ["cerca", "hotel"],
        xp: 3,
      },
    ],
  },
};

export const UNIT6_LESSON_IDS = [
  "u6-l1",
  "u6-l2",
  "u6-l3",
  "u6-l4",
  "u6-l5",
  "u6-l6",
  "u6-l7",
  "u6-l8",
  "u6-l9",
  "u6-l10",
  "u6-l11",
  "u6-l12",
] as const;
