/**
 * Unit 2 — Who I am (lessons 4–12). Spanish.
 * Existing u2-l1…u2-l3 stay in mock-data.ts (audio voice indices stable).
 */
import type { Lesson, WordCard } from "../types";
import { audioSrcFor, voiceForIndex, type AudioVoice } from "../audio";

function teach(
  id: string,
  wordCardId: string
): import("../types").TeachExercise {
  return {
    id,
    type: "teach",
    prompt: "New word — learn it, then practice.",
    explanation: "",
    wordCardId,
    wordCardIds: [wordCardId],
    xp: 0,
  };
}

let listenVoiceIndex = 3100;

function listen(
  id: string,
  audioText: string,
  options: string[],
  correctIndex: number,
  explanation: string,
  wordCardIds: string[],
  xp = 3
): import("../types").ListeningChooseExercise {
  const voice = voiceForIndex(listenVoiceIndex);
  listenVoiceIndex += 1;
  return {
    id,
    type: "listening-choose",
    prompt: "What did you hear?",
    audioText,
    audioSrc: audioSrcFor(audioText, voice),
    options,
    correctIndex,
    explanation,
    wordCardIds,
    xp,
  };
}

function cloze(
  id: string,
  template: string,
  acceptedAnswers: string[],
  explanation: string,
  wordCardIds: string[],
  opts: {
    hint?: string;
    audioText: string;
    voice?: AudioVoice;
    storyLabel?: string;
    xp?: number;
  }
): import("../types").ClozeExercise {
  const voice = opts.voice ?? "f";
  return {
    id,
    type: "cloze",
    prompt: "Fill the blank from the story",
    template,
    acceptedAnswers,
    hint: opts.hint,
    explanation,
    wordCardIds,
    audioText: opts.audioText,
    audioSrc: audioSrcFor(opts.audioText, voice),
    storyLabel: opts.storyLabel ?? "From the story",
    xp: opts.xp ?? 3,
  };
}

function storyListen(
  id: string,
  title: string,
  lines: { text: string; en?: string; voice?: AudioVoice }[],
  questions: {
    prompt: string;
    options: string[];
    correctIndex: number;
    explanation?: string;
  }[],
  wordCardIds: string[],
  explanation = "Story comprehension — replay anytime.",
  xp = 10
): import("../types").StoryListenExercise {
  const withVoices = lines.map((line, i) => ({
    text: line.text,
    en: line.en,
    voice: line.voice ?? voiceForIndex(i),
  }));
  return {
    id,
    type: "story-listen",
    prompt: "Listen to the story, then answer",
    title,
    lines: withVoices,
    questions,
    explanation,
    wordCardIds,
    xp,
  };
}




function conjugate(
  id: string,
  infinitive: string,
  pronoun: string,
  tense: string,
  acceptedAnswers: string[],
  explanation: string,
  wordCardIds: string[],
  opts: { hint?: string; xp?: number } = {}
): import("../types").ConjugateExercise {
  return {
    id,
    type: "conjugate",
    prompt: `Conjugate: ${pronoun} + ${infinitive} (${tense})`,
    infinitive,
    pronoun,
    tense,
    acceptedAnswers,
    hint: opts.hint,
    explanation,
    wordCardIds,
    xp: opts.xp ?? 3,
  };
}

export const UNIT2_WORD_CARDS: Record<string, WordCard> = {
  ciudad: {
    id: "ciudad",
    lemma: "ciudad",
    pos: "noun",
    gender: "f",
    gloss: "city",
    meaningSummary:
      "City. Pair with vivo en: Vivo en la ciudad / Vivo en la Ciudad de México. Feminine: la ciudad.",
    examples: [
      { es: "Vivo en la ciudad.", en: "I live in the city." },
      { es: "Es una ciudad grande.", en: "It's a big city." },
    ],
    useWhen: "Talking about the city you live in or visit.",
    dontUseWhen: "For country of origin use país / soy de…",
    contrast: "país / pueblo",
    formality: "neutral",
    cefr: "A1",
  },
  pais: {
    id: "pais",
    lemma: "país",
    pos: "noun",
    gender: "m",
    gloss: "country",
    meaningSummary:
      "Country. Mi país es… / ¿De qué país eres? Accent on í: país.",
    examples: [
      { es: "¿De qué país eres?", en: "What country are you from?" },
      { es: "Mi país es México.", en: "My country is Mexico." },
    ],
    useWhen: "Naming or asking about a country.",
    dontUseWhen: "For city residence prefer vivo en + city.",
    contrast: "ciudad",
    formality: "neutral",
    cefr: "A1",
  },
  yo: {
    id: "yo",
    lemma: "yo",
    pos: "pronoun",
    gender: "n/a",
    gloss: "I",
    meaningSummary:
      "Subject pronoun I. Often dropped in Spanish (Soy Ana), but Yo soy… adds clarity or emphasis.",
    examples: [
      { es: "Yo soy Ana.", en: "I am Ana." },
      { es: "Yo hablo inglés.", en: "I speak English." },
    ],
    useWhen: "Emphasis or clarity: Yo soy… / Yo hablo…",
    dontUseWhen: "Don't force it every sentence — Spanish often omits yo.",
    formality: "neutral",
    cefr: "A1",
  },
  "y-tu": {
    id: "y-tu",
    lemma: "¿y tú?",
    pos: "phrase",
    gender: "n/a",
    gloss: "and you?",
    meaningSummary:
      "Bounce a question back: Estoy bien, ¿y tú? Keeps conversation balanced with tú.",
    examples: [
      { es: "Estoy bien, ¿y tú?", en: "I'm fine, and you?" },
      { es: "Hablo español, ¿y tú?", en: "I speak Spanish, and you?" },
    ],
    useWhen: "Returning a question to the other person (tú).",
    dontUseWhen: "With usted formality use ¿y usted?",
    contrast: "¿y usted?",
    formality: "informal",
    cefr: "A1",
  },
};

export const UNIT2_LESSONS: Record<string, Lesson> = {
  "u2-l4": {
    id: "u2-l4",
    unitId: "unit-2",
    title: "Soy vs me llamo",
    description: "Identity lines: soy + name/occupation feel vs me llamo.",
    xpReward: 30,
    exercises: [
      teach("teach-u2l4-yo", "yo"),
      {
        id: "u2l4-1",
        type: "select",
        prompt: "“My name is Ana” — most everyday line:",
        options: ["Me llamo Ana", "Yo nombre Ana", "Soy llamo Ana", "Me soy Ana"],
        correctIndex: 0,
        explanation: "Me llamo Ana. Soy Ana also works as a short ID line.",
        wordCardIds: ["me-llamo"],
        xp: 3,
      },
      {
        id: "u2l4-2",
        type: "select",
        prompt: "Soy Ana is best described as:",
        options: [
          "A short “I am Ana” identity line",
          "How to say thank you",
          "A price question",
          "Only for phone numbers",
        ],
        correctIndex: 0,
        explanation: "Soy + name is fine; me llamo is the classic name formula.",
        wordCardIds: ["ser"],
        xp: 3,
      },
      {
        id: "u2l4-3",
        type: "tap-chips",
        prompt: "Build: “I am Mateo.”",
        chips: ["Yo", "soy", "Mateo", "vivo", "diez", "carro"],
        correctOrder: ["Yo", "soy", "Mateo"],
        explanation: "Yo soy Mateo — yo is optional but clear.",
        wordCardIds: ["yo", "ser"],
        xp: 4,
      },
      listen(
        "u2l4-4",
        "Me llamo Ana",
        ["My name is Ana", "I live in Ana", "How much is Ana?", "See you Ana"],
        0,
        "Me llamo Ana = my name is Ana.",
        ["me-llamo"]
      ),
      {
        id: "u2l4-5",
        type: "fill-blank",
        prompt: "Complete the Spanish.",
        template: "Yo ___ Luis.",
        englishPrompt: "I am Luis.",
        acceptedAnswers: ["soy", "Soy"],
        hint: "I am (ser)",
        explanation: "Yo soy Luis.",
        wordCardIds: ["ser", "yo"],
        xp: 3,
      },
      {
        id: "u2l4-6",
        type: "translate",
        prompt: "Translate to Spanish: “My name is Sofía.”",
        acceptedAnswers: ["me llamo sofía", "me llamo sofia", "Me llamo Sofía", "Me llamo Sofia"],
        hint: "Me llamo + name.",
        explanation: "Me llamo Sofía.",
        wordCardIds: ["me-llamo"],
        xp: 3,
      },
      {
        id: "u2l4-7",
        type: "situational-choose",
        prompt: "Best intro?",
        situation: "New classmate asks who you are.",
        options: [
          "Hola, me llamo Alex.",
          "Hola, cuesta Alex.",
          "Hola, tengo Alex años.",
          "Hola, gratis Alex.",
        ],
        correctIndex: 0,
        explanation: "Hola, me llamo…",
        wordCardIds: ["hola", "me-llamo"],
        xp: 3,
      },
      {
        id: "u2l4-match",
        type: "match-pairs",
        prompt: "Match identity lines.",
        pairs: [
          { left: "Me llamo…", right: "My name is…" },
          { left: "Yo soy…", right: "I am…" },
          { left: "¿Cómo te llamas?", right: "What's your name?" },
          { left: "Mucho gusto", right: "Nice to meet you" },
        ],
        explanation: "Name toolkit.",
        wordCardIds: ["me-llamo", "ser", "como-te-llamas", "mucho-gusto"],
        xp: 4,
      },
    
      conjugate(
        "u2l4-conj-1",
        "ser",
        "yo",
        "Present indicative",
        ["soy", "Soy"],
        "yo + ser → soy.",
        ["ser"],
        { hint: "soy", xp: 3 }
      ),
      conjugate(
        "u2l4-conj-2",
        "ser",
        "tú",
        "Present indicative",
        ["eres", "Eres"],
        "tú + ser → eres.",
        ["ser"],
        { hint: "eres", xp: 3 }
      ),
    ],
  },

  "u2-l5": {
    id: "u2-l5",
    unitId: "unit-2",
    title: "Where are you from?",
    description: "¿De dónde eres? and soy de… with countries.",
    xpReward: 30,
    exercises: [
      {
        id: "u2l5-1",
        type: "select",
        prompt: "How do you ask “Where are you from?” (tú)",
        options: ["¿De dónde eres?", "¿Dónde vivo eres?", "¿Cuánto eres?", "¿Cómo estás de?"],
        correctIndex: 0,
        explanation: "¿De dónde eres?",
        wordCardIds: ["de-donde-eres"],
        xp: 3,
      },
      {
        id: "u2l5-2",
        type: "tap-chips",
        prompt: "Build: “I'm from Mexico.”",
        chips: ["Soy", "de", "México", "vivo", "celular", "mal"],
        correctOrder: ["Soy", "de", "México"],
        explanation: "Soy de México — origin with ser.",
        wordCardIds: ["soy-de", "mexico"],
        xp: 4,
      },
      teach("teach-u2l5-pais", "pais"),
      {
        id: "u2l5-3",
        type: "situational-choose",
        prompt: "Best answer?",
        situation: "Someone asks ¿De dónde eres? You’re from the United States.",
        options: [
          "Soy de Estados Unidos.",
          "Vivo de Estados Unidos.",
          "Tengo Estados Unidos.",
          "Cuesta Estados Unidos.",
        ],
        correctIndex: 0,
        explanation: "Soy de + place for origin.",
        wordCardIds: ["soy-de", "estados-unidos"],
        xp: 3,
      },
      listen(
        "u2l5-4",
        "¿De dónde eres?",
        ["Where are you from?", "How old are you?", "What's your name?", "How much is it?"],
        0,
        "¿De dónde eres? = where are you from?",
        ["de-donde-eres"]
      ),
      {
        id: "u2l5-5",
        type: "fill-blank",
        prompt: "Complete the Spanish.",
        template: "Soy ___ México.",
        englishPrompt: "I'm from Mexico.",
        acceptedAnswers: ["de", "De"],
        hint: "from",
        explanation: "Soy de México.",
        wordCardIds: ["soy-de", "mexico"],
        xp: 3,
      },
      {
        id: "u2l5-6",
        type: "translate",
        prompt: "Translate to Spanish: “Where are you from?”",
        acceptedAnswers: ["de dónde eres", "de donde eres", "¿de dónde eres?", "¿de donde eres?"],
        hint: "de + dónde + eres",
        explanation: "¿De dónde eres?",
        wordCardIds: ["de-donde-eres"],
        xp: 3,
      },
      {
        id: "u2l5-7",
        type: "select",
        prompt: "Estadounidense means:",
        options: ["From the United States", "From Mexico only", "A phone plan", "Free of charge"],
        correctIndex: 0,
        explanation: "Estadounidense = U.S. person / related to the U.S.",
        wordCardIds: ["estadounidense"],
        xp: 3,
      },
      {
        id: "u2l5-match",
        type: "match-pairs",
        prompt: "Match origin phrases.",
        pairs: [
          { left: "¿De dónde eres?", right: "Where are you from?" },
          { left: "Soy de México", right: "I'm from Mexico" },
          { left: "Estados Unidos", right: "United States" },
          { left: "país", right: "country" },
        ],
        explanation: "Origin set.",
        wordCardIds: ["de-donde-eres", "soy-de", "estados-unidos", "pais"],
        xp: 4,
      },
    ],
  },

  "u2-l6": {
    id: "u2-l6",
    unitId: "unit-2",
    title: "Where I live",
    description: "Vivo en… city vs soy de… origin — keep them separate.",
    xpReward: 30,
    exercises: [
      teach("teach-u2l6-ciudad", "ciudad"),
      {
        id: "u2l6-1",
        type: "select",
        prompt: "“I live in…” uses:",
        options: ["Vivo en…", "Soy en…", "Tengo en…", "Hablo en ciudad"],
        correctIndex: 0,
        explanation: "Vivo en + place for residence.",
        wordCardIds: ["vivo-en"],
        xp: 3,
      },
      {
        id: "u2l6-2",
        type: "situational-choose",
        prompt: "Pick the accurate line.",
        situation: "You’re from Mexico but you live in Chicago right now.",
        options: [
          "Soy de México. Vivo en Chicago.",
          "Soy en Chicago. Vivo de México.",
          "Tengo México en Chicago.",
          "Cuesta Chicago México.",
        ],
        correctIndex: 0,
        explanation: "Origin = soy de; residence = vivo en.",
        wordCardIds: ["soy-de", "vivo-en"],
        xp: 3,
      },
      {
        id: "u2l6-3",
        type: "tap-chips",
        prompt: "Build: “I live in the city.”",
        chips: ["Vivo", "en", "la", "ciudad", "país", "mal"],
        correctOrder: ["Vivo", "en", "la", "ciudad"],
        explanation: "Vivo en la ciudad.",
        wordCardIds: ["vivo-en", "ciudad"],
        xp: 4,
      },
      listen(
        "u2l6-4",
        "Vivo en la ciudad",
        ["I live in the city", "I'm from the city", "The city is free", "How old is the city?"],
        0,
        "Vivo en la ciudad = I live in the city.",
        ["vivo-en", "ciudad"]
      ),
      {
        id: "u2l6-5",
        type: "fill-blank",
        prompt: "Complete the Spanish.",
        template: "Vivo ___ Bogotá.",
        englishPrompt: "I live in Bogotá.",
        acceptedAnswers: ["en", "En"],
        hint: "in",
        explanation: "Vivo en Bogotá.",
        wordCardIds: ["vivo-en"],
        xp: 3,
      },
      {
        id: "u2l6-6",
        type: "translate",
        prompt: "Translate to Spanish: “I live in Mexico.”",
        acceptedAnswers: ["vivo en méxico", "vivo en mexico", "Vivo en México", "Vivo en Mexico"],
        hint: "vivo en + place",
        explanation: "Vivo en México.",
        wordCardIds: ["vivo-en", "mexico"],
        xp: 3,
      },
      {
        id: "u2l6-7",
        type: "select",
        prompt: "Ciudad means:",
        options: ["city", "please", "twenty", "thank you"],
        correctIndex: 0,
        explanation: "Ciudad = city.",
        wordCardIds: ["ciudad"],
        xp: 3,
      },
      {
        id: "u2l6-match",
        type: "match-pairs",
        prompt: "Match residence vs origin.",
        pairs: [
          { left: "Vivo en…", right: "I live in…" },
          { left: "Soy de…", right: "I'm from…" },
          { left: "ciudad", right: "city" },
          { left: "país", right: "country" },
        ],
        explanation: "Don't mix origin and residence.",
        wordCardIds: ["vivo-en", "soy-de", "ciudad", "pais"],
        xp: 4,
      },
    
      conjugate(
        "u2l6-conj-1",
        "hablar",
        "yo",
        "Present indicative",
        ["hablo", "Hablo"],
        "yo + hablar → hablo.",
        ["hablar"],
        { hint: "hablo", xp: 3 }
      ),
      conjugate(
        "u2l6-conj-2",
        "hablar",
        "nosotros/as",
        "Present indicative",
        ["hablamos", "Hablamos"],
        "nosotros + hablar → hablamos.",
        ["hablar"],
        { hint: "hablamos", xp: 3 }
      ),
    ],
  },

  "u2-l7": {
    id: "u2-l7",
    unitId: "unit-2",
    title: "Languages deepen",
    description: "Hablo…, un poco de, también, and pero.",
    xpReward: 32,
    exercises: [
      {
        id: "u2l7-1",
        type: "select",
        prompt: "“I speak Spanish” is:",
        options: ["Hablo español", "Soy español habla", "Vivo español", "Tengo español"],
        correctIndex: 0,
        explanation: "Hablo español.",
        wordCardIds: ["hablar", "espanol"],
        xp: 3,
      },
      {
        id: "u2l7-2",
        type: "tap-chips",
        prompt: "Build: “I speak a little Spanish.”",
        chips: ["Hablo", "un", "poco", "de", "español", "carro"],
        correctOrder: ["Hablo", "un", "poco", "de", "español"],
        explanation: "Hablo un poco de español — honest beginner line.",
        wordCardIds: ["hablar", "un-poco-de", "espanol"],
        xp: 4,
      },
      {
        id: "u2l7-3",
        type: "situational-choose",
        prompt: "Best humble line?",
        situation: "Someone asks if you speak Spanish. You’re a beginner.",
        options: [
          "Hablo un poco de español.",
          "Hablo cero carro.",
          "Soy un poco México.",
          "Cuesta un poco español.",
        ],
        correctIndex: 0,
        explanation: "Hablo un poco de español.",
        wordCardIds: ["un-poco-de", "espanol"],
        xp: 3,
      },
      listen(
        "u2l7-4",
        "Hablo inglés y un poco de español",
        [
          "I speak English and a little Spanish",
          "I live in English",
          "It costs English",
          "My name is English",
        ],
        0,
        "Hablo inglés y un poco de español.",
        ["hablar", "ingles", "un-poco-de", "espanol"]
      ),
      {
        id: "u2l7-5",
        type: "fill-blank",
        prompt: "Complete the Spanish.",
        template: "Hablo inglés ___.",
        englishPrompt: "I speak English too.",
        acceptedAnswers: ["también", "tambien", "También"],
        hint: "also / too",
        explanation: "Hablo inglés también.",
        wordCardIds: ["tambien", "ingles"],
        xp: 3,
      },
      {
        id: "u2l7-6",
        type: "select",
        prompt: "Pero means:",
        options: ["but", "please", "city", "phone"],
        correctIndex: 0,
        explanation: "Pero = but: Hablo español, pero un poco.",
        wordCardIds: ["pero"],
        xp: 3,
      },
      {
        id: "u2l7-7",
        type: "translate",
        prompt: "Translate to Spanish: “I speak English.”",
        acceptedAnswers: ["hablo inglés", "hablo ingles", "Hablo inglés", "Hablo ingles"],
        hint: "hablo + language",
        explanation: "Hablo inglés.",
        wordCardIds: ["hablar", "ingles"],
        xp: 3,
      },
      teach("teach-u2l7-y-tu", "y-tu"),
      {
        id: "u2l7-8",
        type: "situational-choose",
        prompt: "Return the question:",
        situation: "You said Hablo español. You want to ask them too.",
        options: ["¿Y tú?", "¿Y pesos?", "¿Y celular?", "¿Y gratis?"],
        correctIndex: 0,
        explanation: "¿Y tú? bounces it back.",
        wordCardIds: ["y-tu"],
        xp: 3,
      },
    ],
  },

  "u2-l8": {
    id: "u2-l8",
    unitId: "unit-2",
    title: "About you review",
    description: "Mix name, origin, home, and languages.",
    xpReward: 30,
    exercises: [
      {
        id: "u2l8-1",
        type: "select",
        prompt: "Origin uses:",
        options: ["Soy de…", "Vivo de…", "Hablo de ciudad", "Tengo de…"],
        correctIndex: 0,
        explanation: "Soy de… for origin.",
        wordCardIds: ["soy-de"],
        xp: 3,
      },
      {
        id: "u2l8-2",
        type: "select",
        prompt: "Residence uses:",
        options: ["Vivo en…", "Soy en…", "Me llamo en…", "Gracias en…"],
        correctIndex: 0,
        explanation: "Vivo en… for where you live.",
        wordCardIds: ["vivo-en"],
        xp: 3,
      },
      {
        id: "u2l8-3",
        type: "tap-chips",
        prompt: "Build: “I'm from the United States.”",
        chips: ["Soy", "de", "Estados", "Unidos", "hablo", "mal"],
        correctOrder: ["Soy", "de", "Estados", "Unidos"],
        explanation: "Soy de Estados Unidos.",
        wordCardIds: ["soy-de", "estados-unidos"],
        xp: 4,
      },
      listen(
        "u2l8-4",
        "Hablo un poco de español",
        ["I speak a little Spanish", "I am a little Spanish", "Spanish is free", "See you Spanish"],
        0,
        "Hablo un poco de español.",
        ["hablar", "un-poco-de", "espanol"]
      ),
      {
        id: "u2l8-5",
        type: "fill-blank",
        prompt: "Complete the Spanish.",
        template: "¿De dónde ___?",
        englishPrompt: "Where are you from?",
        acceptedAnswers: ["eres", "Eres"],
        hint: "you are (ser)",
        explanation: "¿De dónde eres?",
        wordCardIds: ["de-donde-eres"],
        xp: 3,
      },
      {
        id: "u2l8-6",
        type: "translate",
        prompt: "Translate to Spanish: “I live in the city.”",
        acceptedAnswers: [
          "vivo en la ciudad",
          "Vivo en la ciudad",
          "yo vivo en la ciudad",
          "Yo vivo en la ciudad",
        ],
        hint: "vivo en la ciudad",
        explanation: "Vivo en la ciudad.",
        wordCardIds: ["vivo-en", "ciudad"],
        xp: 3,
      },
      {
        id: "u2l8-7",
        type: "situational-choose",
        prompt: "Honest beginner language line:",
        situation: "New friend asks about languages.",
        options: [
          "Hablo inglés, pero un poco de español.",
          "Hablo celular y pesos.",
          "Soy de español un poco.",
          "Vivo inglés gratis.",
        ],
        correctIndex: 0,
        explanation: "Hablo… pero un poco de… is natural.",
        wordCardIds: ["hablar", "pero", "un-poco-de"],
        xp: 3,
      },
      {
        id: "u2l8-match",
        type: "match-pairs",
        prompt: "Review matches.",
        pairs: [
          { left: "también", right: "also / too" },
          { left: "pero", right: "but" },
          { left: "un poco de", right: "a little" },
          { left: "¿y tú?", right: "and you?" },
        ],
        explanation: "Connectors + bounce-back.",
        wordCardIds: ["tambien", "pero", "un-poco-de", "y-tu"],
        xp: 4,
      },
    ],
  },

  "u2-l9": {
    id: "u2-l9",
    unitId: "unit-2",
    title: "Story: Introducing myself",
    description: "Listen to a simple self-intro, then cloze the key lines.",
    xpReward: 40,
    exercises: [
      storyListen(
        "u2l9-story",
        "Me presento",
        [
          { text: "Hola, me llamo Valentina.", en: "Hi, my name is Valentina." },
          { text: "Soy de México.", en: "I'm from Mexico." },
          { text: "Ahora vivo en la ciudad.", en: "Now I live in the city." },
          { text: "Hablo español e inglés.", en: "I speak Spanish and English." },
          { text: "Hablo un poco de inglés también.", en: "I also speak a little English." },
          { text: "Mucho gusto.", en: "Nice to meet you." },
        ],
        [
          {
            prompt: "What is her name?",
            options: ["Valentina", "Mateo", "Carlos", "Luz"],
            correctIndex: 0,
            explanation: "Me llamo Valentina.",
          },
          {
            prompt: "Where is she from?",
            options: ["Mexico", "Only the metro", "A café menu", "Nowhere said"],
            correctIndex: 0,
            explanation: "Soy de México.",
          },
          {
            prompt: "Where does she live now?",
            options: ["In the city", "In a phone", "In pesos", "On a bus only"],
            correctIndex: 0,
            explanation: "Vivo en la ciudad.",
          },
          {
            prompt: "Which languages come up?",
            options: ["Spanish and English", "Only numbers", "Only goodbyes", "Only prices"],
            correctIndex: 0,
            explanation: "Hablo español e inglés.",
          },
        ],
        ["me-llamo", "soy-de", "mexico", "vivo-en", "ciudad", "hablar", "espanol", "ingles", "mucho-gusto"],
        "Self-intro story for Unit 2.",
        12
      ),
      cloze(
        "u2l9-cloze-1",
        "Soy ___ México.",
        ["de", "De"],
        "Soy de México.",
        ["soy-de", "mexico"],
        { hint: "from", audioText: "Soy de México.", voice: "f" }
      ),
      cloze(
        "u2l9-cloze-2",
        "Vivo en la ___.",
        ["ciudad", "Ciudad"],
        "Vivo en la ciudad.",
        ["vivo-en", "ciudad"],
        { hint: "city", audioText: "Vivo en la ciudad.", voice: "m" }
      ),
      cloze(
        "u2l9-cloze-3",
        "Hablo un poco de ___.",
        ["inglés", "ingles", "Inglés"],
        "Hablo un poco de inglés.",
        ["un-poco-de", "ingles"],
        { hint: "English", audioText: "Hablo un poco de inglés.", voice: "c" }
      ),
    ],
  },

  "u2-l10": {
    id: "u2-l10",
    unitId: "unit-2",
    title: "More identity practice",
    description: "Extra reps: name, origin, city, languages.",
    xpReward: 28,
    exercises: [
      {
        id: "u2l10-1",
        type: "select",
        prompt: "¿De qué país eres? asks about your:",
        options: ["country", "phone number", "price", "age only"],
        correctIndex: 0,
        explanation: "País = country.",
        wordCardIds: ["pais"],
        xp: 3,
      },
      {
        id: "u2l10-2",
        type: "tap-chips",
        prompt: "Build: “I speak Spanish too.”",
        chips: ["Hablo", "español", "también", "pero", "mal"],
        correctOrder: ["Hablo", "español", "también"],
        explanation: "Hablo español también.",
        wordCardIds: ["hablar", "espanol", "tambien"],
        xp: 4,
      },
      {
        id: "u2l10-3",
        type: "situational-choose",
        prompt: "Clarify origin vs home:",
        situation: "You’re from Colombia and live in Miami.",
        options: [
          "Soy de Colombia. Vivo en Miami.",
          "Vivo de Colombia. Soy en Miami.",
          "Hablo de Miami Colombia.",
          "Tengo Colombia en Miami.",
        ],
        correctIndex: 0,
        explanation: "Soy de… / Vivo en…",
        wordCardIds: ["soy-de", "vivo-en"],
        xp: 3,
      },
      listen(
        "u2l10-4",
        "Soy de Estados Unidos",
        ["I'm from the United States", "I live on dollars", "My name is United", "See you USA"],
        0,
        "Soy de Estados Unidos.",
        ["soy-de", "estados-unidos"]
      ),
      {
        id: "u2l10-5",
        type: "fill-blank",
        prompt: "Complete the Spanish.",
        template: "Me ___ Diego.",
        englishPrompt: "My name is Diego.",
        acceptedAnswers: ["llamo", "Llamo"],
        hint: "my name is",
        explanation: "Me llamo Diego.",
        wordCardIds: ["me-llamo"],
        xp: 3,
      },
      {
        id: "u2l10-6",
        type: "translate",
        prompt: "Translate to Spanish: “And you?”",
        acceptedAnswers: ["y tú", "y tu", "¿y tú?", "¿y tu?"],
        hint: "bounce the question back",
        explanation: "¿Y tú?",
        wordCardIds: ["y-tu"],
        xp: 3,
      },
      {
        id: "u2l10-7",
        type: "select",
        prompt: "Estadounidense is related to:",
        options: ["the United States", "only Mexico City traffic", "free water", "a goodbye"],
        correctIndex: 0,
        explanation: "Estadounidense ↔ Estados Unidos.",
        wordCardIds: ["estadounidense"],
        xp: 3,
      },
      {
        id: "u2l10-8",
        type: "match-pairs",
        prompt: "Identity matches.",
        pairs: [
          { left: "Yo soy…", right: "I am…" },
          { left: "Soy de…", right: "I'm from…" },
          { left: "Vivo en…", right: "I live in…" },
          { left: "Hablo…", right: "I speak…" },
        ],
        explanation: "Four identity verbs/phrases.",
        wordCardIds: ["ser", "soy-de", "vivo-en", "hablar"],
        xp: 4,
      },
    ],
  },

  "u2-l11": {
    id: "u2-l11",
    unitId: "unit-2",
    title: "Story: New neighbors",
    description: "Neighbors swap names, origin, and languages — then cloze.",
    xpReward: 40,
    exercises: [
      storyListen(
        "u2l11-story",
        "Los vecinos",
        [
          { text: "Hola, ¿cómo te llamas?", en: "Hi, what's your name?" },
          { text: "Me llamo Bruno. ¿Y tú?", en: "My name is Bruno. And you?" },
          { text: "Me llamo Camila.", en: "My name is Camila." },
          { text: "¿De dónde eres?", en: "Where are you from?" },
          { text: "Soy de México. Vivo aquí en la ciudad.", en: "I'm from Mexico. I live here in the city." },
          { text: "Yo hablo inglés y un poco de español.", en: "I speak English and a little Spanish." },
        ],
        [
          {
            prompt: "Who asks the first name question?",
            options: ["The opener with ¿cómo te llamas?", "A cashier asking prices", "Nobody", "Only a robot"],
            correctIndex: 0,
            explanation: "Hola, ¿cómo te llamas?",
          },
          {
            prompt: "Bruno’s next question is about:",
            options: ["Origin", "Pesos only", "Good night only", "A car"],
            correctIndex: 0,
            explanation: "¿De dónde eres?",
          },
          {
            prompt: "Camila lives…",
            options: ["In the city", "Inside a cellphone", "On a menu", "Nowhere"],
            correctIndex: 0,
            explanation: "Vivo aquí en la ciudad.",
          },
          {
            prompt: "Bruno’s languages?",
            options: ["English and a little Spanish", "Only numbers 1–3", "Only gracias", "Only adiós"],
            correctIndex: 0,
            explanation: "Hablo inglés y un poco de español.",
          },
        ],
        ["como-te-llamas", "me-llamo", "y-tu", "de-donde-eres", "soy-de", "vivo-en", "ciudad", "hablar", "ingles", "un-poco-de", "espanol"],
        "Neighbor intro story.",
        12
      ),
      cloze(
        "u2l11-cloze-1",
        "¿De dónde ___?",
        ["eres", "Eres"],
        "¿De dónde eres?",
        ["de-donde-eres"],
        { hint: "you are", audioText: "¿De dónde eres?", voice: "f" }
      ),
      cloze(
        "u2l11-cloze-2",
        "Soy de ___.",
        ["México", "Mexico", "méxico", "mexico"],
        "Soy de México.",
        ["soy-de", "mexico"],
        { hint: "Mexico", audioText: "Soy de México.", voice: "m" }
      ),
      cloze(
        "u2l11-cloze-3",
        "Hablo inglés y un poco de ___.",
        ["español", "espanol", "Español"],
        "Hablo inglés y un poco de español.",
        ["hablar", "un-poco-de", "espanol"],
        { hint: "Spanish", audioText: "Hablo inglés y un poco de español.", voice: "c" }
      ),
    ],
  },

  "u2-l12": {
    id: "u2-l12",
    unitId: "unit-2",
    title: "Unit 2 check",
    description: "Show you can say who you are: name, origin, home, languages.",
    xpReward: 35,
    exercises: [
      {
        id: "u2l12-1",
        type: "select",
        prompt: "My name is…",
        options: ["Me llamo…", "Me vivo…", "Me cuesta…", "Me perdón…"],
        correctIndex: 0,
        explanation: "Me llamo…",
        wordCardIds: ["me-llamo"],
        xp: 3,
      },
      {
        id: "u2l12-2",
        type: "select",
        prompt: "Where are you from?",
        options: ["¿De dónde eres?", "¿Cuánto cuesta?", "¿Cómo estás pesos?", "¿Qué tal celular?"],
        correctIndex: 0,
        explanation: "¿De dónde eres?",
        wordCardIds: ["de-donde-eres"],
        xp: 3,
      },
      {
        id: "u2l12-3",
        type: "tap-chips",
        prompt: "Build: “I live in the city.”",
        chips: ["Vivo", "en", "la", "ciudad", "país", "sí"],
        correctOrder: ["Vivo", "en", "la", "ciudad"],
        explanation: "Vivo en la ciudad.",
        wordCardIds: ["vivo-en", "ciudad"],
        xp: 4,
      },
      {
        id: "u2l12-4",
        type: "translate",
        prompt: "Translate to Spanish: “I speak a little Spanish.”",
        acceptedAnswers: [
          "hablo un poco de español",
          "hablo un poco de espanol",
          "Hablo un poco de español",
          "Hablo un poco de espanol",
        ],
        hint: "hablo un poco de…",
        explanation: "Hablo un poco de español.",
        wordCardIds: ["hablar", "un-poco-de", "espanol"],
        xp: 3,
      },
      {
        id: "u2l12-5",
        type: "fill-blank",
        prompt: "Complete the Spanish.",
        template: "Soy ___ México.",
        englishPrompt: "I'm from Mexico.",
        acceptedAnswers: ["de", "De"],
        hint: "from",
        explanation: "Soy de México.",
        wordCardIds: ["soy-de"],
        xp: 3,
      },
      {
        id: "u2l12-6",
        type: "situational-choose",
        prompt: "Bounce it back:",
        situation: "Friend: “Hablo inglés.” You want to ask them about Spanish too — start with…",
        options: ["¿Y tú?", "¿Y veinte?", "¿Y gratis?", "¿Y adiós?"],
        correctIndex: 0,
        explanation: "¿Y tú?",
        wordCardIds: ["y-tu"],
        xp: 3,
      },
      listen(
        "u2l12-7",
        "Mucho gusto",
        ["Nice to meet you", "How much?", "Good night", "I live here"],
        0,
        "Mucho gusto.",
        ["mucho-gusto"]
      ),
      {
        id: "u2l12-match",
        type: "match-pairs",
        prompt: "Unit 2 final matches.",
        pairs: [
          { left: "país", right: "country" },
          { left: "ciudad", right: "city" },
          { left: "también", right: "also" },
          { left: "pero", right: "but" },
        ],
        explanation: "Core Unit 2 nouns + connectors.",
        wordCardIds: ["pais", "ciudad", "tambien", "pero"],
        xp: 4,
      },
    ],
  },
};
