/**
 * Unit 5 — Food & ordering (~12 lessons). Spanish.
 * Merged via intermediate.ts into mock-data.
 */
import type { Lesson, WordCard } from "../types";
import { audioSrcFor, voiceForIndex, type AudioVoice } from "../audio";

function teach(
  id: string,
  wordCardId: string
): import("../types").TeachExercise {
  return {
    id,
    type: "teach",
    prompt: "New word — learn it, then practice.",
    explanation: "",
    wordCardId,
    wordCardIds: [wordCardId],
    xp: 0,
  };
}

let listenVoiceIndex = 500;

function listen(
  id: string,
  audioText: string,
  options: string[],
  correctIndex: number,
  explanation: string,
  wordCardIds: string[],
  xp = 3
): import("../types").ListeningChooseExercise {
  const voice = voiceForIndex(listenVoiceIndex);
  listenVoiceIndex += 1;
  return {
    id,
    type: "listening-choose",
    prompt: "What did you hear?",
    audioText,
    audioSrc: audioSrcFor(audioText, voice),
    options,
    correctIndex,
    explanation,
    wordCardIds,
    xp,
  };
}

function cloze(
  id: string,
  template: string,
  acceptedAnswers: string[],
  explanation: string,
  wordCardIds: string[],
  opts: {
    hint?: string;
    audioText: string;
    voice?: AudioVoice;
    storyLabel?: string;
    xp?: number;
  }
): import("../types").ClozeExercise {
  const voice = opts.voice ?? "f";
  return {
    id,
    type: "cloze",
    prompt: "Fill the blank from the story",
    template,
    acceptedAnswers,
    hint: opts.hint,
    explanation,
    wordCardIds,
    audioText: opts.audioText,
    audioSrc: audioSrcFor(opts.audioText, voice),
    storyLabel: opts.storyLabel ?? "From the story",
    xp: opts.xp ?? 3,
  };
}

function storyListen(
  id: string,
  title: string,
  lines: { text: string; en?: string; voice?: AudioVoice }[],
  questions: {
    prompt: string;
    options: string[];
    correctIndex: number;
    explanation?: string;
  }[],
  wordCardIds: string[],
  explanation = "Story comprehension — replay anytime.",
  xp = 10
): import("../types").StoryListenExercise {
  const withVoices = lines.map((line, i) => ({
    text: line.text,
    en: line.en,
    voice: line.voice ?? voiceForIndex(i),
  }));
  return {
    id,
    type: "story-listen",
    prompt: "Listen to the story, then answer",
    title,
    lines: withVoices,
    questions,
    explanation,
    wordCardIds,
    xp,
  };
}



function dictation(
  id: string,
  audioText: string,
  acceptedAnswers: string[],
  explanation: string,
  wordCardIds: string[],
  opts: { hint?: string; voice?: AudioVoice; xp?: number } = {}
): import("../types").DictationExercise {
  const voice = opts.voice ?? "f";
  return {
    id,
    type: "dictation",
    prompt: "Type what you hear",
    audioText,
    audioSrc: audioSrcFor(audioText, voice),
    acceptedAnswers,
    hint: opts.hint,
    explanation,
    wordCardIds,
    xp: opts.xp ?? 4,
  };
}


export const UNIT5_WORD_CARDS: Record<string, WordCard> = {
  tacos: {
    id: "tacos",
    lemma: "tacos",
    pos: "noun",
    gender: "m",
    gloss: "tacos",
    meaningSummary:
      "Everyday food word. Me gustan los tacos / Quiero tacos, por favor. Plural is the default when talking about the dish.",
    examples: [
      { es: "Me gustan los tacos.", en: "I like tacos." },
      { es: "Quiero tacos, por favor.", en: "I want tacos, please." },
    ],
    useWhen: "Talking about or ordering tacos.",
    dontUseWhen: "n/a — extremely common.",
    formality: "neutral",
    cefr: "A2",
  },
  agua: {
    id: "agua",
    lemma: "agua",
    pos: "noun",
    gender: "f",
    gloss: "water",
    meaningSummary:
      "Water. Feminine noun but uses el/un in singular: el agua, un agua. At restaurants: Un agua, por favor.",
    examples: [
      { es: "Un agua, por favor.", en: "A water, please." },
      { es: "¿Me trae agua, por favor?", en: "Could you bring me water, please?" },
    ],
    useWhen: "Ordering or asking for water.",
    dontUseWhen: "Don't say la agua in singular — use el agua / un agua.",
    contrast: "jugo / café / té",
    formality: "neutral",
    cefr: "A2",
  },
  menu: {
    id: "menu",
    lemma: "menú",
    pos: "noun",
    gender: "m",
    gloss: "menu",
    meaningSummary:
      "The restaurant menu. Polite with staff: Disculpe, ¿me puede traer un menú?",
    examples: [
      { es: "Disculpe, ¿me puede traer un menú?", en: "Excuse me, could you bring me a menu?" },
      { es: "¿Tienen menú del día?", en: "Do you have a daily special menu?" },
    ],
    useWhen: "Asking for or talking about the menu.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A2",
  },
  comida: {
    id: "comida",
    lemma: "comida",
    pos: "noun",
    gender: "f",
    gloss: "food / meal",
    meaningSummary:
      "Food in general, or a meal. La comida está rica / ¿Qué comida quieres?",
    examples: [
      { es: "La comida está muy buena.", en: "The food is really good." },
      { es: "¿Qué comida te gusta?", en: "What food do you like?" },
    ],
    useWhen: "Talking about food or a meal in general.",
    dontUseWhen: "For a specific dish, name it (tacos, pollo, arroz…).",
    formality: "neutral",
    cefr: "A2",
  },
  pan: {
    id: "pan",
    lemma: "pan",
    pos: "noun",
    gender: "m",
    gloss: "bread",
    meaningSummary: "Bread. Quiero pan / Me gusta el pan fresco.",
    examples: [
      { es: "Quiero pan, por favor.", en: "I want bread, please." },
      { es: "Me gusta el pan.", en: "I like bread." },
    ],
    useWhen: "Ordering or talking about bread.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A2",
  },
  pollo: {
    id: "pollo",
    lemma: "pollo",
    pos: "noun",
    gender: "m",
    gloss: "chicken",
    meaningSummary: "Chicken (the meat or dish). Quiero pollo / Me gusta el pollo.",
    examples: [
      { es: "Quiero pollo con arroz.", en: "I want chicken with rice." },
      { es: "¿Me recomienda el pollo?", en: "Do you recommend the chicken?" },
    ],
    useWhen: "Ordering or talking about chicken.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A2",
  },
  arroz: {
    id: "arroz",
    lemma: "arroz",
    pos: "noun",
    gender: "m",
    gloss: "rice",
    meaningSummary: "Rice. Common side or plate: pollo con arroz / Quiero arroz.",
    examples: [
      { es: "Quiero arroz, por favor.", en: "I want rice, please." },
      { es: "El pollo viene con arroz.", en: "The chicken comes with rice." },
    ],
    useWhen: "Ordering or describing rice dishes.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A2",
  },
  leche: {
    id: "leche",
    lemma: "leche",
    pos: "noun",
    gender: "f",
    gloss: "milk",
    meaningSummary:
      "Milk. At cafés: café con leche. Also: Quiero leche, por favor.",
    examples: [
      { es: "Un café con leche, por favor.", en: "A coffee with milk, please." },
      { es: "¿Tienen leche?", en: "Do you have milk?" },
    ],
    useWhen: "Drinks with milk or ordering milk.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A2",
  },
  te: {
    id: "te",
    lemma: "té",
    pos: "noun",
    gender: "m",
    gloss: "tea",
    meaningSummary: "Tea. Un té, por favor / Me gusta el té.",
    examples: [
      { es: "Un té, por favor.", en: "A tea, please." },
      { es: "Me gusta el té.", en: "I like tea." },
    ],
    useWhen: "Ordering or talking about tea.",
    dontUseWhen: "Don't confuse written té (tea) with the object pronoun te.",
    contrast: "café / jugo / agua",
    formality: "neutral",
    cefr: "A2",
  },
  restaurante: {
    id: "restaurante",
    lemma: "restaurante",
    pos: "noun",
    gender: "m",
    gloss: "restaurant",
    meaningSummary:
      "Restaurant. Vamos a un restaurante / El restaurante está cerca.",
    examples: [
      { es: "Vamos a un restaurante.", en: "Let's go to a restaurant." },
      { es: "El restaurante está cerca del centro.", en: "The restaurant is near downtown." },
    ],
    useWhen: "Talking about eating out.",
    dontUseWhen: "For a small café you can also say café.",
    contrast: "café (coffee shop)",
    formality: "neutral",
    cefr: "A2",
  },
  mesero: {
    id: "mesero",
    lemma: "mesero / mesera",
    pos: "noun",
    gender: "mf",
    gloss: "waiter / waitress",
    meaningSummary:
      "Service staff at a restaurant. Ask politely with usted: Disculpe… to the mesero/mesera.",
    examples: [
      { es: "El mesero trae la cuenta.", en: "The waiter brings the check." },
      { es: "Disculpe, ¿me puede ayudar?", en: "Excuse me, can you help me?" },
    ],
    useWhen: "Referring to restaurant staff.",
    dontUseWhen: "With the person, usted + Disculpe is more useful than naming the job.",
    formality: "neutral",
    cefr: "A2",
  },
  "me-gustaria": {
    id: "me-gustaria",
    lemma: "me gustaría",
    pos: "phrase",
    gender: "n/a",
    gloss: "I would like",
    meaningSummary:
      "Softer than quiero for orders and wishes: Me gustaría un café, por favor. Polite with servers; still clear.",
    examples: [
      { es: "Me gustaría un café, por favor.", en: "I would like a coffee, please." },
      { es: "Me gustaría el pollo.", en: "I would like the chicken." },
    ],
    useWhen: "Polite ordering or soft wants.",
    dontUseWhen: "For a quick counter order, Quiero un café is also fine and very common.",
    contrast: "quiero (more direct) / me gusta (I like — preference, not the order)",
    formality: "neutral",
    cefr: "A2",
  },
  propina: {
    id: "propina",
    lemma: "propina",
    pos: "noun",
    gender: "f",
    gloss: "tip",
    meaningSummary:
      "Tip for service. ¿Dejamos propina? / La propina no está incluida.",
    examples: [
      { es: "¿Dejamos propina?", en: "Shall we leave a tip?" },
      { es: "La propina no está incluida.", en: "The tip is not included." },
    ],
    useWhen: "Paying and tipping after a meal.",
    dontUseWhen: "Not the same as la cuenta (the check).",
    contrast: "la cuenta (the check)",
    formality: "neutral",
    cefr: "A2",
  },
  "para-llevar": {
    id: "para-llevar",
    lemma: "para llevar",
    pos: "phrase",
    gender: "n/a",
    gloss: "to go / takeaway",
    meaningSummary:
      "Takeaway vs eating here: Para llevar / Para comer aquí. Common at cafés and counters.",
    examples: [
      { es: "Para llevar, por favor.", en: "To go, please." },
      { es: "¿Para llevar o para comer aquí?", en: "To go or for here?" },
    ],
    useWhen: "Saying you want takeaway.",
    dontUseWhen: "n/a",
    contrast: "para comer aquí (for here)",
    formality: "neutral",
    cefr: "A2",
  },
  almuerzo: {
    id: "almuerzo",
    lemma: "almuerzo",
    pos: "noun",
    gender: "m",
    gloss: "lunch",
    meaningSummary:
      "Lunch (meal). Also verb almorzar: Almuerzo a las dos. El almuerzo is the midday meal.",
    examples: [
      { es: "El almuerzo está listo.", en: "Lunch is ready." },
      { es: "¿Qué quieres de almuerzo?", en: "What do you want for lunch?" },
    ],
    useWhen: "Talking about lunch.",
    dontUseWhen: "Breakfast is desayuno; dinner is cena.",
    contrast: "desayuno / cena",
    formality: "neutral",
    cefr: "A2",
  },
  cena: {
    id: "cena",
    lemma: "cena",
    pos: "noun",
    gender: "f",
    gloss: "dinner",
    meaningSummary:
      "Dinner / evening meal. La cena / ¿Qué cenamos? Related verb: cenar.",
    examples: [
      { es: "La cena es a las ocho.", en: "Dinner is at eight." },
      { es: "¿Quieres cena en el restaurante?", en: "Do you want dinner at the restaurant?" },
    ],
    useWhen: "Talking about dinner.",
    dontUseWhen: "Lunch is almuerzo; breakfast is desayuno.",
    contrast: "almuerzo / desayuno",
    formality: "neutral",
    cefr: "A2",
  },
};


export const UNIT5_LESSONS: Record<string, Lesson> = {
  "u5-l1": {
    id: "u5-l1",
    unitId: "unit-5",
    title: "Me gusta vs quiero",
    description: "Likes vs ordering — café, jugo, tacos, and clear wants.",
    xpReward: 42,
    exercises: [
      teach("teach-u5l1-me-gusta", "me-gusta"),
      {
        id: "u5l1-1",
        type: "select",
        prompt: "“I like coffee” is…",
        options: ["Quiero gusta café.", "Soy café.", "Me gusta el café.", "Tengo gusto café."],
        correctIndex: 2,
        explanation: "Me gusta el café — gustar flips the subject.",
        wordCardIds: ["me-gusta", "cafe"],
        xp: 3,
      },
      teach("teach-u5l1-quiero", "quiero"),
      {
        id: "u5l1-2",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "You're at the counter ordering a juice.",
        options: [
          "Me gusta un jugo, por favor.",
          "Soy un jugo.",
          "Comí un jugo ayer.",
          "Quiero un jugo, por favor.",
        ],
        correctIndex: 3,
        explanation: "Orders use quiero. Me gusta states preference, not the order itself.",
        wordCardIds: ["quiero", "jugo"],
        xp: 4,
      },
      teach("teach-u5l1-jugo", "jugo"),
      teach("teach-u5l1-cafe", "cafe"),
      teach("teach-u5l1-tacos", "tacos"),
      {
        id: "u5l1-3",
        type: "tap-chips",
        prompt: "Build: “I like tacos.”",
        chips: ["Me", "gustan", "los", "tacos.", "quiero", "jugo"],
        correctOrder: ["Me", "gustan", "los", "tacos."],
        explanation: "Plural liked things → me gustan.",
        wordCardIds: ["me-gusta", "tacos"],
        xp: 3,
      },
      {
        id: "u5l1-4",
        type: "translate",
        prompt: "Translate: “I want an orange juice.”",
        acceptedAnswers: [
          "Quiero un jugo de naranja.",
          "Quiero un jugo de naranja",
          "Yo quiero un jugo de naranja.",
        ],
        hint: "jugo de naranja",
        explanation: "Quiero un jugo de naranja.",
        wordCardIds: ["quiero", "jugo"],
        xp: 4,
      },
      listen(
        "u5l1-5",
        "Me gusta el café.",
        ["I want coffee.", "The check, please.", "I ate coffee.", "I like coffee."],
        3,
        "Me gusta el café = I like coffee.",
        ["me-gusta", "cafe"]
      ),
      {
        id: "u5l1-6",
        type: "select",
        prompt: "At a café, the clearer order is…",
        options: [
          "Me gusta un café, por favor.",
          "Quiero un café, por favor.",
          "Fui un café.",
          "Me parece un café.",
        ],
        correctIndex: 1,
        explanation: "Quiero + item (+ por favor) for ordering.",
        wordCardIds: ["quiero", "cafe"],
        xp: 3,
      },
      {
        id: "u5l1-7",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I like coffee.",
        template: "Me ___ el café.",
        acceptedAnswers: ["gusta", "Gusta"],
        hint: "I like (singular)",
        explanation: "Me gusta el café.",
        wordCardIds: ["me-gusta"],
        xp: 3,
      },
      {
        id: "u5l1-8",
        type: "match-pairs",
        prompt: "Match preference vs order.",
        pairs: [
          { left: "Me gusta el café", right: "I like coffee" },
          { left: "Quiero un café", right: "I want a coffee (ordering)" },
          { left: "jugo", right: "juice" },
          { left: "Me gustan los tacos", right: "I like tacos" },
        ],
        explanation: "Gustar = like; querer = want/order.",
        wordCardIds: ["me-gusta", "quiero", "jugo", "cafe", "tacos"],
        xp: 4,
      },
      listen(
        "u5l1-9",
        "Quiero un jugo de naranja.",
        ["I like orange juice.", "I want an orange juice.", "Where is the juice?", "I went for juice yesterday."],
        1,
        "Quiero un jugo de naranja = I want an orange juice.",
        ["quiero", "jugo"]
      ),
      {
        id: "u5l1-10",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "A friend asks if you like tacos (tú chat).",
        options: [
          "Sí, quiero los tacos siempre cuenta.",
          "Sí, soy los tacos.",
          "Sí, me gustan los tacos.",
          "Sí, la cuenta los tacos.",
        ],
        correctIndex: 2,
        explanation: "Me gustan los tacos — preference with plural.",
        wordCardIds: ["me-gusta", "tacos"],
        xp: 3,
      },
    ],
  },
  "u5-l2": {
    id: "u5-l2",
    unitId: "unit-5",
    title: "Ordering with usted",
    description: "Polite café Spanish — menus, recommendations, the check.",
    xpReward: 42,
    exercises: [
      teach("teach-u5l2-usted", "usted-server"),
      {
        id: "u5l2-1",
        type: "select",
        prompt: "With a waiter you don't know, the safer default is…",
        options: ["only slang nicknames", "skip the name", "no greeting", "usted"],
        correctIndex: 3,
        explanation: "Usted is the polite default with service staff in many places.",
        wordCardIds: ["usted-server"],
        xp: 3,
      },
      teach("teach-u5l2-cuenta", "la-cuenta"),
      {
        id: "u5l2-2",
        type: "tap-chips",
        prompt: "Build: “The check, please.”",
        chips: ["La", "cuenta,", "por", "favor.", "jugo", "carro"],
        correctOrder: ["La", "cuenta,", "por", "favor."],
        explanation: "La cuenta, por favor.",
        wordCardIds: ["la-cuenta"],
        xp: 3,
      },
      teach("teach-u5l2-menu", "menu"),
      {
        id: "u5l2-3",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "You need a menu from the server (polite).",
        options: [
          "Oye, dame menú ya.",
          "Me gusta el menú ayer.",
          "Disculpe, ¿me puede traer un menú?",
          "Fui el menú.",
        ],
        correctIndex: 2,
        explanation: "Disculpe + ¿me puede traer…? is polite usted service Spanish.",
        wordCardIds: ["usted-server", "menu"],
        xp: 4,
      },
      listen(
        "u5l2-4",
        "¿Me trae la cuenta, por favor?",
        ["Do you like the check?", "Where is the metro?", "I woke up early.", "Could you bring me the check, please?"],
        3,
        "¿Me trae la cuenta, por favor? — polite bill request.",
        ["la-cuenta", "usted-server"]
      ),
      {
        id: "u5l2-5",
        type: "translate",
        prompt: "Translate: “Could you recommend something, please?”",
        acceptedAnswers: [
          "¿Me recomienda algo, por favor?",
          "Me recomienda algo, por favor?",
          "¿Me recomienda algo por favor?",
        ],
        hint: "me recomienda (usted)",
        explanation: "¿Me recomienda algo, por favor?",
        wordCardIds: ["usted-server"],
        xp: 4,
      },
      {
        id: "u5l2-6",
        type: "select",
        prompt: "“Excuse me” to get a server's attention:",
        options: ["Adiós", "Todo recto", "Disculpe", "Ayer"],
        correctIndex: 2,
        explanation: "Disculpe is the polite attention-getter.",
        wordCardIds: ["usted-server", "disculpe"],
        xp: 3,
      },
      {
        id: "u5l2-7",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "Could you bring me the check, please?",
        template: "¿Me trae la ___, por favor?",
        acceptedAnswers: ["cuenta", "Cuenta"],
        hint: "the check",
        explanation: "¿Me trae la cuenta, por favor?",
        wordCardIds: ["la-cuenta"],
        xp: 3,
      },
      {
        id: "u5l2-8",
        type: "match-pairs",
        prompt: "Match café service lines.",
        pairs: [
          { left: "Disculpe", right: "Excuse me (polite)" },
          { left: "la cuenta", right: "the check" },
          { left: "¿Me puede traer…?", right: "Could you bring me…?" },
          { left: "¿Me recomienda algo?", right: "Could you recommend something?" },
        ],
        explanation: "Polite ordering toolkit.",
        wordCardIds: ["usted-server", "la-cuenta", "menu"],
        xp: 4,
      },
      listen(
        "u5l2-9",
        "Disculpe, ¿me puede traer un menú?",
        ["I like the menu.", "Where is the apartment?", "Excuse me, could you bring me a menu?", "I went yesterday."],
        2,
        "Polite menu request with usted.",
        ["usted-server", "menu"]
      ),
      {
        id: "u5l2-10",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "You're done eating and want the bill (polite).",
        options: [
          "Me gusta la cuenta ahora.",
          "Quiero el mesero ayer.",
          "Camino la cuenta.",
          "¿Me trae la cuenta, por favor?",
        ],
        correctIndex: 3,
        explanation: "¿Me trae la cuenta, por favor?",
        wordCardIds: ["la-cuenta", "usted-server"],
        xp: 3,
      },
    ],
  },

  "u5-l3": {
    id: "u5-l3",
    unitId: "unit-5",
    title: "Menu & food nouns",
    description: "Core plate words — tacos, pollo, arroz, pan, comida, menú.",
    xpReward: 42,
    exercises: [
      teach("teach-u5l3-comida", "comida"),
      {
        id: "u5l3-1",
        type: "select",
        prompt: "“Food / meal” is…",
        options: ["cuenta", "comida", "oficina", "carro"],
        correctIndex: 1,
        explanation: "comida = food or a meal.",
        wordCardIds: ["comida"],
        xp: 3,
      },
      teach("teach-u5l3-tacos", "tacos"),
      teach("teach-u5l3-pollo", "pollo"),
      {
        id: "u5l3-2",
        type: "tap-chips",
        prompt: "Build: “I want chicken with rice.”",
        chips: ["Quiero", "pollo", "con", "arroz.", "jugo", "metro"],
        correctOrder: ["Quiero", "pollo", "con", "arroz."],
        explanation: "Quiero pollo con arroz.",
        wordCardIds: ["quiero", "pollo", "arroz"],
        xp: 3,
      },
      teach("teach-u5l3-arroz", "arroz"),
      teach("teach-u5l3-pan", "pan"),
      {
        id: "u5l3-3",
        type: "translate",
        prompt: "Translate: “I want bread, please.”",
        acceptedAnswers: [
          "Quiero pan, por favor.",
          "Quiero pan, por favor",
          "Quiero pan por favor.",
          "Yo quiero pan, por favor.",
        ],
        hint: "pan + por favor",
        explanation: "Quiero pan, por favor.",
        wordCardIds: ["quiero", "pan"],
        xp: 4,
      },
      listen(
        "u5l3-4",
        "La comida está muy buena.",
        ["The check is really good.", "The food is really good.", "I want juice.", "Turn left."],
        1,
        "La comida está muy buena.",
        ["comida"]
      ),
      {
        id: "u5l3-5",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "Looking at the menu, you decide on tacos (tú order style).",
        options: [
          "Me gusta tacos la cuenta.",
          "Soy tacos.",
          "Quiero tacos, por favor.",
          "Camino tacos.",
        ],
        correctIndex: 2,
        explanation: "Quiero tacos, por favor.",
        wordCardIds: ["quiero", "tacos"],
        xp: 3,
      },
      {
        id: "u5l3-6",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I want chicken with rice.",
        template: "Quiero pollo con ___.",
        acceptedAnswers: ["arroz", "Arroz"],
        hint: "rice",
        explanation: "Quiero pollo con arroz.",
        wordCardIds: ["pollo", "arroz"],
        xp: 3,
      },
      {
        id: "u5l3-7",
        type: "match-pairs",
        prompt: "Match food nouns.",
        pairs: [
          { left: "comida", right: "food / meal" },
          { left: "tacos", right: "tacos" },
          { left: "pollo", right: "chicken" },
          { left: "arroz", right: "rice" },
          { left: "pan", right: "bread" },
        ],
        explanation: "Core menu nouns.",
        wordCardIds: ["comida", "tacos", "pollo", "arroz", "pan"],
        xp: 4,
      },
      listen(
        "u5l3-8",
        "¿Tienen menú del día?",
        ["Do you like the day?", "Where is the office?", "Do you have a daily special menu?", "I woke up early."],
        2,
        "¿Tienen menú del día?",
        ["menu"]
      ),
      {
        id: "u5l3-9",
        type: "select",
        prompt: "The list of dishes you ask for is the…",
        options: ["propina", "departamento", "derecha", "menú"],
        correctIndex: 3,
        explanation: "menú — the menu.",
        wordCardIds: ["menu"],
        xp: 3,
      },
    ],
  },
  "u5-l4": {
    id: "u5-l4",
    unitId: "unit-5",
    title: "Likes & wants with food",
    description: "Me gusta / me gustan / quiero with real menu words.",
    xpReward: 42,
    exercises: [
      {
        id: "u5l4-1",
        type: "select",
        prompt: "“I like chicken” is…",
        options: ["Me gustan el pollo.", "Quiero gusta pollo.", "Me gusta el pollo.", "Soy el pollo."],
        correctIndex: 2,
        explanation: "Singular liked thing → me gusta.",
        wordCardIds: ["me-gusta", "pollo"],
        xp: 3,
      },
      {
        id: "u5l4-2",
        type: "tap-chips",
        prompt: "Build: “I like rice.”",
        chips: ["Me", "gusta", "el", "arroz.", "gustan", "tacos"],
        correctOrder: ["Me", "gusta", "el", "arroz."],
        explanation: "Me gusta el arroz.",
        wordCardIds: ["me-gusta", "arroz"],
        xp: 3,
      },
      {
        id: "u5l4-3",
        type: "translate",
        prompt: "Translate: “I want chicken, please.”",
        acceptedAnswers: [
          "Quiero pollo, por favor.",
          "Quiero pollo, por favor",
          "Quiero pollo por favor.",
          "Yo quiero pollo, por favor.",
        ],
        hint: "Quiero pollo…",
        explanation: "Quiero pollo, por favor.",
        wordCardIds: ["quiero", "pollo"],
        xp: 4,
      },
      listen(
        "u5l4-4",
        "Me gustan los tacos.",
        ["I want tacos only as a bill.", "I walk tacos.", "I like tacos.", "The check likes tacos."],
        2,
        "Me gustan los tacos.",
        ["me-gusta", "tacos"]
      ),
      {
        id: "u5l4-5",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "Friend asks what food you like (tú).",
        options: [
          "Quiero la comida la cuenta.",
          "Soy comida.",
          "Me despierto comida.",
          "Me gusta la comida mexicana.",
        ],
        correctIndex: 3,
        explanation: "Me gusta la comida… for preference.",
        wordCardIds: ["me-gusta", "comida"],
        xp: 3,
      },
      {
        id: "u5l4-6",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I like tacos.",
        template: "Me ___ los tacos.",
        acceptedAnswers: ["gustan", "Gustan"],
        hint: "I like (plural)",
        explanation: "Me gustan los tacos.",
        wordCardIds: ["me-gusta", "tacos"],
        xp: 3,
      },
      {
        id: "u5l4-7",
        type: "match-pairs",
        prompt: "Match.",
        pairs: [
          { left: "Me gusta el pan", right: "I like bread" },
          { left: "Me gustan los tacos", right: "I like tacos" },
          { left: "Quiero arroz", right: "I want rice" },
          { left: "Quiero pollo", right: "I want chicken" },
        ],
        explanation: "Like vs want with food nouns.",
        wordCardIds: ["me-gusta", "quiero", "pan", "tacos", "arroz", "pollo"],
        xp: 4,
      },
      {
        id: "u5l4-8",
        type: "select",
        prompt: "Ordering at the counter, pick the clearer line:",
        options: [
          "Me gusta pan, por favor.",
          "Fui pan, por favor.",
          "Descanso pan, por favor.",
          "Quiero pan, por favor.",
        ],
        correctIndex: 3,
        explanation: "Quiero for the order; me gusta for preference.",
        wordCardIds: ["quiero", "pan", "me-gusta"],
        xp: 3,
      },
      listen(
        "u5l4-9",
        "Quiero pollo con arroz.",
        ["I like only water.", "I want chicken with rice.", "Where is the metro?", "I get up early."],
        1,
        "Quiero pollo con arroz.",
        ["quiero", "pollo", "arroz"]
      ),
    ],
  },
  "u5-l5": {
    id: "u5-l5",
    unitId: "unit-5",
    title: "Polite orders",
    description: "Me gustaría, recommendations, and soft usted lines.",
    xpReward: 44,
    exercises: [
      teach("teach-u5l5-me-gustaria", "me-gustaria"),
      {
        id: "u5l5-1",
        type: "select",
        prompt: "A softer order than quiero is…",
        options: [
          "Me gusta un café, por favor.",
          "Soy un café, por favor.",
          "Camino un café, por favor.",
          "Me gustaría un café, por favor.",
        ],
        correctIndex: 3,
        explanation: "Me gustaría = I would like — polite order.",
        wordCardIds: ["me-gustaria", "cafe"],
        xp: 3,
      },
      teach("teach-u5l5-mesero", "mesero"),
      {
        id: "u5l5-2",
        type: "tap-chips",
        prompt: "Build: “I would like the chicken.”",
        chips: ["Me", "gustaría", "el", "pollo.", "gusta", "carro"],
        correctOrder: ["Me", "gustaría", "el", "pollo."],
        explanation: "Me gustaría el pollo.",
        wordCardIds: ["me-gustaria", "pollo"],
        xp: 3,
      },
      {
        id: "u5l5-3",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "You want the server's recommendation (usted).",
        options: [
          "¿Me gusta el pollo ayer?",
          "¿Camino el pollo?",
          "¿Me recomienda el pollo?",
          "¿Soy el mesero pollo?",
        ],
        correctIndex: 2,
        explanation: "¿Me recomienda…? with usted.",
        wordCardIds: ["usted-server", "pollo"],
        xp: 4,
      },
      listen(
        "u5l5-4",
        "Me gustaría un café, por favor.",
        ["I like coffee forever only.", "The check is coffee.", "I walked to coffee.", "I would like a coffee, please."],
        3,
        "Me gustaría un café, por favor.",
        ["me-gustaria", "cafe"]
      ),
      {
        id: "u5l5-5",
        type: "translate",
        prompt: "Translate: “Excuse me, could you bring me water?”",
        acceptedAnswers: [
          "Disculpe, ¿me puede traer agua?",
          "Disculpe, me puede traer agua?",
          "Disculpe, ¿me puede traer agua, por favor?",
          "Disculpe, ¿me trae agua, por favor?",
        ],
        hint: "Disculpe + me puede traer…",
        explanation: "Disculpe, ¿me puede traer agua?",
        wordCardIds: ["usted-server", "agua", "disculpe"],
        xp: 4,
      },
      {
        id: "u5l5-6",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I would like a tea, please.",
        template: "Me ___ un té, por favor.",
        acceptedAnswers: ["gustaría", "gustaria", "Gustaría"],
        hint: "I would like",
        explanation: "Me gustaría un té, por favor.",
        wordCardIds: ["me-gustaria", "te"],
        xp: 3,
      },
      {
        id: "u5l5-7",
        type: "match-pairs",
        prompt: "Match polite service Spanish.",
        pairs: [
          { left: "Me gustaría…", right: "I would like…" },
          { left: "¿Me recomienda…?", right: "Do you recommend…?" },
          { left: "mesero", right: "waiter" },
          { left: "Disculpe", right: "Excuse me (polite)" },
        ],
        explanation: "Soft usted toolkit.",
        wordCardIds: ["me-gustaria", "usted-server", "mesero", "disculpe"],
        xp: 4,
      },
      {
        id: "u5l5-8",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "Casual tú order with a friend at a food stall.",
        options: [
          "¿Me puede usted despertar tacos?",
          "Quiero tacos, por favor.",
          "La propina es tacos solamente.",
          "Me levanto tacos.",
        ],
        correctIndex: 1,
        explanation: "With peers / stalls, quiero + por favor is natural.",
        wordCardIds: ["quiero", "tacos"],
        xp: 3,
      },
      listen(
        "u5l5-9",
        "¿Me recomienda algo, por favor?",
        ["Do you like something yesterday?", "Where is rice?", "Could you recommend something, please?", "I shower please."],
        2,
        "¿Me recomienda algo, por favor?",
        ["usted-server"]
      ),
    ],
  },
  "u5-l6": {
    id: "u5-l6",
    unitId: "unit-5",
    title: "Café & drinks",
    description: "Café, jugo, agua, té, leche — order your drink.",
    xpReward: 42,
    exercises: [
      teach("teach-u5l6-agua", "agua"),
      {
        id: "u5l6-1",
        type: "select",
        prompt: "“A water, please” is…",
        options: [
          "La cuenta agua solamente.",
          "Un agua, por favor.",
          "El metro agua.",
          "Me despierto agua.",
        ],
        correctIndex: 1,
        explanation: "Un agua, por favor — el/un with singular agua.",
        wordCardIds: ["agua"],
        xp: 3,
      },
      teach("teach-u5l6-leche", "leche"),
      teach("teach-u5l6-te", "te"),
      {
        id: "u5l6-2",
        type: "tap-chips",
        prompt: "Build: “A coffee with milk, please.”",
        chips: ["Un", "café", "con", "leche,", "por", "favor.", "arroz", "metro"],
        correctOrder: ["Un", "café", "con", "leche,", "por", "favor."],
        explanation: "Un café con leche, por favor.",
        wordCardIds: ["cafe", "leche"],
        xp: 3,
      },
      {
        id: "u5l6-3",
        type: "translate",
        prompt: "Translate: “A tea, please.”",
        acceptedAnswers: [
          "Un té, por favor.",
          "Un te, por favor.",
          "Un té, por favor",
          "Un té por favor.",
        ],
        hint: "Un té…",
        explanation: "Un té, por favor.",
        wordCardIds: ["te"],
        xp: 4,
      },
      listen(
        "u5l6-4",
        "Un café con leche, por favor.",
        ["A check with milk.", "A coffee with milk, please.", "I like rice.", "Turn right."],
        1,
        "Un café con leche, por favor.",
        ["cafe", "leche"]
      ),
      {
        id: "u5l6-5",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "You're thirsty and only want water (tú/counter).",
        options: [
          "Me gusta un agua la cuenta.",
          "Soy agua.",
          "Quiero un agua, por favor.",
          "Lavo agua la oficina.",
        ],
        correctIndex: 2,
        explanation: "Quiero un agua, por favor.",
        wordCardIds: ["quiero", "agua"],
        xp: 3,
      },
      {
        id: "u5l6-6",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "A coffee with milk, please.",
        template: "Un café con ___, por favor.",
        acceptedAnswers: ["leche", "Leche"],
        hint: "milk",
        explanation: "Un café con leche, por favor.",
        wordCardIds: ["cafe", "leche"],
        xp: 3,
      },
      {
        id: "u5l6-7",
        type: "match-pairs",
        prompt: "Match drinks.",
        pairs: [
          { left: "café", right: "coffee" },
          { left: "jugo", right: "juice" },
          { left: "agua", right: "water" },
          { left: "té", right: "tea" },
          { left: "leche", right: "milk" },
        ],
        explanation: "Core drink set.",
        wordCardIds: ["cafe", "jugo", "agua", "te", "leche"],
        xp: 4,
      },
      listen(
        "u5l6-8",
        "¿Tienen jugo natural?",
        ["Do you have a car?", "Where is the kitchen?", "Do you have fresh juice?", "I rest on weekends."],
        2,
        "¿Tienen jugo natural?",
        ["jugo"]
      ),
      {
        id: "u5l6-9",
        type: "select",
        prompt: "“I like tea” is…",
        options: ["Me gustan el té.", "Quiero gusta té.", "La cuenta té.", "Me gusta el té."],
        correctIndex: 3,
        explanation: "Me gusta el té.",
        wordCardIds: ["me-gusta", "te"],
        xp: 3,
      },
    ],
  },

  "u5-l7": {
    id: "u5-l7",
    unitId: "unit-5",
    title: "Restaurant situations",
    description: "Restaurante, para llevar, propina, almuerzo, and cena.",
    xpReward: 44,
    exercises: [
      teach("teach-u5l7-restaurante", "restaurante"),
      {
        id: "u5l7-1",
        type: "select",
        prompt: "“Restaurant” is…",
        options: ["departamento", "oficina", "restaurante", "derecha"],
        correctIndex: 2,
        explanation: "restaurante.",
        wordCardIds: ["restaurante"],
        xp: 3,
      },
      teach("teach-u5l7-para-llevar", "para-llevar"),
      {
        id: "u5l7-2",
        type: "tap-chips",
        prompt: "Build: “To go, please.”",
        chips: ["Para", "llevar,", "por", "favor.", "arroz", "metro"],
        correctOrder: ["Para", "llevar,", "por", "favor."],
        explanation: "Para llevar, por favor.",
        wordCardIds: ["para-llevar"],
        xp: 3,
      },
      teach("teach-u5l7-propina", "propina"),
      teach("teach-u5l7-almuerzo", "almuerzo"),
      teach("teach-u5l7-cena", "cena"),
      {
        id: "u5l7-3",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "Cashier asks if it's for here or to go; you want takeaway.",
        options: [
          "Para la cuenta despertar.",
          "Para llevar, por favor.",
          "Me gusta llevar el metro.",
          "Soy para oficina.",
        ],
        correctIndex: 1,
        explanation: "Para llevar, por favor.",
        wordCardIds: ["para-llevar"],
        xp: 4,
      },
      listen(
        "u5l7-4",
        "¿Dejamos propina?",
        ["Shall we leave the metro?", "Do you like juice?", "Shall we leave a tip?", "Where is downtown?"],
        2,
        "¿Dejamos propina?",
        ["propina"]
      ),
      {
        id: "u5l7-5",
        type: "translate",
        prompt: "Translate: “Let's go to a restaurant.”",
        acceptedAnswers: [
          "Vamos a un restaurante.",
          "Vamos a un restaurante",
        ],
        hint: "Vamos a un…",
        explanation: "Vamos a un restaurante.",
        wordCardIds: ["restaurante", "ir"],
        xp: 4,
      },
      {
        id: "u5l7-6",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "The tip is not included.",
        template: "La ___ no está incluida.",
        acceptedAnswers: ["propina", "Propina"],
        hint: "tip",
        explanation: "La propina no está incluida.",
        wordCardIds: ["propina"],
        xp: 3,
      },
      {
        id: "u5l7-7",
        type: "match-pairs",
        prompt: "Match restaurant words.",
        pairs: [
          { left: "restaurante", right: "restaurant" },
          { left: "para llevar", right: "to go" },
          { left: "propina", right: "tip" },
          { left: "almuerzo", right: "lunch" },
          { left: "cena", right: "dinner" },
        ],
        explanation: "Eating-out situation words.",
        wordCardIds: ["restaurante", "para-llevar", "propina", "almuerzo", "cena"],
        xp: 4,
      },
      {
        id: "u5l7-8",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "It's evening and you suggest dinner out (tú).",
        options: [
          "¿Quieres la oficina en el carro?",
          "¿Me despierto la propina?",
          "¿Camino el menú ayer?",
          "¿Quieres cena en el restaurante?",
        ],
        correctIndex: 3,
        explanation: "¿Quieres cena en el restaurante?",
        wordCardIds: ["cena", "restaurante", "quiero"],
        xp: 3,
      },
      listen(
        "u5l7-9",
        "¿Para llevar o para comer aquí?",
        ["Tip or check only?", "To go or for here?", "Wake up or shower?", "Left or right?"],
        1,
        "¿Para llevar o para comer aquí?",
        ["para-llevar"]
      ),
    ],
  },
  "u5-l8": {
    id: "u5-l8",
    unitId: "unit-5",
    title: "Food review + weak reuse",
    description: "Mix Unit 5 food Spanish with Unit 4 and earlier lemmas.",
    xpReward: 42,
    exercises: [
      {
        id: "u5l8-1",
        type: "translate",
        prompt: "Translate: “I want coffee, please.”",
        acceptedAnswers: [
          "Quiero un café, por favor.",
          "Quiero cafe, por favor.",
          "Quiero un café, por favor",
          "Quiero café, por favor.",
          "Yo quiero un café, por favor.",
        ],
        hint: "Quiero un café…",
        explanation: "Quiero un café, por favor.",
        wordCardIds: ["quiero", "cafe"],
        xp: 4,
      },
      {
        id: "u5l8-2",
        type: "tap-chips",
        prompt: "Build: “I like coffee.”",
        chips: ["Me", "gusta", "el", "café.", "cuenta", "metro"],
        correctOrder: ["Me", "gusta", "el", "café."],
        explanation: "Me gusta el café.",
        wordCardIds: ["me-gusta", "cafe"],
        xp: 3,
      },
      listen(
        "u5l8-3",
        "Trabajo en una oficina.",
        ["I order juice only.", "The tip is included.", "I work in an office.", "Turn left."],
        2,
        "Unit 4 reuse: Trabajo en una oficina.",
        ["trabajar", "oficina"]
      ),
      {
        id: "u5l8-4",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I live in an apartment.",
        template: "Vivo en un ___.",
        acceptedAnswers: ["departamento", "Departamento"],
        hint: "apartment",
        explanation: "Vivo en un departamento — weak reuse from Unit 4.",
        wordCardIds: ["departamento"],
        xp: 3,
      },
      {
        id: "u5l8-5",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "After the meal you need the check (polite).",
        options: [
          "El departamento, por favor.",
          "La cuenta, por favor.",
          "Me levanto, por favor.",
          "Todo recto, por favor.",
        ],
        correctIndex: 1,
        explanation: "La cuenta, por favor.",
        wordCardIds: ["la-cuenta"],
        xp: 3,
      },
      {
        id: "u5l8-6",
        type: "match-pairs",
        prompt: "Mixed match.",
        pairs: [
          { left: "me gusta", right: "I like" },
          { left: "quiero", right: "I want" },
          { left: "la cuenta", right: "the check" },
          { left: "me despierto", right: "I wake up" },
        ],
        explanation: "Food + routine glue.",
        wordCardIds: ["me-gusta", "quiero", "la-cuenta", "despertarse"],
        xp: 4,
      },
      {
        id: "u5l8-7",
        type: "select",
        prompt: "Review: “Thank you” is…",
        options: ["Propina", "Arroz", "Temprano", "Gracias"],
        correctIndex: 3,
        explanation: "Gracias — keep polite basics warm.",
        wordCardIds: ["gracias"],
        xp: 2,
      },
      {
        id: "u5l8-8",
        type: "translate",
        prompt: "Translate: “I would like juice, please.”",
        acceptedAnswers: [
          "Me gustaría un jugo, por favor.",
          "Me gustaria un jugo, por favor.",
          "Me gustaría jugo, por favor.",
          "Me gustaría un jugo por favor.",
        ],
        hint: "Me gustaría…",
        explanation: "Me gustaría un jugo, por favor.",
        wordCardIds: ["me-gustaria", "jugo"],
        xp: 4,
      },
      {
        id: "u5l8-9",
        type: "select",
        prompt: "Word for juice?",
        options: ["cuenta", "oficina", "jugo", "platos"],
        correctIndex: 2,
        explanation: "jugo.",
        wordCardIds: ["jugo"],
        xp: 3,
      },
    ],
  },

  "u5-l9": {
    id: "u5-l9",
    unitId: "unit-5",
    title: "Story: Ordering lunch",
    description: "Listen to a café order story, then answer — plus story cloze drills.",
    xpReward: 45,
    exercises: [
      storyListen(
        "u5l9-story",
        "Pedimos el almuerzo",
        [
          { text: "Entramos a un restaurante cerca del centro.", en: "We go into a restaurant near downtown." },
          { text: "Disculpe, ¿me puede traer un menú?", en: "Excuse me, can you bring me a menu?" },
          { text: "Me gustaría el pollo con arroz, por favor.", en: "I would like the chicken with rice, please." },
          { text: "También quiero un jugo de naranja.", en: "I also want an orange juice." },
          { text: "La comida está muy buena. Gracias.", en: "The food is really good. Thank you." },
          { text: "¿Me trae la cuenta, por favor?", en: "Can you bring me the check, please?" },
        ],
        [
          {
            prompt: "Where is the restaurant?",
            options: ["Only on the metro", "Near downtown", "In the office kitchen", "Far from everything"],
            correctIndex: 1,
            explanation: "cerca del centro.",
          },
          {
            prompt: "What does the speaker order to eat?",
            options: [
              "Only water",
              "Just bread forever",
              "Chicken with rice",
              "Nothing — they leave",
            ],
            correctIndex: 2,
            explanation: "Me gustaría el pollo con arroz.",
          },
          {
            prompt: "What drink do they want?",
            options: ["Only tea", "Orange juice", "Milk alone", "Nothing to drink"],
            correctIndex: 1,
            explanation: "También quiero un jugo de naranja.",
          },
          {
            prompt: "How do they end the meal?",
            options: ["Ask for the metro", "Go to sleep", "Wash clothes", "Ask for the check"],
            correctIndex: 3,
            explanation: "¿Me trae la cuenta, por favor?",
          },
        ],
        ["restaurante", "menu", "me-gustaria", "pollo", "arroz", "jugo", "comida", "la-cuenta", "el-centro"],
        "Ordering story — voices rotate across Neural2 A/B/C.",
        12
      ),
      dictation(
        "u5l9-story-dict-1",
        "Entramos a un restaurante cerca del centro.",
        ["Entramos a un restaurante cerca del centro."],
        "Type the line you heard: Entramos a un restaurante cerca del centro.",
        [],
        { hint: "Replay if needed", voice: "f", xp: 4 }
      ),
      dictation(
        "u5l9-story-dict-2",
        "Disculpe, ¿me puede traer un menú?",
        ["Disculpe, ¿me puede traer un menú?", "Disculpe, me puede traer un menú"],
        "Type the line you heard: Disculpe, ¿me puede traer un menú?",
        [],
        { hint: "Replay if needed", voice: "m", xp: 4 }
      ),
      {
        id: "u5l9-1",
        type: "select",
        prompt: "From the story vibe — polite menu ask was…",
        options: [
          "Oye menú ya.",
          "Disculpe, ¿me puede traer un menú?",
          "Me despierto el menú.",
          "Lavo el menú.",
        ],
        correctIndex: 1,
        explanation: "Disculpe, ¿me puede traer un menú?",
        wordCardIds: ["usted-server", "menu"],
        xp: 3,
      },
      cloze(
        "u5l9-cloze-1",
        "Disculpe, ¿me puede traer un ___?",
        ["menú", "menu", "Menú"],
        "Disculpe, ¿me puede traer un menú?",
        ["menu", "usted-server"],
        {
          hint: "menu",
          audioText: "Disculpe, ¿me puede traer un menú?",
          voice: "f",
        }
      ),
      cloze(
        "u5l9-cloze-2",
        "Me gustaría el pollo con ___, por favor.",
        ["arroz", "Arroz"],
        "Me gustaría el pollo con arroz, por favor.",
        ["me-gustaria", "pollo", "arroz"],
        {
          hint: "rice",
          audioText: "Me gustaría el pollo con arroz, por favor.",
          voice: "m",
        }
      ),
      cloze(
        "u5l9-cloze-3",
        "¿Me trae la ___, por favor?",
        ["cuenta", "Cuenta"],
        "¿Me trae la cuenta, por favor?",
        ["la-cuenta"],
        {
          hint: "the check",
          audioText: "¿Me trae la cuenta, por favor?",
          voice: "c",
        }
      ),
    ],
  },
  "u5-l10": {
    id: "u5-l10",
    unitId: "unit-5",
    title: "More food practice",
    description: "New mixes — drinks, plates, usted, and weak-word reuse.",
    xpReward: 42,
    exercises: [
      {
        id: "u5l10-1",
        type: "translate",
        prompt: "Translate: “I like tacos.”",
        acceptedAnswers: [
          "Me gustan los tacos.",
          "Me gustan los tacos",
          "Me gustan tacos.",
        ],
        hint: "Me gustan…",
        explanation: "Me gustan los tacos.",
        wordCardIds: ["me-gusta", "tacos"],
        xp: 4,
      },
      {
        id: "u5l10-2",
        type: "tap-chips",
        prompt: "Build: “A water, please.”",
        chips: ["Un", "agua,", "por", "favor.", "carro", "platos"],
        correctOrder: ["Un", "agua,", "por", "favor."],
        explanation: "Un agua, por favor.",
        wordCardIds: ["agua"],
        xp: 3,
      },
      listen(
        "u5l10-3",
        "¿Me recomienda el pollo?",
        ["Do you wash the chicken?", "Do you recommend the chicken?", "Where is the tip?", "I study chicken."],
        1,
        "¿Me recomienda el pollo?",
        ["usted-server", "pollo"]
      ),
      {
        id: "u5l10-4",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "To go, please.",
        template: "Para ___, por favor.",
        acceptedAnswers: ["llevar", "Llevar"],
        hint: "to go",
        explanation: "Para llevar, por favor.",
        wordCardIds: ["para-llevar"],
        xp: 3,
      },
      {
        id: "u5l10-5",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "You want a soft polite coffee order.",
        options: [
          "Me gusta un café, por favor.",
          "Me levanto un café.",
          "Me despierto la cuenta café.",
          "Me gustaría un café, por favor.",
        ],
        correctIndex: 3,
        explanation: "Me gustaría un café, por favor.",
        wordCardIds: ["me-gustaria", "cafe"],
        xp: 3,
      },
      {
        id: "u5l10-6",
        type: "match-pairs",
        prompt: "Match.",
        pairs: [
          { left: "un té", right: "a tea" },
          { left: "café con leche", right: "coffee with milk" },
          { left: "almuerzo", right: "lunch" },
          { left: "cena", right: "dinner" },
        ],
        explanation: "Drinks and meals.",
        wordCardIds: ["te", "cafe", "leche", "almuerzo", "cena"],
        xp: 4,
      },
      {
        id: "u5l10-7",
        type: "select",
        prompt: "Review: “Where are you from?” is…",
        options: ["¿Qué pollo eres?", "¿Cómo cuenta eres?", "¿De dónde eres?", "¿Fin de semana eres?"],
        correctIndex: 2,
        explanation: "¿De dónde eres? — earlier-unit classic.",
        wordCardIds: ["de-donde-eres"],
        xp: 2,
      },
      {
        id: "u5l10-8",
        type: "translate",
        prompt: "Translate: “The tip is not included.”",
        acceptedAnswers: [
          "La propina no está incluida.",
          "La propina no esta incluida.",
          "La propina no está incluida",
        ],
        hint: "La propina…",
        explanation: "La propina no está incluida.",
        wordCardIds: ["propina"],
        xp: 4,
      },
      {
        id: "u5l10-9",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "Someone says gracias after you pass the menu.",
        options: ["Me ducho.", "De nada.", "Quiero metros.", "Soy temprano."],
        correctIndex: 1,
        explanation: "De nada.",
        wordCardIds: ["de-nada"],
        xp: 3,
      },
    ],
  },
  "u5-l11": {
    id: "u5-l11",
    unitId: "unit-5",
    title: "Story: Café with a friend",
    description: "A second eating-out story with a different voice mix + cloze.",
    xpReward: 45,
    exercises: [
      storyListen(
        "u5l11-story",
        "Un café con un amigo",
        [
          { text: "Hola, ¿cómo estás? ¿Quieres un café?", en: "Hi, how are you? Do you want a coffee?" },
          { text: "Sí, me gusta el café con leche.", en: "Yes, I like coffee with milk." },
          { text: "Yo quiero un té, por favor.", en: "I want a tea, please." },
          { text: "También pedimos pan. La comida es simple.", en: "We also order bread. The food is simple." },
          { text: "Para llevar el jugo de mi amigo.", en: "To go — my friend's juice." },
          { text: "Pagamos la cuenta y dejamos propina. ¡Hasta luego!", en: "We pay the bill and leave a tip. See you later!" },
        ],
        [
          {
            prompt: "What does the friend like?",
            options: ["Only the check", "The metro", "Washing dishes", "Coffee with milk"],
            correctIndex: 3,
            explanation: "Sí, me gusta el café con leche.",
          },
          {
            prompt: "What does the speaker order?",
            options: ["Only rice", "Nothing", "A car", "Tea"],
            correctIndex: 3,
            explanation: "Yo quiero un té, por favor.",
          },
          {
            prompt: "What else do they ask for?",
            options: ["An apartment", "The office", "Directions only", "Bread"],
            correctIndex: 3,
            explanation: "También pedimos pan.",
          },
          {
            prompt: "How do they finish?",
            options: [
              "Wake up early",
              "Pay the check and leave a tip",
              "Walk to the office silently",
              "Study Spanish only",
            ],
            correctIndex: 1,
            explanation: "Pagamos la cuenta y dejamos propina.",
          },
        ],
        ["cafe", "leche", "te", "pan", "comida", "jugo", "para-llevar", "la-cuenta", "propina", "hola", "como-estas"],
        "Café story — mixed Neural2 voices.",
        12
      ),
      dictation(
        "u5l11-story-dict-1",
        "Hola, ¿cómo estás? ¿Quieres un café?",
        ["Hola, ¿cómo estás? ¿Quieres un café?", "Hola, cómo estás Quieres un café"],
        "Type the line you heard: Hola, ¿cómo estás? ¿Quieres un café?",
        [],
        { hint: "Replay if needed", voice: "f", xp: 4 }
      ),
      dictation(
        "u5l11-story-dict-2",
        "Sí, me gusta el café con leche.",
        ["Sí, me gusta el café con leche."],
        "Type the line you heard: Sí, me gusta el café con leche.",
        [],
        { hint: "Replay if needed", voice: "m", xp: 4 }
      ),
      {
        id: "u5l11-1",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I like coffee with milk.",
        template: "Me gusta el café con ___.",
        acceptedAnswers: ["leche", "Leche"],
        hint: "milk",
        explanation: "Me gusta el café con leche.",
        wordCardIds: ["cafe", "leche", "me-gusta"],
        xp: 3,
      },
      cloze(
        "u5l11-cloze-1",
        "Sí, me gusta el café con ___.",
        ["leche", "Leche"],
        "Sí, me gusta el café con leche.",
        ["cafe", "leche", "me-gusta"],
        {
          hint: "milk",
          audioText: "Sí, me gusta el café con leche.",
          voice: "f",
        }
      ),
      cloze(
        "u5l11-cloze-2",
        "Yo quiero un ___, por favor.",
        ["té", "te", "Té"],
        "Yo quiero un té, por favor.",
        ["te", "quiero"],
        {
          hint: "tea",
          audioText: "Yo quiero un té, por favor.",
          voice: "m",
        }
      ),
      cloze(
        "u5l11-cloze-3",
        "Pagamos la cuenta y dejamos ___.",
        ["propina", "Propina"],
        "Pagamos la cuenta y dejamos propina.",
        ["la-cuenta", "propina"],
        {
          hint: "tip",
          audioText: "Pagamos la cuenta y dejamos propina.",
          voice: "c",
        }
      ),
    ],
  },
  "u5-l12": {
    id: "u5-l12",
    unitId: "unit-5",
    title: "Unit 5 check",
    description: "Mixed review — likes, orders, drinks, restaurant, past units.",
    xpReward: 48,
    exercises: [
      {
        id: "u5l12-1",
        type: "select",
        prompt: "Word for juice?",
        options: ["oficina", "jugo", "platos", "derecha"],
        correctIndex: 1,
        explanation: "jugo.",
        wordCardIds: ["jugo"],
        xp: 3,
      },
      {
        id: "u5l12-2",
        type: "select",
        prompt: "“I like coffee” is…",
        options: ["Quiero gusta café.", "Soy café siempre.", "Me gusta el café.", "La cuenta café."],
        correctIndex: 2,
        explanation: "Me gusta el café.",
        wordCardIds: ["me-gusta", "cafe"],
        xp: 3,
      },
      {
        id: "u5l12-3",
        type: "tap-chips",
        prompt: "Build: “The check, please.”",
        chips: ["La", "cuenta,", "por", "favor.", "ducho", "metro"],
        correctOrder: ["La", "cuenta,", "por", "favor."],
        explanation: "La cuenta, por favor.",
        wordCardIds: ["la-cuenta"],
        xp: 3,
      },
      {
        id: "u5l12-4",
        type: "translate",
        prompt: "Translate: “I would like chicken with rice.”",
        acceptedAnswers: [
          "Me gustaría pollo con arroz.",
          "Me gustaria pollo con arroz.",
          "Me gustaría el pollo con arroz.",
          "Me gustaria el pollo con arroz.",
        ],
        hint: "Me gustaría…",
        explanation: "Me gustaría pollo con arroz.",
        wordCardIds: ["me-gustaria", "pollo", "arroz"],
        xp: 4,
      },
      listen(
        "u5l12-5",
        "Un café con leche, por favor.",
        ["I clean the kitchen only.", "Wake up at seven.", "A coffee with milk, please.", "Turn left downtown."],
        2,
        "Un café con leche, por favor.",
        ["cafe", "leche"]
      ),
      {
        id: "u5l12-6",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "To go, please.",
        template: "Para ___, por favor.",
        acceptedAnswers: ["llevar", "Llevar"],
        hint: "to go",
        explanation: "Para llevar, por favor.",
        wordCardIds: ["para-llevar"],
        xp: 3,
      },
      {
        id: "u5l12-7",
        type: "match-pairs",
        prompt: "Final Unit 5 match.",
        pairs: [
          { left: "me gustan los tacos", right: "I like tacos" },
          { left: "quiero un agua", right: "I want a water" },
          { left: "la propina", right: "the tip" },
          { left: "el menú", right: "the menu" },
        ],
        explanation: "Core Unit 5 lemmas.",
        wordCardIds: ["me-gusta", "tacos", "agua", "propina", "menu"],
        xp: 4,
      },
      {
        id: "u5l12-8",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "Polite ask for a recommendation.",
        options: [
          "¿Me ducho algo?",
          "¿Camino algo la oficina?",
          "¿Me recomienda algo, por favor?",
          "¿Soy algo temprano?",
        ],
        correctIndex: 2,
        explanation: "¿Me recomienda algo, por favor?",
        wordCardIds: ["usted-server"],
        xp: 3,
      },
      {
        id: "u5l12-9",
        type: "select",
        prompt: "Unit 4 reuse: “I get up early” is…",
        options: [
          "Me gusta temprano la cuenta.",
          "Quiero temprano menú.",
          "Soy temprano arroz.",
          "Me levanto temprano.",
        ],
        correctIndex: 3,
        explanation: "Me levanto temprano.",
        wordCardIds: ["levantarse", "temprano"],
        xp: 3,
      },
      {
        id: "u5l12-10",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "You're done helping — they say gracias.",
        options: ["Propina arroz.", "De nada.", "Me despierto menú.", "Todo recto jugo."],
        correctIndex: 1,
        explanation: "De nada.",
        wordCardIds: ["de-nada"],
        xp: 3,
      },
    ],
  },
};

export const UNIT5_LESSON_IDS = [
  "u5-l1",
  "u5-l2",
  "u5-l3",
  "u5-l4",
  "u5-l5",
  "u5-l6",
  "u5-l7",
  "u5-l8",
  "u5-l9",
  "u5-l10",
  "u5-l11",
  "u5-l12",
] as const;
