/**
 * Unit 1 — First contact (lessons 5–12). Spanish.
 * Existing u1-l1…u1-l4 stay in mock-data.ts (audio voice indices stable).
 */
import type { Lesson, WordCard } from "../types";
import { audioSrcFor, voiceForIndex, type AudioVoice } from "../audio";

function teach(
  id: string,
  wordCardId: string
): import("../types").TeachExercise {
  return {
    id,
    type: "teach",
    prompt: "New word — learn it, then practice.",
    explanation: "",
    wordCardId,
    wordCardIds: [wordCardId],
    xp: 0,
  };
}

let listenVoiceIndex = 3000;

function listen(
  id: string,
  audioText: string,
  options: string[],
  correctIndex: number,
  explanation: string,
  wordCardIds: string[],
  xp = 3
): import("../types").ListeningChooseExercise {
  const voice = voiceForIndex(listenVoiceIndex);
  listenVoiceIndex += 1;
  return {
    id,
    type: "listening-choose",
    prompt: "What did you hear?",
    audioText,
    audioSrc: audioSrcFor(audioText, voice),
    options,
    correctIndex,
    explanation,
    wordCardIds,
    xp,
  };
}

function cloze(
  id: string,
  template: string,
  acceptedAnswers: string[],
  explanation: string,
  wordCardIds: string[],
  opts: {
    hint?: string;
    audioText: string;
    voice?: AudioVoice;
    storyLabel?: string;
    xp?: number;
  }
): import("../types").ClozeExercise {
  const voice = opts.voice ?? "f";
  return {
    id,
    type: "cloze",
    prompt: "Fill the blank from the story",
    template,
    acceptedAnswers,
    hint: opts.hint,
    explanation,
    wordCardIds,
    audioText: opts.audioText,
    audioSrc: audioSrcFor(opts.audioText, voice),
    storyLabel: opts.storyLabel ?? "From the story",
    xp: opts.xp ?? 3,
  };
}

function storyListen(
  id: string,
  title: string,
  lines: { text: string; en?: string; voice?: AudioVoice }[],
  questions: {
    prompt: string;
    options: string[];
    correctIndex: number;
    explanation?: string;
  }[],
  wordCardIds: string[],
  explanation = "Story comprehension — replay anytime.",
  xp = 10
): import("../types").StoryListenExercise {
  const withVoices = lines.map((line, i) => ({
    text: line.text,
    en: line.en,
    voice: line.voice ?? voiceForIndex(i),
  }));
  return {
    id,
    type: "story-listen",
    prompt: "Listen to the story, then answer",
    title,
    lines: withVoices,
    questions,
    explanation,
    wordCardIds,
    xp,
  };
}





export const UNIT1_WORD_CARDS: Record<string, WordCard> = {
  bien: {
    id: "bien",
    lemma: "bien",
    pos: "adverb",
    gender: "n/a",
    gloss: "well / fine",
    meaningSummary:
      "The everyday answer to ¿Cómo estás?: Estoy bien / Bien, gracias. Neutral and friendly in everyday Spanish.",
    examples: [
      { es: "Estoy bien, gracias.", en: "I'm fine, thanks." },
      { es: "Todo bien.", en: "All good." },
    ],
    useWhen: "Saying you're doing fine.",
    dontUseWhen: "For 'good' as in good morning, use buenos / buenas with the time of day.",
    contrast: "mal (badly / not well)",
    formality: "neutral",
    cefr: "A1",
  },
  mal: {
    id: "mal",
    lemma: "mal",
    pos: "adverb",
    gender: "n/a",
    gloss: "badly / not well",
    meaningSummary:
      "Opposite of bien: Estoy mal / Me siento mal. Soften with un poco mal if you don't want drama.",
    examples: [
      { es: "Estoy un poco mal.", en: "I'm not feeling great." },
      { es: "Hoy estoy mal.", en: "I'm not doing well today." },
    ],
    useWhen: "Saying you're not okay.",
    dontUseWhen: "Don't use for 'wrong' answers in class — that's incorrecto / equivocado.",
    contrast: "bien",
    formality: "neutral",
    cefr: "A1",
  },
  "nos-vemos": {
    id: "nos-vemos",
    lemma: "nos vemos",
    pos: "phrase",
    gender: "n/a",
    gloss: "see you / see you around",
    meaningSummary:
      "Warm everyday goodbye when you'll meet again. Soft like hasta luego; very common in chats and goodbyes.",
    examples: [
      { es: "Nos vemos mañana.", en: "See you tomorrow." },
      { es: "Okay, nos vemos.", en: "Okay, see you." },
    ],
    useWhen: "Casual farewell when you'll see them again.",
    dontUseWhen: "If it's a long or final goodbye, adiós can fit better.",
    contrast: "hasta luego / adiós",
    formality: "informal",
    cefr: "A1",
  },
  "que-tal": {
    id: "que-tal",
    lemma: "¿qué tal?",
    pos: "phrase",
    gender: "n/a",
    gloss: "how's it going? / how are you?",
    meaningSummary:
      "Super common casual check-in — shorter than ¿cómo estás? Works as hello + how are you in one breath: Hola, ¿qué tal?",
    examples: [
      { es: "Hola, ¿qué tal?", en: "Hi, how's it going?" },
      { es: "¿Qué tal todo?", en: "How's everything?" },
    ],
    useWhen: "Casual greeting with friends, classmates, coworkers you tú with.",
    dontUseWhen: "With clear usted formality, prefer ¿cómo está?",
    contrast: "¿cómo estás?",
    formality: "informal",
    cefr: "A1",
  },
  "por-favor": {
    id: "por-favor",
    lemma: "por favor",
    pos: "phrase",
    gender: "n/a",
    gloss: "please",
    meaningSummary:
      "Softens any request: Un café, por favor. You already know por; this locks the full polite chunk.",
    examples: [
      { es: "Un agua, por favor.", en: "A water, please." },
      { es: "Ayúdame, por favor.", en: "Help me, please." },
    ],
    useWhen: "Polite requests.",
    dontUseWhen: "n/a — hard to overuse in learner Spanish.",
    formality: "neutral",
    cefr: "A1",
  },
};

export const UNIT1_LESSONS: Record<string, Lesson> = {
  "u1-l5": {
    id: "u1-l5",
    unitId: "unit-1",
    title: "How are you?",
    description: "Ask and answer ¿cómo estás? and ¿qué tal? (tú first).",
    xpReward: 30,
    exercises: [
      teach("teach-u1l5-como-estas", "como-estas"),
      {
        id: "u1l5-1",
        type: "select",
        prompt: "How do you casually ask “How are you?” (tú)",
        options: ["¿Cómo estás?", "¿Cómo está?", "¿Qué llamas?", "¿De dónde eres?"],
        correctIndex: 0,
        explanation: "¿Cómo estás? is tú. ¿Cómo está? is usted.",
        wordCardIds: ["como-estas"],
        xp: 3,
      },
      teach("teach-u1l5-que-tal", "que-tal"),
      {
        id: "u1l5-2",
        type: "select",
        prompt: "Which short check-in means “How’s it going?”",
        options: ["¿Qué tal?", "¿Qué caro?", "De nada", "Mucho gusto"],
        correctIndex: 0,
        explanation: "¿Qué tal? is a quick casual “how’s it going?”",
        wordCardIds: ["que-tal"],
        xp: 3,
      },
      teach("teach-u1l5-bien", "bien"),
      teach("teach-u1l5-mal", "mal"),
      {
        id: "u1l5-3",
        type: "situational-choose",
        prompt: "Pick the best reply.",
        situation: "A friend asks: “¿Cómo estás?” You’re fine.",
        options: ["Estoy bien, gracias.", "Soy bien, gracias.", "Estoy mal días.", "Me llamo bien."],
        correctIndex: 0,
        explanation: "Estoy bien, gracias — use estar for how you feel right now.",
        wordCardIds: ["bien", "como-estas"],
        xp: 3,
      },
      {
        id: "u1l5-4",
        type: "tap-chips",
        prompt: "Build: “Hi, how are you?”",
        chips: ["Hola,", "¿cómo", "estás?", "soy", "mal", "días"],
        correctOrder: ["Hola,", "¿cómo", "estás?"],
        explanation: "Hola, ¿cómo estás? — classic tú greeting.",
        wordCardIds: ["hola", "como-estas"],
        xp: 4,
      },
      listen(
        "u1l5-5",
        "Hola, ¿cómo estás?",
        ["Hi, how are you?", "What's your name?", "Good night", "You're welcome"],
        0,
        "Hola, ¿cómo estás? = Hi, how are you?",
        ["hola", "como-estas"]
      ),
      {
        id: "u1l5-6",
        type: "fill-blank",
        prompt: "Complete the Spanish.",
        template: "Estoy ___, gracias.",
        englishPrompt: "I'm fine, thanks.",
        acceptedAnswers: ["bien", "Bien"],
        hint: "well / fine",
        explanation: "Estoy bien, gracias.",
        wordCardIds: ["bien"],
        xp: 3,
      },
      {
        id: "u1l5-7",
        type: "translate",
        prompt: "Translate to Spanish: “How’s it going?”",
        acceptedAnswers: ["qué tal", "que tal", "¿qué tal?", "hola qué tal", "hola, qué tal"],
        hint: "Two short words.",
        explanation: "¿Qué tal? is the quick casual check-in.",
        wordCardIds: ["que-tal"],
        xp: 3,
      },
      {
        id: "u1l5-match",
        type: "match-pairs",
        prompt: "Match the check-ins and replies.",
        pairs: [
          { left: "¿Cómo estás?", right: "How are you? (tú)" },
          { left: "¿Qué tal?", right: "How's it going?" },
          { left: "Estoy bien", right: "I'm fine" },
          { left: "Estoy mal", right: "I'm not well" },
        ],
        explanation: "Core how-are-you toolkit.",
        wordCardIds: ["como-estas", "que-tal", "bien", "mal"],
        xp: 4,
      },
    ],
  },

  "u1-l6": {
    id: "u1-l6",
    unitId: "unit-1",
    title: "Please & polite asks",
    description: "Lock por favor, gracias, and soft attention-getters.",
    xpReward: 28,
    exercises: [
      teach("teach-u1l6-por-favor", "por-favor"),
      {
        id: "u1l6-1",
        type: "select",
        prompt: "Which phrase means “please”?",
        options: ["Por favor", "De nada", "Hasta luego", "Mucho gusto"],
        correctIndex: 0,
        explanation: "Por favor softens requests.",
        wordCardIds: ["por-favor", "por"],
        xp: 3,
      },
      {
        id: "u1l6-2",
        type: "tap-chips",
        prompt: "Build: “A coffee, please.”",
        chips: ["Un", "café,", "por", "favor", "carro", "mal"],
        correctOrder: ["Un", "café,", "por", "favor"],
        explanation: "Un café, por favor.",
        wordCardIds: ["por-favor"],
        xp: 4,
      },
      {
        id: "u1l6-3",
        type: "situational-choose",
        prompt: "Best polite opener to get someone’s attention?",
        situation: "You need to ask a stranger for help in a store.",
        options: ["Disculpe…", "Adiós…", "Estoy mal…", "Nos vemos…"],
        correctIndex: 0,
        explanation: "Disculpe is the polite usted attention-getter.",
        wordCardIds: ["disculpe"],
        xp: 3,
      },
      listen(
        "u1l6-4",
        "Un café, por favor",
        ["A coffee, please", "Thank you", "See you later", "My name is"],
        0,
        "Un café, por favor = A coffee, please.",
        ["por-favor"]
      ),
      {
        id: "u1l6-5",
        type: "fill-blank",
        prompt: "Complete the Spanish.",
        template: "Gracias. — De ___.",
        englishPrompt: "Thank you. — You're welcome.",
        acceptedAnswers: ["nada", "Nada"],
        hint: "you're welcome",
        explanation: "—Gracias. —De nada.",
        wordCardIds: ["gracias", "de-nada"],
        xp: 3,
      },
      {
        id: "u1l6-6",
        type: "translate",
        prompt: "Translate to Spanish: “Please.”",
        acceptedAnswers: ["por favor", "Por favor"],
        hint: "Two words.",
        explanation: "Por favor.",
        wordCardIds: ["por-favor"],
        xp: 3,
      },
      {
        id: "u1l6-7",
        type: "select",
        prompt: "You bump into someone lightly. Soft apology?",
        options: ["Perdón", "Buenos días", "Soy de México", "Veinte"],
        correctIndex: 0,
        explanation: "Perdón covers light “excuse me / sorry.”",
        wordCardIds: ["perdon"],
        xp: 3,
      },
      {
        id: "u1l6-8",
        type: "situational-choose",
        prompt: "Choose the natural reply.",
        situation: "The barista says “¡Gracias!” after you pay.",
        options: ["De nada", "¿Cómo te llamas?", "Cuesta diez", "Estoy mal"],
        correctIndex: 0,
        explanation: "De nada answers gracias.",
        wordCardIds: ["de-nada"],
        xp: 3,
      },
      {
        id: "u1l6-match",
        type: "match-pairs",
        prompt: "Match polite essentials.",
        pairs: [
          { left: "Por favor", right: "Please" },
          { left: "Gracias", right: "Thank you" },
          { left: "De nada", right: "You're welcome" },
          { left: "Perdón", right: "Excuse me / sorry" },
        ],
        explanation: "Polite core set.",
        wordCardIds: ["por-favor", "gracias", "de-nada", "perdon"],
        xp: 4,
      },
    ],
  },

  "u1-l7": {
    id: "u1-l7",
    unitId: "unit-1",
    title: "Short dialogues",
    description: "String greeting + name + how-are-you into tiny chats.",
    xpReward: 32,
    exercises: [
      {
        id: "u1l7-1",
        type: "situational-choose",
        prompt: "Best first line?",
        situation: "You meet a classmate for the first time in the morning.",
        options: [
          "Buenos días. ¿Cómo te llamas?",
          "Cuesta veinte pesos.",
          "Estoy mal, adiós.",
          "Hablo cero.",
        ],
        correctIndex: 0,
        explanation: "Morning greeting + name question is a perfect first contact.",
        wordCardIds: ["buenos-dias", "como-te-llamas"],
        xp: 3,
      },
      {
        id: "u1l7-2",
        type: "tap-chips",
        prompt: "Build: “Hi, my name is Sofía.”",
        chips: ["Hola,", "me", "llamo", "Sofía", "vivo", "diez"],
        correctOrder: ["Hola,", "me", "llamo", "Sofía"],
        explanation: "Hola, me llamo Sofía.",
        wordCardIds: ["hola", "me-llamo"],
        xp: 4,
      },
      {
        id: "u1l7-3",
        type: "select",
        prompt: "After “Me llamo Ana,” a warm reply is:",
        options: ["Mucho gusto", "Cuánto cuesta", "Soy celular", "Gratis"],
        correctIndex: 0,
        explanation: "Mucho gusto = nice to meet you.",
        wordCardIds: ["mucho-gusto"],
        xp: 3,
      },
      listen(
        "u1l7-4",
        "Mucho gusto",
        ["Nice to meet you", "How much is it?", "Good night", "I speak English"],
        0,
        "Mucho gusto = nice to meet you.",
        ["mucho-gusto"]
      ),
      {
        id: "u1l7-5",
        type: "fill-blank",
        prompt: "Complete the Spanish.",
        template: "Hola, ¿cómo ___?",
        englishPrompt: "Hi, how are you?",
        acceptedAnswers: ["estás", "estas", "Estás"],
        hint: "you are (tú)",
        explanation: "Hola, ¿cómo estás?",
        wordCardIds: ["como-estas"],
        xp: 3,
      },
      {
        id: "u1l7-6",
        type: "translate",
        prompt: "Translate to Spanish: “Nice to meet you.”",
        acceptedAnswers: ["mucho gusto", "Mucho gusto", "¡mucho gusto!"],
        hint: "Two words.",
        explanation: "Mucho gusto.",
        wordCardIds: ["mucho-gusto"],
        xp: 3,
      },
      {
        id: "u1l7-7",
        type: "situational-choose",
        prompt: "Ending the chat until tomorrow:",
        situation: "You’re leaving and will see your friend tomorrow.",
        options: ["Nos vemos mañana.", "Soy de mañana.", "Cuesta mañana.", "Perdón mañana."],
        correctIndex: 0,
        explanation: "Nos vemos mañana is warm and natural.",
        wordCardIds: ["nos-vemos"],
        xp: 3,
      },
      teach("teach-u1l7-nos-vemos", "nos-vemos"),
      {
        id: "u1l7-8",
        type: "select",
        prompt: "Nos vemos is closest to:",
        options: ["See you", "How old are you?", "Please", "I'm from"],
        correctIndex: 0,
        explanation: "Nos vemos ≈ see you / see you around.",
        wordCardIds: ["nos-vemos"],
        xp: 3,
      },
      {
        id: "u1l7-match",
        type: "match-pairs",
        prompt: "Match dialogue lines.",
        pairs: [
          { left: "¿Cómo te llamas?", right: "What's your name?" },
          { left: "Me llamo Ana", right: "My name is Ana" },
          { left: "Mucho gusto", right: "Nice to meet you" },
          { left: "Nos vemos", right: "See you" },
        ],
        explanation: "Mini dialogue spine.",
        wordCardIds: ["como-te-llamas", "me-llamo", "mucho-gusto", "nos-vemos"],
        xp: 4,
      },
    ],
  },

  "u1-l8": {
    id: "u1-l8",
    unitId: "unit-1",
    title: "Meeting people review",
    description: "Mix greetings, names, politeness, and how-are-you.",
    xpReward: 30,
    exercises: [
      {
        id: "u1l8-1",
        type: "select",
        prompt: "Afternoon hello:",
        options: ["Buenas tardes", "Buenos días", "Buenas noches", "Adiós días"],
        correctIndex: 0,
        explanation: "Afternoon → buenas tardes.",
        wordCardIds: ["buenas-tardes"],
        xp: 3,
      },
      {
        id: "u1l8-2",
        type: "tap-chips",
        prompt: "Build: “See you later.”",
        chips: ["Hasta", "luego", "días", "mal", "celular"],
        correctOrder: ["Hasta", "luego"],
        explanation: "Hasta luego.",
        wordCardIds: ["hasta-luego"],
        xp: 4,
      },
      {
        id: "u1l8-3",
        type: "situational-choose",
        prompt: "Best line?",
        situation: "Someone says “Mucho gusto.” You reply warmly.",
        options: ["Igualmente / Mucho gusto.", "Cuesta diez.", "Hablo pesos.", "Soy gratis."],
        correctIndex: 0,
        explanation: "Igualmente or repeating Mucho gusto both work.",
        wordCardIds: ["mucho-gusto"],
        xp: 3,
      },
      listen(
        "u1l8-4",
        "¿Qué tal?",
        ["How's it going?", "How much?", "Good morning", "My phone"],
        0,
        "¿Qué tal? = how's it going?",
        ["que-tal"]
      ),
      {
        id: "u1l8-5",
        type: "fill-blank",
        prompt: "Complete the Spanish.",
        template: "Me ___ Carlos.",
        englishPrompt: "My name is Carlos.",
        acceptedAnswers: ["llamo", "Llamo"],
        hint: "I call myself…",
        explanation: "Me llamo Carlos.",
        wordCardIds: ["me-llamo"],
        xp: 3,
      },
      {
        id: "u1l8-6",
        type: "translate",
        prompt: "Translate to Spanish: “Thank you.”",
        acceptedAnswers: ["gracias", "Gracias", "¡gracias!", "muchas gracias"],
        hint: "Everyday thanks.",
        explanation: "Gracias.",
        wordCardIds: ["gracias"],
        xp: 3,
      },
      {
        id: "u1l8-7",
        type: "select",
        prompt: "Which is more final-sounding goodbye?",
        options: ["Adiós", "Hola", "Por favor", "Sí"],
        correctIndex: 0,
        explanation: "Adiós can feel more final than hasta luego / nos vemos.",
        wordCardIds: ["adios"],
        xp: 3,
      },
      {
        id: "u1l8-8",
        type: "situational-choose",
        prompt: "Evening farewell before bed:",
        situation: "You're leaving a family dinner late.",
        options: ["Buenas noches", "Buenos días", "Cuánto cuesta", "Tengo veinte"],
        correctIndex: 0,
        explanation: "Buenas noches works as evening hello or good-night goodbye.",
        wordCardIds: ["buenas-noches"],
        xp: 3,
      },
    ],
  },

  "u1-l9": {
    id: "u1-l9",
    unitId: "unit-1",
    title: "Story: Café hello",
    description: "A simple first-meeting story — listen, answer, then cloze.",
    xpReward: 40,
    exercises: [
      storyListen(
        "u1l9-story",
        "En el café",
        [
          { text: "Hola, buenos días.", en: "Hello, good morning." },
          { text: "Hola, ¿cómo te llamas?", en: "Hi, what's your name?" },
          { text: "Me llamo Sofía. ¿Y tú?", en: "My name is Sofía. And you?" },
          { text: "Me llamo Mateo. Mucho gusto.", en: "My name is Mateo. Nice to meet you." },
          { text: "Mucho gusto. ¿Cómo estás?", en: "Nice to meet you. How are you?" },
          { text: "Estoy bien, gracias. Nos vemos.", en: "I'm fine, thanks. See you." },
        ],
        [
          {
            prompt: "Where does this chat feel like it happens?",
            options: ["A quick café hello", "Buying a car only", "A math exam", "A phone bill"],
            correctIndex: 0,
            explanation: "Simple café-style first contact.",
          },
          {
            prompt: "What is her name?",
            options: ["Ana", "Sofía", "Carlos", "Luz"],
            correctIndex: 1,
            explanation: "Me llamo Sofía.",
          },
          {
            prompt: "How does he feel?",
            options: ["He's fine", "He needs pesos", "He is twenty", "He says goodbye only"],
            correctIndex: 0,
            explanation: "Estoy bien, gracias.",
          },
          {
            prompt: "How do they wrap up?",
            options: ["Nos vemos", "Cuesta diez", "Hablo inglés", "Soy gratis"],
            correctIndex: 0,
            explanation: "Nos vemos.",
          },
        ],
        ["hola", "buenos-dias", "como-te-llamas", "me-llamo", "mucho-gusto", "como-estas", "bien", "nos-vemos"],
        "First-contact story — voices rotate across Neural2 A/B/C.",
        12
      ),
      cloze(
        "u1l9-cloze-1",
        "Hola, ¿cómo te ___?",
        ["llamas", "Llamas"],
        "Hola, ¿cómo te llamas?",
        ["como-te-llamas"],
        { hint: "what's your name verb", audioText: "Hola, ¿cómo te llamas?", voice: "f" }
      ),
      cloze(
        "u1l9-cloze-2",
        "Me ___ Sofía.",
        ["llamo", "Llamo"],
        "Me llamo Sofía.",
        ["me-llamo"],
        { hint: "my name is", audioText: "Me llamo Sofía.", voice: "m" }
      ),
      cloze(
        "u1l9-cloze-3",
        "Estoy ___, gracias.",
        ["bien", "Bien"],
        "Estoy bien, gracias.",
        ["bien"],
        { hint: "fine", audioText: "Estoy bien, gracias.", voice: "c" }
      ),
    ],
  },

  "u1-l10": {
    id: "u1-l10",
    unitId: "unit-1",
    title: "More greeting practice",
    description: "Extra reps on time-of-day greetings and soft goodbyes.",
    xpReward: 28,
    exercises: [
      {
        id: "u1l10-1",
        type: "select",
        prompt: "It’s 10 a.m. Best greeting?",
        options: ["Buenos días", "Buenas noches", "Adiós", "Cuánto"],
        correctIndex: 0,
        explanation: "Morning → buenos días.",
        wordCardIds: ["buenos-dias"],
        xp: 3,
      },
      {
        id: "u1l10-2",
        type: "select",
        prompt: "It’s 8 p.m. Best greeting?",
        options: ["Buenas noches", "Buenos días", "Por favor", "Tengo"],
        correctIndex: 0,
        explanation: "Evening → buenas noches.",
        wordCardIds: ["buenas-noches"],
        xp: 3,
      },
      {
        id: "u1l10-3",
        type: "tap-chips",
        prompt: "Build: “Good afternoon.”",
        chips: ["Buenas", "tardes", "días", "mal", "sí"],
        correctOrder: ["Buenas", "tardes"],
        explanation: "Buenas tardes.",
        wordCardIds: ["buenas-tardes"],
        xp: 4,
      },
      listen(
        "u1l10-4",
        "Nos vemos mañana",
        ["See you tomorrow", "How are you?", "Thank you", "My name is"],
        0,
        "Nos vemos mañana = see you tomorrow.",
        ["nos-vemos"]
      ),
      {
        id: "u1l10-5",
        type: "fill-blank",
        prompt: "Complete the Spanish.",
        template: "Hasta ___.",
        englishPrompt: "See you later.",
        acceptedAnswers: ["luego", "Luego"],
        hint: "later",
        explanation: "Hasta luego.",
        wordCardIds: ["hasta-luego"],
        xp: 3,
      },
      {
        id: "u1l10-6",
        type: "translate",
        prompt: "Translate to Spanish: “Hello.”",
        acceptedAnswers: ["hola", "Hola", "¡hola!"],
        hint: "One word.",
        explanation: "Hola.",
        wordCardIds: ["hola"],
        xp: 3,
      },
      {
        id: "u1l10-7",
        type: "situational-choose",
        prompt: "Soft exit when you’ll hang out soon:",
        situation: "Leaving a friend’s place after lunch.",
        options: ["Hasta luego", "Soy de Estados Unidos", "Tengo un celular", "Cuesta gratis"],
        correctIndex: 0,
        explanation: "Hasta luego fits a soon-again goodbye.",
        wordCardIds: ["hasta-luego"],
        xp: 3,
      },
      {
        id: "u1l10-8",
        type: "match-pairs",
        prompt: "Match greetings.",
        pairs: [
          { left: "Buenos días", right: "Good morning" },
          { left: "Buenas tardes", right: "Good afternoon" },
          { left: "Buenas noches", right: "Good evening / night" },
          { left: "Nos vemos", right: "See you" },
        ],
        explanation: "Time-of-day + soft goodbye.",
        wordCardIds: ["buenos-dias", "buenas-tardes", "buenas-noches", "nos-vemos"],
        xp: 4,
      },
    ],
  },

  "u1-l11": {
    id: "u1-l11",
    unitId: "unit-1",
    title: "Story: Hello & goodbye",
    description: "Another short story — greet, chat, thank, leave.",
    xpReward: 40,
    exercises: [
      storyListen(
        "u1l11-story",
        "Hasta luego",
        [
          { text: "Buenas tardes.", en: "Good afternoon." },
          { text: "Buenas tardes. ¿Qué tal?", en: "Good afternoon. How's it going?" },
          { text: "Bien, gracias. ¿Y tú?", en: "Good, thanks. And you?" },
          { text: "También bien.", en: "Also good." },
          { text: "Gracias por tu ayuda.", en: "Thanks for your help." },
          { text: "De nada. Hasta luego.", en: "You're welcome. See you later." },
        ],
        [
          {
            prompt: "What time of day fits the greeting?",
            options: ["Afternoon", "Only midnight math class", "Breakfast only", "No greeting given"],
            correctIndex: 0,
            explanation: "Buenas tardes = afternoon.",
          },
          {
            prompt: "How is the first speaker?",
            options: ["Fine, thanks", "Buying dollars", "Asking for a phone", "Saying adiós only"],
            correctIndex: 0,
            explanation: "Bien, gracias.",
          },
          {
            prompt: "What does the helper say after thanks?",
            options: ["De nada", "Me llamo", "Cuesta veinte", "Hablo español"],
            correctIndex: 0,
            explanation: "De nada.",
          },
          {
            prompt: "Final goodbye in the story?",
            options: ["Hasta luego", "Buenos días", "Soy de México", "Tengo diez"],
            correctIndex: 0,
            explanation: "Hasta luego.",
          },
        ],
        ["buenas-tardes", "que-tal", "bien", "gracias", "de-nada", "hasta-luego"],
        "Hello-and-goodbye story with thanks.",
        12
      ),
      cloze(
        "u1l11-cloze-1",
        "Buenas ___.",
        ["tardes", "Tardes"],
        "Buenas tardes.",
        ["buenas-tardes"],
        { hint: "afternoon", audioText: "Buenas tardes.", voice: "f" }
      ),
      cloze(
        "u1l11-cloze-2",
        "De ___.",
        ["nada", "Nada"],
        "De nada.",
        ["de-nada"],
        { hint: "you're welcome", audioText: "De nada.", voice: "m" }
      ),
      cloze(
        "u1l11-cloze-3",
        "Hasta ___.",
        ["luego", "Luego"],
        "Hasta luego.",
        ["hasta-luego"],
        { hint: "later", audioText: "Hasta luego.", voice: "c" }
      ),
    ],
  },

  "u1-l12": {
    id: "u1-l12",
    unitId: "unit-1",
    title: "Unit 1 check",
    description: "Prove your first-contact toolkit: greet, name, polite, check-in.",
    xpReward: 35,
    exercises: [
      {
        id: "u1l12-1",
        type: "select",
        prompt: "Friendly hello any time of day:",
        options: ["Hola", "Cuesta", "Veinte", "Celular"],
        correctIndex: 0,
        explanation: "Hola.",
        wordCardIds: ["hola"],
        xp: 3,
      },
      {
        id: "u1l12-2",
        type: "select",
        prompt: "Ask someone’s name (tú):",
        options: ["¿Cómo te llamas?", "¿Cuánto cuesta?", "¿Cuántos años tienes?", "¿Hablas pesos?"],
        correctIndex: 0,
        explanation: "¿Cómo te llamas?",
        wordCardIds: ["como-te-llamas"],
        xp: 3,
      },
      {
        id: "u1l12-3",
        type: "tap-chips",
        prompt: "Build: “I'm fine, thanks.”",
        chips: ["Estoy", "bien,", "gracias", "mal", "carro"],
        correctOrder: ["Estoy", "bien,", "gracias"],
        explanation: "Estoy bien, gracias.",
        wordCardIds: ["bien", "gracias"],
        xp: 4,
      },
      {
        id: "u1l12-4",
        type: "translate",
        prompt: "Translate to Spanish: “Please.”",
        acceptedAnswers: ["por favor", "Por favor"],
        hint: "Polite request softener.",
        explanation: "Por favor.",
        wordCardIds: ["por-favor"],
        xp: 3,
      },
      {
        id: "u1l12-5",
        type: "fill-blank",
        prompt: "Complete the Spanish.",
        template: "___ gusto.",
        englishPrompt: "Nice to meet you.",
        acceptedAnswers: ["Mucho", "mucho"],
        hint: "nice to meet you",
        explanation: "Mucho gusto.",
        wordCardIds: ["mucho-gusto"],
        xp: 3,
      },
      {
        id: "u1l12-6",
        type: "situational-choose",
        prompt: "Best soft goodbye:",
        situation: "You’ll see your coworker after lunch.",
        options: ["Nos vemos", "Soy gratis", "Tengo México", "Hablo perdón"],
        correctIndex: 0,
        explanation: "Nos vemos.",
        wordCardIds: ["nos-vemos"],
        xp: 3,
      },
      listen(
        "u1l12-7",
        "¿Cómo estás?",
        ["How are you?", "How much is it?", "Where are you from?", "What's your number?"],
        0,
        "¿Cómo estás? = how are you?",
        ["como-estas"]
      ),
      {
        id: "u1l12-match",
        type: "match-pairs",
        prompt: "Final Unit 1 matches.",
        pairs: [
          { left: "Gracias", right: "Thank you" },
          { left: "De nada", right: "You're welcome" },
          { left: "Perdón", right: "Excuse me / sorry" },
          { left: "¿Qué tal?", right: "How's it going?" },
        ],
        explanation: "Unit 1 polite + check-in set.",
        wordCardIds: ["gracias", "de-nada", "perdon", "que-tal"],
        xp: 4,
      },
    ],
  },
};
