/**
 * Unit 7 — What I did (~12 lessons). Past tense / past focus. Spanish.
 * Merged via intermediate.ts into mock-data.
 */
import type { Lesson, WordCard } from "../types";
import { audioSrcFor, voiceForIndex, type AudioVoice } from "../audio";

const LATAM_PRETERITE = (forms: [string, string, string, string, string]) => [
  {
    label: "Past tense",
    forms: [
      { person: "yo", form: forms[0] },
      { person: "tú", form: forms[1] },
      { person: "él/ella/usted", form: forms[2] },
      { person: "nosotros/as", form: forms[3] },
      { person: "ustedes", form: forms[4] },
    ],
  },
];

function teach(
  id: string,
  wordCardId: string
): import("../types").TeachExercise {
  return {
    id,
    type: "teach",
    prompt: "New word — learn it, then practice.",
    explanation: "",
    wordCardId,
    wordCardIds: [wordCardId],
    xp: 0,
  };
}

let listenVoiceIndex = 700;

function listen(
  id: string,
  audioText: string,
  options: string[],
  correctIndex: number,
  explanation: string,
  wordCardIds: string[],
  xp = 3,
  hint?: string
): import("../types").ListeningChooseExercise {
  const voice = voiceForIndex(listenVoiceIndex);
  listenVoiceIndex += 1;
  return {
    id,
    type: "listening-choose",
    prompt: "What did you hear?",
    audioText,
    audioSrc: audioSrcFor(audioText, voice),
    options,
    correctIndex,
    explanation,
    wordCardIds,
    hint,
    xp,
  };
}

function cloze(
  id: string,
  template: string,
  acceptedAnswers: string[],
  explanation: string,
  wordCardIds: string[],
  opts: {
    hint?: string;
    audioText: string;
    voice?: AudioVoice;
    storyLabel?: string;
    xp?: number;
  }
): import("../types").ClozeExercise {
  const voice = opts.voice ?? "f";
  return {
    id,
    type: "cloze",
    prompt: "Fill the blank from the story",
    template,
    acceptedAnswers,
    hint: opts.hint,
    explanation,
    wordCardIds,
    audioText: opts.audioText,
    audioSrc: audioSrcFor(opts.audioText, voice),
    storyLabel: opts.storyLabel ?? "From the story",
    xp: opts.xp ?? 3,
  };
}

function storyListen(
  id: string,
  title: string,
  lines: { text: string; en?: string; voice?: AudioVoice }[],
  questions: {
    prompt: string;
    options: string[];
    correctIndex: number;
    explanation?: string;
  }[],
  wordCardIds: string[],
  explanation = "Story comprehension — replay anytime.",
  xp = 10
): import("../types").StoryListenExercise {
  const withVoices = lines.map((line) => ({
    text: line.text,
    en: line.en,
    // No per-line rotation: the player picks one narrator per story
    // (narratorVoiceFor) unless a line sets its own voice.
    voice: line.voice,
  }));
  return {
    id,
    type: "story-listen",
    prompt: "Listen to the story, then answer",
    title,
    lines: withVoices,
    questions,
    explanation,
    wordCardIds,
    xp,
  };
}


function dictation(
  id: string,
  audioText: string,
  acceptedAnswers: string[],
  explanation: string,
  wordCardIds: string[],
  opts: { hint?: string; voice?: AudioVoice; xp?: number } = {}
): import("../types").DictationExercise {
  const voice = opts.voice ?? "f";
  return {
    id,
    type: "dictation",
    prompt: "Type what you hear",
    audioText,
    audioSrc: audioSrcFor(audioText, voice),
    acceptedAnswers,
    hint: opts.hint,
    explanation,
    wordCardIds,
    xp: opts.xp ?? 4,
  };
}

function conjugate(
  id: string,
  infinitive: string,
  pronoun: string,
  tense: string,
  acceptedAnswers: string[],
  explanation: string,
  wordCardIds: string[],
  opts: { hint?: string; xp?: number } = {}
): import("../types").ConjugateExercise {
  return {
    id,
    type: "conjugate",
    prompt: `Conjugate: ${pronoun} + ${infinitive} (${tense})`,
    infinitive,
    pronoun,
    tense,
    acceptedAnswers,
    hint: opts.hint,
    explanation,
    wordCardIds,
    xp: opts.xp ?? 3,
  };
}

export const UNIT7_WORD_CARDS: Record<string, WordCard> = {
  anoche: {
    id: "anoche",
    lemma: "anoche",
    pos: "adverb",
    gender: "n/a",
    gloss: "last night",
    meaningSummary:
      "Time anchor for last night — pairs naturally with past tense: Anoche comí / Anoche fui al cine.",
    examples: [
      { es: "Anoche comí tacos.", en: "Last night I ate tacos." },
      { es: "¿Qué hiciste anoche?", en: "What did you do last night?" },
    ],
    useWhen: "Completed actions last night.",
    dontUseWhen: "For 'yesterday' use ayer; for tonight's plans use esta noche.",
    contrast: "ayer / hoy / esta noche",
    formality: "neutral",
    cefr: "A2",
  },
  "esta-manana": {
    id: "esta-manana",
    lemma: "esta mañana",
    pos: "phrase",
    gender: "n/a",
    gloss: "this morning",
    meaningSummary:
      "Timeline phrase for earlier today. Esta mañana desayuné / Esta mañana fui al trabajo.",
    examples: [
      { es: "Esta mañana desayuné café.", en: "This morning I had coffee for breakfast." },
      { es: "Esta mañana trabajé en casa.", en: "This morning I worked at home." },
    ],
    useWhen: "Situating a finished action earlier today.",
    dontUseWhen: "For tomorrow morning say mañana por la mañana.",
    contrast: "anoche / ayer / hoy",
    formality: "neutral",
    cefr: "A2",
  },
  "trabajar-preterite": {
    id: "trabajar-preterite",
    lemma: "trabajar (past tense)",
    pos: "verb",
    gender: "n/a",
    gloss: "to work (past)",
    meaningSummary:
      "Regular -ar past tense: trabajé, trabajaste, trabajó, trabajamos, trabajaron.",
    conjugations: LATAM_PRETERITE([
      "trabajé",
      "trabajaste",
      "trabajó",
      "trabajamos",
      "trabajaron",
    ]),
    examples: [
      { es: "Ayer trabajé hasta tarde.", en: "Yesterday I worked until late." },
      { es: "¿Trabajaste hoy?", en: "Did you work today?" },
    ],
    useWhen: "Completed work days in the past.",
    dontUseWhen: "For habits over time you'll later use past (ongoing) (trabajaba).",
    formality: "neutral",
    cefr: "A2",
  },
  "vivir-preterite": {
    id: "vivir-preterite",
    lemma: "vivir (past tense)",
    pos: "verb",
    gender: "n/a",
    gloss: "to live (past)",
    meaningSummary:
      "Regular -ir past tense: viví, viviste, vivió, vivimos, vivieron. Useful for 'I lived in…' stories.",
    conjugations: LATAM_PRETERITE([
      "viví",
      "viviste",
      "vivió",
      "vivimos",
      "vivieron",
    ]),
    examples: [
      { es: "Viví en México dos años.", en: "I lived in Mexico for two years." },
      { es: "¿Dónde viviste antes?", en: "Where did you live before?" },
    ],
    useWhen: "Completed periods of living somewhere.",
    dontUseWhen: "For where you live now use present: Vivo en…",
    formality: "neutral",
    cefr: "A2",
  },
  "estudiar-preterite": {
    id: "estudiar-preterite",
    lemma: "estudiar (past tense)",
    pos: "verb",
    gender: "n/a",
    gloss: "to study (past)",
    meaningSummary:
      "Regular -ar past tense: estudié, estudiaste, estudió, estudiamos, estudiaron.",
    conjugations: LATAM_PRETERITE([
      "estudié",
      "estudiaste",
      "estudió",
      "estudiamos",
      "estudiaron",
    ]),
    examples: [
      { es: "Anoche estudié español.", en: "Last night I studied Spanish." },
      { es: "¿Estudiaste ayer?", en: "Did you study yesterday?" },
    ],
    useWhen: "Finished study sessions.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A2",
  },
  "venir-preterite": {
    id: "venir-preterite",
    lemma: "venir (past tense)",
    pos: "verb",
    gender: "n/a",
    gloss: "to come (past)",
    meaningSummary:
      "High-frequency irregular: vine, viniste, vino, vinimos, vinieron. Opposite direction of fui.",
    conjugations: LATAM_PRETERITE([
      "vine",
      "viniste",
      "vino",
      "vinimos",
      "vinieron",
    ]),
    examples: [
      { es: "Vine a la oficina temprano.", en: "I came to the office early." },
      { es: "¿Viniste ayer?", en: "Did you come yesterday?" },
    ],
    useWhen: "Someone arrived / came to a place.",
    dontUseWhen: "Going away from here is ir → fui, not vine.",
    contrast: "ir / fui (I went)",
    formality: "neutral",
    cefr: "A2",
  },
  "limpiar-preterite": {
    id: "limpiar-preterite",
    lemma: "limpiar (past tense)",
    pos: "verb",
    gender: "n/a",
    gloss: "to clean (past)",
    meaningSummary:
      "Regular -ar past tense for chores: limpié, limpiaste, limpió… Limpié el departamento ayer.",
    conjugations: LATAM_PRETERITE([
      "limpié",
      "limpiaste",
      "limpió",
      "limpiamos",
      "limpiaron",
    ]),
    examples: [
      { es: "Ayer limpié la cocina.", en: "Yesterday I cleaned the kitchen." },
      { es: "¿Limpiaste el departamento?", en: "Did you clean the apartment?" },
    ],
    useWhen: "Finished cleaning chores.",
    dontUseWhen: "n/a",
    formality: "neutral",
    cefr: "A2",
  },
  "desayunar-preterite": {
    id: "desayunar-preterite",
    lemma: "desayunar (past tense)",
    pos: "verb",
    gender: "n/a",
    gloss: "to eat breakfast (past)",
    meaningSummary:
      "Regular -ar past tense: desayuné, desayunaste, desayunó… Common with esta mañana / ayer.",
    conjugations: LATAM_PRETERITE([
      "desayuné",
      "desayunaste",
      "desayunó",
      "desayunamos",
      "desayunaron",
    ]),
    examples: [
      { es: "Esta mañana desayuné temprano.", en: "This morning I ate breakfast early." },
      { es: "¿Qué desayunaste?", en: "What did you have for breakfast?" },
    ],
    useWhen: "Talking about a finished breakfast.",
    dontUseWhen: "Lunch/dinner use almorcé / cené later.",
    formality: "neutral",
    cefr: "A2",
  },
};

export const UNIT7_LESSONS: Record<string, Lesson> = {
  "u7-l1": {
    id: "u7-l1",
    unitId: "unit-7",
    title: "I ate… today",
    description: "Past tense stories with comer, hablar, ayer, hoy.",
    xpReward: 44,
    exercises: [
      teach("teach-u7l1-comer", "comer"),
      {
        id: "u7l1-1",
        type: "select",
        prompt: "“I ate” (yo, past tense) is…",
        options: ["Comí", "Como", "Comer", "Comía always"],
        correctIndex: 0,
        hint: "Regular -er past-tense yo ending is -í — not the present, the infinitive, or the imperfect.",
        explanation: "Past tense yo of comer → comí.",
        wordCardIds: ["comer"],
        xp: 3,
      },
      teach("teach-u7l1-hablar-pret", "hablar-preterite"),
      {
        id: "u7l1-2",
        type: "select",
        prompt: "“I spoke / I talked” (yo) is…",
        options: ["Hablo", "Hablaba only", "Hablé", "Hacer"],
        correctIndex: 2,
        hint: "Regular -ar past-tense yo ending is -é — not the present, the imperfect, or an unrelated verb.",
        explanation: "Regular -ar past tense: hablé.",
        wordCardIds: ["hablar-preterite"],
        xp: 3,
      },
      teach("teach-u7l1-ayer", "ayer"),
      teach("teach-u7l1-hoy", "hoy"),
      {
        id: "u7l1-3",
        type: "tap-chips",
        prompt: "Build: “I ate tacos today.”",
        chips: ["Comí", "tacos", "hoy.", "ayer", "quiero"],
        correctOrder: ["Comí", "tacos", "hoy."],
        explanation: "Comí tacos hoy.",
        wordCardIds: ["comer", "hoy", "tacos"],
        xp: 3,
      },
      {
        id: "u7l1-4",
        type: "translate",
        prompt: "Translate: “Yesterday I talked with my sister.”",
        acceptedAnswers: [
          "Ayer hablé con mi hermana.",
          "Ayer hable con mi hermana.",
          "Hablé con mi hermana ayer.",
          "Hable con mi hermana ayer.",
        ],
        hint: "hablé",
        explanation: "Ayer hablé con mi hermana.",
        wordCardIds: ["hablar-preterite", "ayer"],
        xp: 4,
      },
      listen(
        "u7l1-5",
        "Comí tacos hoy.",
        ["I ate tacos today.", "I like tacos today.", "I want tacos today.", "Turn right today."],
        0,
        "Comí tacos hoy = I ate tacos today.",
        ["comer", "hoy", "tacos"],
        3,
        "Comí is the past-tense 'I ate' — not gustar or querer."
      ),
      {
        id: "u7l1-6",
        type: "situational-choose",
        prompt: "Pick the best question.",
        situation: "You want to know what a friend ate yesterday.",
        options: [
          "¿Qué comes carro?",
          "¿Dónde está ayer?",
          "¿Qué comiste ayer?",
          "¿Me gusta ayer?",
        ],
        correctIndex: 2,
        hint: "You need comiste (tú past) + ayer — the others swap in the wrong verb or tense.",
        explanation: "¿Qué comiste ayer?",
        wordCardIds: ["comer", "ayer"],
        xp: 3,
      },
      {
        id: "u7l1-7",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "Yesterday I talked with Ana.",
        template: "Ayer ___ con Ana.",
        acceptedAnswers: ["hablé", "hable", "Hablé"],
        hint: "I talked (past tense)",
        explanation: "Ayer hablé con Ana.",
        wordCardIds: ["hablar-preterite", "ayer"],
        xp: 3,
      },
      {
        id: "u7l1-8",
        type: "match-pairs",
        prompt: "Match past tense forms.",
        pairs: [
          { left: "comí", right: "I ate" },
          { left: "hablé", right: "I spoke" },
          { left: "ayer", right: "yesterday" },
          { left: "hoy", right: "today" },
        ],
        explanation: "Regular past tense storytelling anchors.",
        wordCardIds: ["comer", "hablar-preterite", "ayer", "hoy"],
        xp: 4,
      },
      listen(
        "u7l1-9",
        "¿Qué comiste ayer?",
        ["What do you like yesterday?", "What did you eat yesterday?", "Where is yesterday?", "I want juice yesterday."],
        1,
        "¿Qué comiste ayer?",
        ["comer", "ayer"],
        3,
        "Comiste is 'you ate'; ayer means 'yesterday'."
      ),
      {
        id: "u7l1-10",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I ate rice today.",
        template: "___ arroz hoy.",
        acceptedAnswers: ["Comí", "Comi", "comí", "comi"],
        explanation: "Comí arroz hoy.",
        wordCardIds: ["comer", "hoy", "arroz"],
        xp: 3,
      },
    
      conjugate(
        "u7l1-conj-1",
        "comer",
        "yo",
        "Past tense",
        ["comí", "comi", "Comí", "Comi"],
        "yo + comer (past tense) → comí.",
        ["comer"],
        { xp: 3 }
      ),
      conjugate(
        "u7l1-conj-2",
        "hablar",
        "tú",
        "Past tense",
        ["hablaste", "Hablaste"],
        "tú + hablar (past tense) → hablaste.",
        ["hablar"],
        { xp: 3 }
      ),
    ],
  },

  "u7-l2": {
    id: "u7-l2",
    unitId: "unit-7",
    title: "Irregular past hits",
    description: "Fui, hice, tuve, dije — high-frequency past tense irregulars.",
    xpReward: 46,
    exercises: [
      teach("teach-u7l2-ir", "ir"),
      {
        id: "u7l2-1",
        type: "select",
        prompt: "“I went” (yo) is…",
        options: ["Voy", "Ir", "Fui", "Comí"],
        correctIndex: 2,
        hint: "Ir's past yo form is irregular — not voy, the infinitive, or comí.",
        explanation: "Ir past tense yo → fui (same form as ser — context decides).",
        wordCardIds: ["ir"],
        xp: 3,
      },
      teach("teach-u7l2-hacer", "hacer"),
      {
        id: "u7l2-2",
        type: "select",
        prompt: "“I did / I made” (yo) is…",
        options: ["Hice", "Hago", "Hacer", "Hablé"],
        correctIndex: 0,
        hint: "Hacer's past yo form is irregular, starting with hic- — not the present or the infinitive.",
        explanation: "Hacer past tense yo → hice.",
        wordCardIds: ["hacer"],
        xp: 3,
      },
      teach("teach-u7l2-tener-pret", "tener-preterite"),
      teach("teach-u7l2-decir", "decir"),
      {
        id: "u7l2-3",
        type: "tap-chips",
        prompt: "Build: “I went to the supermarket yesterday.”",
        chips: ["Fui", "al", "supermercado", "ayer.", "hice", "jugo"],
        correctOrder: ["Fui", "al", "supermercado", "ayer."],
        explanation: "Fui al supermercado ayer.",
        wordCardIds: ["ir", "ayer"],
        xp: 3,
      },
      {
        id: "u7l2-4",
        type: "translate",
        prompt: "Translate: “What did you do today?”",
        acceptedAnswers: [
          "¿Qué hiciste hoy?",
          "Que hiciste hoy?",
          "¿Qué hiciste hoy",
          "Qué hiciste hoy",
        ],
        hint: "hiciste",
        explanation: "¿Qué hiciste hoy?",
        wordCardIds: ["hacer", "hoy"],
        xp: 4,
      },
      listen(
        "u7l2-5",
        "Fui al supermercado ayer.",
        ["I like the supermarket.", "I went to the supermarket yesterday.", "I want the check.", "Turn left yesterday."],
        1,
        "Fui al supermercado ayer.",
        ["ir", "ayer"],
        3,
        "Fui is 'I went'; al supermercado ayer names where and when."
      ),
      {
        id: "u7l2-6",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "You had a meeting today and want to say so.",
        options: [
          "Tengo una reunión ayer.",
          "Me gusta reunión.",
          "Tuve una reunión hoy.",
          "Todo recto reunión.",
        ],
        correctIndex: 2,
        hint: "Tener's past yo form (tuve) plus hoy — not gustar or todo recto.",
        explanation: "Tuve una reunión hoy.",
        wordCardIds: ["tener-preterite", "hoy"],
        xp: 3,
      },
      {
        id: "u7l2-7",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I told the truth.",
        template: "___ la verdad.",
        acceptedAnswers: ["Dije", "dije"],
        hint: "I said (decir)",
        explanation: "Dije la verdad.",
        wordCardIds: ["decir"],
        xp: 3,
      },
      {
        id: "u7l2-8",
        type: "match-pairs",
        prompt: "Match irregular past-tense forms.",
        pairs: [
          { left: "fui", right: "I went" },
          { left: "hice", right: "I did / I made" },
          { left: "tuve", right: "I had" },
          { left: "dije", right: "I said" },
        ],
        explanation: "High-frequency irregular past-tense forms.",
        wordCardIds: ["ir", "hacer", "tener-preterite", "decir"],
        xp: 4,
      },
      listen(
        "u7l2-9",
        "¿Qué hiciste hoy?",
        ["What do you like today?", "Where is today?", "What did you do today?", "I want coffee today."],
        2,
        "¿Qué hiciste hoy?",
        ["hacer", "hoy"],
        3,
        "Hiciste is 'you did'; hoy means 'today'."
      ),
      {
        id: "u7l2-10",
        type: "select",
        prompt: "“He/she said” is…",
        options: ["dije", "digo", "dijo", "comí"],
        correctIndex: 2,
        hint: "Decir's él/ella past form is irregular — not dije (yo) or digo (present).",
        explanation: "decir → él/ella/usted dijo.",
        wordCardIds: ["decir"],
        xp: 3,
      },
      {
        id: "u7l2-11",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I did the homework last night.",
        template: "___ la tarea anoche.",
        acceptedAnswers: ["Hice", "hice"],
        hint: "I did (hacer)",
        explanation: "Hice la tarea anoche.",
        wordCardIds: ["hacer", "anoche"],
        xp: 3,
      },
    ],
  },

  "u7-l3": {
    id: "u7-l3",
    unitId: "unit-7",
    title: "Regular -ar / -er / -ir past",
    description: "Pattern hits: hablé / comí / viví and friends.",
    xpReward: 44,
    exercises: [
      teach("teach-u7l3-trabajar", "trabajar-preterite"),
      {
        id: "u7l3-1",
        type: "select",
        prompt: "Regular -ar yo past of trabajar is…",
        options: ["Trabajo", "Trabajaba always", "Trabajé", "Trabajar"],
        correctIndex: 2,
        hint: "Regular -ar past-tense yo ending is -é, not the present or imperfect.",
        explanation: "-ar → yo -é: trabajé.",
        wordCardIds: ["trabajar-preterite"],
        xp: 3,
      },
      teach("teach-u7l3-vivir", "vivir-preterite"),
      {
        id: "u7l3-2",
        type: "select",
        prompt: "Regular -ir yo past of vivir is…",
        options: ["Vivo", "Viví", "Voy", "Fui only"],
        correctIndex: 1,
        hint: "Regular -ir past-tense yo ending is -í, not the present or ir's irregular fui.",
        explanation: "-ir → yo -í: viví.",
        wordCardIds: ["vivir-preterite"],
        xp: 3,
      },
      teach("teach-u7l3-estudiar", "estudiar-preterite"),
      {
        id: "u7l3-3",
        type: "tap-chips",
        prompt: "Build: “Yesterday I worked until late.”",
        chips: ["Ayer", "trabajé", "hasta", "tarde.", "como", "metro"],
        correctOrder: ["Ayer", "trabajé", "hasta", "tarde."],
        explanation: "Ayer trabajé hasta tarde.",
        wordCardIds: ["trabajar-preterite", "ayer"],
        xp: 3,
      },
      {
        id: "u7l3-4",
        type: "translate",
        prompt: "Translate: “I lived in Mexico.”",
        acceptedAnswers: [
          "Viví en México.",
          "Vivi en Mexico.",
          "Viví en Mexico.",
          "Yo viví en México.",
        ],
        hint: "Vivir in the past tense, yo form (-ir verbs take -í), then en + the country.",
        explanation: "Viví en México.",
        wordCardIds: ["vivir-preterite"],
        xp: 4,
      },
      listen(
        "u7l3-5",
        "Anoche estudié español.",
        ["Last night I studied Spanish.", "I like Spanish tonight.", "I want Spanish juice.", "Turn left Spanish."],
        0,
        "Anoche estudié español.",
        ["estudiar-preterite", "anoche"],
        3,
        "Anoche means 'last night'; estudié is the past-tense 'I studied'."
      ),
      {
        id: "u7l3-6",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I ate tacos yesterday.",
        template: "___ tacos ayer.",
        acceptedAnswers: ["Comí", "Comi", "comí", "comi"],
        hint: "I ate (-er past)",
        explanation: "Comí tacos ayer. Regular -er yo → -í.",
        wordCardIds: ["comer", "ayer", "tacos"],
        xp: 3,
      },
      {
        id: "u7l3-7",
        type: "match-pairs",
        prompt: "Match regular yo past endings.",
        pairs: [
          { left: "hablé", right: "-ar → -é" },
          { left: "comí", right: "-er → -í" },
          { left: "viví", right: "-ir → -í" },
          { left: "estudié", right: "I studied" },
        ],
        explanation: "Regular past tense yo patterns.",
        wordCardIds: ["hablar-preterite", "comer", "vivir-preterite", "estudiar-preterite"],
        xp: 4,
      },
      {
        id: "u7l3-8",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "Friend asks if you studied last night.",
        options: [
          "Sí, estudié anoche.",
          "Sí, estudio carro.",
          "Sí, fui menú.",
          "Sí, me gusta anoche solo.",
        ],
        correctIndex: 0,
        hint: "You need the past-tense estudiar form plus anoche — not present tense or an unrelated verb.",
        explanation: "Sí, estudié anoche.",
        wordCardIds: ["estudiar-preterite", "anoche"],
        xp: 3,
      },
      listen(
        "u7l3-9",
        "¿Trabajaste hoy?",
        ["Did you work today?", "Do you like work today?", "Where is work?", "I want coffee work."],
        0,
        "¿Trabajaste hoy?",
        ["trabajar-preterite", "hoy"],
        3,
        "Trabajaste is the tú past of trabajar; hoy means 'today'."
      ),
      {
        id: "u7l3-10",
        type: "select",
        prompt: "tú past of hablar is…",
        options: ["hablé", "hablaste", "hablo", "hablaron"],
        correctIndex: 1,
        hint: "Informal tú past of -ar verbs ends in -aste — not -é (yo) or -aron (they).",
        explanation: "Informal -aste for -ar: hablaste.",
        wordCardIds: ["hablar-preterite"],
        xp: 3,
      },
    
      conjugate(
        "u7l3-conj-1",
        "ir",
        "yo",
        "Past tense",
        ["fui", "Fui"],
        "yo + ir (past tense) → fui.",
        ["ir"],
        { xp: 3 }
      ),
      conjugate(
        "u7l3-conj-2",
        "hacer",
        "él/ella/usted",
        "Past tense",
        ["hizo", "Hizo"],
        "él/ella/usted + hacer → hizo.",
        ["hacer"],
        { xp: 3 }
      ),
    ],
  },

  "u7-l4": {
    id: "u7-l4",
    unitId: "unit-7",
    title: "More irregulars + vine",
    description: "Nail the big five irregular past forms: fui, hice, tuve, dije, vine.",
    xpReward: 45,
    exercises: [
      teach("teach-u7l4-venir", "venir-preterite"),
      {
        id: "u7l4-1",
        type: "select",
        prompt: "“I came” (yo) is…",
        options: ["Voy", "Vengo", "Vine", "Fui always only"],
        correctIndex: 2,
        hint: "Venir's past yo form is irregular — not voy, vengo, or fui.",
        explanation: "venir past tense yo → vine.",
        wordCardIds: ["venir-preterite"],
        xp: 3,
      },
      {
        id: "u7l4-2",
        type: "select",
        prompt: "fui vs vine — “I went to the office” uses…",
        options: ["Vine a la oficina.", "Fui a la oficina.", "Como la oficina.", "Dije la oficina."],
        correctIndex: 1,
        hint: "Going there uses fui (from ir); vine is for coming here.",
        explanation: "Going there → fui. Coming here → vine.",
        wordCardIds: ["ir", "venir-preterite"],
        xp: 3,
      },
      {
        id: "u7l4-3",
        type: "tap-chips",
        prompt: "Build: “I came early yesterday.”",
        chips: ["Vine", "temprano", "ayer.", "fui", "jugo"],
        correctOrder: ["Vine", "temprano", "ayer."],
        explanation: "Vine temprano ayer.",
        wordCardIds: ["venir-preterite", "ayer"],
        xp: 3,
      },
      {
        id: "u7l4-4",
        type: "translate",
        prompt: "Translate: “Did you come yesterday?”",
        acceptedAnswers: [
          "¿Viniste ayer?",
          "Viniste ayer?",
          "¿Viniste ayer",
          "Viniste ayer",
        ],
        hint: "Venir is irregular in the past: the tú form ends in -iste. Then the ‘yesterday’ adverb. No ‘did’ needed.",
        explanation: "¿Viniste ayer?",
        wordCardIds: ["venir-preterite", "ayer"],
        xp: 4,
      },
      listen(
        "u7l4-5",
        "Vine a la oficina temprano.",
        ["I came to the office early.", "I went to juice early.", "I like the office.", "Turn right office."],
        0,
        "Vine a la oficina temprano.",
        ["venir-preterite", "oficina"],
        3,
        "Vine is 'I came'; temprano means 'early'."
      ),
      {
        id: "u7l4-6",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I had no time yesterday.",
        template: "No ___ tiempo ayer.",
        acceptedAnswers: ["tuve", "Tuve"],
        hint: "I had (tener past)",
        explanation: "No tuve tiempo ayer.",
        wordCardIds: ["tener-preterite", "ayer"],
        xp: 3,
      },
      {
        id: "u7l4-7",
        type: "match-pairs",
        prompt: "Match the big five.",
        pairs: [
          { left: "fui", right: "I went" },
          { left: "hice", right: "I did" },
          { left: "tuve", right: "I had" },
          { left: "dije", right: "I said" },
          { left: "vine", right: "I came" },
        ],
        explanation: "Core irregular past-tense forms.",
        wordCardIds: ["ir", "hacer", "tener-preterite", "decir", "venir-preterite"],
        xp: 5,
      },
      {
        id: "u7l4-8",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "Someone asks what you said to the waiter.",
        options: [
          "Dije la verdad.",
          "Como la verdad.",
          "Voy verdad.",
          "Me gusta verdad metro.",
        ],
        correctIndex: 0,
        hint: "Decir's past yo form (dije) plus la verdad — not comer or ir.",
        explanation: "Dije la verdad — or report what you said.",
        wordCardIds: ["decir"],
        xp: 3,
      },
      listen(
        "u7l4-9",
        "¿Viniste ayer?",
        ["Did you come yesterday?", "Did you go juice?", "Where is yesterday?", "I want tacos."],
        0,
        "¿Viniste ayer?",
        ["venir-preterite", "ayer"],
        3,
        "Viniste is the tú past of venir; ayer means 'yesterday'."
      ),
      {
        id: "u7l4-10",
        type: "select",
        prompt: "él/ella of hacer in the past is…",
        options: ["hice", "hizo", "hago", "hacemos"],
        correctIndex: 1,
        hint: "Hacer's él/ella past form is irregular — not hice (yo) or hago (present).",
        explanation: "hacer → él/ella/usted hizo.",
        wordCardIds: ["hacer"],
        xp: 3,
      },
    ],
  },

  "u7-l5": {
    id: "u7-l5",
    unitId: "unit-7",
    title: "Yesterday timeline",
    description: "Ayer, anoche, esta mañana, hoy — sequence a day.",
    xpReward: 44,
    exercises: [
      teach("teach-u7l5-anoche", "anoche"),
      teach("teach-u7l5-manana", "esta-manana"),
      {
        id: "u7l5-1",
        type: "select",
        prompt: "“Last night” is…",
        options: ["hoy", "anoche", "mañana", "carro"],
        correctIndex: 1,
        hint: "Not hoy, mañana, or a car — it's the word for 'last night'.",
        explanation: "anoche = last night.",
        wordCardIds: ["anoche"],
        xp: 3,
      },
      {
        id: "u7l5-2",
        type: "select",
        prompt: "“This morning” is…",
        options: ["esta mañana", "anoche", "el carro mañana", "el metro"],
        correctIndex: 0,
        hint: "Not anoche or unrelated nouns — it's 'this morning'.",
        explanation: "esta mañana.",
        wordCardIds: ["esta-manana"],
        xp: 3,
      },
      {
        id: "u7l5-3",
        type: "tap-chips",
        prompt: "Build: “Last night I ate tacos.”",
        chips: ["Anoche", "comí", "tacos.", "fui", "menu"],
        correctOrder: ["Anoche", "comí", "tacos."],
        explanation: "Anoche comí tacos.",
        wordCardIds: ["anoche", "comer", "tacos"],
        xp: 3,
      },
      {
        id: "u7l5-4",
        type: "translate",
        prompt: "Translate: “This morning I worked.”",
        acceptedAnswers: [
          "Esta mañana trabajé.",
          "Esta manana trabaje.",
          "Esta mañana trabaje.",
          "Trabajé esta mañana.",
        ],
        hint: "trabajé",
        explanation: "Esta mañana trabajé.",
        wordCardIds: ["esta-manana", "trabajar-preterite"],
        xp: 4,
      },
      listen(
        "u7l5-5",
        "Anoche hice la tarea.",
        ["Last night I did the homework.", "I like homework juice.", "Where is homework?", "Turn left task."],
        0,
        "Anoche hice la tarea.",
        ["anoche", "hacer"],
        3,
        "Anoche is 'last night'; hice is the past-tense 'I did'."
      ),
      {
        id: "u7l5-6",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "Yesterday I went downtown.",
        template: "___ fui al centro.",
        acceptedAnswers: ["Ayer", "ayer"],
        hint: "The time word for the day before today — starts with a-, two syllables.",
        explanation: "Ayer fui al centro.",
        wordCardIds: ["ayer", "ir", "el-centro"],
        xp: 3,
      },
      {
        id: "u7l5-7",
        type: "match-pairs",
        prompt: "Match time words.",
        pairs: [
          { left: "ayer", right: "yesterday" },
          { left: "anoche", right: "last night" },
          { left: "esta mañana", right: "this morning" },
          { left: "hoy", right: "today" },
        ],
        explanation: "Past tense timeline anchors.",
        wordCardIds: ["ayer", "anoche", "esta-manana", "hoy"],
        xp: 4,
      },
      {
        id: "u7l5-8",
        type: "situational-choose",
        prompt: "Pick the best question.",
        situation: "Ask what someone did last night.",
        options: [
          "¿Qué hiciste anoche?",
          "¿Qué comes metro?",
          "¿Dónde está anoche?",
          "¿Me gusta anoche?",
        ],
        correctIndex: 0,
        hint: "You need hiciste (past) plus anoche — the others swap in the wrong verb or tense.",
        explanation: "¿Qué hiciste anoche?",
        wordCardIds: ["hacer", "anoche"],
        xp: 3,
      },
      listen(
        "u7l5-9",
        "Esta mañana desayuné temprano.",
        ["This morning I ate breakfast early.", "I want breakfast metro.", "Last night juice.", "Turn right morning."],
        0,
        "Esta mañana desayuné temprano.",
        ["esta-manana", "desayunar-preterite"],
        3,
        "Esta mañana is 'this morning'; desayuné is the past-tense 'I had breakfast'."
      ),
      {
        id: "u7l5-10",
        type: "select",
        prompt: "Which set gives three distinct past-time words for telling about your day?",
        options: [
          "anoche / ayer / esta mañana (all same)",
          "esta mañana · ayer · anoche",
          "Only mañana forever",
          "Never use hoy",
        ],
        correctIndex: 1,
        hint: "You need three different past time words — one for earlier today, one for the day before, one for last night. Rule out any option that treats them as the same or throws one away.",
        explanation: "esta mañana · ayer · anoche — three different past-time words, each pointing to a different moment.",
        wordCardIds: ["esta-manana", "anoche", "ayer"],
        xp: 3,
      },
    
      conjugate(
        "u7l5-conj-1",
        "tener",
        "yo",
        "Past tense",
        ["tuve", "Tuve"],
        "yo + tener (past tense) → tuve.",
        ["tener"],
        { xp: 3 }
      ),
      conjugate(
        "u7l5-conj-2",
        "decir",
        "yo",
        "Past tense",
        ["dije", "Dije"],
        "yo + decir (past tense) → dije.",
        ["decir"],
        { xp: 3 }
      ),
    ],
  },

  "u7-l6": {
    id: "u7-l6",
    unitId: "unit-7",
    title: "Food & home in the past",
    description: "Put meals, chores, and home life into the past: desayuné, limpié, comí.",
    xpReward: 45,
    exercises: [
      teach("teach-u7l6-desayunar", "desayunar-preterite"),
      teach("teach-u7l6-limpiar", "limpiar-preterite"),
      {
        id: "u7l6-1",
        type: "select",
        prompt: "“I ate breakfast” (yo past) is…",
        options: ["Desayuno", "Desayuné", "Quiero desayuno only", "La cuenta"],
        correctIndex: 1,
        hint: "The past-tense yo form of desayunar ends in -é, not the present or an unrelated phrase.",
        explanation: "desayuné.",
        wordCardIds: ["desayunar-preterite"],
        xp: 3,
      },
      {
        id: "u7l6-2",
        type: "tap-chips",
        prompt: "Build: “Yesterday I cleaned the kitchen.”",
        chips: ["Ayer", "limpié", "la", "cocina.", "jugo", "metro"],
        correctOrder: ["Ayer", "limpié", "la", "cocina."],
        explanation: "Ayer limpié la cocina.",
        wordCardIds: ["limpiar-preterite", "ayer", "cocina"],
        xp: 3,
      },
      {
        id: "u7l6-3",
        type: "translate",
        prompt: "Translate: “I ate tacos yesterday.”",
        acceptedAnswers: [
          "Comí tacos ayer.",
          "Comi tacos ayer.",
          "Ayer comí tacos.",
          "Ayer comi tacos.",
        ],
        hint: "Comer in the past tense, yo form (-er verbs take -í) + tacos + the ‘yesterday’ adverb.",
        explanation: "Comí tacos ayer.",
        wordCardIds: ["comer", "tacos", "ayer"],
        xp: 4,
      },
      listen(
        "u7l6-4",
        "Desayuné café esta mañana.",
        ["I had coffee for breakfast this morning.", "I want coffee metro.", "Where is coffee?", "Turn left café."],
        0,
        "Desayuné café esta mañana.",
        ["desayunar-preterite", "cafe", "esta-manana"],
        3,
        "Desayuné is 'I had breakfast'; esta mañana names when."
      ),
      {
        id: "u7l6-5",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I cleaned the apartment yesterday.",
        template: "___ el departamento ayer.",
        acceptedAnswers: ["Limpié", "Limpie", "limpié", "limpie"],
        explanation: "Limpié el departamento ayer.",
        wordCardIds: ["limpiar-preterite", "departamento", "ayer"],
        xp: 3,
      },
      {
        id: "u7l6-6",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "Friend asks what you ordered / ate at the café.",
        options: [
          "Comí arroz y jugo.",
          "Me ducho el jugo.",
          "Todo recto arroz.",
          "Soy el menú ayer.",
        ],
        correctIndex: 0,
        hint: "You need comí (past) plus food and drink words — not ducharse or todo recto.",
        explanation: "Comí arroz y jugo.",
        wordCardIds: ["comer", "arroz", "jugo"],
        xp: 3,
      },
      {
        id: "u7l6-7",
        type: "match-pairs",
        prompt: "Match home/food past.",
        pairs: [
          { left: "desayuné", right: "I ate breakfast" },
          { left: "limpié", right: "I cleaned" },
          { left: "comí", right: "I ate" },
          { left: "hablé", right: "I talked" },
        ],
        explanation: "Unit 4–5 reuse in past tense.",
        wordCardIds: ["desayunar-preterite", "limpiar-preterite", "comer", "hablar-preterite"],
        xp: 4,
      },
      listen(
        "u7l6-8",
        "¿Limpiaste el departamento?",
        ["Did you clean the apartment?", "Do you like the apartment?", "Where is juice?", "I want the check."],
        0,
        "¿Limpiaste el departamento?",
        ["limpiar-preterite", "departamento"],
        3,
        "Limpiaste is the tú past of limpiar; el departamento is what's asked about."
      ),
      {
        id: "u7l6-9",
        type: "select",
        prompt: "Unit 5 reuse: everyday word for juice?",
        options: ["oficina", "jugo", "derecha", "anoche"],
        correctIndex: 1,
        hint: "Not an office, a direction, or 'last night' — it's the drink word.",
        explanation: "jugo.",
        wordCardIds: ["jugo"],
        xp: 3,
      },
      {
        id: "u7l6-10",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I drank juice yesterday. (use Tomé)",
        template: "___ jugo ayer.",
        acceptedAnswers: ["Tomé", "Tome", "tomé", "tome"],
        hint: "I drank / I had (tomar past)",
        explanation: "Tomé jugo ayer — common with drinks.",
        wordCardIds: ["jugo", "ayer"],
        xp: 3,
      },
    ],
  },

  "u7-l7": {
    id: "u7-l7",
    unitId: "unit-7",
    title: "What did you do…?",
    description: "Situations: ask and answer about the past day.",
    xpReward: 45,
    exercises: [
      {
        id: "u7l7-1",
        type: "situational-choose",
        prompt: "Pick the best question.",
        situation: "Catch up with a friend about today.",
        options: [
          "¿Qué hiciste hoy?",
          "¿Qué comes carro hoy?",
          "¿Dónde está hoy el baño solo?",
          "¿Me gusta hoy?",
        ],
        correctIndex: 0,
        hint: "You need hiciste (past) plus hoy — the others garble the question with the wrong verb.",
        explanation: "¿Qué hiciste hoy?",
        wordCardIds: ["hacer", "hoy"],
        xp: 3,
      },
      {
        id: "u7l7-2",
        type: "situational-choose",
        prompt: "Pick the best answer.",
        situation: "Someone asks ¿Qué hiciste ayer? You worked.",
        options: [
          "Ayer trabajé.",
          "Ayer quiero metro.",
          "Ayer me gusta baño.",
          "Ayer soy jugo.",
        ],
        correctIndex: 0,
        hint: "Answering with what you did uses the past tense of trabajar, not querer or gustar.",
        explanation: "Ayer trabajé.",
        wordCardIds: ["trabajar-preterite", "ayer"],
        xp: 3,
      },
      {
        id: "u7l7-3",
        type: "tap-chips",
        prompt: "Build: “I went to the office and I talked with Ana.”",
        chips: ["Fui", "a", "la", "oficina", "y", "hablé", "con", "Ana.", "metro"],
        correctOrder: ["Fui", "a", "la", "oficina", "y", "hablé", "con", "Ana."],
        explanation: "Fui a la oficina y hablé con Ana.",
        wordCardIds: ["ir", "oficina", "hablar-preterite"],
        xp: 4,
      },
      {
        id: "u7l7-4",
        type: "translate",
        prompt: "Translate: “What did you do last night?”",
        acceptedAnswers: [
          "¿Qué hiciste anoche?",
          "Que hiciste anoche?",
          "¿Qué hiciste anoche",
          "Qué hiciste anoche",
        ],
        hint: "The ‘what’ question word + the tú past form of hacer (irregular, ends in -iste) + the ‘last night’ adverb.",
        explanation: "¿Qué hiciste anoche?",
        wordCardIds: ["hacer", "anoche"],
        xp: 4,
      },
      listen(
        "u7l7-5",
        "Fui al centro y comí tacos.",
        ["I went downtown and ate tacos.", "I like downtown juice.", "Where is the check?", "Turn left tacos."],
        0,
        "Fui al centro y comí tacos.",
        ["ir", "el-centro", "comer", "tacos"],
        3,
        "Fui...y comí links two past-tense actions — going and eating."
      ),
      {
        id: "u7l7-6",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I had a meeting today.",
        template: "___ una reunión hoy.",
        acceptedAnswers: ["Tuve", "tuve"],
        explanation: "Tuve una reunión hoy.",
        wordCardIds: ["tener-preterite", "hoy"],
        xp: 3,
      },
      {
        id: "u7l7-7",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "You came late and need to admit it.",
        options: [
          "Vine tarde.",
          "Como tarde el metro forever.",
          "Me ducho tarde la cuenta.",
          "Soy tarde jugo.",
        ],
        correctIndex: 0,
        hint: "Admitting lateness uses vine (past of venir) plus tarde — not comer or ducharse.",
        explanation: "Vine tarde.",
        wordCardIds: ["venir-preterite"],
        xp: 3,
      },
      {
        id: "u7l7-8",
        type: "match-pairs",
        prompt: "Match Q → natural answer vibe.",
        pairs: [
          { left: "¿Qué hiciste?", right: "Trabajé / Estudié…" },
          { left: "¿Qué comiste?", right: "Comí tacos…" },
          { left: "¿Fuiste al centro?", right: "Sí, fui. / No, no fui." },
          { left: "¿Viniste?", right: "Sí, vine temprano." },
        ],
        explanation: "Question → past tense answer.",
        wordCardIds: ["hacer", "comer", "ir", "venir-preterite"],
        xp: 4,
      },
      listen(
        "u7l7-9",
        "¿Qué hiciste anoche?",
        ["What did you do last night?", "What do you like juice?", "Where is last night?", "I want coffee."],
        0,
        "¿Qué hiciste anoche?",
        ["hacer", "anoche"],
        3,
        "Hiciste is 'you did'; anoche means 'last night'."
      ),
      {
        id: "u7l7-10",
        type: "select",
        prompt: "Soft polite ask to a coworker:",
        options: [
          "¿Qué hiciste este fin de semana?",
          "¿Qué comes el baño?",
          "¿Dónde está el jugo ayer?",
          "Comí tu fin.",
        ],
        correctIndex: 0,
        hint: "Only one option pairs hiciste with a real time phrase.",
        explanation: "¿Qué hiciste este fin de semana?",
        wordCardIds: ["hacer", "fin-de-semana"],
        xp: 3,
      },
    ],
  },

  "u7-l8": {
    id: "u7-l8",
    unitId: "unit-7",
    title: "Past tense review",
    description: "Tell what happened with regular and irregular past forms plus ayer and anoche.",
    xpReward: 44,
    exercises: [
      {
        id: "u7l8-1",
        type: "select",
        prompt: "“I went” is…",
        options: ["Voy", "Fui", "Vine only forever", "Como"],
        correctIndex: 1,
        hint: "Ir's irregular past yo form — not voy, vine, or como.",
        explanation: "fui.",
        wordCardIds: ["ir"],
        xp: 3,
      },
      {
        id: "u7l8-2",
        type: "tap-chips",
        prompt: "Build: “Yesterday I studied Spanish.”",
        chips: ["Ayer", "estudié", "español.", "metro", "cuenta"],
        correctOrder: ["Ayer", "estudié", "español."],
        explanation: "Ayer estudié español.",
        wordCardIds: ["estudiar-preterite", "ayer"],
        xp: 3,
      },
      listen(
        "u7l8-3",
        "Tuve una reunión hoy.",
        ["I had a meeting today.", "I like meetings juice.", "Where is the meeting?", "Turn right meeting."],
        0,
        "Tuve una reunión hoy.",
        ["tener-preterite", "hoy"],
        3,
        "Tuve is the past-tense 'I had'; hoy means 'today'."
      ),
      {
        id: "u7l8-4",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I said the truth.",
        template: "___ la verdad.",
        acceptedAnswers: ["Dije", "dije"],
        explanation: "Dije la verdad.",
        wordCardIds: ["decir"],
        xp: 3,
      },
      {
        id: "u7l8-5",
        type: "translate",
        prompt: "Translate: “I came to the office early.”",
        acceptedAnswers: [
          "Vine a la oficina temprano.",
          "Vine a la oficina temprano",
          "Yo vine a la oficina temprano.",
        ],
        hint: "Venir in the past, yo form (irregular, one syllable) + a la + the office word + the ‘early’ adverb.",
        explanation: "Vine a la oficina temprano.",
        wordCardIds: ["venir-preterite", "oficina"],
        xp: 4,
      },
      {
        id: "u7l8-6",
        type: "match-pairs",
        prompt: "Quick Unit 7 match.",
        pairs: [
          { left: "anoche", right: "last night" },
          { left: "hice", right: "I did" },
          { left: "viví", right: "I lived" },
          { left: "limpié", right: "I cleaned" },
        ],
        explanation: "Core Unit 7 lemmas.",
        wordCardIds: ["anoche", "hacer", "vivir-preterite", "limpiar-preterite"],
        xp: 4,
      },
      {
        id: "u7l8-7",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "Unit 6 reuse: you went by metro yesterday.",
        options: [
          "Ayer fui en metro.",
          "Ayer me ducho metro.",
          "Ayer quiero lejos metro forever.",
          "Ayer soy la cuenta.",
        ],
        correctIndex: 0,
        hint: "A Unit 6 reuse — fui en metro, not ducharse or querer.",
        explanation: "Ayer fui en metro.",
        wordCardIds: ["ir", "metro", "ayer"],
        xp: 3,
      },
      {
        id: "u7l8-8",
        type: "select",
        prompt: "Unit 5 reuse: after the meal you ask for…",
        options: ["la cuenta", "el baño forever only", "el metro tip", "todo recto jugo"],
        correctIndex: 0,
        hint: "Not a bathroom, a metro tip, or a direction — it's the check.",
        explanation: "la cuenta.",
        wordCardIds: ["la-cuenta"],
        xp: 3,
      },
      listen(
        "u7l8-9",
        "Anoche comí arroz y jugo.",
        ["Last night I ate rice and juice.", "I want rice metro.", "Where is juice?", "Turn left rice."],
        0,
        "Anoche comí arroz y jugo.",
        ["anoche", "comer", "arroz", "jugo"],
        3,
        "Anoche is 'last night'; comí is the past-tense 'I ate'."
      ),
      {
        id: "u7l8-10",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "What did you eat yesterday?",
        template: "¿Qué ___ ayer?",
        acceptedAnswers: ["comiste", "Comiste"],
        hint: "you ate (informal)",
        explanation: "¿Qué comiste ayer?",
        wordCardIds: ["comer", "ayer"],
        xp: 3,
      },
    ],
  },

  "u7-l9": {
    id: "u7-l9",
    unitId: "unit-7",
    title: "Story: Yesterday with Ana",
    description: "Listen to a past-day story, then fill in lines from it.",
    xpReward: 48,
    exercises: [
      storyListen(
        "u7l9-story",
        "Ayer con Ana",
        [
          { text: "Ayer fui al centro con Ana.", en: "Yesterday I went downtown with Ana." },
          { text: "Comimos tacos y tomamos jugo.", en: "We ate tacos and drank juice." },
          { text: "Después hablé con mi hermana por teléfono.", en: "Afterwards I talked with my sister on the phone." },
          { text: "Anoche estudié español una hora.", en: "Last night I studied Spanish for an hour." },
          { text: "Hoy trabajé en la oficina.", en: "Today I worked at the office." },
        ],
        [
          {
            prompt: "Where did the narrator go yesterday?",
            options: ["Only the bathroom", "Downtown", "The pharmacy tip", "The check forever"],
            correctIndex: 1,
            explanation: "Ayer fui al centro con Ana.",
          },
          {
            prompt: "What did the narrator and Ana eat and drink?",
            options: ["Tacos and juice", "Only metro tickets", "Soap", "Nothing said"],
            correctIndex: 0,
            explanation: "Comimos tacos y tomamos jugo.",
          },
          {
            prompt: "What happened after?",
            options: ["Turned left forever", "Talked with sister on the phone", "Asked for the map only", "Ordered only water forever"],
            correctIndex: 1,
            explanation: "Después hablé con mi hermana por teléfono.",
          },
          {
            prompt: "What about last night?",
            options: ["Studied Spanish an hour", "Only slept in the bank", "Cleaned the metro", "No past verbs"],
            correctIndex: 0,
            explanation: "Anoche estudié español una hora.",
          },
        ],
        ["ayer", "ir", "el-centro", "comer", "tacos", "jugo", "hablar-preterite", "anoche", "estudiar-preterite", "hoy", "trabajar-preterite", "oficina"],
        "You followed the whole story. Replay it anytime from the lesson.",
        12
      ),
      dictation(
        "u7l9-story-dict-1",
        "Ayer fui al centro con Ana.",
        ["Ayer fui al centro con Ana."],
        "Type the line you heard: Ayer fui al centro con Ana.",
        [],
        { hint: "Ayer opens it, then fui al centro (I went downtown) + con Ana.", voice: "f", xp: 4 }
      ),
      dictation(
        "u7l9-story-dict-2",
        "Comimos tacos y tomamos jugo.",
        ["Comimos tacos y tomamos jugo."],
        "Type the line you heard: Comimos tacos y tomamos jugo.",
        [],
        { hint: "Two nosotros past forms: comimos (we ate) and tomamos (we drank).", voice: "m", xp: 4 }
      ),
      {
        id: "u7l9-1",
        type: "select",
        prompt: "From the story — first line was…",
        options: [
          "Ayer fui al centro con Ana.",
          "Me ducho el centro.",
          "Quiero el metro centro.",
          "La cuenta Ana.",
        ],
        correctIndex: 0,
        hint: "The story's first line opens with ayer and the past-tense fui, not an unrelated verb.",
        explanation: "Ayer fui al centro con Ana.",
        wordCardIds: ["ayer", "ir", "el-centro"],
        xp: 3,
      },
      cloze(
        "u7l9-cloze-1",
        "Ayer ___ al centro con Ana.",
        ["fui", "Fui"],
        "Ayer fui al centro con Ana.",
        ["ayer", "ir", "el-centro"],
        {
          audioText: "Ayer fui al centro con Ana.",
          voice: "f",
        }
      ),
      cloze(
        "u7l9-cloze-2",
        "Anoche ___ español una hora.",
        ["estudié", "estudie", "Estudié"],
        "Anoche estudié español una hora.",
        ["anoche", "estudiar-preterite"],
        {
          audioText: "Anoche estudié español una hora.",
          voice: "m",
        }
      ),
      cloze(
        "u7l9-cloze-3",
        "Hoy ___ en la oficina.",
        ["trabajé", "trabaje", "Trabajé"],
        "Hoy trabajé en la oficina.",
        ["hoy", "trabajar-preterite", "oficina"],
        {
          audioText: "Hoy trabajé en la oficina.",
          voice: "c",
        }
      ),
    ],
  },

  "u7-l10": {
    id: "u7-l10",
    unitId: "unit-7",
    title: "More past practice",
    description: "More past-tense practice: hice, vine, tuve, plus meals and chores at home.",
    xpReward: 44,
    exercises: [
      {
        id: "u7l10-1",
        type: "translate",
        prompt: "Translate: “I did the homework last night.”",
        acceptedAnswers: [
          "Hice la tarea anoche.",
          "Hice la tarea anoche",
          "Anoche hice la tarea.",
          "Anoche hice la tarea",
        ],
        hint: "Hacer in the past, yo form (irregular, starts with hic-) + la + the homework word + the ‘last night’ adverb.",
        explanation: "Hice la tarea anoche.",
        wordCardIds: ["hacer", "anoche"],
        xp: 4,
      },
      {
        id: "u7l10-2",
        type: "tap-chips",
        prompt: "Build: “This morning I ate breakfast early.”",
        chips: ["Esta", "mañana", "desayuné", "temprano.", "metro", "cuenta"],
        correctOrder: ["Esta", "mañana", "desayuné", "temprano."],
        explanation: "Esta mañana desayuné temprano.",
        wordCardIds: ["esta-manana", "desayunar-preterite"],
        xp: 3,
      },
      listen(
        "u7l10-3",
        "¿Viniste a la oficina ayer?",
        ["Did you come to the office yesterday?", "Do you like the office?", "Where is juice?", "I want the check."],
        0,
        "¿Viniste a la oficina ayer?",
        ["venir-preterite", "oficina", "ayer"],
        3,
        "Viniste is 'did you come'; a la oficina ayer names where and when."
      ),
      {
        id: "u7l10-4",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I lived in Mexico two years.",
        template: "___ en México dos años.",
        acceptedAnswers: ["Viví", "Vivi", "viví", "vivi"],
        explanation: "Viví en México dos años.",
        wordCardIds: ["vivir-preterite"],
        xp: 3,
      },
      {
        id: "u7l10-5",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "You cleaned the apartment yesterday.",
        options: [
          "Ayer limpié el departamento.",
          "Ayer me gusta el departamento jugo.",
          "Ayer soy lejos departamento.",
          "Ayer la cuenta departamento.",
        ],
        correctIndex: 0,
        hint: "You need the past-tense limpiar form plus ayer — not gustar or ser.",
        explanation: "Ayer limpié el departamento.",
        wordCardIds: ["limpiar-preterite", "departamento", "ayer"],
        xp: 3,
      },
      {
        id: "u7l10-6",
        type: "select",
        prompt: "tú of decir in the past is…",
        options: ["dije", "dijiste", "digo", "dijeron"],
        correctIndex: 1,
        hint: "Informal tú past of decir ends in -iste — not dije (yo) or dijeron (they).",
        explanation: "dijiste (informal you).",
        wordCardIds: ["decir"],
        xp: 3,
      },
      {
        id: "u7l10-7",
        type: "match-pairs",
        prompt: "Practice match.",
        pairs: [
          { left: "fui", right: "I went" },
          { left: "vine", right: "I came" },
          { left: "tuve", right: "I had" },
          { left: "estudié", right: "I studied" },
        ],
        explanation: "Irregulars + regular.",
        wordCardIds: ["ir", "venir-preterite", "tener-preterite", "estudiar-preterite"],
        xp: 4,
      },
      listen(
        "u7l10-8",
        "Ayer trabajé hasta tarde.",
        ["Yesterday I worked until late.", "I like work juice.", "Where is late?", "Turn left work."],
        0,
        "Ayer trabajé hasta tarde.",
        ["trabajar-preterite", "ayer"],
        3,
        "Ayer trabajé is the past tense; hasta tarde means 'until late'."
      ),
      {
        id: "u7l10-9",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "Last night I talked with Ana.",
        template: "Anoche ___ con Ana.",
        acceptedAnswers: ["hablé", "hable", "Hablé"],
        explanation: "Anoche hablé con Ana.",
        wordCardIds: ["hablar-preterite", "anoche"],
        xp: 3,
      },
      {
        id: "u7l10-10",
        type: "situational-choose",
        prompt: "Pick the best question.",
        situation: "Ask if they went downtown.",
        options: [
          "¿Fuiste al centro?",
          "¿Comes el centro?",
          "¿Dónde está el jugo centro?",
          "¿Me ducho el centro?",
        ],
        correctIndex: 0,
        hint: "You need fuiste (tú past of ir) — the others swap in the wrong verb.",
        explanation: "¿Fuiste al centro?",
        wordCardIds: ["ir", "el-centro"],
        xp: 3,
      },
    ],
  },

  "u7-l11": {
    id: "u7-l11",
    unitId: "unit-7",
    title: "Story: A busy yesterday",
    description: "A second story to listen to and fill in — chores, food, irregulars.",
    xpReward: 48,
    exercises: [
      storyListen(
        "u7l11-story",
        "Un ayer ocupado",
        [
          { text: "Esta mañana desayuné café en mi departamento.", en: "This morning I had coffee for breakfast in my apartment." },
          { text: "Luego fui al supermercado.", en: "Then I went to the supermarket." },
          { text: "Por la tarde limpié la cocina.", en: "In the afternoon I cleaned the kitchen." },
          { text: "Mi amigo vino a las seis.", en: "My friend came at six." },
          { text: "Anoche hicimos la tarea juntos.", en: "Last night we did homework together." },
        ],
        [
          {
            prompt: "What happened this morning?",
            options: ["Breakfast coffee at home", "Only metro forever", "Asked for the tip only", "Nothing"],
            correctIndex: 0,
            explanation: "Esta mañana desayuné café en mi departamento.",
          },
          {
            prompt: "Where did the narrator go next?",
            options: ["The supermarket", "Only the tip jar", "Only the bank tip", "Nowhere"],
            correctIndex: 0,
            explanation: "Luego fui al supermercado.",
          },
          {
            prompt: "What chore in the afternoon?",
            options: ["Cleaned the kitchen", "Ordered only juice forever", "Turned left", "Slept at the station"],
            correctIndex: 0,
            explanation: "Por la tarde limpié la cocina.",
          },
          {
            prompt: "What about the friend?",
            options: ["Came at six", "Ate the map", "Asked for the check only", "No friend"],
            correctIndex: 0,
            explanation: "Mi amigo vino a las seis.",
          },
        ],
        ["esta-manana", "desayunar-preterite", "cafe", "departamento", "ir", "limpiar-preterite", "cocina", "venir-preterite", "anoche", "hacer"],
        "You followed the whole story. Replay it anytime from the lesson.",
        12
      ),
      dictation(
        "u7l11-story-dict-1",
        "Esta mañana desayuné café en mi departamento.",
        ["Esta mañana desayuné café en mi departamento."],
        "Type the line you heard: Esta mañana desayuné café en mi departamento.",
        [],
        { hint: "Esta mañana opens it, then desayuné café (I had coffee for breakfast) + en mi departamento.", voice: "f", xp: 4 }
      ),
      dictation(
        "u7l11-story-dict-2",
        "Luego fui al supermercado.",
        ["Luego fui al supermercado."],
        "Type the line you heard: Luego fui al supermercado.",
        [],
        { hint: "Luego ('then'), then fui al supermercado (I went to the supermarket).", voice: "m", xp: 4 }
      ),
      {
        id: "u7l11-1",
        type: "select",
        prompt: "From the story — friend arrival used…",
        options: ["vino", "voy", "como", "la cuenta"],
        correctIndex: 0,
        hint: "Venir's él/ella past form is irregular — not voy, como, or la cuenta.",
        explanation: "vino (él/ella of venir past).",
        wordCardIds: ["venir-preterite"],
        xp: 3,
      },
      cloze(
        "u7l11-cloze-1",
        "Esta mañana ___ café en mi departamento.",
        ["desayuné", "desayune", "Desayuné"],
        "Esta mañana desayuné café en mi departamento.",
        ["esta-manana", "desayunar-preterite", "cafe", "departamento"],
        {
          hint: "I ate breakfast",
          audioText: "Esta mañana desayuné café en mi departamento.",
          voice: "f",
        }
      ),
      cloze(
        "u7l11-cloze-2",
        "Luego ___ al supermercado.",
        ["fui", "Fui"],
        "Luego fui al supermercado.",
        ["ir"],
        {
          audioText: "Luego fui al supermercado.",
          voice: "m",
        }
      ),
      cloze(
        "u7l11-cloze-3",
        "Anoche ___ la tarea juntos.",
        ["hicimos", "Hicimos"],
        "Anoche hicimos la tarea juntos.",
        ["anoche", "hacer"],
        {
          audioText: "Anoche hicimos la tarea juntos.",
          voice: "c",
        }
      ),
    ],
  },

  "u7-l12": {
    id: "u7-l12",
    unitId: "unit-7",
    title: "Unit 7 check",
    description: "Final check — past tense, the day's timeline, and story lines.",
    xpReward: 50,
    exercises: [
      {
        id: "u7l12-1",
        type: "select",
        prompt: "“I ate” is…",
        options: ["Como", "Comer", "Comí", "Comía only forever"],
        correctIndex: 2,
        hint: "Regular -er past-tense yo ending is -í, not the present or the infinitive.",
        explanation: "comí.",
        wordCardIds: ["comer"],
        xp: 3,
      },
      {
        id: "u7l12-2",
        type: "select",
        prompt: "“I came” is…",
        options: ["Vine", "Voy", "Fui always same meaning", "Como"],
        correctIndex: 0,
        hint: "Venir's irregular past yo form — not voy, fui, or como.",
        explanation: "vine.",
        wordCardIds: ["venir-preterite"],
        xp: 3,
      },
      {
        id: "u7l12-3",
        type: "tap-chips",
        prompt: "Build: “Last night I did the homework.”",
        chips: ["Anoche", "hice", "la", "tarea.", "metro", "jugo"],
        correctOrder: ["Anoche", "hice", "la", "tarea."],
        explanation: "Anoche hice la tarea.",
        wordCardIds: ["anoche", "hacer"],
        xp: 3,
      },
      {
        id: "u7l12-4",
        type: "translate",
        prompt: "Translate: “What did you do yesterday?”",
        acceptedAnswers: [
          "¿Qué hiciste ayer?",
          "Que hiciste ayer?",
          "¿Qué hiciste ayer",
          "Qué hiciste ayer",
        ],
        hint: "hiciste",
        explanation: "¿Qué hiciste ayer?",
        wordCardIds: ["hacer", "ayer"],
        xp: 4,
      },
      listen(
        "u7l12-5",
        "Fui al centro y hablé con Ana.",
        ["I went downtown and talked with Ana.", "I like Ana juice.", "Where is Ana?", "Turn left Ana."],
        0,
        "Fui al centro y hablé con Ana.",
        ["ir", "el-centro", "hablar-preterite"],
        3,
        "Fui...y hablé links two past-tense actions — going and talking."
      ),
      {
        id: "u7l12-6",
        type: "fill-blank",
        prompt: "Type the missing Spanish.",
        englishPrompt: "I had a meeting today.",
        template: "___ una reunión hoy.",
        acceptedAnswers: ["Tuve", "tuve"],
        explanation: "Tuve una reunión hoy.",
        wordCardIds: ["tener-preterite", "hoy"],
        xp: 3,
      },
      {
        id: "u7l12-7",
        type: "match-pairs",
        prompt: "Final Unit 7 match.",
        pairs: [
          { left: "fui", right: "I went" },
          { left: "dije", right: "I said" },
          { left: "anoche", right: "last night" },
          { left: "trabajé", right: "I worked" },
        ],
        explanation: "Core Unit 7 lemmas.",
        wordCardIds: ["ir", "decir", "anoche", "trabajar-preterite"],
        xp: 4,
      },
      {
        id: "u7l12-8",
        type: "situational-choose",
        prompt: "Pick the best line.",
        situation: "Friend asks what you ate this morning.",
        options: [
          "Desayuné café esta mañana.",
          "Me ducho café.",
          "Todo recto café.",
          "Soy el metro café.",
        ],
        correctIndex: 0,
        hint: "You need the past-tense desayunar form plus esta mañana — not ducharse or todo recto.",
        explanation: "Desayuné café esta mañana.",
        wordCardIds: ["desayunar-preterite", "cafe", "esta-manana"],
        xp: 3,
      },
      {
        id: "u7l12-9",
        type: "select",
        prompt: "Unit 4 reuse: “I cleaned the kitchen yesterday” is…",
        options: [
          "Ayer limpié la cocina.",
          "Ayer quiero la cocina metro.",
          "Ayer soy la cuenta.",
          "Ayer me gusta lejos cocina.",
        ],
        correctIndex: 0,
        hint: "A Unit 4 reuse — the past-tense limpiar form plus ayer, not querer or gustar.",
        explanation: "Ayer limpié la cocina.",
        wordCardIds: ["limpiar-preterite", "cocina", "ayer"],
        xp: 3,
      },
      {
        id: "u7l12-10",
        type: "situational-choose",
        prompt: "Pick the best answer.",
        situation: "Someone asks ¿Viniste ayer? You did.",
        options: ["Sí, vine.", "Sí, como.", "Sí, la cuenta.", "Sí, todo recto."],
        correctIndex: 0,
        hint: "Confirming with vine (past of venir) — not comer, la cuenta, or todo recto.",
        explanation: "Sí, vine.",
        wordCardIds: ["venir-preterite", "ayer"],
        xp: 3,
      },
      listen(
        "u7l12-11",
        "¿Qué hiciste anoche?",
        ["What did you do last night?", "What do you like?", "Where is last night?", "I want tacos."],
        0,
        "¿Qué hiciste anoche?",
        ["hacer", "anoche"],
        3,
        "Hiciste is 'you did'; anoche means 'last night'."
      ),
    ],
  },
};

export const UNIT7_LESSON_IDS = [
  "u7-l1",
  "u7-l2",
  "u7-l3",
  "u7-l4",
  "u7-l5",
  "u7-l6",
  "u7-l7",
  "u7-l8",
  "u7-l9",
  "u7-l10",
  "u7-l11",
  "u7-l12",
] as const;
