/**
 * Mock content for Uno (LatAm-neutral Spanish).
 * Later: replace with Postgres on Unraid :5433
 */
import type { DemoUser, Lesson, Unit, WordCard } from "./types";

export const DEMO_USER: DemoUser = {
  id: "demo-1",
  name: "",
  xp: 0,
  streak: 0,
  dailyGoal: 20,
  dailyXp: 0,
  completedLessonIds: [],
  weakWordIds: [],
  onboardingComplete: false,
  startingLevel: "absolute_beginner",
};

export const WORD_CARDS: Record<string, WordCard> = {

  "buenos-dias": {
    id: "buenos-dias",
    lemma: "buenos días",
    pos: "phrase",
    gender: "n/a",
    gloss: "good morning",
    meaningSummary: "A warm morning greeting used from waking until around noon. Literally “good days,” it’s the default polite hello before lunch across Latin America.",
    examples: [
      "¡Buenos días! ¿Cómo estás?",
      "Buenos días, señor López.",
    ],
    useWhen: "Greeting someone in the morning until around noon.",
    dontUseWhen: "Don't use after midday — switch to buenas tardes.",
    contrast: "buenas tardes (afternoon) / buenas noches (evening/night)",
    formality: "neutral",
    cefr: "A1",
  },

  "buenas-tardes": {
    id: "buenas-tardes",
    lemma: "buenas tardes",
    pos: "phrase",
    gender: "n/a",
    gloss: "good afternoon",
    meaningSummary: "The standard afternoon greeting from roughly noon until evening. Use it when buenos días no longer fits and it’s not yet dark enough for buenas noches.",
    examples: [
      "Buenas tardes, ¿en qué puedo ayudarte?",
      "¡Buenas tardes! Llegamos a tiempo.",
    ],
    useWhen: "Greeting from roughly noon until evening.",
    dontUseWhen: "Don't use in the morning (use buenos días) or late at night (buenas noches).",
    contrast: "buenos días / buenas noches",
    formality: "neutral",
    cefr: "A1",
  },

  "buenas-noches": {
    id: "buenas-noches",
    lemma: "buenas noches",
    pos: "phrase",
    gender: "n/a",
    gloss: "good evening / good night",
    meaningSummary: "Works as both an evening hello and a good-night farewell. Context and tone tell you whether someone is arriving or heading to bed.",
    examples: [
      "Buenas noches, que descanses.",
      "¡Buenas noches! Nos vemos mañana.",
    ],
    useWhen: "Greeting or farewell in the evening or before bed.",
    dontUseWhen: "Don't use as a morning greeting.",
    contrast: "buenos días / buenas tardes",
    formality: "neutral",
    cefr: "A1",
  },

  "mucho-gusto": {
    id: "mucho-gusto",
    lemma: "mucho gusto",
    pos: "phrase",
    gender: "n/a",
    gloss: "nice to meet you",
    meaningSummary: "The everyday “nice to meet you” after introductions. Short, friendly, and safe in almost any LatAm setting when you meet someone for the first time.",
    examples: [
      "Hola, soy Ana. ¡Mucho gusto!",
      "Mucho gusto, Carlos. Bienvenido.",
    ],
    useWhen: "When meeting someone for the first time.",
    dontUseWhen: "Don't use with people you already know well.",
    contrast: "encantado/a (also 'pleased to meet you', slightly more formal)",
    formality: "neutral",
    cefr: "A1",
  },

  "perdon": {
    id: "perdon",
    lemma: "perdón",
    pos: "interjection",
    gender: "m",
    gloss: "sorry / excuse me",
    meaningSummary: "A light apology and polite attention-getter. Use it when you bump someone, need to pass, or didn’t catch what was said — not for deep regret (prefer lo siento).",
    examples: [
      "Perdón, ¿dónde está el baño?",
      "¡Perdón! No te vi.",
    ],
    useWhen: "To apologize lightly or get someone's attention politely.",
    dontUseWhen: "For a deeper apology, prefer lo siento.",
    contrast: "disculpa / lo siento",
    formality: "neutral",
    cefr: "A1",
  },

  "hola": {
    id: "hola",
    lemma: "hola",
    pos: "interjection",
    gender: "n/a",
    gloss: "hello / hi",
    meaningSummary: "The universal casual hello — any time of day, friends or friendly strangers. In very formal writing you might prefer a time-of-day greeting instead.",
    examples: [
      "¡Hola! ¿Qué tal?",
      "Hola, me llamo Sofía.",
    ],
    useWhen: "Friendly greeting any time of day.",
    dontUseWhen: "In very formal written contexts, prefer a time-of-day greeting.",
    formality: "informal",
    cefr: "A1",
  },

  "como-estas": {
    id: "como-estas",
    lemma: "¿cómo estás?",
    pos: "phrase",
    gender: "n/a",
    gloss: "how are you?",
    meaningSummary: "Informal “how are you?” with tú. For strangers, elders, or workplace formality, switch to ¿cómo está? (usted).",
    examples: [
      "Hola, ¿cómo estás?",
      "¿Cómo estás hoy?",
    ],
    useWhen: "Informal check-in with friends, family, peers (tú).",
    dontUseWhen: "With strangers or formal situations — use ¿cómo está?",
    contrast: "¿cómo está? (formal usted)",
    formality: "informal",
    cefr: "A1",
  },

  "me-llamo": {
    id: "me-llamo",
    lemma: "llamarse",
    pos: "verb",
    gender: "n/a",
    gloss: "to be called / to be named",
    meaningSummary: "Reflexive verb for saying your name. Me llamo + name is the everyday introduction — never “soy llamo.” You’ll also hear ¿Cómo te llamas? for “What’s your name?”",
    conjugations: [
      {
        label: "Present indicative",
        forms: [
          { person: "yo", form: "me llamo" },
          { person: "tú", form: "te llamas" },
          { person: "él/ella/usted", form: "se llama" },
          { person: "nosotros/as", form: "nos llamamos" },
          { person: "ustedes", form: "se llaman" },
        ],
      },
    ],
    examples: [
      "Me llamo Diego.",
      "Hola, me llamo Valeria. Mucho gusto.",
    ],
    useWhen: "Introducing yourself by name.",
    dontUseWhen: "Don't say 'soy llamo' — that's a common learner error.",
    contrast: "mi nombre es… (also fine, a bit more formal)",
    formality: "neutral",
    cefr: "A1",
  },

  "gracias": {
    id: "gracias",
    lemma: "gracias",
    pos: "interjection",
    gender: "n/a",
    gloss: "thank you",
    meaningSummary: "The everyday thank-you. Add muchas for stronger gratitude. Pair with de nada when someone thanks you.",
    examples: [
      "Gracias por tu ayuda.",
      "¡Muchas gracias!",
    ],
    useWhen: "Any time you want to thank someone.",
    dontUseWhen: "n/a — always safe; add de nada as the reply.",
    contrast: "muchas gracias (stronger thanks)",
    formality: "neutral",
    cefr: "A1",
  },

  "de-nada": {
    id: "de-nada",
    lemma: "de nada",
    pos: "phrase",
    gender: "n/a",
    gloss: "you're welcome",
    meaningSummary: "The classic reply to gracias — literally “of nothing,” meaning it was no trouble. Friendly alternatives include con gusto and no hay de qué.",
    examples: [
      "—Gracias. —De nada.",
      "De nada, con gusto.",
    ],
    useWhen: "Responding to gracias.",
    dontUseWhen: "Don't use it as a greeting or standalone opener.",
    contrast: "con gusto / no hay de qué",
    formality: "neutral",
    region: "LatAm-wide; 'no hay de qué' also common",
    cefr: "A1",
  },

  "por": {
    id: "por",
    lemma: "por favor",
    pos: "phrase",
    gender: "n/a",
    gloss: "please",
    meaningSummary: "Softens requests and orders. Usually sits at the end (Un café, por favor) or the start; you don’t need it on every statement — only when asking.",
    examples: [
      "Un café, por favor.",
      "¿Me pasas el menú, por favor?",
    ],
    useWhen: "Softening requests and orders.",
    dontUseWhen: "Not needed for every statement — only requests.",
    formality: "neutral",
    cefr: "A1",
  },

  "adios": {
    id: "adios",
    lemma: "adiós",
    pos: "interjection",
    gender: "n/a",
    gloss: "goodbye",
    meaningSummary: "A clear goodbye, often when you won’t see someone soon. For a casual “see you later,” hasta luego or nos vemos feels warmer.",
    examples: [
      "Adiós, nos vemos pronto.",
      "¡Adiós! Que te vaya bien.",
    ],
    useWhen: "Saying goodbye, especially if you won't see them soon.",
    dontUseWhen: "For 'see you later', hasta luego is more natural.",
    contrast: "hasta luego / nos vemos",
    formality: "neutral",
    cefr: "A1",
  },

  "ser": {
    id: "ser",
    lemma: "ser",
    pos: "verb",
    gender: "n/a",
    gloss: "to be (identity / essence)",
    meaningSummary: "Ser covers identity, origin, profession, and lasting traits — who or what something is. Don’t confuse it with estar, which is for location and temporary states.",
    conjugations: [
      {
        label: "Present indicative",
        forms: [
          { person: "yo", form: "soy" },
          { person: "tú", form: "eres" },
          { person: "él/ella/usted", form: "es" },
          { person: "nosotros/as", form: "somos" },
          { person: "ustedes", form: "son" },
        ],
      },
    ],
    examples: [
      "Soy estudiante.",
      "Ella es de México.",
    ],
    useWhen: "Identity, origin, profession, permanent characteristics.",
    dontUseWhen: "Don't use for location or temporary feelings — use estar.",
    contrast: "estar (location / temporary states)",
    formality: "neutral",
    cefr: "A1",
  },

  "hablar": {
    id: "hablar",
    lemma: "hablar",
    pos: "verb",
    gender: "n/a",
    gloss: "to speak / to talk",
    meaningSummary: "Regular -ar verb for speaking a language or talking with someone. Hablo español / ¿Hablas inglés? are core A1 patterns.",
    conjugations: [
      {
        label: "Present indicative",
        forms: [
          { person: "yo", form: "hablo" },
          { person: "tú", form: "hablas" },
          { person: "él/ella/usted", form: "habla" },
          { person: "nosotros/as", form: "hablamos" },
          { person: "ustedes", form: "hablan" },
        ],
      },
    ],
    examples: [
      "Hablo un poco de español.",
      "¿Ustedes hablan inglés?",
    ],
    useWhen: "Talking about languages or the act of speaking.",
    dontUseWhen: "For 'say' a specific phrase, prefer decir.",
    contrast: "decir (to say) / platicar (chat, LatAm)",
    formality: "neutral",
    region: "LatAm; platicar is a common casual synonym for chatting",
    cefr: "A1",
  },

};


export const LESSONS: Record<string, Lesson> = {
  "u1-l1": {
    id: "u1-l1",
    unitId: "unit-1",
    title: "Greetings & first contact",
    description: "Say hello, introduce yourself, and stay polite.",
    xpReward: 25,
    exercises: [
      {
        id: "teach-u1l1-buenos-dias",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "buenos-dias",
        wordCardIds: ["buenos-dias"],
        xp: 0,
      },
      {
        id: "ex-1",
        type: "select",
        prompt: "How do you say “good morning” in Spanish?",
        options: ["Buenas noches", "Buenos días", "Hasta luego", "De nada"],
        correctIndex: 1,
        explanation:
          "Buenos días is the standard morning greeting across Latin America. Use it until around noon.",
        wordCardIds: ["buenos-dias"],
        xp: 3,
      },
      {
        id: "teach-u1l1-buenas-tardes",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "buenas-tardes",
        wordCardIds: ["buenas-tardes"],
        xp: 0,
      },
      {
        id: "ex-2",
        type: "situational-choose",
        prompt: "Pick the best greeting.",
        situation: "It's 3 p.m. You walk into a café and greet the barista.",
        options: ["Buenos días", "Buenas tardes", "Buenas noches", "Adiós"],
        correctIndex: 1,
        explanation:
          "At 3 p.m. you want buenas tardes. Buenos días is morning; buenas noches is evening/night.",
        wordCardIds: ["buenas-tardes"],
        xp: 3,
      },
      {
        id: "teach-u1l1-mucho-gusto",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "mucho-gusto",
        wordCardIds: ["mucho-gusto"],
        xp: 0,
      },
      {
        id: "ex-3",
        type: "listening-choose",
        prompt: "What did you hear?",
        audioText: "Mucho gusto",
        options: ["Mucho gusto", "Me llamo", "Por favor", "De nada"],
        correctIndex: 0,
        explanation:
          "Mucho gusto means “nice to meet you.” You'll hear it right after introductions.",
        wordCardIds: ["mucho-gusto"],
        xp: 3,
      },
      {
        id: "teach-u1l1-hola",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "hola",
        wordCardIds: ["hola"],
        xp: 0,
      },
      {
        id: "teach-u1l1-me-llamo",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "me-llamo",
        wordCardIds: ["me-llamo"],
        xp: 0,
      },
      {
        id: "ex-4",
        type: "tap-chips",
        prompt: "Build: “Hello, my name is Ana.”",
        chips: ["Ana", "Hola,", "me", "llamo", "días", "perdón"],
        correctOrder: ["Hola,", "me", "llamo", "Ana"],
        explanation:
          "Me llamo + name is the everyday way to introduce yourself. Avoid “soy llamo.”",
        wordCardIds: ["hola", "me-llamo"],
        xp: 4,
      },
      {
        id: "ex-5",
        type: "translate",
        prompt: "Translate to Spanish: “Nice to meet you.”",
        acceptedAnswers: [
          "mucho gusto",
          "¡mucho gusto!",
          "mucho gusto!",
          "encantado",
          "encantada",
        ],
        hint: "Two words; very common when meeting someone new.",
        explanation:
          "Mucho gusto is the go-to phrase when you meet someone. Encantado/a also works and feels a bit more formal.",
        wordCardIds: ["mucho-gusto"],
        xp: 4,
      },
      {
        id: "teach-u1l1-perdon",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "perdon",
        wordCardIds: ["perdon"],
        xp: 0,
      },
      {
        id: "ex-6",
        type: "select",
        prompt: "Which phrase means “excuse me / sorry” (light apology)?",
        options: ["Gracias", "Perdón", "Adiós", "Buenas noches"],
        correctIndex: 1,
        explanation:
          "Perdón covers “excuse me” and light “sorry.” For a deeper apology, use lo siento.",
        wordCardIds: ["perdon"],
        xp: 3,
      },
      {
        id: "teach-u1l1-gracias",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "gracias",
        wordCardIds: ["gracias"],
        xp: 0,
      },
      {
        id: "teach-u1l1-de-nada",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "de-nada",
        wordCardIds: ["de-nada"],
        xp: 0,
      },
      {
        id: "ex-7",
        type: "situational-choose",
        prompt: "What should you say?",
        situation:
          "Someone thanks you: “¡Gracias!” You want to reply “You're welcome.”",
        options: ["De nada", "Perdón", "Mucho gusto", "Buenos días"],
        correctIndex: 0,
        explanation:
          "De nada is the classic reply to gracias across LatAm. Con gusto is also friendly.",
        wordCardIds: ["de-nada", "gracias"],
        xp: 3,
      },
      {
        id: "teach-u1l1-buenas-noches",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "buenas-noches",
        wordCardIds: ["buenas-noches"],
        xp: 0,
      },
      {
        id: "ex-8",
        type: "listening-choose",
        prompt: "Listen and choose the matching meaning.",
        audioText: "Buenas noches",
        options: [
          "Good morning",
          "Good afternoon",
          "Good evening / good night",
          "See you later",
        ],
        correctIndex: 2,
        explanation:
          "Buenas noches works as both an evening greeting and a good-night farewell.",
        wordCardIds: ["buenas-noches"],
        xp: 3,
      },
      {
        id: "teach-u1l1-por",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "por",
        wordCardIds: ["por"],
        xp: 0,
      },
      {
        id: "ex-9",
        type: "tap-chips",
        prompt: "Build a polite request: “A coffee, please.”",
        chips: ["Un", "café,", "por", "favor", "jugo", "carro"],
        correctOrder: ["Un", "café,", "por", "favor"],
        explanation:
          "Por favor softens requests. (LatAm tip: juice is jugo, not zumo; car is carro.)",
        wordCardIds: ["por"],
        xp: 4,
      },
      {
        id: "ex-10",
        type: "translate",
        prompt: "Translate to Spanish: “Thank you.”",
        acceptedAnswers: [
          "gracias",
          "¡gracias!",
          "muchas gracias",
          "mil gracias",
        ],
        hint: "One word you'll use every day.",
        explanation:
          "Gracias is thank you; muchas gracias turns up the gratitude.",
        wordCardIds: ["gracias"],
        xp: 3,
      },
      {
        id: "teach-u1l1-como-estas",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "como-estas",
        wordCardIds: ["como-estas"],
        xp: 0,
      },
      {
        id: "ex-11",
        type: "select",
        prompt: "How do you casually ask a friend “How are you?”",
        options: [
          "¿Cómo está?",
          "¿Cómo estás?",
          "¿Qué llamo?",
          "¿Buenos días?",
        ],
        correctIndex: 1,
        explanation:
          "¿Cómo estás? uses tú (informal). With strangers or formal settings, prefer ¿cómo está?",
        wordCardIds: ["como-estas"],
        xp: 3,
      },
      {
        id: "teach-u1l1-adios",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "adios",
        wordCardIds: ["adios"],
        xp: 0,
      },
      {
        id: "ex-12",
        type: "situational-choose",
        prompt: "Choose the best farewell.",
        situation: "You're leaving a friend's house and will see them tomorrow.",
        options: ["Adiós", "Hasta luego", "Buenos días", "Perdón"],
        correctIndex: 1,
        explanation:
          "Hasta luego (“see you later”) fits when you'll meet again soon. Adiós can feel more final.",
        wordCardIds: ["adios"],
        xp: 3,
      },
    ],
  },
  "u1-l2": {
    id: "u1-l2",
    unitId: "unit-1",
    title: "Polite basics",
    description: "Practice apologies, thanks, and soft requests.",
    xpReward: 20,
    exercises: [
      {
        id: "teach-u1l2-perdon",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "perdon",
        wordCardIds: ["perdon"],
        xp: 0,
      },
      {
        id: "u1l2-1",
        type: "select",
        prompt: "Someone bumps into you lightly. What do they often say?",
        options: ["Mucho gusto", "Perdón", "Me llamo", "Buenas tardes"],
        correctIndex: 1,
        explanation: "Perdón is the quick, everyday “excuse me / sorry.”",
        wordCardIds: ["perdon"],
        xp: 3,
      },
      {
        id: "teach-u1l2-por",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "por",
        wordCardIds: ["por"],
        xp: 0,
      },
      {
        id: "u1l2-2",
        type: "translate",
        prompt: "Translate: “Please.”",
        acceptedAnswers: ["por favor", "porfa"],
        explanation: "Por favor goes at the end or start of a polite request.",
        wordCardIds: ["por"],
        xp: 3,
      },
      {
        id: "teach-u1l2-gracias",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "gracias",
        wordCardIds: ["gracias"],
        xp: 0,
      },
      {
        id: "u1l2-3",
        type: "listening-choose",
        prompt: "What did you hear?",
        audioText: "Gracias",
        options: ["Gracias", "De nada", "Hola", "Adiós"],
        correctIndex: 0,
        explanation: "Gracias = thank you.",
        wordCardIds: ["gracias"],
        xp: 3,
      },
      {
        id: "teach-u1l2-de-nada",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "de-nada",
        wordCardIds: ["de-nada"],
        xp: 0,
      },
      {
        id: "u1l2-4",
        type: "situational-choose",
        prompt: "Best reply?",
        situation: "A coworker says “¡Muchas gracias!”",
        options: ["De nada", "Buenos días", "Me llamo Alex", "Carro"],
        correctIndex: 0,
        explanation: "Answer thanks with de nada.",
        wordCardIds: ["de-nada"],
        xp: 3,
      },
      {
        id: "teach-u1l2-buenas-noches",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "buenas-noches",
        wordCardIds: ["buenas-noches"],
        xp: 0,
      },
      {
        id: "u1l2-5",
        type: "tap-chips",
        prompt: "Build: “Good evening.”",
        chips: ["Buenas", "noches", "días", "tardes", "jugo"],
        correctOrder: ["Buenas", "noches"],
        explanation: "Buenas noches for evening/night.",
        wordCardIds: ["buenas-noches"],
        xp: 3,
      },
      {
        id: "teach-u1l2-hola",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "hola",
        wordCardIds: ["hola"],
        xp: 0,
      },
      {
        id: "u1l2-6",
        type: "select",
        prompt: "Which is a friendly daytime hello?",
        options: ["Hola", "Departamento", "Celular", "Computadora"],
        correctIndex: 0,
        explanation:
          "Hola works any time. (LatAm vocab: departamento, celular, computadora — not piso/móvil/ordenador.)",
        wordCardIds: ["hola"],
        xp: 3,
      },
      {
        id: "teach-u1l2-buenas-tardes",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "buenas-tardes",
        wordCardIds: ["buenas-tardes"],
        xp: 0,
      },
      {
        id: "u1l2-7",
        type: "translate",
        prompt: "Translate: “Good afternoon.”",
        acceptedAnswers: [
          "buenas tardes",
          "¡buenas tardes!",
          "buenas tarde",
        ],
        explanation: "Buenas tardes from midday into the evening.",
        wordCardIds: ["buenas-tardes"],
        xp: 3,
      },
      {
        id: "teach-u1l2-mucho-gusto",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "mucho-gusto",
        wordCardIds: ["mucho-gusto"],
        xp: 0,
      },
      {
        id: "u1l2-8",
        type: "situational-choose",
        prompt: "You meet someone new at a meetup.",
        situation: "After saying your name, what do you add?",
        options: ["Mucho gusto", "Adiós", "Perdón", "De nada"],
        correctIndex: 0,
        explanation: "Mucho gusto = nice to meet you.",
        wordCardIds: ["mucho-gusto"],
        xp: 3,
      },
      {
        id: "u1l2-9",
        type: "translate",
        prompt: "Translate: “Excuse me” / light “sorry.”",
        acceptedAnswers: [
          "perdón",
          "perdon",
          "disculpe",
          "desculpe",
          "disculúlpame",
          "disculpame",
          "disculpa",
          "dispensa",
        ],
        hint: "Common light apology / attention-getter.",
        explanation:
          "Perdón is the everyday light “excuse me / sorry.” Disculpe / discúlpame and dispensa are also accepted near-synonyms.",
        wordCardIds: ["perdon"],
        xp: 3,
      },
    ],
  },
  "u2-l1": {
    id: "u2-l1",
    unitId: "unit-2",
    title: "Meeting people",
    description: "Names, introductions, and small talk openers.",
    xpReward: 25,
    exercises: [
      {
        id: "teach-u2l1-me-llamo",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "me-llamo",
        wordCardIds: ["me-llamo"],
        xp: 0,
      },
      {
        id: "teach-u2l1-ser",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "ser",
        wordCardIds: ["ser"],
        xp: 0,
      },
      {
        id: "u2l1-1",
        type: "select",
        prompt: "“My name is…” in Spanish is:",
        options: ["Me llamo…", "Yo nombre…", "Soy llamo…", "Te llamas…"],
        correctIndex: 0,
        explanation: "Me llamo + name. Never “soy llamo.”",
        wordCardIds: ["me-llamo"],
        xp: 3,
      },
      {
        id: "teach-u2l1-hola",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "hola",
        wordCardIds: ["hola"],
        xp: 0,
      },
      {
        id: "teach-u2l1-como-estas",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "como-estas",
        wordCardIds: ["como-estas"],
        xp: 0,
      },
      {
        id: "u2l1-2",
        type: "listening-choose",
        prompt: "What greeting did you hear?",
        audioText: "Hola, ¿cómo estás?",
        options: [
          "Hola, ¿cómo estás?",
          "Buenas noches",
          "Mucho gusto",
          "Por favor",
        ],
        correctIndex: 0,
        explanation: "A friendly informal check-in: Hola, ¿cómo estás?",
        wordCardIds: ["hola", "como-estas"],
        xp: 3,
      },
      {
        id: "teach-u2l1-mucho-gusto",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "mucho-gusto",
        wordCardIds: ["mucho-gusto"],
        xp: 0,
      },
      {
        id: "u2l1-3",
        type: "tap-chips",
        prompt: "Build: “Nice to meet you.”",
        chips: ["Mucho", "gusto", "nada", "perdón", "días"],
        correctOrder: ["Mucho", "gusto"],
        explanation: "Two-word classic for first meetings.",
        wordCardIds: ["mucho-gusto"],
        xp: 3,
      },
      {
        id: "u2l1-4",
        type: "translate",
        prompt: "Translate: “Hello.”",
        acceptedAnswers: ["hola", "¡hola!", "ola"],
        explanation: "Hola is the universal casual hello.",
        wordCardIds: ["hola"],
        xp: 2,
      },
      {
        id: "teach-u2l1-buenos-dias",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "buenos-dias",
        wordCardIds: ["buenos-dias"],
        xp: 0,
      },
      {
        id: "u2l1-5",
        type: "situational-choose",
        prompt: "It's 9 a.m. at the office.",
        situation: "You greet your manager as you arrive.",
        options: ["Buenos días", "Buenas noches", "Adiós", "De nada"],
        correctIndex: 0,
        explanation: "Morning → buenos días.",
        wordCardIds: ["buenos-dias"],
        xp: 3,
      },
      {
        id: "u2l1-6",
        type: "select",
        prompt: "Formal “How are you?” uses:",
        options: ["¿Cómo estás?", "¿Cómo está?", "¿Cómo soy?", "¿Qué tal tú?"],
        correctIndex: 1,
        explanation: "¿Cómo está? = usted (formal).",
        wordCardIds: ["como-estas"],
        xp: 3,
      },
      {
        id: "teach-u2l1-hablar",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "hablar",
        wordCardIds: ["hablar"],
        xp: 0,
      },
      {
        id: "u2l1-7",
        type: "listening-choose",
        prompt: "Match the audio.",
        audioText: "Me llamo Sofía",
        options: [
          "Me llamo Sofía",
          "Mucho gusto Sofía",
          "Perdón Sofía",
          "Gracias Sofía",
        ],
        correctIndex: 0,
        explanation: "Self-introduction with me llamo.",
        wordCardIds: ["me-llamo"],
        xp: 3,
      },
      {
        id: "teach-u2l1-adios",
        type: "teach",
        prompt: "New word — learn it, then practice.",
        explanation: "",
        wordCardId: "adios",
        wordCardIds: ["adios"],
        xp: 0,
      },
      {
        id: "u2l1-8",
        type: "translate",
        prompt: "Translate: “Goodbye.”",
        acceptedAnswers: [
          "adiós",
          "adios",
          "¡adiós!",
          "hasta luego",
          "nos vemos",
        ],
        explanation: "Adiós for goodbye; hasta luego if you'll see them soon.",
        wordCardIds: ["adios"],
        xp: 3,
      },
    ],
  },
};


export const UNITS: Unit[] = [
  {
    id: "unit-1",
    number: 1,
    title: "First contact",
    description: "Greetings, names, and polite essentials.",
    lessonIds: ["u1-l1", "u1-l2"],
    unlocked: true,
  },
  {
    id: "unit-2",
    number: 2,
    title: "Meeting people",
    description: "Introductions and friendly check-ins.",
    lessonIds: ["u2-l1"],
    unlocked: true,
  },
  {
    id: "unit-3",
    number: 3,
    title: "Around town",
    description: "Asking for places — carro, departamento, and more.",
    lessonIds: [],
    unlocked: false,
  },
  {
    id: "unit-4",
    number: 4,
    title: "Food & drink",
    description: "Order jugo, café, and everyday snacks.",
    lessonIds: [],
    unlocked: false,
  },
  {
    id: "unit-5",
    number: 5,
    title: "Tech talk",
    description: "Celular, computadora, and modern life vocab.",
    lessonIds: [],
    unlocked: false,
  },
];

export const DAILY_GOAL_OPTIONS = [10, 20, 30, 50] as const;

export function getWordCard(id: string): WordCard | undefined {
  return WORD_CARDS[id];
}

export function getLesson(id: string): Lesson | undefined {
  return LESSONS[id];
}

export function getAllWordCards(): WordCard[] {
  return Object.values(WORD_CARDS);
}
