/** Curated A1–B1 padding for Word of the Day (~500 pot with Word Cards). */

export interface WotdPadEntry {
  lemma: string;
  gloss: string;
  exampleEs: string;
  exampleEn: string;
}

export const WOTD_PAD: WotdPadEntry[] = [
  { lemma: "amigo", gloss: "friend (m.)", exampleEs: "Él es mi amigo.", exampleEn: "He is my friend." },
  { lemma: "amiga", gloss: "friend (f.)", exampleEs: "Ella es mi amiga.", exampleEn: "She is my friend." },
  { lemma: "familia", gloss: "family", exampleEs: "Mi familia es grande.", exampleEn: "My family is big." },
  { lemma: "padre", gloss: "father", exampleEs: "Mi padre trabaja mucho.", exampleEn: "My father works a lot." },
  { lemma: "madre", gloss: "mother", exampleEs: "Mi madre cocina bien.", exampleEn: "My mother cooks well." },
  { lemma: "hermano", gloss: "brother", exampleEs: "Tengo un hermano.", exampleEn: "I have a brother." },
  { lemma: "hermana", gloss: "sister", exampleEs: "Mi hermana estudia.", exampleEn: "My sister studies." },
  { lemma: "hijo", gloss: "son", exampleEs: "Su hijo tiene cinco años.", exampleEn: "His son is five years old." },
  { lemma: "hija", gloss: "daughter", exampleEs: "Su hija canta.", exampleEn: "Her daughter sings." },
  { lemma: "esposo", gloss: "husband", exampleEs: "Mi esposo llega tarde.", exampleEn: "My husband arrives late." },
  { lemma: "esposa", gloss: "wife", exampleEs: "Mi esposa es doctora.", exampleEn: "My wife is a doctor." },
  { lemma: "niño", gloss: "boy / child", exampleEs: "El niño juega.", exampleEn: "The boy plays." },
  { lemma: "niña", gloss: "girl", exampleEs: "La niña lee un libro.", exampleEn: "The girl reads a book." },
  { lemma: "persona", gloss: "person", exampleEs: "Es una persona amable.", exampleEn: "He/She is a kind person." },
  { lemma: "gente", gloss: "people", exampleEs: "Hay mucha gente aquí.", exampleEn: "There are a lot of people here." },
  { lemma: "nombre", gloss: "name", exampleEs: "¿Cuál es tu nombre?", exampleEn: "What is your name?" },
  { lemma: "edad", gloss: "age", exampleEs: "¿Qué edad tienes?", exampleEn: "How old are you?" },
  { lemma: "trabajo", gloss: "work / job", exampleEs: "Me gusta mi trabajo.", exampleEn: "I like my job." },
  { lemma: "oficina", gloss: "office", exampleEs: "Trabajo en una oficina.", exampleEn: "I work in an office." },
  { lemma: "escuela", gloss: "school", exampleEs: "Voy a la escuela.", exampleEn: "I go to school." },
  { lemma: "universidad", gloss: "university", exampleEs: "Estudio en la universidad.", exampleEn: "I study at the university." },
  { lemma: "estudiante", gloss: "student", exampleEs: "Soy estudiante.", exampleEn: "I am a student." },
  { lemma: "profesor", gloss: "teacher (m.)", exampleEs: "El profesor explica bien.", exampleEn: "The teacher explains well." },
  { lemma: "profesora", gloss: "teacher (f.)", exampleEs: "La profesora es patient.", exampleEn: "The teacher is patient." },
  { lemma: "doctor", gloss: "doctor (m.)", exampleEs: "El doctor llega mañana.", exampleEn: "The doctor arrives tomorrow." },
  { lemma: "doctora", gloss: "doctor (f.)", exampleEs: "La doctora me ayuda.", exampleEn: "The doctor helps me." },
  { lemma: "vecino", gloss: "neighbor (m.)", exampleEs: "Mi vecino es simpático.", exampleEn: "My neighbor is nice." },
  { lemma: "casa", gloss: "house / home", exampleEs: "Vivo en una casa pequeña.", exampleEn: "I live in a small house." },
  { lemma: "ciudad", gloss: "city", exampleEs: "La ciudad es grande.", exampleEn: "The city is big." },
  { lemma: "pueblo", gloss: "town", exampleEs: "Soy de un pueblo pequeño.", exampleEn: "I'm from a small town." },
  { lemma: "país", gloss: "country", exampleEs: "Este país es hermoso.", exampleEn: "This country is beautiful." },
  { lemma: "calle", gloss: "street", exampleEs: "Vivo en esta calle.", exampleEn: "I live on this street." },
  { lemma: "dirección", gloss: "address", exampleEs: "¿Cuál es tu dirección?", exampleEn: "What is your address?" },
  { lemma: "mapa", gloss: "map", exampleEs: "Necesito un mapa.", exampleEn: "I need a map." },
  { lemma: "hoy", gloss: "today", exampleEs: "Hoy estoy ocupado.", exampleEn: "Today I am busy." },
  { lemma: "ayer", gloss: "yesterday", exampleEs: "Ayer fui al mercado.", exampleEn: "Yesterday I went to the market." },
  { lemma: "mañana", gloss: "tomorrow / morning", exampleEs: "Mañana voy al doctor.", exampleEn: "Tomorrow I'm going to the doctor." },
  { lemma: "noche", gloss: "night", exampleEs: "Por la noche descanso.", exampleEn: "At night I rest." },
  { lemma: "tarde", gloss: "afternoon / late", exampleEs: "Llego tarde.", exampleEn: "I arrive late." },
  { lemma: "semana", gloss: "week", exampleEs: "Esta semana estudio mucho.", exampleEn: "This week I study a lot." },
  { lemma: "mes", gloss: "month", exampleEs: "El mes pasado viajé.", exampleEn: "Last month I traveled." },
  { lemma: "año", gloss: "year", exampleEs: "Este año aprendo español.", exampleEn: "This year I'm learning Spanish." },
  { lemma: "hora", gloss: "hour / time", exampleEs: "¿Qué hora es?", exampleEn: "What time is it?" },
  { lemma: "minuto", gloss: "minute", exampleEs: "Espera un minuto.", exampleEn: "Wait a minute." },
  { lemma: "segundo", gloss: "second", exampleEs: "Un segundo, por favor.", exampleEn: "One second, please." },
  { lemma: "lunes", gloss: "Monday", exampleEs: "El lunes trabajo.", exampleEn: "On Monday I work." },
  { lemma: "martes", gloss: "Tuesday", exampleEs: "El martes tengo clase.", exampleEn: "On Tuesday I have class." },
  { lemma: "miércoles", gloss: "Wednesday", exampleEs: "El miércoles salgo temprano.", exampleEn: "On Wednesday I leave early." },
  { lemma: "jueves", gloss: "Thursday", exampleEs: "El jueves cocino.", exampleEn: "On Thursday I cook." },
  { lemma: "viernes", gloss: "Friday", exampleEs: "El viernes salimos.", exampleEn: "On Friday we go out." },
  { lemma: "sábado", gloss: "Saturday", exampleEs: "El sábado descanso.", exampleEn: "On Saturday I rest." },
  { lemma: "domingo", gloss: "Sunday", exampleEs: "El domingo veo a mi familia.", exampleEn: "On Sunday I see my family." },
  { lemma: "siempre", gloss: "always", exampleEs: "Siempre desayuno café.", exampleEn: "I always have coffee for breakfast." },
  { lemma: "nunca", gloss: "never", exampleEs: "Nunca fumo.", exampleEn: "I never smoke." },
  { lemma: "a veces", gloss: "sometimes", exampleEs: "A veces camino al trabajo.", exampleEn: "Sometimes I walk to work." },
  { lemma: "ahora", gloss: "now", exampleEs: "Ahora estoy libre.", exampleEn: "Now I am free." },
  { lemma: "después", gloss: "after / later", exampleEs: "Después voy al gimnasio.", exampleEn: "Later I'm going to the gym." },
  { lemma: "antes", gloss: "before", exampleEs: "Antes de comer, lavo las manos.", exampleEn: "Before eating, I wash my hands." },
  { lemma: "temprano", gloss: "early", exampleEs: "Me levanto temprano.", exampleEn: "I get up early." },
  { lemma: "pronto", gloss: "soon", exampleEs: "Llego pronto.", exampleEn: "I'll arrive soon." },
  { lemma: "ya", gloss: "already / now", exampleEs: "Ya terminé.", exampleEn: "I already finished." },
  { lemma: "todavía", gloss: "still / yet", exampleEs: "Todavía estoy aquí.", exampleEn: "I'm still here." },
  { lemma: "tener", gloss: "to have", exampleEs: "Tengo dos hermanos.", exampleEn: "I have two brothers." },
  { lemma: "hacer", gloss: "to do / to make", exampleEs: "¿Qué haces?", exampleEn: "What are you doing?" },
  { lemma: "ir", gloss: "to go", exampleEs: "Voy al mercado.", exampleEn: "I'm going to the market." },
  { lemma: "venir", gloss: "to come", exampleEs: "¿Vienes conmigo?", exampleEn: "Are you coming with me?" },
  { lemma: "ver", gloss: "to see", exampleEs: "Veo la televisión.", exampleEn: "I watch TV." },
  { lemma: "mirar", gloss: "to look / watch", exampleEs: "Miro las fotos.", exampleEn: "I look at the photos." },
  { lemma: "oír", gloss: "to hear", exampleEs: "Oigo música.", exampleEn: "I hear music." },
  { lemma: "escuchar", gloss: "to listen", exampleEs: "Escucho la radio.", exampleEn: "I listen to the radio." },
  { lemma: "hablar", gloss: "to speak / talk", exampleEs: "Hablo con mi amigo.", exampleEn: "I talk with my friend." },
  { lemma: "decir", gloss: "to say / tell", exampleEs: "¿Qué dices?", exampleEn: "What are you saying?" },
  { lemma: "pensar", gloss: "to think", exampleEs: "Pienso en ti.", exampleEn: "I think about you." },
  { lemma: "saber", gloss: "to know (facts)", exampleEs: "No sé la respuesta.", exampleEn: "I don't know the answer." },
  { lemma: "conocer", gloss: "to know / meet (people/places)", exampleEs: "Conozco esta ciudad.", exampleEn: "I know this city." },
  { lemma: "querer", gloss: "to want / love", exampleEs: "Quiero agua.", exampleEn: "I want water." },
  { lemma: "poder", gloss: "to be able to / can", exampleEs: "¿Puedes ayudarme?", exampleEn: "Can you help me?" },
  { lemma: "deber", gloss: "should / must", exampleEs: "Debo estudiar.", exampleEn: "I should study." },
  { lemma: "necesitar", gloss: "to need", exampleEs: "Necesito ayuda.", exampleEn: "I need help." },
  { lemma: "gustar", gloss: "to like", exampleEs: "Me gusta el café.", exampleEn: "I like coffee." },
  { lemma: "preferir", gloss: "to prefer", exampleEs: "Prefiero té.", exampleEn: "I prefer tea." },
  { lemma: "empezar", gloss: "to start", exampleEs: "Empezamos ahora.", exampleEn: "We start now." },
  { lemma: "terminar", gloss: "to finish", exampleEs: "Termino a las cinco.", exampleEn: "I finish at five." },
  { lemma: "abrir", gloss: "to open", exampleEs: "Abre la puerta.", exampleEn: "Open the door." },
  { lemma: "cerrar", gloss: "to close", exampleEs: "Cierra la ventana.", exampleEn: "Close the window." },
  { lemma: "entrar", gloss: "to enter", exampleEs: "Entro en la tienda.", exampleEn: "I enter the store." },
  { lemma: "salir", gloss: "to leave / go out", exampleEs: "Salgo a las ocho.", exampleEn: "I leave at eight." },
  { lemma: "llegar", gloss: "to arrive", exampleEs: "Llego temprano.", exampleEn: "I arrive early." },
  { lemma: "volver", gloss: "to return", exampleEs: "Vuelvo mañana.", exampleEn: "I return tomorrow." },
  { lemma: "traer", gloss: "to bring", exampleEs: "Traigo pan.", exampleEn: "I'm bringing bread." },
  { lemma: "llevar", gloss: "to take / wear / carry", exampleEs: "Llevo una chaqueta.", exampleEn: "I'm wearing a jacket." },
  { lemma: "dar", gloss: "to give", exampleEs: "Te doy mi número.", exampleEn: "I'll give you my number." },
  { lemma: "recibir", gloss: "to receive", exampleEs: "Recibo un mensaje.", exampleEn: "I receive a message." },
  { lemma: "llamar", gloss: "to call", exampleEs: "Te llamo luego.", exampleEn: "I'll call you later." },
  { lemma: "esperar", gloss: "to wait / hope", exampleEs: "Espero el autobús.", exampleEn: "I'm waiting for the bus." },
  { lemma: "buscar", gloss: "to look for", exampleEs: "Busco mis llaves.", exampleEn: "I'm looking for my keys." },
  { lemma: "encontrar", gloss: "to find", exampleEs: "Encuentro el libro.", exampleEn: "I find the book." },
  { lemma: "perder", gloss: "to lose / miss", exampleEs: "Pierdo el tren.", exampleEn: "I miss the train." },
  { lemma: "ganar", gloss: "to win / earn", exampleEs: "Gano poco dinero.", exampleEn: "I earn little money." },
  { lemma: "pagar", gloss: "to pay", exampleEs: "Pago con tarjeta.", exampleEn: "I pay with a card." },
  { lemma: "comprar", gloss: "to buy", exampleEs: "Compro fruta.", exampleEn: "I buy fruit." },
  { lemma: "vender", gloss: "to sell", exampleEs: "Venden café aquí.", exampleEn: "They sell coffee here." },
  { lemma: "costar", gloss: "to cost", exampleEs: "¿Cuánto cuesta?", exampleEn: "How much does it cost?" },
  { lemma: "usar", gloss: "to use", exampleEs: "Uso mi teléfono.", exampleEn: "I use my phone." },
  { lemma: "trabajar", gloss: "to work", exampleEs: "Trabajo de lunes a viernes.", exampleEn: "I work Monday to Friday." },
  { lemma: "estudiar", gloss: "to study", exampleEs: "Estudio español.", exampleEn: "I study Spanish." },
  { lemma: "aprender", gloss: "to learn", exampleEs: "Aprendo rápido.", exampleEn: "I learn quickly." },
  { lemma: "enseñar", gloss: "to teach", exampleEs: "Ella enseña inglés.", exampleEn: "She teaches English." },
  { lemma: "leer", gloss: "to read", exampleEs: "Leo cada noche.", exampleEn: "I read every night." },
  { lemma: "escribir", gloss: "to write", exampleEs: "Escribo un mensaje.", exampleEn: "I write a message." },
  { lemma: "comer", gloss: "to eat", exampleEs: "Como fruta.", exampleEn: "I eat fruit." },
  { lemma: "beber", gloss: "to drink", exampleEs: "Bebo agua.", exampleEn: "I drink water." },
  { lemma: "cocinar", gloss: "to cook", exampleEs: "Cocino en casa.", exampleEn: "I cook at home." },
  { lemma: "desayunar", gloss: "to have breakfast", exampleEs: "Desayuno a las siete.", exampleEn: "I have breakfast at seven." },
  { lemma: "almorzar", gloss: "to have lunch", exampleEs: "Almuerzo con amigos.", exampleEn: "I have lunch with friends." },
  { lemma: "cenar", gloss: "to have dinner", exampleEs: "Cenamos juntos.", exampleEn: "We have dinner together." },
  { lemma: "dormir", gloss: "to sleep", exampleEs: "Duermo ocho horas.", exampleEn: "I sleep eight hours." },
  { lemma: "despertar", gloss: "to wake (someone)", exampleEs: "El ruido me despierta.", exampleEn: "The noise wakes me." },
  { lemma: "levantarse", gloss: "to get up", exampleEs: "Me levanto a las seis.", exampleEn: "I get up at six." },
  { lemma: "bañarse", gloss: "to bathe", exampleEs: "Me baño por la mañana.", exampleEn: "I bathe in the morning." },
  { lemma: "ducharse", gloss: "to shower", exampleEs: "Me ducho rápido.", exampleEn: "I shower quickly." },
  { lemma: "vestirse", gloss: "to get dressed", exampleEs: "Me visto en cinco minutos.", exampleEn: "I get dressed in five minutes." },
  { lemma: "lavar", gloss: "to wash", exampleEs: "Lavo los platos.", exampleEn: "I wash the dishes." },
  { lemma: "limpiar", gloss: "to clean", exampleEs: "Limpio la cocina.", exampleEn: "I clean the kitchen." },
  { lemma: "caminar", gloss: "to walk", exampleEs: "Camino al parque.", exampleEn: "I walk to the park." },
  { lemma: "correr", gloss: "to run", exampleEs: "Corro en el parque.", exampleEn: "I run in the park." },
  { lemma: "viajar", gloss: "to travel", exampleEs: "Viajo en verano.", exampleEn: "I travel in summer." },
  { lemma: "visitar", gloss: "to visit", exampleEs: "Visito a mis abuelos.", exampleEn: "I visit my grandparents." },
  { lemma: "quedarse", gloss: "to stay", exampleEs: "Me quedo en casa.", exampleEn: "I stay home." },
  { lemma: "vivir", gloss: "to live", exampleEs: "Vivo cerca del centro.", exampleEn: "I live near downtown." },
  { lemma: "nacer", gloss: "to be born", exampleEs: "Nací en México.", exampleEn: "I was born in Mexico." },
  { lemma: "morir", gloss: "to die", exampleEs: "La planta se murió.", exampleEn: "The plant died." },
  { lemma: "sentir", gloss: "to feel", exampleEs: "Siento frío.", exampleEn: "I feel cold." },
  { lemma: "creer", gloss: "to believe / think", exampleEs: "Creo que sí.", exampleEn: "I think so." },
  { lemma: "entender", gloss: "to understand", exampleEs: "No entiendo.", exampleEn: "I don't understand." },
  { lemma: "explicar", gloss: "to explain", exampleEs: "¿Me puedes explicar?", exampleEn: "Can you explain to me?" },
  { lemma: "preguntar", gloss: "to ask (a question)", exampleEs: "Pregunto la hora.", exampleEn: "I ask the time." },
  { lemma: "responder", gloss: "to answer", exampleEs: "Respondo el correo.", exampleEn: "I answer the email." },
  { lemma: "ayudar", gloss: "to help", exampleEs: "¿Me puedes ayudar?", exampleEn: "Can you help me?" },
  { lemma: "cambiar", gloss: "to change", exampleEs: "Cambio de ropa.", exampleEn: "I change clothes." },
  { lemma: "probar", gloss: "to try / taste", exampleEs: "Pruebo la sopa.", exampleEn: "I taste the soup." },
  { lemma: "tocar", gloss: "to touch / play (instrument)", exampleEs: "Toco la guitarra.", exampleEn: "I play the guitar." },
  { lemma: "jugar", gloss: "to play (games)", exampleEs: "Juego fútbol.", exampleEn: "I play soccer." },
  { lemma: "cantar", gloss: "to sing", exampleEs: "Ella canta bien.", exampleEn: "She sings well." },
  { lemma: "bailar", gloss: "to dance", exampleEs: "Bailamos en la fiesta.", exampleEn: "We dance at the party." },
  { lemma: "reír", gloss: "to laugh", exampleEs: "Nos reímos mucho.", exampleEn: "We laugh a lot." },
  { lemma: "llorar", gloss: "to cry", exampleEs: "El bebé llora.", exampleEn: "The baby cries." },
  { lemma: "sonreír", gloss: "to smile", exampleEs: "Ella sonríe siempre.", exampleEn: "She always smiles." },
  { lemma: "amar", gloss: "to love", exampleEs: "Amo a mi familia.", exampleEn: "I love my family." },
  { lemma: "odiar", gloss: "to hate", exampleEs: "Odio madrugar.", exampleEn: "I hate getting up early." },
  { lemma: "olvidar", gloss: "to forget", exampleEs: "Olvido el nombre.", exampleEn: "I forget the name." },
  { lemma: "recordar", gloss: "to remember", exampleEs: "Recuerdo tu cara.", exampleEn: "I remember your face." },
  { lemma: "decidir", gloss: "to decide", exampleEs: "Decido quedarme.", exampleEn: "I decide to stay." },
  { lemma: "intentar", gloss: "to try", exampleEs: "Intento hablar español.", exampleEn: "I try to speak Spanish." },
  { lemma: "permitir", gloss: "to allow", exampleEs: "No permiten fumar.", exampleEn: "They don't allow smoking." },
  { lemma: "invitar", gloss: "to invite", exampleEs: "Te invito a cenar.", exampleEn: "I invite you to dinner." },
  { lemma: "aceptar", gloss: "to accept", exampleEs: "Acepto la invitación.", exampleEn: "I accept the invitation." },
  { lemma: "rechazar", gloss: "to reject", exampleEs: "Rechazo la oferta.", exampleEn: "I reject the offer." },
  { lemma: "prometer", gloss: "to promise", exampleEs: "Prometo llegar temprano.", exampleEn: "I promise to arrive early." },
  { lemma: "cumplir", gloss: "to fulfill / turn (age)", exampleEs: "Cumplo treinta años.", exampleEn: "I turn thirty." },
  { lemma: "celebrar", gloss: "to celebrate", exampleEs: "Celebramos tu cumpleaños.", exampleEn: "We celebrate your birthday." },
  { lemma: "agua", gloss: "water", exampleEs: "Quiero un vaso de agua.", exampleEn: "I want a glass of water." },
  { lemma: "café", gloss: "coffee", exampleEs: "Un café, por favor.", exampleEn: "A coffee, please." },
  { lemma: "té", gloss: "tea", exampleEs: "Prefiero té verde.", exampleEn: "I prefer green tea." },
  { lemma: "leche", gloss: "milk", exampleEs: "La leche está fría.", exampleEn: "The milk is cold." },
  { lemma: "jugo", gloss: "juice", exampleEs: "Un jugo de naranja.", exampleEn: "An orange juice." },
  { lemma: "pan", gloss: "bread", exampleEs: "Compro pan fresco.", exampleEn: "I buy fresh bread." },
  { lemma: "arroz", gloss: "rice", exampleEs: "El arroz está listo.", exampleEn: "The rice is ready." },
  { lemma: "pollo", gloss: "chicken", exampleEs: "Como pollo asado.", exampleEn: "I eat roast chicken." },
  { lemma: "carne", gloss: "meat", exampleEs: "No como carne.", exampleEn: "I don't eat meat." },
  { lemma: "pescado", gloss: "fish (food)", exampleEs: "El pescado es fresco.", exampleEn: "The fish is fresh." },
  { lemma: "huevo", gloss: "egg", exampleEs: "Dos huevos, por favor.", exampleEn: "Two eggs, please." },
  { lemma: "queso", gloss: "cheese", exampleEs: "Me gusta el queso.", exampleEn: "I like cheese." },
  { lemma: "fruta", gloss: "fruit", exampleEs: "Como fruta cada día.", exampleEn: "I eat fruit every day." },
  { lemma: "manzana", gloss: "apple", exampleEs: "Una manzana roja.", exampleEn: "A red apple." },
  { lemma: "plátano", gloss: "banana", exampleEs: "Como un plátano.", exampleEn: "I eat a banana." },
  { lemma: "naranja", gloss: "orange (fruit)", exampleEs: "Esta naranja es dulce.", exampleEn: "This orange is sweet." },
  { lemma: "verdura", gloss: "vegetable", exampleEs: "Como más verdura.", exampleEn: "I eat more vegetables." },
  { lemma: "ensalada", gloss: "salad", exampleEs: "Una ensalada mixta.", exampleEn: "A mixed salad." },
  { lemma: "sopa", gloss: "soup", exampleEs: "La sopa está caliente.", exampleEn: "The soup is hot." },
  { lemma: "comida", gloss: "food / meal", exampleEs: "La comida está rica.", exampleEn: "The food is tasty." },
  { lemma: "cena", gloss: "dinner", exampleEs: "La cena es a las ocho.", exampleEn: "Dinner is at eight." },
  { lemma: "almuerzo", gloss: "lunch", exampleEs: "El almuerzo fue rápido.", exampleEn: "Lunch was quick." },
  { lemma: "desayuno", gloss: "breakfast", exampleEs: "El desayuno es importante.", exampleEn: "Breakfast is important." },
  { lemma: "azúcar", gloss: "sugar", exampleEs: "Sin azúcar, por favor.", exampleEn: "No sugar, please." },
  { lemma: "sal", gloss: "salt", exampleEs: "Pasa la sal.", exampleEn: "Pass the salt." },
  { lemma: "pimienta", gloss: "pepper", exampleEs: "Un poco de pimienta.", exampleEn: "A little pepper." },
  { lemma: "aceite", gloss: "oil", exampleEs: "Aceite de oliva.", exampleEn: "Olive oil." },
  { lemma: "mantequilla", gloss: "butter", exampleEs: "Pan con mantequilla.", exampleEn: "Bread with butter." },
  { lemma: "chocolate", gloss: "chocolate", exampleEs: "Me encanta el chocolate.", exampleEn: "I love chocolate." },
  { lemma: "helado", gloss: "ice cream", exampleEs: "Un helado de vainilla.", exampleEn: "A vanilla ice cream." },
  { lemma: "postre", gloss: "dessert", exampleEs: "¿Quieres postre?", exampleEn: "Do you want dessert?" },
  { lemma: "cuenta", gloss: "bill / check", exampleEs: "La cuenta, por favor.", exampleEn: "The check, please." },
  { lemma: "menú", gloss: "menu", exampleEs: "¿Me trae el menú?", exampleEn: "Can you bring me the menu?" },
  { lemma: "restaurante", gloss: "restaurant", exampleEs: "Vamos a un restaurante.", exampleEn: "Let's go to a restaurant." },
  { lemma: "cocina", gloss: "kitchen / cuisine", exampleEs: "La cocina está limpia.", exampleEn: "The kitchen is clean." },
  { lemma: "plato", gloss: "plate / dish", exampleEs: "Este plato es delicioso.", exampleEn: "This dish is delicious." },
  { lemma: "vaso", gloss: "glass (cup)", exampleEs: "Un vaso de agua.", exampleEn: "A glass of water." },
  { lemma: "taza", gloss: "cup", exampleEs: "Una taza de café.", exampleEn: "A cup of coffee." },
  { lemma: "cuchara", gloss: "spoon", exampleEs: "Necesito una cuchara.", exampleEn: "I need a spoon." },
  { lemma: "tenedor", gloss: "fork", exampleEs: "Pásame el tenedor.", exampleEn: "Pass me the fork." },
  { lemma: "cuchillo", gloss: "knife", exampleEs: "Cuidado con el cuchillo.", exampleEn: "Careful with the knife." },
  { lemma: "aeropuerto", gloss: "airport", exampleEs: "Voy al aeropuerto.", exampleEn: "I'm going to the airport." },
  { lemma: "estación", gloss: "station", exampleEs: "La estación está cerca.", exampleEn: "The station is nearby." },
  { lemma: "hotel", gloss: "hotel", exampleEs: "Reservamos un hotel.", exampleEn: "We book a hotel." },
  { lemma: "habitación", gloss: "room", exampleEs: "La habitación es grande.", exampleEn: "The room is big." },
  { lemma: "baño", gloss: "bathroom", exampleEs: "¿Dónde está el baño?", exampleEn: "Where is the bathroom?" },
  { lemma: "tienda", gloss: "store / shop", exampleEs: "Compro en esa tienda.", exampleEn: "I shop at that store." },
  { lemma: "supermercado", gloss: "supermarket", exampleEs: "Voy al supermercado.", exampleEn: "I'm going to the supermarket." },
  { lemma: "mercado", gloss: "market", exampleEs: "El mercado abre temprano.", exampleEn: "The market opens early." },
  { lemma: "farmacia", gloss: "pharmacy", exampleEs: "Necesito la farmacia.", exampleEn: "I need the pharmacy." },
  { lemma: "banco", gloss: "bank", exampleEs: "Voy al banco.", exampleEn: "I'm going to the bank." },
  { lemma: "correo", gloss: "mail / post office", exampleEs: "Mando el correo hoy.", exampleEn: "I'm sending the mail today." },
  { lemma: "parque", gloss: "park", exampleEs: "Corro en el parque.", exampleEn: "I run in the park." },
  { lemma: "playa", gloss: "beach", exampleEs: "La playa está limpia.", exampleEn: "The beach is clean." },
  { lemma: "montaña", gloss: "mountain", exampleEs: "Subimos la montaña.", exampleEn: "We climb the mountain." },
  { lemma: "río", gloss: "river", exampleEs: "El río es largo.", exampleEn: "The river is long." },
  { lemma: "mar", gloss: "sea", exampleEs: "El mar está azul.", exampleEn: "The sea is blue." },
  { lemma: "bosque", gloss: "forest", exampleEs: "Caminamos por el bosque.", exampleEn: "We walk through the forest." },
  { lemma: "puente", gloss: "bridge", exampleEs: "Cruzamos el puente.", exampleEn: "We cross the bridge." },
  { lemma: "plaza", gloss: "plaza / square", exampleEs: "Nos vemos en la plaza.", exampleEn: "We'll meet in the plaza." },
  { lemma: "iglesia", gloss: "church", exampleEs: "La iglesia es antigua.", exampleEn: "The church is old." },
  { lemma: "museo", gloss: "museum", exampleEs: "Visitamos el museo.", exampleEn: "We visit the museum." },
  { lemma: "cine", gloss: "movie theater", exampleEs: "Vamos al cine.", exampleEn: "We're going to the movies." },
  { lemma: "teatro", gloss: "theater", exampleEs: "El teatro está lleno.", exampleEn: "The theater is full." },
  { lemma: "hospital", gloss: "hospital", exampleEs: "Trabaja en el hospital.", exampleEn: "He/She works at the hospital." },
  { lemma: "clínica", gloss: "clinic", exampleEs: "Tengo cita en la clínica.", exampleEn: "I have an appointment at the clinic." },
  { lemma: "gimnasio", gloss: "gym", exampleEs: "Voy al gimnasio.", exampleEn: "I go to the gym." },
  { lemma: "biblioteca", gloss: "library", exampleEs: "Estudio en la biblioteca.", exampleEn: "I study at the library." },
  { lemma: "librería", gloss: "bookstore", exampleEs: "Compro libros en la librería.", exampleEn: "I buy books at the bookstore." },
  { lemma: "estación de metro", gloss: "metro station", exampleEs: "La estación de metro está lejos.", exampleEn: "The metro station is far." },
  { lemma: "parada", gloss: "stop (bus)", exampleEs: "Espero en la parada.", exampleEn: "I wait at the stop." },
  { lemma: "billete", gloss: "ticket", exampleEs: "Compro un billete.", exampleEn: "I buy a ticket." },
  { lemma: "pasaporte", gloss: "passport", exampleEs: "¿Dónde está mi pasaporte?", exampleEn: "Where is my passport?" },
  { lemma: "maleta", gloss: "suitcase", exampleEs: "Mi maleta es pesada.", exampleEn: "My suitcase is heavy." },
  { lemma: "viaje", gloss: "trip", exampleEs: "El viaje fue largo.", exampleEn: "The trip was long." },
  { lemma: "vacaciones", gloss: "vacation", exampleEs: "Estoy de vacaciones.", exampleEn: "I'm on vacation." },
  { lemma: "llave", gloss: "key", exampleEs: "Perdí la llave.", exampleEn: "I lost the key." },
  { lemma: "puerta", gloss: "door", exampleEs: "Cierra la puerta.", exampleEn: "Close the door." },
  { lemma: "ventana", gloss: "window", exampleEs: "Abre la ventana.", exampleEn: "Open the window." },
  { lemma: "mesa", gloss: "table", exampleEs: "La mesa está puesta.", exampleEn: "The table is set." },
  { lemma: "silla", gloss: "chair", exampleEs: "Siéntate en la silla.", exampleEn: "Sit on the chair." },
  { lemma: "cama", gloss: "bed", exampleEs: "La cama es cómoda.", exampleEn: "The bed is comfortable." },
  { lemma: "sofá", gloss: "sofa", exampleEs: "Me siento en el sofá.", exampleEn: "I sit on the sofa." },
  { lemma: "luz", gloss: "light", exampleEs: "Enciende la luz.", exampleEn: "Turn on the light." },
  { lemma: "agua caliente", gloss: "hot water", exampleEs: "No hay agua caliente.", exampleEn: "There's no hot water." },
  { lemma: "jabón", gloss: "soap", exampleEs: "¿Dónde está el jabón?", exampleEn: "Where is the soap?" },
  { lemma: "toalla", gloss: "towel", exampleEs: "Necesito una toalla.", exampleEn: "I need a towel." },
  { lemma: "ropa", gloss: "clothes", exampleEs: "Lavo la ropa.", exampleEn: "I wash the clothes." },
  { lemma: "camisa", gloss: "shirt", exampleEs: "Esta camisa es nueva.", exampleEn: "This shirt is new." },
  { lemma: "pantalón", gloss: "pants", exampleEs: "Compro un pantalón.", exampleEn: "I buy pants." },
  { lemma: "zapatos", gloss: "shoes", exampleEs: "Mis zapatos son negros.", exampleEn: "My shoes are black." },
  { lemma: "chaqueta", gloss: "jacket", exampleEs: "Llevo una chaqueta.", exampleEn: "I'm wearing a jacket." },
  { lemma: "abrigo", gloss: "coat", exampleEs: "Necesito un abrigo.", exampleEn: "I need a coat." },
  { lemma: "sombrero", gloss: "hat", exampleEs: "Usa un sombrero.", exampleEn: "He/She wears a hat." },
  { lemma: "bolsa", gloss: "bag", exampleEs: "Pongo todo en la bolsa.", exampleEn: "I put everything in the bag." },
  { lemma: "mochila", gloss: "backpack", exampleEs: "Mi mochila es pesada.", exampleEn: "My backpack is heavy." },
  { lemma: "dinero", gloss: "money", exampleEs: "No tengo dinero.", exampleEn: "I don't have money." },
  { lemma: "tarjeta", gloss: "card", exampleEs: "Pago con tarjeta.", exampleEn: "I pay with a card." },
  { lemma: "precio", gloss: "price", exampleEs: "El precio es alto.", exampleEn: "The price is high." },
  { lemma: "descuento", gloss: "discount", exampleEs: "Hay un descuento.", exampleEn: "There's a discount." },
  { lemma: "regalo", gloss: "gift", exampleEs: "Es un regalo para ti.", exampleEn: "It's a gift for you." },
  { lemma: "foto", gloss: "photo", exampleEs: "Saco una foto.", exampleEn: "I take a photo." },
  { lemma: "cámara", gloss: "camera", exampleEs: "La cámara es nueva.", exampleEn: "The camera is new." },
  { lemma: "televisión", gloss: "television", exampleEs: "Veo la televisión.", exampleEn: "I watch television." },
  { lemma: "radio", gloss: "radio", exampleEs: "Escucho la radio.", exampleEn: "I listen to the radio." },
  { lemma: "computadora", gloss: "computer", exampleEs: "Trabajo en la computadora.", exampleEn: "I work on the computer." },
  { lemma: "pantalla", gloss: "screen", exampleEs: "La pantalla es grande.", exampleEn: "The screen is big." },
  { lemma: "internet", gloss: "internet", exampleEs: "No hay internet.", exampleEn: "There's no internet." },
  { lemma: "mensaje", gloss: "message", exampleEs: "Te mando un mensaje.", exampleEn: "I'll send you a message." },
  { lemma: "correo electrónico", gloss: "email", exampleEs: "Reviso el correo electrónico.", exampleEn: "I check email." },
  { lemma: "contraseña", gloss: "password", exampleEs: "Olvidé la contraseña.", exampleEn: "I forgot the password." },
  { lemma: "aplicación", gloss: "app", exampleEs: "Descargo una aplicación.", exampleEn: "I download an app." },
  { lemma: "batería", gloss: "battery", exampleEs: "La batería está baja.", exampleEn: "The battery is low." },
  { lemma: "cargador", gloss: "charger", exampleEs: "¿Tienes un cargador?", exampleEn: "Do you have a charger?" },
  { lemma: "grande", gloss: "big / large", exampleEs: "La casa es grande.", exampleEn: "The house is big." },
  { lemma: "pequeño", gloss: "small", exampleEs: "El pueblo es pequeño.", exampleEn: "The town is small." },
  { lemma: "nuevo", gloss: "new", exampleEs: "Tengo un coche nuevo.", exampleEn: "I have a new car." },
  { lemma: "viejo", gloss: "old", exampleEs: "El edificio es viejo.", exampleEn: "The building is old." },
  { lemma: "joven", gloss: "young", exampleEs: "Somos jóvenes.", exampleEn: "We are young." },
  { lemma: "bonito", gloss: "pretty / nice", exampleEs: "Qué bonito lugar.", exampleEn: "What a pretty place." },
  { lemma: "feo", gloss: "ugly", exampleEs: "Ese edificio es feo.", exampleEn: "That building is ugly." },
  { lemma: "bueno", gloss: "good", exampleEs: "Es un buen día.", exampleEn: "It's a good day." },
  { lemma: "malo", gloss: "bad", exampleEs: "Tengo un mal día.", exampleEn: "I'm having a bad day." },
  { lemma: "mejor", gloss: "better / best", exampleEs: "Este es mejor.", exampleEn: "This one is better." },
  { lemma: "peor", gloss: "worse / worst", exampleEs: "Hoy está peor.", exampleEn: "Today it's worse." },
  { lemma: "fácil", gloss: "easy", exampleEs: "Es fácil.", exampleEn: "It's easy." },
  { lemma: "difícil", gloss: "difficult", exampleEs: "Es difícil.", exampleEn: "It's difficult." },
  { lemma: "rápido", gloss: "fast", exampleEs: "El tren es rápido.", exampleEn: "The train is fast." },
  { lemma: "lento", gloss: "slow", exampleEs: "El servicio es lento.", exampleEn: "The service is slow." },
  { lemma: "caliente", gloss: "hot", exampleEs: "El café está caliente.", exampleEn: "The coffee is hot." },
  { lemma: "frío", gloss: "cold", exampleEs: "Hace frío.", exampleEn: "It's cold." },
  { lemma: "fresco", gloss: "cool / fresh", exampleEs: "El aire está fresco.", exampleEn: "The air is cool." },
  { lemma: "caluroso", gloss: "hot (weather)", exampleEs: "Hoy está caluroso.", exampleEn: "Today it's hot." },
  { lemma: "húmedo", gloss: "humid", exampleEs: "El clima es húmedo.", exampleEn: "The climate is humid." },
  { lemma: "seco", gloss: "dry", exampleEs: "El desierto es seco.", exampleEn: "The desert is dry." },
  { lemma: "lleno", gloss: "full", exampleEs: "El restaurante está lleno.", exampleEn: "The restaurant is full." },
  { lemma: "vacío", gloss: "empty", exampleEs: "El vaso está vacío.", exampleEn: "The glass is empty." },
  { lemma: "abierto", gloss: "open", exampleEs: "La tienda está abierta.", exampleEn: "The store is open." },
  { lemma: "cerrado", gloss: "closed", exampleEs: "Está cerrado hoy.", exampleEn: "It's closed today." },
  { lemma: "cerca", gloss: "near", exampleEs: "Vivo cerca.", exampleEn: "I live nearby." },
  { lemma: "lejos", gloss: "far", exampleEs: "Queda lejos.", exampleEn: "It's far." },
  { lemma: "aquí", gloss: "here", exampleEs: "Ven aquí.", exampleEn: "Come here." },
  { lemma: "allí", gloss: "there", exampleEs: "Está allí.", exampleEn: "It's over there." },
  { lemma: "arriba", gloss: "up / upstairs", exampleEs: "Sube arriba.", exampleEn: "Go upstairs." },
  { lemma: "abajo", gloss: "down / downstairs", exampleEs: "Está abajo.", exampleEn: "It's downstairs." },
  { lemma: "dentro", gloss: "inside", exampleEs: "Estoy dentro.", exampleEn: "I'm inside." },
  { lemma: "fuera", gloss: "outside", exampleEs: "Espera fuera.", exampleEn: "Wait outside." },
  { lemma: "izquierda", gloss: "left", exampleEs: "Gira a la izquierda.", exampleEn: "Turn left." },
  { lemma: "derecha", gloss: "right", exampleEs: "Gira a la derecha.", exampleEn: "Turn right." },
  { lemma: "recto", gloss: "straight", exampleEs: "Sigue recto.", exampleEn: "Go straight." },
  { lemma: "importante", gloss: "important", exampleEs: "Es importante.", exampleEn: "It's important." },
  { lemma: "interesante", gloss: "interesting", exampleEs: "La clase es interesante.", exampleEn: "The class is interesting." },
  { lemma: "aburrido", gloss: "boring / bored", exampleEs: "La película es aburrida.", exampleEn: "The movie is boring." },
  { lemma: "feliz", gloss: "happy", exampleEs: "Estoy feliz.", exampleEn: "I am happy." },
  { lemma: "triste", gloss: "sad", exampleEs: "Se ve triste.", exampleEn: "He/She looks sad." },
  { lemma: "cansado", gloss: "tired", exampleEs: "Estoy cansado.", exampleEn: "I am tired." },
  { lemma: "enfermo", gloss: "sick", exampleEs: "Me siento enfermo.", exampleEn: "I feel sick." },
  { lemma: "sano", gloss: "healthy", exampleEs: "Quiero estar sano.", exampleEn: "I want to be healthy." },
  { lemma: "ocupado", gloss: "busy", exampleEs: "Hoy estoy ocupado.", exampleEn: "Today I'm busy." },
  { lemma: "libre", gloss: "free", exampleEs: "¿Estás libre?", exampleEn: "Are you free?" },
  { lemma: "listo", gloss: "ready / smart", exampleEs: "Estoy listo.", exampleEn: "I'm ready." },
  { lemma: "seguro", gloss: "sure / safe", exampleEs: "Estoy seguro.", exampleEn: "I'm sure." },
  { lemma: "peligroso", gloss: "dangerous", exampleEs: "Es peligroso.", exampleEn: "It's dangerous." },
  { lemma: "barato", gloss: "cheap", exampleEs: "Es barato.", exampleEn: "It's cheap." },
  { lemma: "caro", gloss: "expensive", exampleEs: "Es caro.", exampleEn: "It's expensive." },
  { lemma: "gratis", gloss: "free (no cost)", exampleEs: "Es gratis.", exampleEn: "It's free." },
  { lemma: "rico", gloss: "rich / tasty", exampleEs: "La comida está rica.", exampleEn: "The food is tasty." },
  { lemma: "pobre", gloss: "poor", exampleEs: "Era un pueblo pobre.", exampleEn: "It was a poor town." },
  { lemma: "limpio", gloss: "clean", exampleEs: "Todo está limpio.", exampleEn: "Everything is clean." },
  { lemma: "sucio", gloss: "dirty", exampleEs: "El piso está sucio.", exampleEn: "The floor is dirty." },
  { lemma: "alto", gloss: "tall / high", exampleEs: "El edificio es alto.", exampleEn: "The building is tall." },
  { lemma: "bajo", gloss: "short / low", exampleEs: "La mesa es baja.", exampleEn: "The table is low." },
  { lemma: "largo", gloss: "long", exampleEs: "El camino es largo.", exampleEn: "The road is long." },
  { lemma: "corto", gloss: "short", exampleEs: "El viaje es corto.", exampleEn: "The trip is short." },
  { lemma: "ancho", gloss: "wide", exampleEs: "La calle es ancha.", exampleEn: "The street is wide." },
  { lemma: "estrecho", gloss: "narrow", exampleEs: "El pasillo es estrecho.", exampleEn: "The hallway is narrow." },
  { lemma: "fuerte", gloss: "strong", exampleEs: "Él es fuerte.", exampleEn: "He is strong." },
  { lemma: "débil", gloss: "weak", exampleEs: "Me siento débil.", exampleEn: "I feel weak." },
  { lemma: "dulce", gloss: "sweet", exampleEs: "El postre es dulce.", exampleEn: "The dessert is sweet." },
  { lemma: "salado", gloss: "salty", exampleEs: "Está demasiado salado.", exampleEn: "It's too salty." },
  { lemma: "amargo", gloss: "bitter", exampleEs: "El café está amargo.", exampleEn: "The coffee is bitter." },
  { lemma: "picante", gloss: "spicy", exampleEs: "La salsa es picante.", exampleEn: "The sauce is spicy." },
  { lemma: "sol", gloss: "sun", exampleEs: "Hoy hay sol.", exampleEn: "There's sun today." },
  { lemma: "lluvia", gloss: "rain", exampleEs: "Hay lluvia.", exampleEn: "There's rain." },
  { lemma: "nube", gloss: "cloud", exampleEs: "Hay muchas nubes.", exampleEn: "There are many clouds." },
  { lemma: "viento", gloss: "wind", exampleEs: "Hace viento.", exampleEn: "It's windy." },
  { lemma: "nieve", gloss: "snow", exampleEs: "Cae nieve.", exampleEn: "It's snowing." },
  { lemma: "tormenta", gloss: "storm", exampleEs: "Hay una tormenta.", exampleEn: "There's a storm." },
  { lemma: "temperatura", gloss: "temperature", exampleEs: "La temperatura sube.", exampleEn: "The temperature rises." },
  { lemma: "clima", gloss: "climate / weather", exampleEs: "Me gusta el clima.", exampleEn: "I like the climate." },
  { lemma: "estación del año", gloss: "season", exampleEs: "Mi estación favorita es el otoño.", exampleEn: "My favorite season is fall." },
  { lemma: "primavera", gloss: "spring", exampleEs: "En primavera llueve.", exampleEn: "In spring it rains." },
  { lemma: "verano", gloss: "summer", exampleEs: "En verano hace calor.", exampleEn: "In summer it's hot." },
  { lemma: "otoño", gloss: "fall / autumn", exampleEs: "En otoño caen las hojas.", exampleEn: "In fall the leaves fall." },
  { lemma: "invierno", gloss: "winter", exampleEs: "En invierno hace frío.", exampleEn: "In winter it's cold." },
  { lemma: "cabeza", gloss: "head", exampleEs: "Me duele la cabeza.", exampleEn: "My head hurts." },
  { lemma: "ojo", gloss: "eye", exampleEs: "Tengo los ojos cansados.", exampleEn: "My eyes are tired." },
  { lemma: "oreja", gloss: "ear", exampleEs: "Me duele la oreja.", exampleEn: "My ear hurts." },
  { lemma: "nariz", gloss: "nose", exampleEs: "Tengo la nariz tapada.", exampleEn: "My nose is stuffy." },
  { lemma: "boca", gloss: "mouth", exampleEs: "Abre la boca.", exampleEn: "Open your mouth." },
  { lemma: "diente", gloss: "tooth", exampleEs: "Me duele un diente.", exampleEn: "I have a toothache." },
  { lemma: "mano", gloss: "hand", exampleEs: "Dame la mano.", exampleEn: "Give me your hand." },
  { lemma: "brazo", gloss: "arm", exampleEs: "Me duele el brazo.", exampleEn: "My arm hurts." },
  { lemma: "pierna", gloss: "leg", exampleEs: "Corro con las piernas fuertes.", exampleEn: "I run with strong legs." },
  { lemma: "pie", gloss: "foot", exampleEs: "Me duele el pie.", exampleEn: "My foot hurts." },
  { lemma: "espalda", gloss: "back", exampleEs: "Tengo dolor de espalda.", exampleEn: "I have back pain." },
  { lemma: "estómago", gloss: "stomach", exampleEs: "Me duele el estómago.", exampleEn: "My stomach hurts." },
  { lemma: "corazón", gloss: "heart", exampleEs: "El corazón late rápido.", exampleEn: "The heart beats fast." },
  { lemma: "dolor", gloss: "pain", exampleEs: "Tengo dolor.", exampleEn: "I have pain." },
  { lemma: "fiebre", gloss: "fever", exampleEs: "Tengo fiebre.", exampleEn: "I have a fever." },
  { lemma: "medicina", gloss: "medicine", exampleEs: "Tomo la medicina.", exampleEn: "I take the medicine." },
  { lemma: "cita", gloss: "appointment", exampleEs: "Tengo una cita.", exampleEn: "I have an appointment." },
  { lemma: "pregunta", gloss: "question", exampleEs: "Tengo una pregunta.", exampleEn: "I have a question." },
  { lemma: "respuesta", gloss: "answer", exampleEs: "No sé la respuesta.", exampleEn: "I don't know the answer." },
  { lemma: "conversación", gloss: "conversation", exampleEs: "Es una buena conversación.", exampleEn: "It's a good conversation." },
  { lemma: "historia", gloss: "story / history", exampleEs: "Cuéntame una historia.", exampleEn: "Tell me a story." },
  { lemma: "noticia", gloss: "news", exampleEs: "Vi la noticia.", exampleEn: "I saw the news." },
  { lemma: "problema", gloss: "problem", exampleEs: "No hay problema.", exampleEn: "No problem." },
  { lemma: "solución", gloss: "solution", exampleEs: "Buscamos una solución.", exampleEn: "We're looking for a solution." },
  { lemma: "idea", gloss: "idea", exampleEs: "Tengo una idea.", exampleEn: "I have an idea." },
  { lemma: "plan", gloss: "plan", exampleEs: "¿Cuál es el plan?", exampleEn: "What's the plan?" },
  { lemma: "fiesta", gloss: "party", exampleEs: "Vamos a la fiesta.", exampleEn: "We're going to the party." },
  { lemma: "cumpleaños", gloss: "birthday", exampleEs: "Feliz cumpleaños.", exampleEn: "Happy birthday." },
  { lemma: "boda", gloss: "wedding", exampleEs: "Fui a una boda.", exampleEn: "I went to a wedding." },
  { lemma: "reunión", gloss: "meeting", exampleEs: "Tengo una reunión.", exampleEn: "I have a meeting." },
  { lemma: "amigo cercano", gloss: "close friend", exampleEs: "Es un amigo cercano.", exampleEn: "He's a close friend." },
  { lemma: "novio", gloss: "boyfriend / fiancé", exampleEs: "Mi novio llega tarde.", exampleEn: "My boyfriend arrives late." },
  { lemma: "novia", gloss: "girlfriend / fiancée", exampleEs: "Mi novia estudia medicina.", exampleEn: "My girlfriend studies medicine." },
  { lemma: "cosa", gloss: "thing", exampleEs: "Es una cosa importante.", exampleEn: "It's an important thing." },
  { lemma: "lugar", gloss: "place", exampleEs: "Es un buen lugar.", exampleEn: "It's a good place." },
  { lemma: "vez", gloss: "time (occasion)", exampleEs: "Una vez más.", exampleEn: "One more time." },
  { lemma: "parte", gloss: "part", exampleEs: "Esta parte es difícil.", exampleEn: "This part is difficult." },
  { lemma: "lado", gloss: "side", exampleEs: "Al otro lado.", exampleEn: "On the other side." },
  { lemma: "ejemplo", gloss: "example", exampleEs: "Dame un ejemplo.", exampleEn: "Give me an example." },
  { lemma: "número", gloss: "number", exampleEs: "¿Cuál es el número?", exampleEn: "What's the number?" },
  { lemma: "letra", gloss: "letter (alphabet)", exampleEs: "Escribe la letra A.", exampleEn: "Write the letter A." },
  { lemma: "palabra", gloss: "word", exampleEs: "Es una palabra nueva.", exampleEn: "It's a new word." },
  { lemma: "frase", gloss: "sentence / phrase", exampleEs: "Repite la frase.", exampleEn: "Repeat the sentence." },
  { lemma: "idioma", gloss: "language", exampleEs: "El español es un idioma.", exampleEn: "Spanish is a language." },
  { lemma: "inglés", gloss: "English", exampleEs: "Hablo inglés.", exampleEn: "I speak English." },
  { lemma: "español", gloss: "Spanish", exampleEs: "Aprendo español.", exampleEn: "I'm learning Spanish." },
  { lemma: "verdad", gloss: "truth", exampleEs: "Es la verdad.", exampleEn: "It's the truth." },
  { lemma: "mentira", gloss: "lie", exampleEs: "Eso es una mentira.", exampleEn: "That's a lie." },
  { lemma: "razón", gloss: "reason", exampleEs: "Tienes razón.", exampleEn: "You're right." },
  { lemma: "causa", gloss: "cause", exampleEs: "¿Cuál es la causa?", exampleEn: "What's the cause?" },
  { lemma: "resultado", gloss: "result", exampleEs: "El resultado es bueno.", exampleEn: "The result is good." },
  { lemma: "éxito", gloss: "success", exampleEs: "Fue un éxito.", exampleEn: "It was a success." },
  { lemma: "error", gloss: "mistake", exampleEs: "Fue un error.", exampleEn: "It was a mistake." },
  { lemma: "oportunidad", gloss: "opportunity", exampleEs: "Es una buena oportunidad.", exampleEn: "It's a good opportunity." },
  { lemma: "peligro", gloss: "danger", exampleEs: "Hay peligro.", exampleEn: "There's danger." },
  { lemma: "ayuda", gloss: "help", exampleEs: "Necesito ayuda.", exampleEn: "I need help." },
  { lemma: "favor", gloss: "favor", exampleEs: "Hazme un favor.", exampleEn: "Do me a favor." },
  { lemma: "perdón", gloss: "forgiveness / sorry", exampleEs: "Pido perdón.", exampleEn: "I apologize." },
  { lemma: "gracias", gloss: "thanks", exampleEs: "Muchas gracias.", exampleEn: "Thank you very much." },
  { lemma: "por favor", gloss: "please", exampleEs: "Agua, por favor.", exampleEn: "Water, please." },
  { lemma: "de nada", gloss: "you're welcome", exampleEs: "De nada.", exampleEn: "You're welcome." },
  { lemma: "con permiso", gloss: "excuse me (passing)", exampleEs: "Con permiso.", exampleEn: "Excuse me." },
  { lemma: "salud", gloss: "health / bless you", exampleEs: "¡Salud!", exampleEn: "Bless you! / Cheers!" },
  { lemma: "cuidado", gloss: "careful / care", exampleEs: "Ten cuidado.", exampleEn: "Be careful." },
  { lemma: "listo ya", gloss: "ready already", exampleEs: "¿Listo ya?", exampleEn: "Ready already?" },
  { lemma: "otra vez", gloss: "again", exampleEs: "Otra vez, por favor.", exampleEn: "Again, please." },
  { lemma: "más o menos", gloss: "more or less", exampleEs: "Más o menos.", exampleEn: "More or less." },
  { lemma: "por supuesto", gloss: "of course", exampleEs: "Por supuesto.", exampleEn: "Of course." },
  { lemma: "tal vez", gloss: "maybe", exampleEs: "Tal vez mañana.", exampleEn: "Maybe tomorrow." },
  { lemma: "claro", gloss: "clear / of course", exampleEs: "Claro que sí.", exampleEn: "Of course." },
  { lemma: "vale", gloss: "okay / deal", exampleEs: "Vale.", exampleEn: "Okay." },
  { lemma: "bueno pues", gloss: "well then", exampleEs: "Bueno pues, vamos.", exampleEn: "Well then, let's go." },
  { lemma: "en serio", gloss: "seriously", exampleEs: "¿En serio?", exampleEn: "Seriously?" },
  { lemma: "de verdad", gloss: "really", exampleEs: "De verdad.", exampleEn: "Really." },
  { lemma: "sin problema", gloss: "no problem", exampleEs: "Sin problema.", exampleEn: "No problem." },
  { lemma: "con gusto", gloss: "gladly", exampleEs: "Con gusto.", exampleEn: "Gladly." },
  { lemma: "hasta pronto", gloss: "see you soon", exampleEs: "Hasta pronto.", exampleEn: "See you soon." },
  { lemma: "nos vemos", gloss: "see you", exampleEs: "Nos vemos mañana.", exampleEn: "See you tomorrow." },
  { lemma: "qué tal", gloss: "how's it going", exampleEs: "¿Qué tal?", exampleEn: "How's it going?" },
  { lemma: "qué pasa", gloss: "what's up", exampleEs: "¿Qué pasa?", exampleEn: "What's up?" },
  { lemma: "cómo te va", gloss: "how are you doing", exampleEs: "¿Cómo te va?", exampleEn: "How are you doing?" },
  { lemma: "mucho gusto", gloss: "nice to meet you", exampleEs: "Mucho gusto.", exampleEn: "Nice to meet you." },
  { lemma: "encantado", gloss: "pleased to meet you", exampleEs: "Encantado.", exampleEn: "Pleased to meet you." },
  { lemma: "bienvenido", gloss: "welcome", exampleEs: "Bienvenido.", exampleEn: "Welcome." },
  { lemma: "felicidades", gloss: "congratulations", exampleEs: "¡Felicidades!", exampleEn: "Congratulations!" },
  { lemma: "buena suerte", gloss: "good luck", exampleEs: "Buena suerte.", exampleEn: "Good luck." },
  { lemma: "que te vaya bien", gloss: "take care / farewell", exampleEs: "Que te vaya bien.", exampleEn: "Take care." },
  { lemma: "cuánto cuesta", gloss: "how much does it cost", exampleEs: "¿Cuánto cuesta?", exampleEn: "How much does it cost?" },
  { lemma: "dónde está", gloss: "where is", exampleEs: "¿Dónde está el baño?", exampleEn: "Where is the bathroom?" },
  { lemma: "cómo se dice", gloss: "how do you say", exampleEs: "¿Cómo se dice…?", exampleEn: "How do you say…?" },
  { lemma: "no entiendo", gloss: "I don't understand", exampleEs: "No entiendo.", exampleEn: "I don't understand." },
  { lemma: "más despacio", gloss: "more slowly", exampleEs: "Más despacio, por favor.", exampleEn: "More slowly, please." },
  { lemma: "puedes repetir", gloss: "can you repeat", exampleEs: "¿Puedes repetir?", exampleEn: "Can you repeat?" },
  { lemma: "estoy perdido", gloss: "I'm lost", exampleEs: "Estoy perdido.", exampleEn: "I'm lost." },
  { lemma: "busca trabajo", gloss: "looking for work", exampleEs: "Busca trabajo.", exampleEn: "He/She is looking for work." },
  { lemma: "tengo hambre", gloss: "I'm hungry", exampleEs: "Tengo hambre.", exampleEn: "I'm hungry." },
  { lemma: "tengo sed", gloss: "I'm thirsty", exampleEs: "Tengo sed.", exampleEn: "I'm thirsty." },
  { lemma: "tengo sueño", gloss: "I'm sleepy", exampleEs: "Tengo sueño.", exampleEn: "I'm sleepy." },
  { lemma: "tengo frío", gloss: "I'm cold", exampleEs: "Tengo frío.", exampleEn: "I'm cold." },
  { lemma: "tengo calor", gloss: "I'm hot", exampleEs: "Tengo calor.", exampleEn: "I'm hot." },
  { lemma: "hace buen tiempo", gloss: "the weather is nice", exampleEs: "Hace buen tiempo.", exampleEn: "The weather is nice." },
  { lemma: "hace mal tiempo", gloss: "the weather is bad", exampleEs: "Hace mal tiempo.", exampleEn: "The weather is bad." },
  { lemma: "qué hora es", gloss: "what time is it", exampleEs: "¿Qué hora es?", exampleEn: "What time is it?" },
  { lemma: "a qué hora", gloss: "at what time", exampleEs: "¿A qué hora sales?", exampleEn: "What time do you leave?" },
  { lemma: "cuántos años", gloss: "how old", exampleEs: "¿Cuántos años tienes?", exampleEn: "How old are you?" },
  { lemma: "me llamo", gloss: "my name is", exampleEs: "Me llamo Ana.", exampleEn: "My name is Ana." },
  { lemma: "soy de", gloss: "I'm from", exampleEs: "Soy de Colombia.", exampleEn: "I'm from Colombia." },
  { lemma: "vivo en", gloss: "I live in", exampleEs: "Vivo en la ciudad.", exampleEn: "I live in the city." },
  { lemma: "trabajo en", gloss: "I work at/in", exampleEs: "Trabajo en una oficina.", exampleEn: "I work in an office." },
  { lemma: "estudio en", gloss: "I study at", exampleEs: "Estudio en la universidad.", exampleEn: "I study at the university." },
  { lemma: "me gusta", gloss: "I like", exampleEs: "Me gusta caminar.", exampleEn: "I like to walk." },
  { lemma: "no me gusta", gloss: "I don't like", exampleEs: "No me gusta madrugar.", exampleEn: "I don't like getting up early." },
  { lemma: "quiero ir", gloss: "I want to go", exampleEs: "Quiero ir al cine.", exampleEn: "I want to go to the movies." },
  { lemma: "vamos a", gloss: "we're going to / let's", exampleEs: "Vamos a comer.", exampleEn: "Let's eat." },
  { lemma: "hay que", gloss: "one must / we need to", exampleEs: "Hay que estudiar.", exampleEn: "We need to study." },
  { lemma: "tengo que", gloss: "I have to", exampleEs: "Tengo que salir.", exampleEn: "I have to leave." },
  { lemma: "puedo", gloss: "I can", exampleEs: "Puedo ayudarte.", exampleEn: "I can help you." },
  { lemma: "no puedo", gloss: "I can't", exampleEs: "No puedo ir.", exampleEn: "I can't go." },
  { lemma: "voy a", gloss: "I'm going to", exampleEs: "Voy a estudiar.", exampleEn: "I'm going to study." },
  { lemma: "acabo de", gloss: "I just", exampleEs: "Acabo de llegar.", exampleEn: "I just arrived." },
  { lemma: "estoy aprendiendo", gloss: "I'm learning", exampleEs: "Estoy aprendiendo español.", exampleEn: "I'm learning Spanish." },
  { lemma: "un poco", gloss: "a little", exampleEs: "Hablo un poco.", exampleEn: "I speak a little." },
  { lemma: "mucho", gloss: "a lot / very", exampleEs: "Gracias, mucho.", exampleEn: "Thanks a lot." },
  { lemma: "poco", gloss: "little / few", exampleEs: "Tengo poco tiempo.", exampleEn: "I have little time." },
  { lemma: "bastante", gloss: "quite / enough", exampleEs: "Es bastante fácil.", exampleEn: "It's quite easy." },
  { lemma: "demasiado", gloss: "too much", exampleEs: "Es demasiado caro.", exampleEn: "It's too expensive." },
  { lemma: "también", gloss: "also / too", exampleEs: "Yo también.", exampleEn: "Me too." },
  { lemma: "tampoco", gloss: "neither / either", exampleEs: "Yo tampoco.", exampleEn: "Me neither." },
  { lemma: "pero", gloss: "but", exampleEs: "Quiero ir, pero no puedo.", exampleEn: "I want to go, but I can't." },
  { lemma: "porque", gloss: "because", exampleEs: "Estudio porque me gusta.", exampleEn: "I study because I like it." },
  { lemma: "aunque", gloss: "although", exampleEs: "Aunque llueve, salgo.", exampleEn: "Although it rains, I go out." },
  { lemma: "si", gloss: "if", exampleEs: "Si llueve, me quedo.", exampleEn: "If it rains, I stay." },
  { lemma: "cuando", gloss: "when", exampleEs: "Cuando llegues, llama.", exampleEn: "When you arrive, call." },
  { lemma: "donde", gloss: "where", exampleEs: "Donde vivo hay un parque.", exampleEn: "Where I live there's a park." },
  { lemma: "quien", gloss: "who", exampleEs: "Quien llega primero gana.", exampleEn: "Whoever arrives first wins." },
  { lemma: "qué", gloss: "what", exampleEs: "¿Qué quieres?", exampleEn: "What do you want?" },
  { lemma: "cuál", gloss: "which", exampleEs: "¿Cuál prefieres?", exampleEn: "Which do you prefer?" },
  { lemma: "cuánto", gloss: "how much", exampleEs: "¿Cuánto es?", exampleEn: "How much is it?" },
  { lemma: "cuántos", gloss: "how many", exampleEs: "¿Cuántos hay?", exampleEn: "How many are there?" },
  { lemma: "este", gloss: "this (m.)", exampleEs: "Este libro es mío.", exampleEn: "This book is mine." },
  { lemma: "esta", gloss: "this (f.)", exampleEs: "Esta casa es grande.", exampleEn: "This house is big." },
  { lemma: "ese", gloss: "that (m.)", exampleEs: "Ese coche es rápido.", exampleEn: "That car is fast." },
  { lemma: "esa", gloss: "that (f.)", exampleEs: "Esa idea es buena.", exampleEn: "That idea is good." },
  { lemma: "aquel", gloss: "that (over there, m.)", exampleEs: "Aquel edificio es viejo.", exampleEn: "That building over there is old." },
  { lemma: "mí", gloss: "me (after prep.)", exampleEs: "Ven conmigo — habla de mí.", exampleEn: "Come with me — talk about me." },
  { lemma: "ti", gloss: "you (after prep.)", exampleEs: "Esto es para ti.", exampleEn: "This is for you." },
  { lemma: "nosotros", gloss: "we / us", exampleEs: "Nosotros vamos juntos.", exampleEn: "We go together." },
  { lemma: "ellos", gloss: "they (m.)", exampleEs: "Ellos llegan tarde.", exampleEn: "They arrive late." },
  { lemma: "ellas", gloss: "they (f.)", exampleEs: "Ellas estudian juntas.", exampleEn: "They study together." },
  { lemma: "usted", gloss: "you (formal)", exampleEs: "¿Cómo está usted?", exampleEn: "How are you?" },
  { lemma: "ustedes", gloss: "you all", exampleEs: "¿Cómo están ustedes?", exampleEn: "How are you all?" },
  { lemma: "mío", gloss: "mine", exampleEs: "Es mío.", exampleEn: "It's mine." },
  { lemma: "tuyo", gloss: "yours", exampleEs: "Es tuyo.", exampleEn: "It's yours." },
  { lemma: "nuestro", gloss: "ours", exampleEs: "Es nuestro.", exampleEn: "It's ours." },
  { lemma: "otro", gloss: "other / another", exampleEs: "Quiero otro café.", exampleEn: "I want another coffee." },
  { lemma: "mismo", gloss: "same", exampleEs: "El mismo día.", exampleEn: "The same day." },
  { lemma: "todo", gloss: "everything / all", exampleEs: "Todo está bien.", exampleEn: "Everything is fine." },
  { lemma: "nada", gloss: "nothing", exampleEs: "No pasa nada.", exampleEn: "Nothing's wrong." },
  { lemma: "algo", gloss: "something", exampleEs: "Necesito algo.", exampleEn: "I need something." },
  { lemma: "alguien", gloss: "someone", exampleEs: "Alguien llama.", exampleEn: "Someone is calling." },
  { lemma: "nadie", gloss: "nobody", exampleEs: "No hay nadie.", exampleEn: "There's nobody." },
  { lemma: "cada", gloss: "each / every", exampleEs: "Cada día aprendo.", exampleEn: "Every day I learn." },
  { lemma: "ambos", gloss: "both", exampleEs: "Ambos están bien.", exampleEn: "Both are fine." },
  { lemma: "varios", gloss: "several", exampleEs: "Tengo varios libros.", exampleEn: "I have several books." },
  { lemma: "poco a poco", gloss: "little by little", exampleEs: "Poco a poco mejoro.", exampleEn: "Little by little I improve." },
  { lemma: "de repente", gloss: "suddenly", exampleEs: "De repente empezó a llover.", exampleEn: "Suddenly it started to rain." },
  { lemma: "por fin", gloss: "finally", exampleEs: "Por fin llegamos.", exampleEn: "We finally arrived." },
  { lemma: "en seguida", gloss: "right away", exampleEs: "Voy en seguida.", exampleEn: "I'll go right away." },
  { lemma: "a menudo", gloss: "often", exampleEs: "A menudo camino.", exampleEn: "I often walk." },
  { lemma: "de vez en cuando", gloss: "from time to time", exampleEs: "De vez en cuando viajo.", exampleEn: "From time to time I travel." },
  { lemma: "sin embargo", gloss: "however", exampleEs: "Sin embargo, sigo.", exampleEn: "However, I continue." },
  { lemma: "además", gloss: "besides / also", exampleEs: "Además, es barato.", exampleEn: "Besides, it's cheap." },
  { lemma: "entonces", gloss: "then / so", exampleEs: "Entonces, ¿vamos?", exampleEn: "So, shall we go?" },
  { lemma: "así", gloss: "like this / so", exampleEs: "Hazlo así.", exampleEn: "Do it like this." },
  { lemma: "casi", gloss: "almost", exampleEs: "Casi termino.", exampleEn: "I'm almost finished." },
  { lemma: "apenas", gloss: "barely / just", exampleEs: "Apenas llego.", exampleEn: "I just arrived." },
  { lemma: "todavía no", gloss: "not yet", exampleEs: "Todavía no.", exampleEn: "Not yet." },
  { lemma: "ya no", gloss: "no longer", exampleEs: "Ya no vivo ahí.", exampleEn: "I no longer live there." },
  { lemma: "otra cosa", gloss: "something else", exampleEs: "¿Otra cosa?", exampleEn: "Anything else?" },
  { lemma: "lo siento", gloss: "I'm sorry", exampleEs: "Lo siento.", exampleEn: "I'm sorry." },
  { lemma: "no hay de qué", gloss: "you're welcome", exampleEs: "No hay de qué.", exampleEn: "You're welcome." },
  { lemma: "con mucho gusto", gloss: "with pleasure", exampleEs: "Con mucho gusto.", exampleEn: "With pleasure." },
  { lemma: "qué lástima", gloss: "what a shame", exampleEs: "Qué lástima.", exampleEn: "What a shame." },
  { lemma: "qué bueno", gloss: "how nice", exampleEs: "Qué bueno.", exampleEn: "How nice." },
  { lemma: "qué raro", gloss: "how strange", exampleEs: "Qué raro.", exampleEn: "How strange." },
  { lemma: "da igual", gloss: "it doesn't matter", exampleEs: "Me da igual.", exampleEn: "It doesn't matter to me." },
  { lemma: "no pasa nada", gloss: "it's okay / no worries", exampleEs: "No pasa nada.", exampleEn: "No worries." },
  { lemma: "está bien", gloss: "it's okay / fine", exampleEs: "Está bien.", exampleEn: "It's fine." },
  { lemma: "perfecto", gloss: "perfect", exampleEs: "Perfecto.", exampleEn: "Perfect." },
  { lemma: "excelente", gloss: "excellent", exampleEs: "Excelente idea.", exampleEn: "Excellent idea." },
  { lemma: "increíble", gloss: "incredible", exampleEs: "Es increíble.", exampleEn: "It's incredible." },
  { lemma: "posible", gloss: "possible", exampleEs: "Es posible.", exampleEn: "It's possible." },
  { lemma: "imposible", gloss: "impossible", exampleEs: "Es imposible.", exampleEn: "It's impossible." },
  { lemma: "necesario", gloss: "necessary", exampleEs: "Es necesario.", exampleEn: "It's necessary." },
  { lemma: "disponible", gloss: "available", exampleEs: "¿Está disponible?", exampleEn: "Is it available?" },
  { lemma: "ocupado ahora", gloss: "busy now", exampleEs: "Estoy ocupado ahora.", exampleEn: "I'm busy now." },
  { lemma: "próximo", gloss: "next", exampleEs: "La próxima semana.", exampleEn: "Next week." },
  { lemma: "pasado", gloss: "past / last", exampleEs: "El año pasado.", exampleEn: "Last year." },
  { lemma: "último", gloss: "last / latest", exampleEs: "El último tren.", exampleEn: "The last train." },
  { lemma: "primero", gloss: "first", exampleEs: "El primer día.", exampleEn: "The first day." },
  { lemma: "segundo piso", gloss: "second floor", exampleEs: "Vivo en el segundo piso.", exampleEn: "I live on the second floor." },
  { lemma: "medio", gloss: "half / middle", exampleEs: "Media hora.", exampleEn: "Half an hour." },
  { lemma: "doble", gloss: "double", exampleEs: "Una porción doble.", exampleEn: "A double portion." },
  { lemma: "simple", gloss: "simple", exampleEs: "Es simple.", exampleEn: "It's simple." },
  { lemma: "especial", gloss: "special", exampleEs: "Es un día especial.", exampleEn: "It's a special day." },
  { lemma: "normal", gloss: "normal", exampleEs: "Es normal.", exampleEn: "It's normal." },
  { lemma: "raro", gloss: "strange / rare", exampleEs: "Es raro.", exampleEn: "It's strange." },
  { lemma: "común", gloss: "common", exampleEs: "Es común.", exampleEn: "It's common." },
  { lemma: "único", gloss: "unique / only", exampleEs: "Es único.", exampleEn: "It's unique." },
  { lemma: "diferente", gloss: "different", exampleEs: "Es diferente.", exampleEn: "It's different." },
  { lemma: "igual", gloss: "same / equal", exampleEs: "Somos iguales.", exampleEn: "We're the same." },
  { lemma: "parecido", gloss: "similar", exampleEs: "Es parecido.", exampleEn: "It's similar." },
  { lemma: "completo", gloss: "complete / full", exampleEs: "El hotel está completo.", exampleEn: "The hotel is full." },
  { lemma: "incompleto", gloss: "incomplete", exampleEs: "Está incompleto.", exampleEn: "It's incomplete." },
  { lemma: "correcto", gloss: "correct", exampleEs: "Es correcto.", exampleEn: "It's correct." },
  { lemma: "incorrecto", gloss: "incorrect", exampleEs: "Es incorrecto.", exampleEn: "It's incorrect." },
  { lemma: "verdadero", gloss: "true", exampleEs: "Es verdadero.", exampleEn: "It's true." },
  { lemma: "falso", gloss: "false", exampleEs: "Es falso.", exampleEn: "It's false." },
];
